
MANAGE_ACCOUNTS_TITLE=Manage Accounts
NEW_ACCOUNT=New Account
ACCOUNT_AT_RISK=Your current account is at risk! Fix that first before creating a new account.
LOST_ACCOUNT=Lost Account?
ACCOUNTS_FOUND=Accounts Found
SERVER_FOUND_ACCOUNT_LATE=We found an existing account you may want to use. Select one of the accounts listed to continue playing.
SERVER_FOUND_ACCOUNT_ON_BOOT=We found an existing account you may want to use. Select one of the accounts listed to continue playing, or create a new account.
SWITCH_ACCOUNT=Switch
GUILD=Guild
ACCOUNT_NOT_SECURE=Not Secure!
AT_RISK=At risk
MANAGE=At risk
PLEASE_CHOOSE_ACCOUNT=Please choose an account.
MANAGE_ACCOUNT_INFO=This account is attached to these recovery methods:
MANAGE_ACCOUNT_INFO_RISK=Make your account recoverable by connecting to one of these:
CONNECT=Connect
CONNECTED=Connected:
DISCONNECT=Disconnect
CURRENT_ACCOUNT_HEADING=Current Account
OTHER_ACCOUNTS_HEADING=Other Accounts
MANAGE_ACCOUNT_TITLE=Manage Account
ACTIVE_ACCOUNT=Active Account
ACCOUNT_RECOVERY_FACEBOOK=Add Facebook as a recovery method.
ACCOUNT_RECOVERY_GOOGLE=Add Google Play as a recovery method.
NO_CURRENT_EMAIL=No current email connected
ANDROID_PERMISSIONS_INFO=We access your accounts and phone state to more securely link your user account to your device. Please allow access to the permissions.
ANDROID_DETAILED_PERMISSION_TITLE=Secure Your Account
ANDROID_DETAILED_PERMISSION_INFO=To secure your Disney Heroes account by connecting it to your device, we need two pieces of information:
ANDROID_DETAILED_PERMISSION_BULLET_1="Make and manage phone calls:" Provides us with a unique device ID to identify and link your account.
ANDROID_DETAILED_PERMISSION_BULLET_2="Access your contacts:" Provides us with your email address for account recovery.
ANDROID_DETAILED_PERMISSION_OTHER_USES=We do not use these permissions for any other purpose.
EDIT_PERMISSION_SETTINGS=Edit Permission Settings
REQUEST_PERMISSIONS=Request Again
LOST_ACCOUNT_TITLE=Account Recovery
LOST_ACCOUNT_INFO=Connect to one of these to try and find your account.
ACCOUNT_LOST_EMAIL_SUPPORT=Still lost? Check out our FAQ.
SUPPORT_FAQ=FAQ
LOST_ACCOUNT_FACEBOOK=Try to find your account by connecting to Facebook.
LOST_ACCOUNT_CURRENTLY_CONNECTED=You are already connected to %1$s. If you have another account at %1$s you can disconnect this one and try that one.
FACEBOOK=Facebook
LOST_ACCOUNT_GOOGLE=Try to find your account by connecting to Google Play.
GOOGLE_PLUS=Google Play
SERVER_WINDOW_TITLE=Choose Your Server
NO_SERVERS_AVAILBLE_FOR_ACCOUNT=No servers currently available. Check back later.
SERVER_MAX_TEAM_LEVEL_FORMAT=Level Cap: %1$d
SERVER_FULL=Full
SERVER_FULL_CONFIRM_TITLE=Server Full
SERVER_FULL_CONFIRM_INFO=This server is full, but we do allow people to make new accounts so they can play with friends. Are you sure you want to make an account here?
SERVER_OPENS_IN_PREFIX=Opens In:
SERVER_HAS_ACCOUNT=Account Already Exists
SERVER_UNAVAILABLE=Temporarily Unavailable
MANAGE_BUTTON=Manage
SERVER_NAME_FORMAT={#3ec07b}%1$d) %2$s{}
STOP_SHOWING_WARNING=Stop showing this type of warning
GOLD_CAP_REACHED_TITLE=Gold Cap Reached
GOLD_CAP_ITEM_SELLING=Sorry, selling this amount would cause you to exceed the 2 billion gold cap. Please choose a lower amount to sell or spend some gold.
GOLD_CAP_NEARING_TITLE=Warning: Nearing Gold Cap
GOLD_CAP_NEARING=You're nearing the 2 billion gold cap. Please start spending gold now. If you reach the cap, you'll be unable to sell items or collect gold from most rewards.
GOLD_CAP_REACHED_TITLE_WARNING=Warning: Gold Cap Reached!
GOLD_CAP_REACHED=You're currently at or near the 2 billion gold cap. Please spend your gold now or you'll be unable to sell inventory items, claim mailbox rewards and could lose gold rewards from modes. Any in-app or diamond bundle purchases that contain gold will award it as credit items.
GOLD_CAP_REACHED_SELLING=You're currently at or near the 2 billion gold cap. You won't be able to sell any items until you've spent some of your gold.
GOLD_CAP_REACHED_BUYING=You're currently at or near the 2 billion gold cap. You won't be able to buy any gold until you've spent some of your gold.
GOLD_CAP_LOSE_GOLD_TITLE=Warning: You May Lose Gold!
GOLD_CAP_REACHED_REWARD=You're currently at or near the 2 billion gold cap. You may lose gold rewards if you continue.
CONFIRM_DISCONNECT_GAME_CENTER=Are you sure you want to disconnect Game Center from this account? You will lose access to the account if there is no other recovery method connected.
GAME_CENTER_SIGNIN_PROMPT=Please sign in to your Game Center account by navigating to your device's settings then tapping on Game Center.
ACCOUNT_RECOVERY_GAMECENTER=Add GameCenter as a recovery method.
LOST_ACCOUNT_GAMECENTER=Try to find your account by connecting to Game Center.
GAME_CENTER=Game Center
CONFIRM_DISCONNECT_APPLE_SIGN_IN=Are you sure you want to disconnect Sign in with Apple from this account? You will lose access to the account if there is no other recovery method connected.
ACCOUNT_RECOVERY_APPLE_SIGN_IN=Add Sign in with Apple as a recovery method.
LOST_ACCOUNT_APPLE_SIGN_IN=Try to find your account by connecting to Sign in with Apple.
APPLE_SIGN_IN=Sign in with Apple
UPDATE_TO_API_19_DESC=We will be discontinuing support for Android OS older than 4.4(API Level 19), please upgrade your device to keep playing
