
INFO_PROPOSITION=Great Rewards Daily for 30 Days!
VALUE1=%1$d
VALUE2=$%1$d!
BUY_BUTTON=Buy Now
RENEW_BUTTON=Renew
TIME_REMAINING=Days left
RETURN_PROMPT=Come back each day to collect your air drop!
DIAMOND_VALUE=diamond value
FOR_ONLY=for only
HOW_TO_PLAY=Get a daily shipment of goodies!
CURR_DAY=Day %1$d
