
PASS_TITLE=Diamond Quest
BATTLE_PASS_TITLE=Battle Pass
PREMIUM=Premium
NO_PASS=Unlock the Premium Pass to claim this reward.
NOT_ENOUGH_POINTS=Earn more Quest Points to claim this reward.
PREMIUM_REWARDS=Premium Rewards
EVENT_REWARDS_INFO=Earn the following rewards over the course of the event:
PURCHASE_RECIEVE=Purchase now to immediately receive:
PREMIUM_BUTTON=Get Premium - %1$s
CHEST_HEROES_TITLE=Premium Mystery Chip Heroes
ALREADY_CLAIMED=You've already claimed this reward.
DIAMOND_QUEST_REWARDS=Diamond Quest Rewards
FREE_REWARDS=Free Rewards
UNLOCK_DIAMOND_QUEST=Reach Team Level %1$d to unlock Diamond Quests and claim rewards!
EARN_QUEST_POINTS=These are the Quest Points that you've earned so far. Reach the goal to earn your next Diamond Quest reward.
EARN_MORE_QUEST_POINTS=These are the Quest Points that you've earned so far. Reach the goal to earn your next Battle Pass reward.
MYSTERY_CHIP_SUBTITLE=Premium Mystery Chips will award Hero Chips for one of the heroes shown below. The Heroes in this list can update if newer Heroes become available, granting you access to those Heroes.  All listed heroes have an equal chance of dropping.
UNCLAIMED=%1$d Unclaimed
COLLECT=Collect
DAILY_POINT_METER=These are your Daily Quest Points that you have accumulated. You can earn up to 10 per day.
NEXT_EVENT=Next Event Begins In:
INTERSTITIAL_TITLE=Diamond Quest Premium Pass
INTERSTITIAL_FIRST=Purchase a Diamond Quest Premium Pass now to immediately receive:
INTERSTITIAL_SECOND=Earn these additional rewards over the course of the event:
COMPLETED=COMPLETED!
UNCLAIMED_FREE_TRACK_TITLE=Free Pass
UNCLAIMED_PREMIUM_TRACK_TITLE=Premium Pass
UNCLAIMED_REWARDS_TITLE=Battle Pass Rewards
BUY_OUT_CONFIRMATION_TITLE=Buyout?
BUY_OUT_CONFIRMATION_INFO=Are you sure you want to Buyout the rest of your Battle Pass rewards?
BUY_PREMIUM_PASS_TITLE=Premium Pass
BUY_PREMIUM_PASS_INFO=Purchase a Premium Pass now to receive this immediate bonus!
BUY_PREMIUM_PASS_BUYOUT_UPSELL=You will also unlock the Buyout option, which will allow you to purchase any rewards you may miss out on for only:
BUY_OUT_TOOLTIP=Buyout remaining rewards with a Premium Pass!
BATTLE_PASS_COMPLETE=Battle Pass Complete!
UNLOCK_BATTLE_PASS=Reach Team Level %1$d to unlock Battle Pass and claim rewards!
BATTLE_PASS_DELAY=The new Battle Pass will be available soon!
BUY_OUT_COMPLETE=BUYOUT COMPLETE!
BUY_OUT_INFO_BOX_TOOLTIP=Purchase the Premium Pass to unlock the Buyout option, which will allow you to purchase all of these rewards for only:
BUY_OUT_INFO_BOX_TITLE=Buyout Preview
BUY_PREMIUM_PASS_INTERSTITIAL_TITLE=Premium Battle Pass
BUY_PREMIUM_PASS_INTERSTITIAL_INFO=Purchase a Premium Battle Pass now to receive this immediate bonus!
SEASON_PANEL_TITLE=Season %1$d
ACTIVATED=Activated
