
LOADING_ELLIPSIS=Loading...
STARTING_DOWNLOAD=Starting Download...
INSTALLING=Installing...
CONTENT_UPDATE_FAILED_TITLE=Content Update Failed
UPDATING_CONTENT=Updating... %1$d%% %2$s
MB_DOWNLOAD_FORMAT=%1$dMB / %2$dMB
KB_DOWNLOAD_FORMAT=%1$dkb / %2$dkb
LOGIN_SERVER_ERROR=Login Issue
LOGIN_SERVER_ERROR_INFO=There was an issue connecting to the login server. We are aware of this issue and looking into it.
LOGIN_SERVER_STATUS_CODE=Status Code: %1$d
SERVER_ERROR=Server Issue
UPDATE_GAME=Update Game
SOFT_UPDATE_INFO=There is a game update available!
OPEN=Open
UPDATE_OPEN=You're using an old version of Disney Heroes. But never fear, you already have the new version installed!
INSTALL=Install
UPDATE_INSTALL=A new version of Disney Heroes is available! Please migrate to the new app to help us grow the DH community. This adjustment is due to technical changes and does not include a content update. Thanks for supporting us; we look forward to releasing awesome new content in the near future!
UPDATE_TITLE=Update Available
SERVER_MISSING_CONFIG=There was a problem updating stats.
CONNECTION_LOST=Connection Lost
SERVER_DOWN=Unable to connect
RELOAD=Reload
DOWNLOAD_REQUIRED=Download Required
DOWNLOAD_REQUIRED_INFO=Disney Heroes needs to download %1$s of required game content, and you are on a metered network. Press OK to begin the download or the X to quit.
DOWNLOAD_REQUIRED_BEGIN=Begin Download
UPDATE_INFO=Update required! Please visit your app store and update.
UPDATE_INFO_SOON=Update required! It will be in your app store shortly.
UPDATE_INFO_SERVER=The server will be updating shortly.
INVALID_APP=This version of the app is invalid.
SERVER_DOWN_FOR_UPDATE=Server down for update.
NEW_CONNECTION_WAS_CREATED=Your account has logged into a different device.
CONTENT_DOWNLOAD_TITLE=Content Download
CONTENT_DOWNLOAD_INFO=Downloading additional content...
AVOIDING_DOWNLOAD_LOOP=It looks like there is a download loop issue.
COPYRIGHT=©Disney. ©Disney/Pixar.
GOT_IT=Got it
QUIT=Quit
CANCEL=Cancel
TEXTURES_UNSUPPORTED=This version of the app contains textures unsupported by your device and may not render properly. Make sure you've downloaded the app from a supported app store and not a third-party site.
NUM_FIRST_INSTALL_TIPS=7
FIRST_INSTALL_TIP_1=Welcome to Disney Heroes: Battle Mode! Help the Heroes protect the City from mysterious glitches.
FIRST_INSTALL_TIP_2=Unlock and power up Heroes to construct unique teams and discover powerful synergies.
FIRST_INSTALL_TIP_3=Tap white "i"-buttons in game to get more info about something. You can also tap items for more info.
FIRST_INSTALL_TIP_4=We have a friendly community and expect all players to treat each other with respect. Visit the forums to get involved!
FIRST_INSTALL_TIP_5=Most teams should have one of each role: damage, tank, support, and control. But there are always exceptions to the rule!
FIRST_INSTALL_TIP_6=Hero skills make all the difference in combat. Sometimes your strongest team isn't the best for a particular fight. Try mixing it up!
FIRST_INSTALL_TIP_7=Equip badges to Heroes to power them up. After 6 badges, Heroes promote and can learn new skills!
ACCOUNT_SUSPENDED=Your account has been suspended. Reason: %1$s
DEVICE_SUSPENDED=Your device has been suspended. Reason: %1$s
TOU_VIOLATION_SHARING_ACCOUNT=Sharing Account
TOU_VIOLATION_SELLING_ACCOUNT=Selling Account
TOU_VIOLATION_CHEATING=Cheating
TOU_VIOLATION_GOOGLE_REFUNDS=Google Refunds
TOU_VIOLATION_HARASSMENT=Harassment
TOU_VIOLATION_GROOMING=Grooming
TOU_VIOLATION_CHAT_USE=Inappropriate Chat Use
TOU_VIOLATION_THIRD_PARTY_SOFTWARE=Third Party Software
TOU_VIOLATION_CHARGEBACKS=Chargebacks
TOU_VIOLATION_SUSPENDED_DEVICE=Suspended Device
TOU_VIOLATION_OTHER=Other
TOU_VIOLATION_MISCONDUCT=Misconduct
TOU_VIOLATION_GUILD_SABOTAGE=Guild Sabotage
