
RAID_OUTCOME_TITLE=Raiding!
RAID_BONUS_HEADING=Bonus
NO_LOOT_FOUND=No items found.
BATTLE_X=Raid %1$d
ELITE_STAGE_RESETS=More elite stage resets!
NO_MORE_ELITE_RESETS=No more elite resets available for this level.
NEXT=Next
RAID_MAX=Raid Max (%1$d)
ENEMIES=Enemies
LOOT=Loot
DOUBLE_DROP_ITEM_PAUSED=Double Drops Item Paused
DOUBLE_DROP_EVENT_COUNTDOWN_PREFIX=Double Drops:
VIP_BENEFIT_MORE_RAID_TICKETS=More Raid Tickets each day!
NOT_ENOUGH_STAMINA=You don't have enough stamina.
RAID_STARS_REQUIREMENT=Get 3 stars on this level to unlock raiding.
UNLOCK_RAID10=The "Multi-Raid" feature!
RESET=Reset
ELITE_CHANCES_LEFT=Chances left: {%1$s}%2$d{} / %3$d
CAMPAIGN_SCREEN_TITLE=The City
CAMPAIGN_MAINLAND=The Hub
CAMPAIGN_BEAT_NORMAL_TO_UNLOCK_ELITE=Complete the next stage on normal mode to unlock it for elite mode.
CAMPAIGN_MAKE_PROGRESS_TO_UNLOCK=Complete the earlier levels to unlock.
CAMPAIGN_CHAPTER_LOCKED=Reach Team Level %1$d to unlock.
CHAPTER_X_FORMAT=Chapter %1$d
CHAPTER_NAME_FORMAT=Ch%1$d: %2$s
TAB_NORMAL=Normal
TAB_ELITE=Elite
TAB_FRIENDS=Friends
SUMMARY_HEADING=Summary:
ENEMIES_HEADING=Enemies:
LOOT_HEADING=Loot:
NO_LOOT_INFO=Nothing drops on this level.
NO_ENEMIES_INFO=No enemies for this level. Sounds pretty easy!
ELITE_CHANCES_FORMAT=(%1$d/%2$d)
NOT_ENOUGH_RAID_TICKETS=Not enough Raid Tickets.
CHAPTER_COMPLETE_TITLE=Chapter %1$d Complete
CHAPTER_COMPLETE_INFO=You've cleared the virus from this district of the city!
HUB_CHAPTER_COMPLETE_INFO=You've freed this part of the Hub from the Mega Virus!
QUOTE_FORMAT="%1$s"
NORMAL_LEVEL_INCOMPLETE=Finish normal campaign stage %1$s to unlock this stage.
PREV_LEVEL_INCOMPLETE=Finish the previous stage first.
TEAM_LEVEL_NOT_HIGH_ENOUGH=Reach Team Level %1$d to unlock this stage.
INFECTED_STAMP=Infected
INFECTION_CLEARED_HEADING=Virus Cleared!
INFECTION_CLEARED_INFO=Peace and prosperity have returned to %1$s once more.
INFECTION_CLEARED_REWARDS=Rewards:
FRIEND_TOOLTIP_CHAPTER=Episode %1$d: %2$d/%3$d
UNLOCK_CAMPAIGN_LEVEL_ITEM=Unlock Campaign %1$s: %2$s to collect.
NO_ACTIVE_FRIEND_CAMPAIGN=Unlock a friend episode by leveling up your hero friendships!
COMPLETED_ALL_FRIEND_CAMPAIGNS=You have completed all available friendship episodes.
UNLOCK_ELITE_CAMPAIGN_LEVEL_ITEM=Unlock Elite Campaign %1$s: %2$s to collect.
RAID_BUTTON=Raid
RAID_LEFT_BUTTON=Raid (%1$s Left)
ANTI_VIRUS_BUTTON=Anti-Virus
FRIENDSHIP_HELPER_BUTTON=Friend Finder
ELITE_CAMPAIGN=Elite Campaign
FRIEND_CAMPAIGN=Friend Campaign
NEED_FRIEND_PAIR_WITH_LEVEL=Level up a Friend Pair to Friend Level %1$d to unlock the Friend Campaign!
RAID_ALL_BUTTON=Raid All
UNLOCK_ELITE_LEVELS=Unlock Elite Campaign levels to Raid!
RESET_ELITE_CHANCES=Reset Elite Chances?
RESET_THIS_HERO=Reset this Hero only
RESET_ALL_ELITE_CHANCES=Reset all Elite chances
USE_ITEM=Use Item
ALL_ELITE_CHANCES_RESET=All Elite Campaign Chances Reset!
USED_ALL_ELITE_RESETS=You used all resets for this hero today!
NO_ELITE_RAID_TICKETS=You don't have enough raid tickets.
CONFIRM_STAMINA_WINDOW_CONTINUE=Max Raid With Stamina
STAMINA_RAID_MAX_CONFIRMATION=You're currently out of Raid Tickets and will instead spend {#ffe00f}%1$s{} stamina to raid {#ffe00f}%2$s{} times. Are you sure you'd like to continue?
RAID_MAX_CONFIRMATION=You're about to raid {#ffe00f}%1$s{} times and spend {#ffe00f}%2$s{} stamina. Are you sure you'd like to continue?
CONFIRM_WINDOW_CONTINUE=Max Raid With Tickets
CONFIRM_WINDOW_CONTINUE_NO_TICKETS=Max Raid
DROP_BOOSTED=Boost
RAID_MAP=Raid Map
RAID_MAP_MAX=Raid Map Max (%1$d)
RAID_CHAPTER=Raid Chapter
RAID_CHAPTER_MAX=Raid Ch Max (%1$d)
