
CHALLENGES=Challenges
UNLOCK_SLOT=Unlock new challenge slot
PROGRESS=Progress:
TIME=Time Left:
RATIO={#ffe00f}%1$d{} / %2$d
WEEKLY=Weekly:
PICKEM=Pick 'Em:
BOOKS=Books:
COLLECTION=My Challenges
CHALLENGES_COMPLETED=Challenges Completed
BUY=Buy
WEEKLY_CHALLENGE=Weekly
STARTER_CHALLENGE=Starter
PICKEM_CHALLENGE=Pick 'Em
BOOK_CHALLENGE=%1$s Challenge
ADD_CHALLENGE=Add a challenge
CHALLENGE_BOOKS=Challenge Books
BOOK_WITH_NUM=%1$s Book #%2$d
BOOK_NO_NUM=%1$s Book
INCOMPLETE=Incomplete
COMPLETE=Complete
ACTIVATE=Activate
TIME_LIMIT=Time Limit:
CANCEL_TITLE=Cancel Challenge?
CANCEL_TEXT=Are you sure you want to cancel this challenge? You will lose all progress toward completing it.
PURCHASE_CHALLENGE=Purchase Challenge?
PURCHASE_BOOK_TITLE=Purchase Book?
PUCHASE_SINGLE_CHALLENGE=Buy %1$s for %2$d diamonds?
PURCHASE_PROMPT_BOOK=You must purchase the %1$s book to unlock this challenge. Purchase %1$s book for %2$d diamonds?
PURCHASE_BOOK_QUESTION=Buy %1$s?
PURCHASE_NEW_SLOT=Buy extra challenge slot for %1$s diamonds?
FULL_SLOTS=You currently don't have an open slot for a new challenge.
CHALLENGE_ACTIVATED=%1$s Challenge Activated!
LOCKED_BOOK=This book has not been unlocked!
BUY_BOOK=Buy Book
MY_STICKERS=My Stickers
PICK_A_STICK=Pick a sticker to feature in your profile.
TITLE_CHALLENGE_DONE=%1$s Complete!
COMPLETED=Completed
CHALLENGES_PREFIX=Challenges:
PLAYER_COLLECTION=%1$s's Challenges
NO_CHALLENGES=No challenges have been added for this book yet!
NO_STICKERS=No stickers have been unlocked!
NO_BOOKS=No books have been added! Stay tuned!
STICKER_DATE_LOCKED=This sticker is not yet available!
SLOTS_FULL_HEADER=No Slots Available!
RESTART=Restart
PURCHASE_BOOK=You must purchase the %1$s book to unlock this challenge. Purchase %1$s book for %2$s diamonds?
EXTRA_SLOT_TITLE=Extra Slot?
SLOTS_FULL_INFO=All of your challenge slots are currently full! Buy extra challenge slot for %1$s diamonds?
BOOK_COUNT_HEADING=Book:
COMPLETE_PREVIOUS_STARTER_CHALLENGE=Complete the previous starter challenge first!
RESTART_CONFIRM_TITLE=Restart Challenge?
RESTART_CONFIRM_INFO=Are you sure you want to restart this challenge? You will lose all progress toward completing it.
CHALLENGE_SLOT_UNLOCKED=Challenge Slot Unlocked!
VIEW_LIST_BUTTON=View List
VIEW_BOOKS_BUTTON=View Books
NO_CHALLENGES_IN_COLLECTION=%1$s has not completed any challenges yet.
PLAYERS_BOOKS=%1$s's Books
NO_TIME_LEFT=No Time Left
TOTAL_REWARDS=Total Rewards:
COMPLETION_BONUS_COLON=Completion Bonus:
COMING_SOON=Coming Soon
