
CHAT_TEAM_LEVEL_LOCKED=Reach Team Level %1$d to unlock chat!
CHAT_YOU=You
GUILD_APPLICATION_TEXT=I would like to join your guild!
CHAT_ADD_FRIEND=You are now friends with %1$s.
CHAT_REMOVE_FRIEND=You are no longer friends with %1$s.
JUST_NOW_TIME=now
CHAT_POST_HEROES=Post Heroes
HERO_SKILLS=Skills:
HERO_GEAR=Disk:
JOIN_GUILD_TO_USE_GUILD_CHAT=Join a guild to use Guild Chat!
GUILD_CHAT_VIEW_GUILDS_BUTTON=View Recommended Guilds
NEED_VIP_LEVEL_TO_USE_VIP_CHAT=You'll need VIP Level %1$d to participate in VIP Chat.
NEED_VIP_LEVEL_TO_USE_RAID_ALL_CHAPTERS=You'll need VIP Level %1$d to be able to Raid All Chapters.
SEE_VIP_BENEFITS=See All VIP Benefits!
JOIN_A_GUILD_PLACEHOLDER=Not in Guild
CHAT_ACTION_SAVE_EDIT=Save
CHAT_ACTION_PIN=Pin
CHAT_ACTION_PINNED=Pinned
CHAT_ACTION_DELETE=Delete
NO_FRIENDS_INFO=Tap a player in chat to add them as a friend.
CHAT_RULES_ROW=Please respect all players: no profanity, hate speech or spam. Never share your personal information.
BLOCKED_LIST_FULL_TITLE=Blocked List Full
BLOCKED_LIST_FULL_INFO=You have the max number of players blocked. Unblock someone before you can block another player.
BLOCKED_LIST_FULL_BUTTON=View Blocked List
PREVIOUS_NAME_FORMAT=Formerly "%1$s"
CONFIRM_BLOCK_FRIEND_INFO=Are you sure you want to block %1$s, no longer see their chat, and no longer be friends?
CONFIRM_BLOCK_INFO=Are you sure you want to block %1$s and no longer see their chat?
PLAYER_BLOCKED=You have blocked %1$s.
CONFIRM_FRIEND_REMOVAL_INFO=Are you sure you want to remove %1$s as a friend?
FRIEND_REMOVED=You have removed %1$s.
PLAYER_AGE=Player Age: %1$s
GUILD_APPLICATION_DECLINE=Decline
GUILD_APPLICATION_ACCEPT=Accept
CHAT_EMPTY_MESSAGE=No messages here. Post something!
CHAT_PM_STARTED_MESSAGE=This is the start of a thread between you and %1$s.
CANT_VIEW_GUILD_IN_BATTLE=You cannot view a guild while in battle.
CANT_VIEW_STICKERS_IN_BATTLE=You cannot view a collection while in battle.
EDIT=Edit
CONFIRM_DELETE_GUILD_WALL_POST=Are you sure you want to delete this post?
GUILD_APPLICATION_TEXT_FORMAT=%1$s: I would like to join your guild!
CHAT_OPTIONS_TITLE=Chat
PLAYER_WANTS_TO_BE_FRIENDS=wants to be friends.
FRIEND_REQUEST_DECLINED=You declined the request from %1$s.
POST_HEROES_TITLE=Post Heroes
POST_HEROES_WINDOW_ENTER_MESSAGE=Add a Message...
POST_HEROES_SELECTED_FORMAT=Selected: %1$d/%2$d
POST_HEROES_BUTTON=Post to Chat
POST_HEROES_CHOOSE_ERROR=Choose some heroes to post.
POST_HEROES_MAX_ERROR=You can only post 5 heroes max.
CHAT_FRIENDS_LIST_TITLE=Friends List
MODERATE=Moderate
MODERATE_DELETE_CHAT=Delete Chat
CHAT_SILENCE_REASON_FORMAT=Silence: %1$s
CHAT_SILENCE_RESULT_FORMAT=Silenced %1$s for %2$s.
CANT_SILENCE_MODERATOR=You can't silence another moderator. Please report them instead.
MODERATE_WINDOW_INFO=How long do you want to chat silence:
MODERATE_WINDOW_INFO_LINE_2=%1$s (User %2$d)?
CHAT_BUTTON_BLOCK=Block Player
CHAT_BUTTON_REPORT=Report Player
NEW_MESSAGES_BANNER=^^ Back to Top ^^
PLAYER_REPORTED=Thanks for your report.
REPORT_PLAYER_CONFIRM_TITLE=Report Player?
REPORT_PLAYER_CONFIRM_INFO=Are you sure you want to report %1$s?
CLEAR_PM=Clear all private messages from %1$s
TRANSLATE_STEP_ONE=Did you know you can translate text? Tap the translate button at the right to try it.
TRANSLATE_STEP_TWO=Tap it again to translate back.
SPAR=Spar
TRANSLATE=Translate
BLOCK_MESSAGE=You will no longer see them in any chat channel.
REPORT_INFO_1=Are you sure you want to report {#ffe00f}%1$s{} for violating our Terms of Use (ToU) by swearing, harassing players, or discussing inappropriate topics such as sex or illegal activities in chat?
REPORT_INFO_2=Reporting players is a serious action. Please only report players who have actually violated our ToU. Thank you!
PLAYER_REPORTED_NOTIF=You have reported %1$s.
CHAT_SPAR=Chat Spar
ANNOUNCEMENTS_ONLY=This channel is for announcements only.
ANNOUNCEMENTS_MORE_INFO=More Info
CHAT_SPAR_POSTED=Spar results have been posted to chat
CHAT_SPAR_CHAT_MESSAGE=Check out my spar results vs %1$s!
NO_ANNOUNCEMENTS=There are no announcements posted yet.
SETTINGS=Settings
VIP=VIP
GLOBAL=Global
CHAT_HIDDEN_BAR_VIEW=%1$s Chat hidden.
CHAT_HIDDEN_DESCRIPTION=%1$s Chat is currently hidden. This option can be changed in the settings window.
