
DEFAULT=Unspecified Reason
DEFAULT_REASON=An unspecified reason
TOPIC=Topic
TOPIC_REASON=Discussing an inappropriate topic
HARASSMENT=Harassment
HARASSMENT_REASON=Harassing another player
SPAM=Spam
SPAM_REASON=Spamming chat
NAME=Name
NAME_REASON=Having an inappropriate name
LANGUAGE=Language
LANGUAGE_REASON=Using inappropriate language
CLEAN_SPEAK=Language
CLEAN_SPEAK_REASON=Using inappropriate language
SERVTOOL=Language
SERVTOOL_REASON=Using inappropriate language
AUTOMATIC=Automatic
AUTOMATIC_REASON=Sending too many messages in a short period of time
GROOMING=Grooming
GROOMING_REASON=Suspected sexual grooming
