
GOLD_10X_GUARANTEE=Guaranteed Hero!
CHESTS_SCREEN_TITLE=CRATES
SILVER_CHEST_TITLE=Gold Crate
SILVER_CHEST_TITLE_MULTI=Gold Crates
GOLD_CHEST_TITLE=Diamond Crate
GOLD_CHEST_TITLE_MULTI=Diamond Crates
SOUL_CHEST_TITLE=VIP Crate
SOUL_CHEST_TITLE_MULTI=VIP Crates
SOCIAL_CHEST_TITLE=Guild Crate
SOCIAL_CHEST_TITLE_MULTI=Guild Crates
SILVER_CHEST_INFO=Badges & Hero Chips
GOLD_CHEST_INFO=Rare Badges & Full Heroes
SOCIAL_CHEST_INFO=Badges & Featured Hero Chips
SOUL_CHEST_INFO=Featured Hero Chips
CHEST_DETAIL_SCREEN_TAG=WIN THESE GREAT ITEMS & MUCH MORE!
BUY_TEN_SALE_BADGE=10% OFF
FREE_NOW=FREE NOW!
CLAIM_ALL=CLAIM ALL
BUY_NUMBER_FORMAT=BUY %1$d
CHEST_REWARDS_TITLE=CRATE REWARDS
VIEW_BUTTON=VIEW
BUTTON_SWEET=SWEET!
MINIMUM_THIRTY_STONES=
MONTHLY_HERO=FEATURED HERO
DAILY_HEROES=DAILY HEROES
TEN_PERCENT_OFF=10%\nOff!
FREE_IN_PREFIX=Free in: %1$s
VIP_LEVEL_REQUIRED=VIP %1$d Required
SOCIAL_TL_LOCKED=Reach Team Level %1$d and join a guild to unlock the Guild Crate!
SOCIAL_NEED_GUILD=You must be in a guild to unlock the Guild Crate!
EXCLUSIVE_HERO=FEATURED HERO
SAMPLE_ITEMS=SAMPLE ITEMS
GUARANTEED_CHIPS=GUARANTEED CHIPS FOR FEATURED HERO!
BUY_10_CONFIRM_TITLE=Buy Crate?
BUY_10_CONFIRM_INFO=Buy %1$d Diamond Crates for %2$s diamonds?
CHESTS_MULTIBUY_CONFIRM_TITLE=Buy Crates?
CHESTS_MULTIBUY_CONFIRM_INFO=Item: {#ffe00f}%1$s{}\nAmount: {#ffe00f}%2$d{}
GUARANTEED_GEAR=Guaranteed blue badge or better!
GUARANTEED_X_GEAR=Guaranteed %1$s blue badges or better!
NEED_GUILD_TEAM_LEVEL_X=Need Guild, Team Level %1$d
NEED_GUILD=Guild Required
X_PERCENT_OFF_TWO_LINES=%1$d%%\nOff!
EARN_DIAMONDS=Earn Diamonds from Offers and Surveys!
CHESTS_LEFT=Crates Left: {#ffe00f}%1$d{} / %2$d
ENDS_IN_PREFIX=Ends in: %1$s
ENDS_IN_PREFIX_NO_PARAM=Ends in:
PERK_BONUS_BADGE=Perk
DIAMOND_BUNDLE_OPEN=DIAMOND BUNDLE REWARDS
CRATE_UPGRADES=Diamond Crate Upgrades
FREE_UPGRADE=Free Upgrade!
REWARD_TRACK_GOLD=Gold
REWARD_TRACK_XP=Hero XP
REWARD_TRACK_GEAR=Badges
UPGRADE_CHOOSE=Choose
VIEW_UPGRADES=View Current Upgrades
UPGRADES_TITLE=Upgrades
UPGRADE_LEVEL_FORMAT=Level %1$d
UPGRADE_BUTTON=Upgrade
UPGRADE_NEXT_LEVEL=Next Level:
UPGRADES_AVAILABLE=Upgrades Available: %1$s
ONE_TIME_BONUS=One-Time Bonus:
UPGRADE_MAXED=Upgrade Maxed
ONE_TIME_BONUS_UPSELL=If you choose %1$s for your next upgrade, you'll get a one-time bonus of:
OPEN_MORE_CRATES=Open more Diamond Crates to earn an Upgrade!
UPGRADE_TO_OPEN_CRATES=Upgrade first before you buy more crates!
MYSTERY_ITEM_TOOLTIP=Receive a random %1$s badge bit.
TRACK_UPGRADED_FORMAT=%1$s Track Upgraded!
TRACK_BONUS_INFO_TOOLTIP=Choosing other Tracks will add bonus rewards here.
WAITING_FOR_RESULTS=Waiting for results...
DELAYED_CRATE_INFO=Your crate will be delivered as soon as it's ready!
WAITING_BUTTON=Waiting...
CRATE_READY=Crate Ready
CRATE_READY_INFO=The %1$s %2$s you recently purchased or opened has arrived!
DIAMOND_EXCLUSIVE_HERO=Exclusive Hero
DIAMOND_EXCLUSIVE_HERO_INFO=This hero is currently available only in the Diamond Crate and certain special sales.
BUY_GUARANTEE_1=First Buy 10 \n {#ffe00f}Guarantees %1$d Chips!{}
BUY_GUARANTEE_2=Second Buy 10 \n {#ffe00f}Guarantees %1$d Chips!{}
BUY_GUARANTEE_3=Third Buy 10 \n {#ffe00f}Guarantees %1$d Chips!{}
CRATE=crate
EXPEDITION_CHEST_TITLE=City Watch Crate
DIAMOND_BUNDLE_CHEST_TITLE=Diamond Bundle
BUY_GUARANTEE_FREE_BUY1=First Buy 1 \n {#ffe00f}Guarantees %1$d hero FREE!{}
BUY_GUARANTEE_EXCLUSIVE=Each Buy 10 \n {#ffe00f}Guarantees %1$s chips!{}
CRATE_INFO_PARAM=%1$s Info
PRE_ROLL_CRATE_INFO=The contents of this crate are determined when you purchase it.  Rewards will reflect only heroes and items available at the time of purchase. If at any point you have more than a 1000 of these crates in your inventory, a portion of those crates will be automatically opened and their rewards sent to your mailbox to claim.
PRE_ROLL_ORDER_INFO=When opening these crates, newest crates are always opened first.
CRATE_HISTORY=Crate History
CRATE_PURCHASE_DATE_FORMAT=%1$s: %2$d crates
DAILY_HERO_CRATE=Daily Hero Crate
RED_TEAM_HEROES=Red Team Heroes
CONTROL_HEROES=Control Heroes
YELLOW_TEAM_HEROES=Yellow Team Heroes
SUPPORT_HEROES=Support Heroes
BLUE_TEAM_HEROES=Blue Team Heroes
DAMAGE_HEROES=Damage Heroes
TANK_HEROES=Tank Heroes
RED_TEAM_HEROES_TITLE=Red Team Crate
CONTROL_HEROES_TITLE=Control Hero Crate
YELLOW_TEAM_HEROES_TITLE=Yellow Team Crate
SUPPORT_HEROES_TITLE=Support Hero Crate
BLUE_TEAM_HEROES_TITLE=Blue Team Crate
DAMAGE_HEROES_TITLE=Damage Hero Crate
TANK_HEROES_TITLE=Tank Hero Crate
RED_SKILL_TITLE=Red Skill Chip Crate
CODEBASE_TITLE=Megabit Crate
BASE_DROP_CHANCE=Regular Chip Base Chance
WISH_LEVEL_REQUIRED=Team Level %1$d\nor VIP %2$d Required
WISHING_WELL_TARGET=Wish Crate Target
LIST_JUMP_TO=Jump To:
WISHING_WELL_TITLE=Wish Crate
WISHING_WELL_INFO=Get the hero that YOU want! Choose the {#3dc562}Jackpot Hero{} reward for the Wish Crate and earn all of the Hero Chips you need. The {#3dc562}Jackpot Odds{} get better the more you roll!
JACKPOT_INFO=Congratulations on winning the Jackpot!
WISHING_WELL_OTHER_REWARDS_TITLE=Other Reward Examples
CHOOSE_WISHING_WELL_HERO_ACTION=Choose
WISHING_WELL_POSSIBLE_REWARDS=Possible Rewards
WISHING_WELL_HERO_CHIPS_TITLE=Regular Chip Chances
WISHING_WELL_JACKPOT_TITLE=Jackpot Chip Chances
WISHING_WELL_ODDS_RESET=Reset!
WISHING_WELL_JACKPOT=Jackpot!
WISHING_WELL_RESET_CONFIRMATION=Are you sure you want to select a new hero for the Wish Crate?  All of your chances will reset!
WISHING_WELL_RESET_TITLE=Change Hero?
BETTER_ODDS=Better Odds!
WISH_CRATE=Wish Crate
WISH_CRATE_SUBTEXT=Choose Your Rewards
BUY_X_CHESTS=Buy X
BUY_CONFIRM_TITLE=Buy Crate?
BUY_CONFIRM_INFO=Buy %1$d more Crate
