
FREEZE=Units affected by Freeze slowly become unable to move, attack, or use skills for a period of time.
STUN=Stunned units are unable to move, attack, or use skills.
SILENCE=Silenced units are unable to use skills.
CHARM=Charmed units attack their allies but are still targeted by their enemies. Charmed units cannot use their White Skills.
SCARE=Fantastic Damage always Crits against Scared units.
STUDY=Normal Damage always Crits against Studied units.
SLOW=Attack Speed and Movement Speed Decreases count as Slows.
SAP=All energy gained by Sapped units is reduced by half.
CURSE=All healing received by Cursed units is reduced by half.
DAMAGE_OVER_TIME=Damage is dealt over a period of time to the target.
KNOCKBACK=Pushes the target back a distance.
BLIND=Basic attacks from Blinded units always miss.
VULNERABLE=Vulnerable heroes are damaged whenever they receive a buff
FREEZE_NAME=Freeze
STUN_NAME=Stun
SILENCE_NAME=Silence
CHARM_NAME=Charm
SCARE_NAME=Scare
STUDY_NAME=Study
SLOW_NAME=Slow
SAP_NAME=Sap
CURSE_NAME=Curse
DAMAGE_OVER_TIME_NAME=Damage Over Time
KNOCKBACK_NAME=Knockback
BLIND_NAME=Blind
VULNERABLE_NAME=Vulnerable
