
COLLECTIONS=Collections
COLLECTIONS_COLON=Collections:
COLLECTION=Collection
COSMETICS=Cosmetics
HERO_MASTERY=Hero Mastery
LEVEL_MAXED=Level Maxed!
HEROES_MASTERED=Heroes Mastered:
DETAILS_BUTTON=Details
NUM_HEROES_TITLE=(%1$s Heroes)
MASTERY_TOOLTIP_NEXT_LEVEL=To reach the next level in this collection tier, you need to {#ffe00f}master %1$s %2$s-star heroes.{}
MASTERY_TOOLTIP_MASTER_HERO=To master a hero, you must win {#ffe00f}%1$s fights{} with that hero in {#ffe00f}City Watch, Creep Surge, or Invasion Breaker Fights.{}
LOCKED_HEROES=Locked Heroes
STARS_OR_HIGHER=%1$d Stars or Higher
N_TO_M_STARS=%1$d to %2$d Stars
TIER_LEVEL_MASTERED=%1$s Level %2$s mastered!
COLLECTIONS_SHOP=Hero Mastery Shop
AVATAR_BORDERS=Avatar Borders
AVATAR_BADGES=Avatar Badges
AVATAR_TIER_LABEL=-- Tier %1$s --
BADGE_LOCK_TOOLTIP=Achieve %1$s master levels in %2$s to unlock.
CURRENT_AVATAR=Current Avatar
EDIT_BORDER=Edit Border
REMOVE_BORDER=Remove Border
CHOOSE_AVATAR_BORDER=Choose Avatar Border
CHOOSE_AVATAR_BORDER_DESC=Choose a custom border for your avatar icon!
COLLECTION_BORDERS=Collection Borders
COMPLETE_COLLECTION_MSG=Buy this border in the Hero Mastery Shop to unlock!
UNLOCK_BORDERS=Unlock Borders
UNLOCK_BORDERS_MSG=Spend Mastery Tokens at the Hero Mastery Shop to buy cool Avatar Borders, and exclusive Collection Avatars!
UNLOCK_TIER_MSG=Master %1$s to Unlock
TIER_COMPLETE =Tier Complete!
COLLECTION_BUFFS=Collection Buffs:
LEVELS_MASTERED=Levels Mastered
BUFF=Buff
COLLECTIONS_HERO_MASTERED=%1$s Mastered!
HERO_MASTERED_SUBTITLE="%1$s" Collection, %2$s %3$s
MASTER_MORE_TO_COMPLETE=Master %1$d more heroes to complete %2$s %3$s
VIEW_COLLECTION=View Collection
BUFFS_COLON=Buffs:
VIEW_TO_CLAIM=View collection to claim your rewards!
COLLECTIONS_C=C
PROGRESS_FORMAT=%1$d/%2$d
LEVEL_FORMAT=Level {#ff9000}%1$s{}
PROGRESS_SPACED_FORMAT=%1$d / %2$d
POINTS_FORMAT=%1$d points
FILTER_NAME=By Name
FILTER_PROGRESS=By Progress
COSMETICS_REWARDS=Cosmetics Rewards
MAX=Max
COSMETICS_CARD_TITLE=Cosmetics
COSMETICS_CARD_SUBTITLE=Complete sets for Rewards!
HERO_MASTERY_CARD_TITLE=Hero Mastery
HERO_MASTERY_CARD_SUBTITLE=Train groups of heroes for bonuses!
REWARD_STAT_FORMAT=+%1$s%% %2$s
REWARD_STAT_IMPROVED_FORMAT={#ffe000}+%1$s%%{} %2$s
HERO_STATS=Hero Stats
LEVEL_TO_PREVIEW=Level up to Preview more!
TOOLTIP_LOCKED=Unlock {#ffe000}%1$s{} from a cosmetic crate.
TOOLTIP_LOCKED_SHOP=Unlock {#ffe000}%1$s{} from the Hero Mastery shop.
TOOLTIP_LOCKED_EXCLUSIVE=Unlock {#ffe000}%1$s{} from participating in Special Events
TOOLTIP_LOCKED_STICKER=Unlock {#ffe000}%1$s{} from a cosmetic crate or by completing the {#ffe000}%2$s{} challenge.
TOOLTIP_LOCKED_ANNIVERSARY=Unlock {#ffe000}%1$s{} by earning the "Happy 3rd Anniversary!" Medal (only available during the 3rd Anniversary event)
TOOLTIP_DUPLICATE=You already have {#ffe000}%1$s{}, so we gave you {#ffe000}%2$d{} Cosmetic Reward Points instead!
AVATAR_BORDER_DESC=Avatar Border you can use to embellish your Avatar.
AVATAR_DESC=Can be used as your player Avatar.
EMOJI_DESC=Emoji you can use in chat.
COSTUMES_DESC=Can be applied to a hero to change their appearance in combat.
AVATAR_FORMAT=%1$s Avatar
EMOJI_SMILE_FORMAT=%1$s Smile Emoji
EMOJI_EXCITE_FORMAT=%1$s Excited Emoji
EMOJI_GROSS_FORMAT=%1$s Gross Emoji
EMOJI_LOVE_FORMAT=%1$s Love Emoji
EMOJI_POWER_FORMAT=%1$s Power Emoji
EMOJI_SCARED_FORMAT=%1$s Scared Emoji
EMOJI_SLEEP_FORMAT=%1$s Sleep Emoji
EMOJI_SURPRISE_FORMAT=%1$s Surprise Emoji
EMOJI_FORMAT=%1$s Emoji
ICON_DUPE_HEADER=Dupe!
ICON_DUPE_PLUS=+%1$d
REWARDS_COLON=Rewards:
TOTAL_STAT_BOOSTS=Total Stat Boosts
EXTRA_BOOST=Extra Boost!
COMMON=Common
UNCOMMON=Uncommon
RARE=Rare
LEGENDARY=Legendary
COSMETIC_REWARDS_FIRST_CARD=Complete Cosmetic Sets to level up!
ALL_COSMETICS_WARNING_TITLE=Are you sure?
ALL_COSMETICS_WARNING_INFO=You currently own all of the cosmetics available from this crate and opening it will only award you duplicates for Reward Level Points. Are you sure you want to open this Guaranteed Crate?
