
ALICE_IN_WONDERLAND_TITLE=Alice In Wonderland
CHARM_TITLE=Charm
CONTROL_TITLE=Control
DAMAGE_TITLE=Damage
INCREDIBLES_TITLE=Incredibles
SHIELDS_TITLE=Shields
STUN_TITLE=Stun
SUPPORT_TITLE=Support
TANK_TITLE=Tank
TOY_STORY_TITLE=Toy Story
ZOOTOPIA_TITLE=Zootopia
HERO_EMOJIS_TITLE=Hero Emojis
HERO_AVATARS_TITLE=Hero Avatars
MISC_EMOJIS_TITLE=Emojis
MISC_AVATARS_TITLE=Avatars
AVATAR_BORDERS_TITLE=Avatar Borders
COSTUMES_TITLE=Costumes
NPC_AVATARS_FORMAT=Creep Avatars #%1$d
EMOJIS_FORMAT=Emojis #%1$d
AVATAR_BORDERS_FORMAT=Avatar Borders #%1$d
STICKER_AVATARS_FORMAT=Sticker Avatars #%1$d
COSTUMES_FORMAT=Costumes #%1$d
BADGE_AVATARS_FORMAT=Badge Avatars #%1$d
EMOJI_AVATARS_FORMAT=Emoji Avatars #%1$d
KRISTOFF_NAME=Kristoff
GERALD_NAME=Gerald
MARLIN_NAME=Marlin
NEMO_NAME=Nemo
HANK_NAME=Hank
DORY_NAME=Dory
SIMBA_NAME=Simba
NALA_NAME=Nala
TIMON_NAME=Timon
PUMBAA_NAME=Pumbaa
ALICE_IN_WONDERLAND_BUFF_TITLE=Chance to Stun
ALICE_IN_WONDERLAND_BUFF_DESC=Characters in this collection have a %1$s%% chance to stun on basic attacks.
ALICE_IN_WONDERLAND_BUFF_STAT=+%1$s%% Chance to Stun
CHARM_BUFF_TITLE=Extra Skill Power
CHARM_BUFF_DESC=Characters in this collection gain %1$s%% Skill Power.
CHARM_BUFF_STAT=+%1$s%% Skill Power
CONTROL_BUFF_TITLE=Reduce Enemy Energy Gain
CONTROL_BUFF_DESC=Enemy team gains %1$s%% less energy for each character in this collection on your team.
CONTROL_BUFF_STAT=%1$s%% Enemy Energy Gain
DAMAGE_BUFF_TITLE=Extra Damage
DAMAGE_BUFF_DESC=Damage characters do %1$s%% more damage to other Damage characters.
DAMAGE_BUFF_STAT=+%1$s%% Extra Damage
INCREDIBLES_BUFF_TITLE=Extra HP
INCREDIBLES_BUFF_DESC=Characters in this collection gain %1$s%% HP.
INCREDIBLES_BUFF_STAT=+%1$s%% HP
SHIELDS_BUFF_TITLE=Damage Reduction
SHIELDS_BUFF_DESC=Shields reduce damage taken by %1$s%%.
SHIELDS_BUFF_STAT=+%1$s%% Reduced Shield Damage
STUN_BUFF_TITLE=Heal When Stunned
STUN_BUFF_DESC=Heal %1$s%% of missing HP when stunned.
STUN_BUFF_STAT=+%1$s%% Missing HP
SUPPORT_BUFF_TITLE=Starting Energy
SUPPORT_BUFF_DESC=Team starts with %1$s extra energy for each Support on your team.
SUPPORT_BUFF_STAT=+%1$s Energy
TANK_BUFF_TITLE=Extra Armor
TANK_BUFF_DESC=Team gains %1$s%% Armor for each Tank on your team.
TANK_BUFF_STAT=+%1$s%% Armor
TOY_STORY_BUFF_TITLE=Extra Basic Damage
TOY_STORY_BUFF_DESC=Characters in this collection gain %1$s%% Basic Damage.
TOY_STORY_BUFF_STAT=+%1$s%% Basic Damage
ZOOTOPIA_BUFF_TITLE=Extra Reality
ZOOTOPIA_BUFF_DESC=Characters in this collection gain %1$s%% Reality.
ZOOTOPIA_BUFF_STAT=+%1$s%% Reality
WRECK_IT_RALPH_BUFF_TITLE=Extra Energy
WRECK_IT_RALPH_BUFF_DESC=Characters in collection gain an extra %1$s%% energy from taking fantastic damage.
WRECK_IT_RALPH_BUFF_STAT=+%1$s%% Energy
HEALERS_BUFF_TITLE=Extra Healing
HEALERS_BUFF_DESC=Allies regain %1$s%% more HP when you heal them. Effect is doubled on Tanks.
HEALERS_BUFF_STAT=+%1$s%% Healing
WRECK_IT_RALPH_TITLE=Wreck-It Ralph
HEALERS_TITLE=Healers
DUCKTALES_TITLE=DuckTales
DUCKTALES_BUFF_TITLE=Extra Energy Conservation
DUCKTALES_BUFF_DESC=Characters in collection gain %1$s%% energy Conservation.
DUCKTALES_BUFF_STAT=+%1$s%% Conservation
PRINCESS_TITLE=Princesses
PRINCESS_BUFF_TITLE=Longer Buffs
PRINCESS_BUFF_DESC=Buffs last %1$s%% longer on characters in this collection.
PRINCESS_BUFF_STAT=+%1$s%% Longer Buffs
INSIDE_OUT_TITLE=Inside Out
INSIDE_OUT_BUFF_TITLE=Extra Energy Regen
INSIDE_OUT_BUFF_DESC=Team gains %1$s Energy Regen for each character in this collection on your team.
INSIDE_OUT_BUFF_STAT=+%1$s Energy Regen
MUPPETS_TITLE=The Muppets
MUPPETS_BUFF_TITLE=Extra Skill Power to Team
MUPPETS_BUFF_DESC=Team gains %1$s%% Skill Power for each character in this collection on your team.
MUPPETS_BUFF_STAT=+%1$s%% Skill Power
BIG_HERO_SIX_TITLE=Big Hero 6
BIG_HERO_SIX_BUFF_TITLE=Beginning of Wave Shield to Team
BIG_HERO_SIX_BUFF_DESC=Team gains %1$s%% of their Max HP as a Shield for each character in this collection on your team at the start of each wave.
BIG_HERO_SIX_BUFF_STAT=+%1$s%% Max HP as Shield
FROZEN_TITLE=Frozen
FROZEN_BUFF_TITLE=Heal from Freezes
FROZEN_BUFF_DESC=Characters in this collection Heal for %1$s%% of their Max HP when an enemy is Frozen from any source.
FROZEN_BUFF_STAT=+%1$s%% Max HP Heal
LILO_AND_STITCH_TITLE=Lilo and Stitch
LILO_AND_STITCH_BUFF_TITLE=Chance to Remove Hardy
LILO_AND_STITCH_BUFF_DESC=Team gains %1$s%% chance to remove a stack of Hardy with Basic Attacks for each Lilo and Stitch character included.
LILO_AND_STITCH_BUFF_STAT=+%1$s%% Removal Chance
MICKEY_AND_FRIENDS_TITLE=Mickey and Friends
MICKEY_AND_FRIENDS_BUFF_TITLE=Chance to Remove Debuffs
MICKEY_AND_FRIENDS_BUFF_DESC=Characters in this collection have %1$s%% chance to remove a random Debuff from themselves with Basic Attacks.
MICKEY_AND_FRIENDS_BUFF_STAT=+%1$s%% Removal Chance
HERCULES_TITLE=Hercules
HERCULES_BUFF_TITLE=Bonus Energy Per Basic Attack
HERCULES_BUFF_DESC=Characters in this collection gain %1$s bonus Energy per Basic Attack for each Hercules Hero on your team.
HERCULES_BUFF_STAT=+%1$s Energy
ATLANTIS_TITLE=Atlantis
ATLANTIS_BUFF_TITLE=Shield for Normal Damage
ATLANTIS_BUFF_DESC=Characters in this collection gain %1$s%% of any Normal Damage they deal as a Shield.
ATLANTIS_BUFF_STAT=+%1$s%% Normal Damage converted to Shield
TANGLED_TITLE=Tangled
TANGLED_BUFF_TITLE=Chance to Study with Basic Attacks
TANGLED_BUFF_DESC=Characters in this Collection have a %1$s%% chance to Study on Basic Attacks.
TANGLED_BUFF_STAT=+%1$s%% chance to Study
NIGHTMARE_BEFORE_CHRISTMAS_TITLE=The Nightmare Before Christmas
NIGHTMARE_BEFORE_CHRISTMAS_BUFF_TITLE=Chance to Scare and Disable
NIGHTMARE_BEFORE_CHRISTMAS_BUFF_DESC=Heroes in this Collection have a %1$s%% chance to inflict Scare and a random Disable upon dealing damage. Disables include Stun, Freeze, Blind, Silence, and Charm.
NIGHTMARE_BEFORE_CHRISTMAS_BUFF_STAT=+%1$s%% chance to inflict Scare and a random Disable
KIM_POSSIBLE_TITLE=Kim Possible
KIM_POSSIBLE_BUFF_TITLE=Chance to Stun and Silence
KIM_POSSIBLE_BUFF_DESC=Characters in this collection gain %1$s%% chance to Stun and Silence enemies with their Basic Attacks.
KIM_POSSIBLE_BUFF_STAT=+%1$s%% Stun and Silence Chance
MULAN_TITLE=Mulan
MULAN_BUFF_TITLE=Increased Attack and Movement Speed
MULAN_BUFF_DESC=Heroes in this collection gain %1$s%% Attack Speed and Movement Speed for 10 seconds each time they cast their Skills. The buff effects of this Collection are active once at a time per Hero and do not stack with each Hero's Skill usage.
MULAN_BUFF_STAT=%1$s%% Attack Speed and Movement Speed
