
MISS=Miss
SILENCE=Silence
CHARMED=Charmed
CURSED=Cursed
LINK=Link
ABSORBED=Absorbed
LINK_MEGARA=Select a hero to {#ea00ff}link{} to Megara
DISABLE_EVADE=Evade
CHOOSE_ACTION=Select an Action!
AUTOSELECT_IN=Auto-select in:
CHOOSE_TARGET=Select a Target
BLOCKED=Blocked
LINK_PHIL=Select a hero to {#ea00ff}link{} to Phil
