
TEAM_POWER_PREFIX=Team Power:
FIGHT_BUTTON=Fight
LINEUP_FULL_ERROR=Your lineup is full.
LINEUP_ALREADY_HAS_TYPE_ERROR=You already have %1$s in your lineup.
HERO_TOO_LOW_LEVEL_FOR_EXPEDITION=Your hero needs to be level %1$d to join the City Watch.
CRYPT_HERO_ALREADY_USED=%1$s has already been used and cannot be used until the Creep Surge restarts.
WAR_HERO_ALREADY_USED=%1$s has already been used and cannot be used until the next War.
WAR_HERO_OFF_DUTY=%1$s is off duty and cannot be used until the next War.
CHOOSER_NO_UNITS_CHOSEN=Choose some heroes from the list below!
TUTORIAL_CANT_DO_THAT_YET=You can't do that just yet. Follow the tutorial arrow.
FIGHT_PIT_NO_HERO_SELECTED_DETAIL=You haven't selected any heroes to defend with! Please select at least one hero.
NO_HERO_SELECTED_DETAIL=You haven't selected any heroes to participate in combat! Please select at least one hero.
USE_YOUR_OWN_HERO=You must have at least one of your own heroes in your lineup to fight.
MORE_HEROES_SELECTABLE_DETAIL=You have additional heroes that could be used. Start fight without them?
FIGHT_PIT_MORE_HEROES_SELECTABLE_DETAIL=You have additional heroes that could be used. Are you sure you want to set your defense without them?
MORE_HEROES_SELECTABLE=Are You Sure?
SELECT_HEROES=Select Heroes
FIGHT_PIT_CHOOSER_TITLE=Arena Station
CRYPT_CHOOSER_TITLE=Surge Station
TEAM_TRIALS_CHOOSER_TITLE=Team Trials Station
PORT_CHOOSER_TITLE=Port Station
EXPEDITION_CHOOSER_TITLE=City Watch Station
TEAM_PREFIX=Team:
MY_POWER_PREFIX=My Power:
ENEMY_POWER_PREFIX=Enemy:
COLISEUM_CHOOSER_TITLE=Coliseum Station
NEED_AT_LEAST_ONE_HERO_PER_TEAM=You need at least one hero on each team.
HIRE=Hire
JOIN_GUILD_TO_HIRE_HERO_NOTIF=Join a guild to hire a mercenary!
CANT_DISABLE_AUTO_ATTACK_FIGHT_PIT=Auto attack cannot be disabled in the Arena.
PAUSED_WINDOW_TITLE=Paused
PAUSED_RETREAT_BUTTON=Retreat
PAUSED_SETTINGS_BUTTON=Settings
TAP_TO_CONTINUE=Tap to Continue
CANT_DISABLE_AUTO_ATTACK_COLISEUM=Auto attack cannot be disabled in the Coliseum.
VICTORY_WINDOW_TITLE=Victory
DEFEAT_WINDOW_TITLE=Defeat
VICTORY_REWARDS=Rewards
VICTORY_LOOT=Loot:
VICTORY_ITEMS=Items:
VICTORY_HERO_XP=Hero XP:
XP_PREFIX=Hero XP:
RE_RUN_BUTTON=Re-Run
DEFEAT_SUBTITLE=You'll get 'em next time!
DEFEAT_TIP_1_TITLE=Level Up Your Heroes
DEFEAT_TIP_1_TEXT=Win fights and use XP drinks to level up your heroes!
DEFEAT_TIP_2_TITLE=Upgrade Your Skills
DEFEAT_TIP_2_TEXT=Upgrade your hero skills and equip badges!
DEFEAT_COMBAT_TIPS=Combat Tips
COLISEUM_HERO_XP_FORMAT=All heroes received {#3ec07b}%1$s xp{}
COLISEUM_RESULTS_HEADING=Results
COLISEUM_ROUND_FORMAT=Round %1$d
COMBAT_STATS_TITLE=Combat Stats
DAMAGE_DEALT=Damage Dealt
DAMAGE_TAKEN=Damage Taken
HEALING_DONE=Healing Done
DAMAGE_TYPE_TOTAL=Total
DAMAGE_TYPE_PHYSICAL=Normal
DAMAGE_TYPE_MAGIC=Fantastic
DAMAGE_TYPE_TRUE=TRUE
STATS=STATS
EXPEDITION_CHOOSER_HERO_DEAD=This hero is KO'd and can no longer join this City Watch.
FAST_FORWARD_UPSELL=Enhanced Fast Forward: No need to 3-star battles first!
RETREAT_AND_VIEW_BENEFITS=Retreat and View Benefits
COMBAT_TEXT_DODGE=Dodge
PHYSICAL_IMMUNE=Resist
UNLOCK_CLEAR_COLISEUM_COLLDOWN=the ability to clear Coliseum cooldowns!
UNLOCK_CLEAR_FIGHT_PIT_COLLDOWN=the ability to clear Arena cooldowns!
UNLOCK_RESET_COLISEUM_CHANCES=%1$d daily Coliseum challenge resets!
UNLOCK_RESET_FIGHT_PIT_CHANCES=%1$d daily Arena challenge resets!
ENEMY_POWER_FULL_PREFIX=Enemy Power:
QUICK_FIGHT_BUTTON=Quick Fight
QUICK_FIGHT_POWER_NEEDED=Your team power is too low to Quick Fight!
QUICK_FIGHT_ERROR=There was an issue running Quick Fight.
QUICK_FIGHT_NEED_WIN=You must win a fight before you can Quick Fight again.
DAMAGE=Damage
INVINCIBLE=Resist
COMBAT_PAUSED_RETREAT=Retreat
COMBAT_PAUSED_ABANDON=Abandon
COMBAT_PAUSED_CRYPT_INFO=Note: Abandoning a Creep Surge will "use" all of your chosen heroes.
COMBAT_PAUSED_RESUME=Resume
COMBAT_PAUSED_TITLE=Paused
FAST_FORWARD_LOCKED=Fast Forward unlocks at Team Level %1$d or VIP Level %2$d.
WAVE_BUTTON_FORMAT=Wave %1$d
DAMAGE_HEADER=Damage:
HEALING_HEADER=Healing:
DEFEAT_SHOW_ME_BUTTON=Show Me
DEFEAT_EVOLVE_TITLE=Evolve %1$s!
DEFEAT_EVOLVE_INFO=You have enough Chips to give %1$s another star!
DEFEAT_PROMOTE_TITLE=Promote %1$s!
DEFEAT_PROMOTE_INFO=%1$s has a full set of badges. Time to Promote.
DEFEAT_LEVEL_TITLE=Level-up %1$s!
DEFEAT_LEVEL_INFO=%1$s is falling behind in levels. Use XP Drinks to level up.
DEFEAT_GEAR_TITLE=Equip Badges!
DEFEAT_GEAR_INFO=You have a badge you can give to %1$s!
DEFEAT_SKILL_TITLE=Upgrade Skills!
DEFEAT_SKILL_INFO=%1$s's Skills seem to be falling behind. Upgrade some of them.
DEFEAT_POWER_TITLE=Replace %1$s
DEFEAT_POWER_INFO=%1$s looks like your weakest hero. Try changing your lineup and trying again.
DEFEAT_POWER_TITLE_FRIEND_CAMPAIGN=Try Again
DEFEAT_POWER_INFO_FRIEND_CAMPAIGN=Don't give up! Try turning off Auto mode and using Active Skills in interesting combinations.
ARMOR_DECREASE=Armor Decreased
ARMOR_INCREASE=Armor Increased
REALITY_DECREASE=Reality Decreased
REALITY_INCREASE=Reality Increased
BULLSEYE=Bullseye (Woody)
DAMAGE_INCREASE=Damage Increased
DAMAGE_DECREASE=Damage Decreased
SKILL_POWER_INCREASE=Skill Power Increased
SKILL_POWER_DECREASE=Skill Power Decreased
ATTACK_SPEED_INCREASE=Attack Speed Increased
ATTACK_SPEED_DECREASE=Attack Speed Decreased
MOVE_SPEED_INCREASE=Move Speed Increase
MOVE_SPEED_DECREASE=Move Speed Decreased
BLIND=Blinded
CHARM=Charmed
SHIELD=Shielded
SILENCE=Silenced
STUN=Stunned
ARMOR_DECREASE_DESC=Armor stat is decreased.
ARMOR_INCREASE_DESC=Armor stat is increased.
REALITY_DECREASE_DESC=Reality stat is decreased.
REALITY_INCREASE_DESC=Reality stat is increased.
BULLSEYE_DESC=Gain HP each time you damage this enemy.
DAMAGE_INCREASE_DESC=Basic damage increased.
DAMAGE_DECREASE_DESC=Basic damage decreased.
SKILL_POWER_INCREASE_DESC=Skill Power increased.
SKILL_POWER_DECREASE_DESC=Skill Power decreased.
ATTACK_SPEED_INCREASE_DESC=Attack speed increased.
ATTACK_SPEED_DECREASE_DESC=Attack speed decreased.
MOVE_SPEED_INCREASE_DESC=Movement speed increased.
MOVE_SPEED_DECREASE_DESC=Movement speed decreased.
BLIND_DESC=Basic attacks always miss.
CHARM_DESC=Attacks allies (enemies still attack you).
SHIELD_DESC=Absorbs damage until out of HP or out of time.
SILENCE_DESC=Unable to use skills.
STUN_DESC=Unable to do anything.
COMBAT_STATUS_ICONS=Combat Status Icons
ICON=Icon
STATUS=Status
DESCRIPTION=Description
STATUS_ICONS=Status Icons
SCARED=Scared
SCARED_DESC=Fantastic damage will always crit.
STUDIED=Studied
STUDIED_DESC=Normal damage will always crit.
CURSED=Cursed
CURSED_DESC=All healing received is reduced by half.
EVENT_BUFF=Powered Up
EVENT_BUFF_DESC=Power is increased during event.
FAST_FORWARD_LOCKED_AB_TEST=Fast Forward unlocks at Team Level %1$d!
DOUBLE_HERO_XP_COUNTDOWN_FORMAT=Double Hero XP ends in: %1$s
MAUI_BUFF=Courage (Maui)
MAUI_BUFF_DESC=Gains more energy from being damaged.
COLI_CLEAR_TITLE=Clear All Teams
COLI_CLEAR_INFO=Do you want to clear all of your teams?
HEX=Hexed
HEX_DESC=This unit will be stunned when using its Active ability.
TOONED_UP=Tooned Up (Mickey)
TOONED_UP_DESC=All damage done increased.
DEFEAT_MODS_TITLE=Equip Mods!
DEFEAT_MODS_INFO=You have a Mod you can equip to %1$s!
LINKED=Linked
LINKED_DESC=This unit is linked to another Hero.
INVINCIBLE_BUFF=Invincible
INVINCIBLE_BUFF_DESC=This unit is immune to damage from all sources.
GROOVY=Groovy (Goofy)
GROOVY_DESC=This unit will heal more per Groovy with "Bust a Move."
MONITORED=Monitored
MONITORED_DESC=Takes periodic damage and has portion of energy stolen.
RAGE=Rage (Anger)
RAGE_DESC=Anger's skills become more powerful with each stack of "Rage."
HAPPINESS=Happiness (Joy)
HAPPINESS_DESC=Joy's skills become more powerful with each stack of "Happiness."
BERSERK=Berserk
BERSERK_DESC=This unit's health cannot fall below 1 HP.
HAKUNA_MATATA=Hakuna Matata (Timon and Pumbaa)
HAKUNA_MATATA_DESC=This unit has increased armor and heals HP every second.
MADAM_MIM_SKILL1=Wizard Duel (Madam Mim)
MADAM_MIM_SKILL1_DESC=Madam Mim will transform into a tiger, a dragon, or a crocodile with "Wizard Duel" depending on the last enemy Hero to use an active ability.
CHARGED=Charged (Megavolt)
CHARGED_DESC=This unit will take more damage per stack of "Charged" from Megavolt's skills.
MOST_WANTED=Most Wanted
MOST_WANTED_DESC=The Most Wanted enemy is the one who has dealt the most damage in the battle.
SAPPED=Sapped
SAPPED_DESC=All energy gained is reduced by half.
HARDY=Hardy
HARDY_DESC=Each stack of "Hardy" will block a debuff applied to this unit.
HUNNY=Hunny (Winnie the Pooh)
HUNNY_DESC=Each stack of "Hunny" increases the damage this unit takes from bees.
TENACITY_INCREASE=Tenacity Increased
TENACITY_INCREASE_DESC=Tenacity stat is increased.
TENACITY_DECREASE=Tenacity Decreased
TENACITY_DECREASE_DESC=Tenacity stat is decreased.
BOUNCY=Bouncy (Tigger)
BOUNCY_DESC=For every stack, Tigger's "Super Bounce" will hit an additional enemy and Tigger's "Spring Into Action" cooldown will be reduced.
RED_DOT=Red DOT
RED_DOT_DESC=Attack and movement speed slowed, and taking damage over time
EVIL_QUEEN_MARKED=Marked (Evil Queen)
EVIL_QUEEN_MARKED_DESC=Takes more damage from The Evil Queen's attacks and abilities.
IMMUNE=Immune
PRECISE=Precise
PRECISE_DESC=Precise heroes can target invisible enemies and their attacks cannot be dodged or evaded.
MOSQUITO=Mosquitoes (Pleakley)
MOSQUITO_DESC=Each stack of "Mosquitoes" makes Pleakley's skills against this unit more powerful.
FATIGUE=Fatigue
FATIGUE_DESC=Each stack of "Fatigue" will block a buff applied to this unit.
AUTO_NOT_UNLOCKED=Auto Fight unlocks at Team Level %1$d!
NORMAL_CRIT_INCREASE=Normal Crit Increased
NORMAL_CRIT_INCREASE_DESC=Normal Crit stat is increased.
NORMAL_CRIT_DECREASE=Normal Crit Decreased
NORMAL_CRIT_DECREASE_DESC=Normal Crit stat is decreased.
FANTASTIC_CRIT_INCREASE=Fantastic Crit Increased
FANTASTIC_CRIT_INCREASE_DESC=Fantastic Crit stat is increased.
FANTASTIC_CRIT_DECREASE=Fantastic Crit Decreased
FANTASTIC_CRIT_DECREASE_DESC=Fantastic Crit stat is decreased.
REFLECT=Reflect
REFLECT_DESC=Heroes with Reflect prevent %d%% of incoming damage. %d%% of incoming damage is also returned to the enemy who dealt the damage.\n\nReflected damage cannot Crit, be Dodged, or Reflected again.
SORROW=Sorrow (Sadness)
SORROW_DESC=Sadness's skills become more powerful with each stack of "Sorrow."
EVASION_INCREASE=Evasion Increased
EVASION_INCREASE_DESC=Evasion stat is increased.
EVASION_DECREASE=Evasion Decreased
EVASION_DECREASE_DESC=Evasion stat is decreased.
FROST=Frost
FROST_DESC=This unit will take more damage while frozen for each stack of "Frost."
DISTASTE=Distaste (Disgust)
DISTASTE_DESC=Disgust's skills become more powerful with each stack of "Distaste."
WEAKNESS=Weakness
WEAKNESS_DESC=This unit will take more damage for each stack of "Weakness."
ENERGIZED=Energized
ENERGIZED_DESC=This unit gains more energy each time they perform a basic attack.
MANTICORE_FAVORITE=Favorite (The Manticore)
MANTICORE_FAVORITE_DESC=Preferred target of The Manticore.
FEAR_DREAD=Dread (Fear)
FEAR_DREAD_DESC=Fear's skills become more powerful with each stack of "Dread."
GREEN_SKILL_LEVEL_DECREASE=Green Skill Level Decrease
GREEN_SKILL_LEVEL_DECREASE_DESC=The level of this unit's Green Skill is reduced.
ENCOURAGED=Encouraged (Barley)
ENCOURAGED_DESC=This unit gains Basic Damage and Skill Power when Barley is attacked.
DISTRACTED=Distracted
DISTRACTED_DESC=Distracted units target the distractor with their attacks.
MAX_HP_DECREASE=Max HP Decrease
MAX_HP_DECREASE_DESC=Max HP is decreased.
MAX_HP_INCREASE=Max HP Increase
MAX_HP_INCREASE_DESC=Max HP is increased.
SHATTERED=Shattered
SHATTERED_DESC=Shattered units take 8% of their Max HP as True Damage each time they are dealt Fantastic Damage. Skills that deal damage over time can only trigger Shatter once per second.
DUPLICATE_HERO_RULE_MORE_INFO=This Hero is being used by the defender. Attackers cannot use the Heroes the defender is using during this Challenger Season.
SNARE=Snare
SNARE_DESCRIPTION=Snared enemies have their Movement Speed reduced to 0%. They can still use Basic Attacks and Skills that are within range.
PIERCE=Pierced
PIERCE_DESCRIPTION=Pierced units take 5% of their Max HP as True Damage each time they are dealt Normal Damage. Skills that deal damage over time can only trigger Pierce once per second.
PERSEVERANCE=Perseverance (Raya)
PERSEVERANCE_DESCRIPTION=Raya's skills become more powerful with each stack of "Perseverance."
TAKE_A_NUMBER=Take a Number (Flash)
TAKE_A_NUMBER_DESCRIPTION=Enemies with a Take a Number Ticket are Stunned and take Fantastic Damage per second.
LIMIT=Limit
LIMIT_DESCRIPTION=Limited units have their Skill levels reduced by 50%. Reductions are always rounded down.
DETERMINATION=Determination
DETERMINATION_DESCRIPTION=Each stack of Determination reduces an instance of Normal Crit or Fantastic Crit to regular damage.
DECAY=Decay
DECAY_DESCRIPTION=Each stack of Decay on a unit blocks Cleanse from being applied once. Enemies can have a maximum of 3 stacks.
DRAIN=Drain
DRAIN_DESCRIPTION=Drained units lose 50 Energy per second.
CORRUPTION=Corruption
CORRUPTION_DESCRIPTION=Each stack of Corruption reduces an enemy's Healable HP by 20%. Enemies can have a maximum of 4 stacks.
MAGIC=Magic (Eda Clawthorne)
MAGIC_DESCRIPTION=Each stack of Magic grants Eda Clawthorne and her allies Armor, Reality, Basic Damage, and Skill Power.
CONFUSION=Confusion
CONFUSION_DESCRIPTION=Confusion allows units to initiate Basic Attacks and Skills that require an animation but interrupts them, preventing them from finishing. Skills interrupted in this way will still consume Energy and go on Cooldown.\n\nConfusion does not work against Revives.
EMPOWERED=Empowered
EMPOWERED_DESCRIPTION=Empowered stacks protect units from having their energy stolen.
DODGE=Dodge
DODGE_DESCRIPTION=Dodge prevents damage from enemy Basic Attacks and Skills.
WELL_FED=Well Fed (Heimlich)
WELL_FED_DESCRIPTION=Each stack of "Well Fed" grants Heimlich increased Max HP and makes some of his Skills more powerful. These stacks cannot be Copied, Stolen, or Removed and they last between waves.
ENDURANCE=Endurance
ENDURANCE_DESCRIPTION=Each Stack of Endurance on a unit will block one instance of damage. Enemies can have a maximum of %d stacks. Stacks cannot be Copied or Stolen.
VULNERABLE=Vulnerable
VULNERABLE_DESCRIPTION=Vulnerable heroes receive %d%% of their max HP as True Damage each time they receive a buff. This Damage cannot be Reflected and the same hero cannot trigger this effect on the same target more than once every %s seconds.
MELODY=Melody (Joe Gardner)
MELODY_DESCRIPTION="Melody" stacks strengthen Joe Gardner's team by providing buffs and increasing his damage based on the number of stacks. Stacks of "Melody" cannot be Copied, Stolen, or Removed and they only reset between waves.
CHERNABOG_LINK=Chernabog's Link
CHERNABOG_LINK_DESCRIPTION=Chernabog Links to the ally with the highest Basic Damage or Skill Power, whichever is greater, granting them bonus effects and additional stat boosts. Chernabog can only Link to each ally once per wave.
TEMPER=Temper
TEMPER_DESC=Stacks of Temper are applied to enemies by Ember Lumen and allies, enhancing Embers Skills and debuffing enemies. Stacks of "Temper" cannot be Copied, Stolen, or Removed.
MUFASA_ENCOURAGED=Encouraged
MUFASA_ENCOURAGED_DESCRIPTION=Allies caught in Mufasa's Aura are Encouraged, reducing their cooldowns, boosting HP and Energy generation, and Healing them every second.
MUFASA_DEMORALIZED=Demoralized
MUFASA_DEMORALIZED_DESCRIPTION=Enemies caught in Mufasa's Aura are Demoralized, decreasing their damage and making them take additional damage.
HUNTSMAN_BOX=Hunter's Box
HUNTSMAN_BOX_DESCRIPTION=Hunter's Box buff is used to display how many buffs the Huntesman Box currently has.
THOMAS_O_MALLEY_CAT_LIVES=Cat Lives
THOMAS_O_MALLEY_CAT_LIVES_DESCRIPTION=Displays how many Cat Lives Thomas O'Malley currently has.
ANXIETY_DISQUIET=Disquiet
ANXIETY_DISQUIET_DESCRIPTION=Each stack of "Disquiet" grants Anxiety increased Dodge chance and makes some of her Skills more powerful. These stacks cannot be Copied, Stolen, or Removed.
ISABELLA_SHAPIRO_NOTEPAD=Isabella's Notepad
ISABELLA_SHAPIRO_NOTEPAD_DESCRIPTION=Enemies affected by Isabella's Notepad debuff can't use their White Skills.
OVERLOAD=Overload
OVERLOAD_DESCRIPTION=Overload increases Heroes Skill Levels by a certain amount.
MOMENTUM=Momentum
MOMENTUM_DESCRIPTION=Momentum reduces the damage received from the next attack by %d%%. Each attack received consumes one Momentum stack and increases the hero's damage by %d%% for %.1f seconds. This damage increase can stack, and heroes can hold up to %d Momentum stacks.
ENVY_JEALOUS=Jealous
ENVY_JEALOUS_DESCRIPTION=Each stack of "Jealous" makes Envy and some of her Skills more powerful. These stacks cannot be Copied, Stolen, or Removed.
ENNUI_DULL=Dull
ENNUI_DULL_DESCRIPTION=Stacks of "Dull" transfer between enemies and allies when they hit each other, granting beneficial effects to allies and harmful effects to enemies. Stacks of "Dull" cannot be Blocked, Copied, Stolen, or Removed by other sources than Ennui and reset between waves.
AWKWARD_EMBARRASSMENT=Awkward
AWKWARD_EMBARRASSMENT_DESCRIPTION=Each "Awkward" stack generated Increases Embarrassment's Reality and Max HP until the end of the wave. These stacks cannot be Copied, Stolen, or Removed.
SNITCH_MODE=Snitch Mode (Candace Flynn)
SNITCH_MODE_DESCRIPTION="Snitch" Mode changes Candace's Skills to be more debuff focused.
BUST_MODE=Bust Mode (Candace Flynn)
BUST_MODE_DESCRIPTION="Bust" Mode changes Candace's Skills to be more buff focused.
PHINEAS_CREATION=Creation (Phineas)
PHINEAS_CREATION_DESCRIPTION=An hero affected by Phineas' Invention becomes Charmed and empowers themselves with Phineas' Skills
DUELIST=Duelist (Amity Blight)
DUELIST_DESCRIPTION=One of Amity Blight's Modes. Amity switches to this offensive mode in order to debuff and damage her enemies.
VOWKEEPER=Vowkeeper (Amity Blight)
VOWKEEPER_DESCRIPTION=One of Amity Blight's Modes. Amity switches to this supportive mode in order to buff, shield and heal her allies.
MILES=Miles
MILES_DESCRIPTION="Miles" increases Lightning McQueen damage​ and adds new effects on his skills. "Miles" cannot be Copied, Stolen, or Removed and they only reset between waves.
LIE=Lie
LIE_DESCRIPTION="Lie" stacks improves some of Pinocchio's skills. "Lie" stacks cannot be Copied, Stolen, or Removed and they only reset between waves.
BAMBI_LINK=Bambi's Link
BAMBI_LINK_DESCRIPTION=At the start of combat, Bambi Links himself to the ally with the lowest Max HP. While linked, Bambi converts a percentage of the damage he takes into healing for his Linked ally.
FACADE=Facade
FACADE_DESCRIPTION=Enemies hit with Facade get progressively weaker till they are Charmed permanently.
DECEPTION=Deception
DECEPTION_DESCRIPTION=Enemies with Deception are dealt bonus damage equal to a percentage of their missing Max HP when attacked by Hans.
MRS_NOUGAT=Mrs. Nougat
MRS_NOUGAT_DESCRIPTION="Mrs. Nougat" is a stack Molly receives whenever she basic attacks. Upon reaching different Milestones, Molly will amplify the effects of debuffs and buff on the battlefield.
SCRAP=Scrap
SCRAP_DESCRIPTION=Each stack of "Scrap" grants Mater increased Shield HP and makes some of his Skills more powerful. \nThese stacks cannot be Copied, Stolen, or Removed and reset between waves.
ACID=Acid
ACID_DESCRIPTION="Acid" is a stack that deals True Damage upon explosion.
FATE=Fate
FATE_DESCRIPTION="Fate" is a stack buff that will guarantee instant victory upon reaching %d stacks. Stacks cannot be Copied, Stolen or Removed.
