
MENU_HEROES=Heroes
MENU_ITEMS=Items
MENU_MAILBOX=Mailbox
MENU_ACHIEVEMENTS=Medals
MENU_DAILY_QUESTS=Quests
MENU_DEBUG=Debug
MILLION_NUMBER=%1$s M
BILLION_NUMBER=%1$s B
THOUSAND_NUMBER=%1$s K
MILLION_SUFFIX=M
THOUSAND_SUFFIX=K
TUTORIAL_CANT_DO_THAT_YET=You can't do that just yet. Follow the tutorial arrow!
WHITE_RARITY_NAME=White
BLUE_RARITY_NAME=Blue
GREEN_RARITY_NAME=Green
PURPLE_RARITY_NAME=Purple
ORANGE_RARITY_NAME=Orange
RED_RARITY_NAME=Red
YELLOW_RARITY_NAME=Yellow
EMERALD_RARITY_NAME=Emerald
SAPPHIRE_RARITY_NAME=Sapphire
DAYS_FULL=%1$d Days
DAYS=%1$dd
HOURS=%1$dh
MINUTES=%1$dm
SECONDS=%1$ds
GOT_IT=Got it
QUIT=Quit
JOIN_GUILD_NOTIF=You have joined %1$s.
NEW_GUILD_ROLE_RULER=You are now the Leader of %1$s.
NEW_GUILD_ROLE_OFFICER=You are now an Officer of %1$s.
NEW_GUILD_ROLE_MEMBER=You are no longer a Tactician of %1$s.
FRIEND_REQUEST_RECEIVED=You have received a new friend request from %1$s.
FRIEND_REQUEST_SENT=A friend request has been sent to %1$s.
FRIEND_REQUEST_ACCEPTED=%1$s has accepted your friend request.
QUIT_WINDOW_TITLE=Quit?
QUIT_WINDOW_TEXT=Are you sure you want to quit?
CANCEL=Cancel
CONTINUE=Continue
VIP_FORMAT=VIP %1$d
LOADING_ELLIPSIS=Loading...
NEED_TEAM_LEVEL_X=Needs Team Level %1$d.
VIEW_BUTTON=View
MODE_DIFFICULTY_ONE=Easy
MODE_DIFFICULTY_TWO=Medium
MODE_DIFFICULTY_THREE=Hard
MODE_DIFFICULTY_FOUR=Very Hard
MODE_DIFFICULTY_FIVE=Super Hard
MODE_DIFFICULTY_SIX=Insane
MODE_DIFFICULTY_SEVEN=Ridiculous
MODE_DIFFICULTY_EIGHT=Shocking
MODE_DIFFICULTY_NINE=Impossible
MODE_DIFFICULTY_TEN=Challenging
MODE_DIFFICULTY_ELEVEN=Absurd
MODE_DIFFICULTY_TWELVE=Ludicrous
MODE_DIFFICULTY_THIRTEEN=Turn Back
MODE_DIFFICULTY_FOURTEEN=Hopeless
MODE_DIFFICULTY_FIFTEEN=Unpossible
MODE_DIFFICULTY_SIXTEEN=Strenuous
MODE_DIFFICULTY_SEVENTEEN=Unbeatable
MODE_DIFFICULTY_EIGHTEEN=Preposterous
MODE_DIFFICULTY_NINETEEN=Never Been Done
MODE_DIFFICULTY_TWENTY=Daunting
MODE_DIFFICULTY_TWENTY_ONE=Inconceivable
MODE_DIFFICULTY_TWENTY_TWO=Outrageous
MODE_DIFFICULTY_TWENTY_THREE=Uncanny
MODE_DIFFICULTY_TWENTY_FOUR=Sisyphean
MODE_DIFFICULTY_TWENTY_FIVE=Surreal
MODE_DIFFICULTY_TWENTY_SIX=Foolhardy
MODE_DIFFICULTY_TWENTY_SEVEN=Mind Bending
MODE_DIFFICULTY_TWENTY_EIGHT=Tyrannical
MODE_DIFFICULTY_TWENTY_NINE=Try Hard
MODE_DIFFICULTY_THIRTY=Warp Speed
MODE_DIFFICULTY_THIRTY_ONE=Get Good
MODE_DIFFICULTY_THIRTY_TWO=Non-Euclidean
MODE_DIFFICULTY_THIRTY_THREE=Moonshot
MODE_DIFFICULTY_THIRTY_FOUR=Infinitesimal
MODE_DIFFICULTY_THIRTY_FIVE=Extinction-Level Event
MODE_DIFFICULTY_THIRTY_NINE=Git Gud
MODE_DIFFICULTY_FORTY=Impassible
MODE_DIFFICULTY_FORTY_ONE=Unfair
MODE_DIFFICULTY_FORTY_TWO=Mega Hard
MODE_DIFFICULTY_FORTY_THREE=Vicious
MODE_DIFFICULTY_FORTY_FOUR=Monumental
MODE_DIFFICULTY_FORTY_FIVE=Frightening
MODE_DIFFICULTY_FORTY_SIX=Scary
MODE_DIFFICULTY_FORTY_SEVEN=Unreal
MODE_DIFFICULTY_FORTY_EIGHT=Heroic
MODE_DIFFICULTY_FORTY_NINE=Gutsy
MODE_DIFFICULTY_FIFTY=Fearless
MODE_DIFFICULTY_FIFTY_ONE=Cruel
MODE_DIFFICULTY_FIFTY_TWO=Ppppffft.
MODE_DIFFICULTY_FIFTY_THREE=Cursed
MODE_DIFFICULTY_FIFTY_FOUR=Overpowered
MODE_DIFFICULTY_FIFTY_FIVE=Tumultuous
MODE_DIFFICULTY_FIFTY_SIX=Yikes
MODE_DIFFICULTY_FIFTY_SEVEN=Bonkers
MODE_DIFFICULTY_FIFTY_EIGHT=Eesh
MODE_DIFFICULTY_FIFTY_NINE=Please Don't
MODE_DIFFICULTY_SIXTY=Regrettable
MODE_DIFFICULTY_SIXTY_ONE=Unspeakable
MODE_DIFFICULTY_SIXTY_TWO=Grim
MODE_DIFFICULTY_SIXTY_THREE=Pyrrhic
MODE_DIFFICULTY_SIXTY_FOUR=Outlandish
MODE_DIFFICULTY_SIXTY_FIVE=Exhausting
MODE_DIFFICULTY_SIXTY_SIX=Merciless
MODE_DIFFICULTY_SIXTY_SEVEN=Bedraggling
MODE_DIFFICULTY_SIXTY_EIGHT=Sleep-Depriving
MODE_DIFFICULTY_SIXTY_NINE=Beastly
MODE_DIFFICULTY_SEVENTY=Polarizing
MODE_DIFFICULTY_SEVENTY_ONE=Demoralizing
MODE_DIFFICULTY_SEVENTY_TWO=Distressing
MODE_DIFFICULTY_SEVENTY_THREE=Onerous
MODE_DIFFICULTY_SEVENTY_FOUR=Fatiguing
MODE_DIFFICULTY_SEVENTY_FIVE=Paradoxical
MODE_DIFFICULTY_SEVENTY_SIX=Unfathomable
MODE_DIFFICULTY_SEVENTY_SEVEN=Arduous
MODE_DIFFICULTY_SEVENTY_EIGHT=Grueling
MODE_DIFFICULTY_SEVENTY_NINE=Gnarly
MODE_DIFFICULTY_EIGHTY=Rigorous
MODE_DIFFICULTY_EIGHTY_ONE=Devitalizing
MODE_DIFFICULTY_EIGHTY_TWO=Laborous
MODE_DIFFICULTY_EIGHTY_THREE=Shattering
MODE_DIFFICULTY_EIGHTY_FOUR=Inexorable
MODE_DIFFICULTY_EIGHTY_FIVE=Indomitable
MODE_DIFFICULTY_EIGHTY_SIX=Oblivion
MODE_DIFFICULTY_EIGHTY_SEVEN=Brutal
MODE_DIFFICULTY_EIGHTY_EIGHT=Super-Brutal
MODE_DIFFICULTY_EIGHTY_NINE=Doom
MODE_DIFFICULTY_NINETY=Void
MODE_DIFFICULTY_NINETY_ONE=Tormentor
MODE_DIFFICULTY_NINETY_TWO=Furious
MODE_DIFFICULTY_NINETY_THREE=Malevolent
MODE_DIFFICULTY_NINETY_FOUR=Cataclysm
MODE_DIFFICULTY_NINETY_FIVE=Overkill
MODE_DIFFICULTY_NINETY_SIX=Exile
MODE_DIFFICULTY_NINETY_SEVEN=Blackout
MODE_DIFFICULTY_NINETY_EIGHT=Dissolution
MODE_DIFFICULTY_NINETY_NINE=Terminus
MODE_DIFFICULTY_HUNDRED=Rebirth
MODE_DIFFICULTY_HUNDRED_ONE=Fracture
MODE_DIFFICULTY_HUNDRED_TWO=Rift
MODE_DIFFICULTY_HUNDRED_THREE=Fogborn
MODE_DIFFICULTY_HUNDRED_FOUR=Splinter
MODE_DIFFICULTY_HUNDRED_FIVE=Hivequeen
MODE_DIFFICULTY_HUNDRED_SIX=Laststand
MODE_DIFFICULTY_HUNDRED_SEVEN=The End
DONE=Done
TIME_AGO=%1$s Ago
CLAIM=Claim
CLAIMED=Claimed
YES=Yes
NO=No
SALE=Sale!
YOU_HAVE_FORMAT=You have {#ffe00f}%1$s{}.
GENERIC_PURCHASE_SALE=Sale! {#ffe00f}%1$d%%{} Off!
CONFIRM_PURCHASE_PROMPT=Do you want to spend %1$s%2$d %3$s{} to %4$s?
RECONNECTING=Reconnecting...
LOADING_NO_ELLIPSE=Loading
GENERIC_VIP_REQUIRES_LEVEL=Requires VIP %1$d.
UNLOCK_BUTTON=Unlock
HERO=Hero
ANY_RARITY=Any Rank
ANY_ITEM=Any Item
DAY_SUNDAY=Sunday
DAY_MONDAY=Monday
DAY_TUESDAY=Tuesday
DAY_WEDNESDAY=Wednesday
DAY_THURSDAY=Thursday
DAY_FRIDAY=Friday
DAY_SATURDAY=Saturday
NEED_VIP_LEVEL=Need VIP Level %1$d.
NEED_MORE_RESOURCE=Looks like you need more %1$s!
FRACTION_FORMAT=%1$d / %2$d
FRACTION_STR_FORMAT=%1$s / %2$s
TOO_MUCH_RESOURCE=You already have enough %1$s. Come back after you've spent some!
BASIC_LEVEL_FORMAT=Level %1$s
WELCOME_TO=Welcome to...
EXCLAMATION_FORMAT=%1$s!
BONUSES=Bonuses:
UNLOCKED=Unlocked!
UNLOCKS_AT_COLON=Unlocks at:
TEAM_LEVEL_EXCLAMATION=Team Level %1$d!
NEW_TEAM_LEVEL=New Team Level!
MAX_HERO_LEVEL=Max Hero Level:
CURRENT_STAMINA=Current Stamina:
MAX_STAMINA=Max Stamina:
VIP_LEVEL_EXCLAMATION=VIP LEVEL %1$d!
TL_WINDOW_FEATURES_UNLOCKED=Features Unlocked:
MODERATOR_BUTTON=Moderator
LAPSED_USER_REWARDS_WINDOW_TITLE=Gift
LAPSED_USER_REWARDS_QUANTITY=%1$d x60 Free Stamina Items*
LAPSED_USER_REWARDS_INFO=*Use them from your Items!
INVITE_FACEBOOK_MESSAGE=Play Disney Heroes with me!
FB_ERROR=Error
FB_OK=Ok
ANDROID_DEPRECATION_WARNING=Message about Android %1$s
ANDORID_DEPRECATION_INFO=We are planning on removing support for Android %1$s in a future version of Disney Heroes. We'd love for you to stick around, so please upgrade soon!
RATE_APP_INFO=Are you enjoying playing Disney Heroes?
RATE_APP_INFO_NOT_ENJOYING=Sorry to hear that! You can find help by tapping the avatar circle in the bottom left of the main screen.
IOS_EMAIL_NOT_SUPPORTED=Email not supported.
IOS_CONFIGURE_AN_EMAIL_ACCOUNT=According to iOS, your device is not configured to send email. Open the Settings app and connect an email account, or directly email us at %1$s
IOS_DEPRECATION_WARNING=Message about iOS %1$s
IOS_DEPRECATION_INFO=We are planning on removing support for iOS %1$s in a future version of Disney Heroes. We'd love for you to stick around, so please upgrade soon!
TAPJOY_CONTENT_ISSUE=There was an issue loading the content from Tapjoy.
TAPJOY_COULD_NOT_CONNECT=Could not connect to Tapjoy.
MENU_HOME=Home
AGE_CONFIRMATION_TITLE=Important - Please read!
AGE_CONFIRMATION_INFO=Disney Heroes: Battle Mode is free to play, but you can speed up your progress with in-app purchases. You can disable in-app purchases in your device settings. You must be 13 years of age or older to play. Tap "Okay" to accept our Terms of Service and Privacy Policy.
AGE_CONFIRMATION_BUTTON_1=Terms of Service
AGE_CONFIRMATION_BUTTON_2=Okay
FORUM_NAME_CHANGE_TITLE=Forums Name
FORUM_NAME_CHANGE_INFO=The first time you visit the forum, we'll automatically create a forum account using your current name. Would you like to change it now?
PAUSED=Paused
CLEAR=Clear
HUNDRED_MILLION_NUMBER=%1$s H
AIR_DROP_MISSED=Missed Claim
MAIL_MESSAGE_WAS_DELETED=The mail message you were viewing no longer exists.
OR=Or
PENDING=Pending
CHOOSE_WEEKLY_REWARD=Choose Your Weekly Reward!
LEARN_MORE=Learn More
REWARDS_REMAINING=Unclaimed Rewards remaining: {#ffe00f}%1$d{}
PREVIOUS=Previous
COLLECT_WEEKLY_QUEST=Collect Weekly Quest?
COLLECT_WEEKLY_INFO=Do you want to collect your Weekly Quest now? You have until Tuesday at 5am to complete more quests.
NEW_GUILD_ROLE_TACTICIAN=You are now a Tactician of %1$s.
ARE_YOU_SURE_CONTINUE=Are you sure you would like to continue?
DECISION_TOGGLE_INFO=Setting this to "ON" will hide this popup the next time \n\n If you change your mind, go to your profile Settings to reset them.
MAIL_REWARDS=Mail Rewards!
DONT_ASK_AGAIN=Don't ask again
CHOOSE_REWARDS=Choose A Reward
WEEKLY_QUEST_TITLE=Weekly Quest Rewards
AUTO_SELECT=Auto Select
GAME_MODE_DIFFICULTY=%1$s (%2$s)
CHANGE_BUTTON=Change
DONT_SHOW_AGAIN=Don't show again
NONE=None
RESET_TUTORIALS=Reset Tutorial
PURCHASE_VOUCHER_TITLE=Use a Purchase Voucher?
PURCHASE_VOUCHER_INFO=Continuing with this purchase will redeem the Purchase Voucher item below from your inventory. Are you sure you'd like to continue?
QUEST_REWARDS=Quest Rewards!
RESET_TIMER=Reset Timer
ADVERTISING_TITLE=Welcome to Disney Heroes!
ADVERTISING_INFO=To provide you with the best game experience, Disney Heroes will need your permission for services like personalizing the ads you choose to watch and growing the community.
OKAY=Okay!
ADVERTISING_INFO_ALT=To provide you with the best game experience, Disney Heroes will need your permission for services like personalizing the ads you choose to watch and growing the community.
ANDROID_RATE_US_MORE_INFO=Sorry to hear that! You can find help from customer service by tapping the avatar circle in the bottom left of the main screen.\nOr, you can leave us feedback on the Play Store.
RATE_US=Rate Us
LEAVE_FEEDBACK=Leave Feedback
CLEAR_TEXT=Clear Text
SELL_MOD_CONFIRM_INFO=Are you sure you want to sell this Mod? It is currently equipped to %1$s
SELL_MOD_CONFIRM_TITLE=Sell Equipped Mod?
DELETE_ACCOUNT_INFO=By deleting this account you will no longer have access to the purchases, progress, diamonds, and rankings associated with this account.  This action is final and cannot be changed, please make sure you want to delete your account before proceeding
DELETE_ACCOUNT_ACTION=Delete
DELETE_ACCOUNT_TITLE=Delete Account?
DELETE_ACCOUNT_MORE_INFO=You will lose everything associated with this account \n Including:
DELETE_ACCOUNT_BULLET_1=Purchases
DELETE_ACCOUNT_BULLET_2=Progress
DELETE_ACCOUNT_BULLET_3=Diamonds
DELETE_ACCOUNT_BULLET_4=Rankings
DELETE_ACCOUNT_INSTRUCTIONS=Type '%1$s' and tap the button to confirm this action.
DELETE_ACCOUNT_SUCCESS=You have successfully deleted your account
DELETE_ACCOUNT_EXIT=Exit Game
DELETE_ACCOUNT_NEW_ACCOUNT=New Account
DELETE_ACCOUNT_SUCCESS_TITLE=Account Deleted
DELETE_ACCOUNT_CONFIRM_FAILURE=Input text does not match '%1$s'
RAID_LOOT_RESULTS_WINDOW_TITLE=Loot Results
CHALLENGE=Challenge
CLIPBOARD_COPY_NOTIFICATION=Copied to clipboard.
MENU_EVENTS=Events
