
PROGRESS_REWARDS=Top Progress Rewards
RANK_REWARDS=Top Rank Rewards
INFORMATION=Information
PRIZES=Prizes
MY_PROGRESS=Current Progress:
CONTEST_ENDS_IN=Contest Ends In:
CONTEST_BEGINS_IN=Contest Begins In:
CURRENT_SCORE=Current Score
OVERVIEW=Overview
POINTS=Points
RANKINGS=Rankings
RANK=Rank
PROGRESS=Progress
CURRENT_RANK=Current Rank:
TASK=Task
DONE_MAX=Done/Max
EARNED=Earned
CONTESTS_TITLE=Contests
DONE_MAX_FORMAT=%1$s / %2$s
SHOW_ALL_PLAYERS=Show All Players
SHOW_GUILD_MEMBERS=Show Only Guild Members
CURRENT_SCORE_FORMAT=Current Score: %1$s
RANK_FORMAT=Rank: %1$s
AMOUNT_OF_AMOUNT={#ffe00f}%1$d{} of %2$d
REWARDS=Rewards
FORMAT_POINTS=%1$s Points
TASK_DESC_RESOURCE_BURN=Spend %2$s %1$s
TASK_DESC_RESOURCE_BURN_SINGULAR=Spend 1 %1$s
TASK_DESC_RESOURCE_EARN=Earn %2$s %1$s
TASK_DESC_RESOURCE_EARN_SINGULAR=Earn 1 %1$s
TASK_DESC_HERO_PROMOTED=Promote %1$s %2$s times
TASK_DESC_HERO_PROMOTED_SINGULAR=Promote %1$s
TASK_DESC_HERO_PROMOTED_ANY_HERO=Promote any Hero %1$s times
TASK_DESC_HERO_PROMOTED_ANY_HERO_SINGULAR=Promote any Hero
TASK_DESC_HERO_EVOLVED=Evolve %1$s %2$s times
TASK_DESC_HERO_EVOLVED_SINGULAR=Evolve %1$s
TASK_DESC_HERO_EVOLVED_ANY_HERO=Evolve any Hero %1$s times
TASK_DESC_HERO_EVOLVED_ANY_HERO_SINGULAR=Evolve any Hero
TASK_DESC_HERO_LEVELS_GAINED=Level up %1$s %2$s times
TASK_DESC_HERO_LEVELS_GAINED_SINGULAR=Level up %1$s
TASK_DESC_HERO_LEVELS_GAINED_ANY_HERO=Level up any Hero %2$s times
TASK_DESC_HERO_LEVELS_GAINED_ANY_HERO_SINGULAR=Level up any Hero
TASK_DESC_HERO_SKILLS_LEVELED=Gain %2$s Skill levels on %1$s
TASK_DESC_HERO_SKILLS_LEVELED_SINGULAR=Gain a Skill level on %1$s
TASK_DESC_HERO_SKILLS_LEVELED_ANY_HERO=Gain %1$s Skill levels on any Hero
TASK_DESC_HERO_SKILLS_LEVELED_ANY_HERO_SINGULAR=Gain a Skill level on any Hero
TASK_DESC_HERO_MISSION_COMPLETE=Complete %2$s Missions using %1$s
TASK_DESC_HERO_MISSION_COMPLETE_SINGULAR=Complete 1 Mission using %1$s
TASK_DESC_HERO_MISSION_COMPLETE_ANY_HERO=Complete %1$s Missions
TASK_DESC_HERO_MISSION_COMPLETE_ANY_HERO_SINGULAR=Complete 1 Mission
TASK_DESC_FRIENDSHIP_MISSION_COMPLETE=Complete %2$s %1$s Missions
TASK_DESC_FRIENDSHIP_MISSION_COMPLETE_SINGULAR=Complete 1 %1$s Mission
TASK_DESC_FRIENDSHIP_MISSION_COMPLETE_ANY_FRIENDSHIP=Complete %1$s Missions
TASK_DESC_FRIENDSHIP_MISSION_COMPLETE_ANY_FRIENDSHIP_SINGULAR=Complete 1 Mission
TASK_DESC_RARITY_EARN_SHARD=Find %2$s %1$s Bits
TASK_DESC_RARITY_EARN_SHARD_SINGULAR=Find 1 %1$s Bit
TASK_DESC_RARITY_EARN_FULL_ITEM=Find %2$s %1$s Items
TASK_DESC_RARITY_EARN_FULL_ITEM_SINGULAR=Find 1 %1$s Item
TASK_DESC_RARITY_CRAFTED=Craft %2$s %1$s Items
TASK_DESC_RARITY_CRAFTED_SINGULAR=Craft 1 %1$s Item
TASK_DESC_RARITY_GEAR_EQUIP=Equip %3$s %1$s Items to %2$s
TASK_DESC_RARITY_GEAR_EQUIP_SINGULAR=Equip 1 %1$s Item to %2$s
TASK_DESC_RARITY_GEAR_EQUIP_ANY_HERO=Equip %2$s %1$s Items
TASK_DESC_RARITY_GEAR_EQUIP_ANY_HERO_SINGULAR=Equip 1 %1$s Item
TASK_DESC_RARITY_ENCHANT_STARS_GAINED=Enhance %3$s %1$s Items equipped to %2$s
TASK_DESC_RARITY_ENCHANT_STARS_GAINED_SINGULAR=Enhance 1 %1$s Item equipped to %2$s
TASK_DESC_RARITY_ENCHANT_STARS_GAINED_ANY_HERO=Enhance %2$s %1$s Items
TASK_DESC_RARITY_ENCHANT_STARS_GAINED_ANY_HERO_SINGULAR=Enhance 1 %1$s Item
TASK_DESC_ITEM_EARN_SHARD=Find %2$s %1$ss
TASK_DESC_ITEM_EARN_SHARD_SINGULAR=Find 1 %1$s
TASK_DESC_ITEM_EARN_SHARD_ANY_ITEM=Find %1$s Bits
TASK_DESC_ITEM_EARN_SHARD_ANY_ITEM_SINGULAR=Find 1 Bit
TASK_DESC_ITEM_EARN_FULL_ITEM=Find %2$s %1$s Items
TASK_DESC_ITEM_EARN_FULL_ITEM_SINGULAR=Find 1 %1$s Item
TASK_DESC_ITEM_EARN_FULL_ITEM_ANY_ITEM=Find %1$s Items
TASK_DESC_ITEM_EARN_FULL_ITEM_ANY_ITEM_SINGULAR=Find any Item
TASK_DESC_ITEM_EARN_CATEGORY=Find %2$s %1$s Items
TASK_DESC_ITEM_EARN_CATEGORY_SINGULAR=Find 1 %1$s Item
TASK_DESC_ITEM_CRAFTED=Craft %2$s %1$s Items
TASK_DESC_ITEM_CRAFTED_SINGULAR=Craft 1 %1$s Item
TASK_DESC_ITEM_CRAFTED_ANY_ITEM=Craft %1$s Items
TASK_DESC_ITEM_CRAFTED_ANY_ITEM_SINGULAR=Craft any Item
TASK_DESC_ITEM_GEAR_EQUIP=Equip %3$s %1$s Items to %2$s
TASK_DESC_ITEM_GEAR_EQUIP_SINGULAR=Equip %1$s to %2$s
TASK_DESC_ITEM_GEAR_EQUIP_ANY_HERO=Equip %2$s %1$s Items
TASK_DESC_ITEM_GEAR_EQUIP_ANY_HERO_SINGULAR=Equip %1$s
TASK_DESC_ITEM_GEAR_EQUIP_ANY_ITEM=Equip %2$s Items to %1$s
TASK_DESC_ITEM_GEAR_EQUIP_ANY_ITEM_SINGULAR=Equip 1 Item to %1$s
TASK_DESC_ITEM_GEAR_EQUIP_ANY_ITEM_ANY_HERO=Equip %1$s Items
TASK_DESC_ITEM_GEAR_EQUIP_ANY_ITEM_ANY_HERO_SINGULAR=Equip 1 Item
TASK_DESC_ITEM_ENCHANT_STARS_GAINED=Enhance %3$s %1$s Items equipped to %2$s
TASK_DESC_ITEM_ENCHANT_STARS_GAINED_SINGULAR=Enhance 1 %1$s Item equipped to %2$s
TASK_DESC_ITEM_ENCHANT_STARS_GAINED_ANY_HERO=Enhance %2$s %1$s Items
TASK_DESC_ITEM_ENCHANT_STARS_GAINED_ANY_HERO_SINGULAR=Enhance 1 %1$s Item
TASK_DESC_ITEM_ENCHANT_STARS_GAINED_ANY_ITEM=Enhance %2$s Items equipped to %1$s
TASK_DESC_ITEM_ENCHANT_STARS_GAINED_ANY_ITEM_SINGULAR=Enhance 1 Item equipped to %1$s
TASK_DESC_ITEM_ENCHANT_STARS_GAINED_ANY_ITEM_ANY_HERO=Enhance %1$s Items
TASK_DESC_ITEM_ENCHANT_STARS_GAINED_ANY_ITEM_ANY_HERO_SINGULAR=Enhance 1 Item
TASK_DESC_ITEM_BURN=Use %2$s %1$s Items
TASK_DESC_ITEM_BURN_SINGULAR=Use 1 %1$s Item
TASK_DESC_ITEM_BURN_SINGULAR_FOR_CRATE=Use 1 %1$s
TASK_DESC_ITEM_BURN_ANY_ITEM=Use %1$s Items
TASK_DESC_ITEM_BURN_ANY_ITEM_SINGULAR=Use 1 Item
TASK_DESC_REAL_GEAR_LEVELS_GAINED=Gain %2$s Memory Disk levels on %1$s
TASK_DESC_REAL_GEAR_LEVELS_GAINED_SINGULAR=Gain 1 Memory Disk level on %1$s
TASK_DESC_REAL_GEAR_LEVELS_GAINED_ANY_REAL_GEAR=Gain %1$s Memory Disk levels
TASK_DESC_REAL_GEAR_LEVELS_GAINED_ANY_REAL_GEAR_SINGULAR=Gain 1 Memory Disk level
TASK_DESC_REAL_GEAR_STARS_GAINED=Gain %2$s Memory Disk star on %1$s
TASK_DESC_REAL_GEAR_STARS_GAINED_SINGULAR=Gain 1 Memory Disk star on %1$s
TASK_DESC_REAL_GEAR_STARS_GAINED_ANY_REAL_GEAR=Gain %1$s Memory Disk star
TASK_DESC_REAL_GEAR_STARS_GAINED_ANY_REAL_GEAR_SINGULAR=Gain 1 Memory Disk star
TASK_DESC_REINFECTIONS_CLEANSED=Clear %1$s Infected areas
TASK_DESC_REINFECTIONS_CLEANSED_SINGULAR=Clear 1 Infected area
TASK_DESC_BATTLE_WON=%2$s: Win %3$s battles with %1$s
TASK_DESC_BATTLE_WON_SINGULAR=%2$s: Win 1 battle with %1$s
TASK_DESC_BATTLE_WON_ANY_MODE=Win %2$s battles with %1$s
TASK_DESC_BATTLE_WON_ANY_MODE_SINGULAR=Win 1 battle with %1$s
TASK_DESC_BATTLE_WON_ANY_HERO=%1$s: Win %2$s battles
TASK_DESC_BATTLE_WON_ANY_HERO_SINGULAR=%1$s: Win 1 battle
TASK_DESC_BATTLE_WON_ANY_HERO_ANY_MODE=Win %1$s battle
TASK_DESC_BATTLE_WON_ANY_HERO_ANY_MODE_SINGULAR=Win 1 battle
TASK_DESC_BATTLE_WON_WITH_HERO_ROLE=%2$s: Win %3$s battles with a %1$s Hero
TASK_DESC_BATTLE_WON_WITH_HERO_ROLE_SINGULAR=%2$s: Win 1 battle with a %1$s Hero
TASK_DESC_BATTLE_WON_WITH_HERO_ROLE_ANY_MODE=Win %2$s battles with a %1$s Hero
TASK_DESC_BATTLE_WON_WITH_HERO_ROLE_ANY_MODE_SINGULAR=Win 1 battle with a %1$s Hero
TASK_DESC_BATTLE_POWER_DEFEATED=%1$s: %2$s enemy Power defeated
TASK_DESC_BATTLE_POWER_DEFEATED_SINGULAR=%1$s: 1 enemy Power defeated
TASK_DESC_BATTLE_POWER_DEFEATED_ANY_MODE=%1$s enemy Power defeated
TASK_DESC_BATTLE_POWER_DEFEATED_ANY_MODE_SINGULAR=1 enemy Power defeated
TASK_DESC_BATTLE_POWER_DEFEATED_ABOVE_OWN=%1$s: %2$s enemy Power defeated above your own
TASK_DESC_BATTLE_POWER_DEFEATED_ABOVE_OWN_SINGULAR=%1$s: 1 enemy Power defeated above your own
TASK_DESC_BATTLE_POWER_DEFEATED_ABOVE_OWN_FUDGE=%1$s: %3$s enemy Power defeated above %2$s%% below your own
TASK_DESC_BATTLE_POWER_DEFEATED_ABOVE_OWN_FUDGE_SINGULAR=%1$s: 1 enemy Power defeated above %2$s%% below your own
TASK_DESC_BATTLE_POWER_DEFEATED_ABOVE_OWN_ANY_MODE=%1$s enemy Power defeated above your own
TASK_DESC_BATTLE_POWER_DEFEATED_ABOVE_OWN_ANY_MODE_SINGULAR=1 enemy Power defeated above your own
TASK_DESC_BATTLE_POWER_DEFEATED_ABOVE_OWN_ANY_MODE_FUDGE=%2$s enemy Power defeated above %1$s%% below your own
TASK_DESC_BATTLE_POWER_DEFEATED_ABOVE_OWN_ANY_MODE_FUDGE_SINGULAR=1 enemy Power defeated above %1$s%% below your own
TASK_DESC_BATTLE_HEROES_LEFT=%1$s: %2$s Heroes survive battles
TASK_DESC_BATTLE_HEROES_LEFT_SINGULAR=%1$s: Hero survives battle
TASK_DESC_BATTLE_HEROES_LEFT_ANY_MODE=%1$s Heroes survive battles
TASK_DESC_BATTLE_HEROES_LEFT_ANY_MODE_SINGULAR=Hero survives battle
TASK_DESC_ENEMY_DEFEATED=%2$s: Defeat %1$s %3$s times
TASK_DESC_ENEMY_DEFEATED_SINGULAR=%2$s: Defeat %1$s
TASK_DESC_ENEMY_DEFEATED_ANY_MODE=Defeat %1$s %2$s times
TASK_DESC_ENEMY_DEFEATED_ANY_MODE_SINGULAR=Defeat %1$s
TASK_DESC_ENEMY_DEFEATED_ANY_HERO=%1$s: Defeat %2$s enemies
TASK_DESC_ENEMY_DEFEATED_ANY_HERO_SINGULAR=%1$s: Defeat 1 enemy
TASK_DESC_ENEMY_DEFEATED_ANY_HERO_ANY_MODE=Defeat %1$s enemies
TASK_DESC_ENEMY_DEFEATED_ANY_HERO_ANY_MODE_SINGULAR=Defeat 1 enemy
TASK_DESC_EXPEDITION_FINISHED=Finish %1$s %2$s times
TASK_DESC_EXPEDITION_FINISHED_SINGULAR=Finish %1$s
TASK_DESC_EXPEDITION_FINISHED_ANY_MODE=Finish City Watch %1$s times
TASK_DESC_EXPEDITION_FINISHED_ANY_MODE_SINGULAR=Finish City Watch
PROGRESS_REWARDS_EARNED=Progress Rewards Earned:
POINTS_TO_NEXT_REWARD=Points to Next Reward:
TASK_DESC_OPEN_CHEST=Open %2$s %1$ss
TASK_DESC_OPEN_CHEST_SINGULAR=Open 1 %1$s
TASK_DESC_OPEN_CHEST_ANY_CHEST=Open %1$s Crates
TASK_DESC_OPEN_CHEST_ANY_CHEST_SINGULAR=Open any Crate
CONTEST_HAS_ENDED=THE CONTEST HAS ENDED
SCORING=Scoring
RANK_COLON=Rank:
SCORE_COLON=Score:
ONGOING=Ongoing
EXPIRED=Expired
OPEN_SOON=Opens Soon
TASK_DESC_WAR_ATTACK=Guild War: Attack with %1$s %2$s times
TASK_DESC_WAR_ATTACK_SINGULAR=Guild War: Attack with %1$s 1 time
TASK_DESC_WAR_ATTACK_ANY_HERO=Guild War: Attack 1 defender %1$s times
TASK_DESC_WAR_ATTACK_ANY_HERO_SINGULAR=Guild War: Attack 1 defender
TASK_DESC_WAR_SABOTAGE_ANY_HERO=Guild War: Spend %1$s tokens to sabotage defending heroes %2$s times
TASK_DESC_WAR_SABOTAGE_ANY_HERO_SINGULAR=Guild War: Spend %1$s tokens to sabotage a defending hero
TASK_DESC_WAR_SABOTAGE_ANY_RESOURCE=Guild War: Sabotage defending %1$s %2$s times
TASK_DESC_WAR_SABOTAGE_ANY_RESOURCE_SINGULAR=Guild War: Sabotage defending %1$s
TASK_DESC_WAR_SABOTAGE_ANY_HERO_ANY_RESOURCE=Guild War: Sabotage %1$s defending heroes
TASK_DESC_WAR_SABOTAGE_ANY_HERO_ANY_RESOURCE_SINGULAR=Guild War: Sabotage a defending hero
TASK_DESC_WAR_SABOTAGE=Guild War: Spend %2$s tokens to sabotage any %1$ %3$s times
TASK_DESC_WAR_SABOTAGE_SINGULAR=Guild War: Spend %2$s tokens to sabotage any %1$ 1 time
HALL_OF_FAME=Hall of Fame
TOP_GUILDS=Top Guilds
TOP_PLAYERS=Top Players
CONTEST_SCORE=Contest Score
INDIVIDUAL_CONTEST=Individual Contest
GUILD_CONTEST=Guild Contest
SERVER_CONTEST=Community Contest
NO_CARD_ENTRIES_HALL_OF_FAME=There are currently no contest results.
NO_RANKING_ENTRIES_HALL_OF_FAME=There are currently no contest rankings for this category.
CONTEST_MEDAL_TOOLTIP=Placing at this rank will earn you this medal in the Hall of Fame rankings.
GUILD_CONTEST_MEDAL_TOOLTIP=Placing at this rank will earn your guild this medal in the Hall of Fame rankings.
COMMUNITY_PROGRESS=Community Progress
MY_RANK=My Rank
