
COSTUMES=Costumes
WEAR=Wear
CURRENT=Current
NOT_ENOUGH_THREADS=You need to collect more Costume Threads to unlock this costume!
COSTUME_UNLOCK=You've unlocked a new costume!
UNLOCK_HERO_TO_WEAR=Unlock this Hero to wear this costume.
