
REQUIRES_LEVEL={#ffe00f}REQUIRES:{} LEVEL {#fe8e1d}%1$d{}
REQUIRES_LEVEL_TOO_LOW={#ffe00f}REQUIRES:{} LEVEL {#ff2f19}%1$d{}
AVAILABLE={#ffe00f}AVAILABLE:{} %1$s
ITEM_EQUIPPED=EQUIPPED!
ITEM_STAT_PERCENT=%1$s +%2$d%%
ITEM_STAT_SUBTRACTIVE=%1$s %2$d
ITEM_STAT_ADDITIVE=%1$s +%2$d
DONE_BUTTON=Done
EQUIP_BUTTON=Equip
DEBUG_GIVE_ITEM=Debug Give Badge
CRAFTING_MISSING_RESOURCE=You don't have enough %1$s to craft.
CRAFT_BUTTON=CRAFT
COLLECT_HERE_HEADING=COLLECT HERE:
NO_WAYS_TO_COLLECT=There are currently no ways to collect this badge.
ELITE_CHANCES_REMAINING=(Elite {%1$s}%2$d{}/%3$d)
AUTO_CRAFT_TITLE=Would you like to quick craft {#e67e38}%1$s{}?
BADGES_NEEDED=Badges Needed
GOLD_NEEDED=Gold Needed
AUTO_CRAFT=QUICK CRAFT
AUTO_FARM=POWER CRAFT
AUTO_FARM_CONFIRM_MSG=The items below will be consumed.
AUTO_FARM_ITEMS_REQUIRED=Items Required
ADDITIONAL_LOOT=Raid Loot:
CORRUPTED_LOCATIONS=Infected Locations
STAMINA_NEEDED_COLON=Stamina Needed:
AUTO_FARM_QUESTION=Power Craft?
GOLD_NEEDED_COLON=Gold Needed:
LEVELS_LOCKED=1+ levels are {#ffe00f}locked{}
LEVELS_RAID_LOCKED=1+ levels {#ffe00f}need 3-stars{}
QUICK_CRAFT_QUESTION=Quick Craft?
POWER_CRAFT_COST_INFO=Rewards gained from raiding are subtracted from the cost.
POWER_CRAFT_ITEMS_USED=Items used in crafting:
NEEDED_COLON=Needed:
NEEDED_OBTAIN_TO_CONTINUE=%1$s: Obtain %2$d total to continue.
CANNOT_CRAFT_ALL=There's something preventing you from crafting all badges right now.
POWER_CRAFT_ALL_STAGES_NEEDED=One or more Campaign stages required are currently locked.
POWER_CRAFT_THREE_STARS_NEEDED=Unlock Chapter %1$d and beat Stage %2$d at 3 stars.
POWER_CRAFT_TEAM_LEVEL_NEEDED=You require a higher Team Level to craft a badge.
POWER_CRAFT_ANTI_VIRUS_NEEDED=One or more stages are currently infected.
POWER_CRAFT_ITEMS_NEEDED=You need the following items or resources:
POWER_CRAFT_LOCKED_STAGES=One or more stages required for crafting are currently locked.  Unlock  [#ffe00f]Chapter %1$d[] and beat stage [#ffe00f]%2$s[] at 3 stars to continue
POWER_CRAFT_3_STAR_STAGES=One or more stages required for crafting have not been beaten at 3 stars.  Beat  [#ffe00f]Chapter %1$d[] stage  [#ffe00f]%2$s[] at 3 stars to continue
POWER_CRAFT_TEAM_LEVEL_REQUIRED=You need to increase your team level to  [#ffe00f]%1$d[] in order to level your hero up to the required level to equip one of the badges
POWER_CRAFT_NODES_INFECTED=One or more stages are currently infected. Clear  [#ffe00f]Chapter %1$d[] stage  [#ffe00f]%2$s[] of the infection to continue.
