
SCREEN_TITLE=Creep Surge
SETTINGS_HEADING=Settings:
GUILD_RANKS_BUTTON=Guild Info
REGIONS_CLEARED_FORMAT=Regions Cleared: %1$d/%2$d
WAVE_FORMAT=Wave: %1$d/%2$d
POWER_HEADING=Power:
FIGHT_BUTTON=Fight
REWARD_INFO_HEADING=%1$s:
REWARD_DISTRICTS_CLEARED_NUMBER={#ffe00f}%1$d/%2$d{}
REWARD_DISTRICTS_CLEARED=Districts Cleared
HEROES_LEFT_FORMAT=Heroes Left: {#ffe00f}%1$d/%2$d{}
HEROES_LEFT_PREFIX=Heroes Left:
POWER_LEFT_FORMAT=Power Left: {#ffe00f}%1$s{}
POWER_LEFT_PREFIX=Power Left:
POWER_DEFEATED_FORMAT=Power Defeated: {#ffe00f}%1$s{}
POWER_DEFEATED_PREFIX=Power Defeated:
DISTRICTS_CLEARED_FORMAT=Districts Cleared: {#ffe00f}%1$s{}
DISTRICTS_CLEARED_PREFIX=Districts Cleared:
SETTINGS_TITLE=Settings
SETTINGS_DIFFICULTY_HEADING=Creep Surge Difficulty:
SETTINGS_MAX_DISTRICTS_HEADING=Max Districts Per Guild Member:
CRYPT_PLAYER_DEFEATED_ERROR=Your guild has already defeated this enemy!
CRYPT_TIME_COMPLETE_ERROR=This Creep Surge is over, check back tomorrow for another.
CRYPT_USED_ALL_HEROES_ERROR=You've used all your Heroes for this Creep Surge.
CRYPT_ANOTHER_ATTACK_IN_PROGRESS_ERROR=Another player is currently attacking this enemy.
CRYPT_JOINED_LATE_ERROR=You joined the guild after this Creep Surge started. You will be able to participate in the next Creep Surge tomorrow.
CRYPT_SETTINGS_DIFFICULTY=Surge Difficulty:
CRYPT_SETTINGS_MAX_ATTACKS_PER_PLAYER=Max Districts Per Guild Member:
CRYPT_SETTINGS_NO_LIMIT=No limit
CRYPT_DIFFICULTY_LOCKED=Complete the previous difficulty to unlock.
GUILD_SETTINGS_PERMISSION_ERROR=You don't have permission to change that setting.
CRYPT_MAX_DISTRICTS_ERROR=You've cleared the maximum number of districts for this wave.
REGION_CLEARED_WINDOW=Region Cleared!
REGION_CLEARED_SURGE_COMPLETE_INFO=%1$d more until Surge complete...
WAVE_CLEARED_WINDOW=Wave Cleared!
WAVE_CLEARED_STARTING_NEXT=Starting next wave...
FINAL_WAVE_CLEARED=Final Wave Cleared!
SURGE_COMPLETE_TITLE=Surge Complete!
REGION_CLEARED_SHORT=Cleared!
INFLUENCE_REWARDS_HEADING=Influence Rewards:
REGIONS_CLEARED_HEADING=%1$d Regions Cleared:
COMPLETION_BONUS_HEADING=Completion Bonus:
TOTAL_HEADING=Total:
NO_HEROES=No Heroes
COMPLETE_CHECK_MAILBOX=Check your mailbox for Surge Token rewards!
COMPLETE_SHORT=Complete!
UNDER_ATTACK_HEADING=Under Attack By:
COMPLETE_THE_TUTORIAL=Complete the tutorial first.
PERK_UPSELL_INFO=Unlock new Creep Surge difficulties by upgrading your Guild Perks!
REGION_CLEARED_WAVE_COMPLETE_INFO=%1$d more until Wave complete...
SURGE_INCOMPLETE_TITLE=Surge Incomplete!
INCOMPLETE_SHORT=Incomplete
NEXT_SURGE=Next Surge:
PARTICIPATE_NEXT_SURGE=Participate in the next Creep Surge to earn rewards!
ATTACK_LOG=Attack Log
ATTACK_NUMBER=Attack #%1$d
TIME_AGO_POSTFIX=%1$s ago
HEROES_VS_HEROES=vs
ATTACK_LOG_EMPTY=There are no attacks yet. Go make an attack!
DROPDOWN_RANKS=Ranks
RAIDS_REMAINING=Raids Remaining: %1$s
POWER_NEEDED_FORMAT=Power Needed to Raid: {#ffe00f}%1$s{}
TICKETS_LEFT=Tickets Left: %1$s
TIER_FORMAT=Tier %1$s:
GOLD_MULTIPLIER_FORMAT=x%1$s
NEXT_TIER=Next Tier:
MULTIPLIER_DESCRIPTION=These are the points your guild has accumulated. Earn enough points to unlock reward tiers which multiply everyone's Surge gold!
AT_MAX_TIER=Max tier! Upgrade Guild perks to unlock more reward tiers!
DISTRICT_CLEAR_FORMAT=District %1$s Cleared!
GUILD_BONUS=Guild Bonus!
MY_VAULT=My  Vault
GUILD_PROGRESS=Guild Bank
MY_CONTRIBUTION=My Contribution:
PLUS_PERCENT_FORMAT=+%1$s%%
REGION_CLEARED_HEADING=Region Cleared!
WAVE_CLEARED_HEADING=Wave Cleared!
GUILD_LOOT=Guild Loot
RAID_ANYWAY=RAIDS CAN'T EARN BONUSES
RAID_ANYWAY_DESC=Bonuses can only be earned with Fights and Quick Fights. Raid anyway?
OBJECTIVE_NO_TANKS=Bonus: No Tanks
OBJECTIVE_NO_TANKS_DESC=Win with no Tank role Heroes
OBJECTIVE_NO_DPS=Bonus: No Damage
OBJECTIVE_NO_DPS_DESC=Win with no Damage role Heroes
OBJECTIVE_NO_SUPPORT=Bonus: No Support
OBJECTIVE_NO_SUPPORT_DESC=Win with no Support role Heroes
OBJECTIVE_NO_CONTROL=Bonus: No Control
OBJECTIVE_NO_CONTROL_DESC=Win with no Control role Heroes
OBJECTIVE_NO_YELLOW=Bonus: No Yellow
OBJECTIVE_NO_YELLOW_DESC=Win with no Yellow team Heroes
OBJECTIVE_NO_BLUE=Bonus: No Blue
OBJECTIVE_NO_BLUE_DESC=Win with no Blue team Heroes
OBJECTIVE_NO_RED=Bonus: No Red
OBJECTIVE_NO_RED_DESC=Win with no Red team Heroes
OBJECTIVE_WITH_MERC=Bonus: Use Mercenary
OBJECTIVE_WITH_MERC_DESC=Win while using a Mercenary
OBJECTIVE_SMALL_TEAM=Bonus: 5 Heroes
OBJECTIVE_SMALL_TEAM_DESC=Win with exactly 5 Heroes
OBJECTIVE_NO_KO=Bonus: No Heroes Lost
OBJECTIVE_NO_KO_DESC=Win without losing any of your Heroes.
OBJECTIVE_NO_HEALS=Bonus: No Heals
OBJECTIVE_NO_HEALS_DESC=Win without healing
OBJECTIVE_NO_DISABLES=Bonus: No Disables
OBJECTIVE_NO_DISABLES_DESC=Win without disabling
OBJECTIVE_NO_SHIELDS=Bonus: No Shielding
OBJECTIVE_NO_SHIELDS_DESC=Win without shielding
OBJECTIVE_HIGH_HEALTH=Bonus: High Health
OBJECTIVE_HIGH_HEALTH_DESC=Win with all your Heroes above %1$s%% HP
OBJECTIVE_CLEAR_REGION=Bonus: Clear Region
OBJECTIVE_CLEAR_REGION_DESC=Win a battle that clears a region
ANOTHER_RAID=Another "Surge Raid"
REACH_VIP_TO_UNLOCK=Reach VIP Level %1$s to unlock:
RARITY_COMMON=Common
RARITY_UNCOMMON=Uncommon
RARITY_RARE=Rare
RARITY_SUPER_RARE=Super Rare
POWER_CONTRIBUTED=Power Contributed:
CONTRIBUTE=Contribute
GUILD_HQ=Guild HQ
CONTRIBUTE_HEROES=Contribute %1$s Heroes
HELP_YOUR_GUILD=Help Your Guild
GAIN=Gain:
CREEPS_INCOMING=Creeps Incoming!
CREEPS_INCOMING_DESC=Please wait for the current Surge to finish calculating rewards. Then get ready to fight some more creeps!
TIER_PREFIX=Tier: %1$s
VIP_SHORT_FORMAT=Perk: VIP %1$s
GUILD_TOTAL_FORMAT=Guild Total:
SURGE_REWARDS=Surge Rewards
GUILD_REWARDS=Guild Rewards
MY_REWARDS=My Rewards
HIGHLIGHTS=Highlights
HIGHLIGHT_POWER_BEAT_TITLE=Powerful!
HIGHLIGHT_POWER_BEAT=Power Defeated:
HIGHLIGHT_POINTS_EARNED_TITLE=Valuable!
HIGHLIGHT_POINTS_EARNED=Points Contributed:
HIGHLIGHT_MERCS_HIRED_TITLE=Team Player!
HIGHLIGHT_MERCS_HIRED=Mercenaries Hired:
HIGHLIGHT_REGIONS_CLEARED_TITLE=Region Reclaimer!
HIGHLIGHT_REGIONS_CLEARED=Regions Cleared:
HIGHLIGHT_WAVES_CLEARED_TITLE=Creep Surfer!
HIGHLIGHT_WAVES_CLEARED=Waves Cleared:
HIGHLIGHT_MOST_EFFICIENT_TITLE=Underdog!
HIGHLIGHT_MOST_EFFICIENT=Power Ratio:
HIGHLIGHT_MOST_POWER_CLEARED_TITLE=Personal Record!
HIGHLIGHT_MOST_POWER_CLEARED=Power Defeated:
HIGHLIGHT_MOST_POINTS_EARNED_TITLE=Personal Best!
HIGHLIGHT_MOST_POINTS_EARNED=Points Contributed:
HIGHLIGHT_CONSECUTIVE_SURGES_TITLE=Consistent!
HIGHLIGHT_CONSECUTIVE_SURGES=Days in a Row:
CONTRIBUTE_REMAINING_HEROES=Contributing all your remaining heroes will earn your guild %1$s %2$s.\nHowever, those heroes will no longer be able to fight in this Surge.
HQ_SHORT=HQ
OBJECTIVE_BONUSES=Bonuses
INTERMISSION_MESSAGE=Calculating results...Check back in %1$s
NO_MERC_ON_CLEARED_DISTRICT=Mercenaries cannot be used on previously cleared districts.
HEROES_CONTR_NOTIF=Heroes contributed. Your Guild thanks you!
VAULT_GOLD_TOOLTIP=This is your total gold earned for this Creep Surge. At the end of Surge you'll also receive extra gold equal to this Vault gold times your Guild's Gold multiplier! \n {#ffe00f}%1$s{}
VAULT_TOKENS_TOOLTIP=These are your current stored Surge Tokens, claim them at the end of the Creep Surge.
BANK_INFL_TOOLTIP=This is the total amount of Influence your guild has gained this Creep Surge.
GOLD_MULT_TOOLTIP=This is your guild's current gold multiplier.
TIER_TOOLTIP_CUR_BONUS={#3ec07b}Current Bonus: {i} %1$s{}
TIER_TOOLTIP_TIER_BONUS={#e67e38}Tier Bonus: {i} %1$s{}
TIER_TOOLTIP_NEXT={#e67e38}Next {}
TIER_TOOLTIP_DESC=Earn {i} Surge Points to unlock tiers and multiply {#ffe00f}everyone's Vault gold!{}
SURGE_DISCTRICT_CLEARED=District Cleared
SURGE_DISTRICT_CLEARED_DESC=This district has already been cleared. Clearing it again will still award Surge Points and Gold, but it will not contribute to clearing the Region. Are you sure you'd like to continue?
