
CHANGE_DIFFICULTY=Change Difficulty
RED_TEAM_TITLE=Red Team Trial
OPENS_TOMORROW=Opens Tomorrow
OPENS_DAY_FORMAT=Opens On %1$s
ENTER=Enter
CLOSED=Closed
GET_MORE=Get More
BULLET_EARN_XP=Earn XP
BULLET_FANTASTIC_IMMUNE=Enemies have Fantastic Immunity
BULLET_EARN_GOLD=Earn Gold
BULLET_PHYSICAL_IMMUNE=Enemies have Normal Immunity
PORT_DOCKS=The Docks
PORT_WAREHOUSE=The Warehouse
PORT_DOCKS_LONG=Port: The Docks
PORT_WAREHOUSE_LONG=Port: The Warehouse
TEAM_TRIALS_RED=Red Team
TEAM_TRIALS_YELLOW=Yellow Team
TEAM_TRIALS_BLUE=Blue Team
TEAM_TRIALS_RED_LONG=Trials: Red Team
TEAM_TRIALS_YELLOW_LONG=Trials: Yellow Team
TEAM_TRIALS_BLUE_LONG=Trials: Blue Team
MODE_CLOSED_FORMAT=%1$s is closed. Opens: %2$s
CHOOSE_DIFFICULTY_NO_ATTEMPTS=No Attempts Remaining
CHOOSE_DIFFICULTY_WAIT_COOLDOWN=Please wait for the cooldown to finish.
RESET_PORT_DOCKS_CHANCES=Reset your Docks chances?
RESET_PORT_WAREHOUSE_CHANCES=Reset your Warehouse chances?
RESET_TEAM_TRIALS_CHANCES=Reset your chances for this Team?
RESET_NOW=Reset Now!
CHANCES_LEFT_YELLOW=Chances Left: {#ffe00f}%1$d{} / %2$d
CHANCES_LEFT_WHITE=Chances Left: %1$d / %2$d
COOLDOWN_HEADING=Cooldown:
TEAM_HEROES_HEADING=%1$s Heroes:
CHOOSE_HEROES_TEAM=Choose %1$s Heroes!
TEAM_TRIALS_RED_DESC=Heroes from the Red Team battle in this mode!
TEAM_TRIALS_YELLOW_DESC=Heroes from the Yellow Team battle in this mode!
TEAM_TRIALS_BLUE_DESC=Heroes from the Blue Team battle in this mode!
PORT_DOCKS_DESC=Earn XP. Enemies have Fantastic Immunity!
PORT_WAREHOUSE_DESC=Earn Gold. Enemies have Normal Immunity!
RAID_DIFFICULTY_STARS_REQUIREMENT=Get 3 Stars on %1$s and VIP 4 to unlock multi-raiding.
GAME_MODE_ABOUT_TEAM_TRIALS=About Team Trials
TEAM_TRIALS_INFO=Team Trials offers three battle modes that are open different days each week:\nRed Team: Open Sun, Tue, Fri.\nBlue Team: Open Sun, Wed, Sat.\nYellow Team: Open Sun, Mon, Thu.
TEAM_TRIALS_INFO_POINT_1=You can win a fight in a mode up to 5 times each day. Winning 3 times will give you a quest reward. Chances reset each day at 5am local time.
TEAM_TRIALS_INFO_POINT_2=Only a victory drops loot and consumes a chance. There is a 10-minute cooldown after each victory before you can fight again.
TEAM_TRIALS_INFO_POINT_3=The higher the difficulty level, the more and better loot you will receive. Level your team to unlock tougher difficulties.
GAME_MODE_ABOUT_MOUNTAIN=About The Port
PORT_INFO=The Port offers two battle modes that are open different days of the week:\n\nThe Docks: Gain XP potions fighting creeps at the Docks! Open Mon, Wed, Fri, Sun.\n\nThe Warehouse: Raid shipping containers for Gold! Open Tue, Thu, Sat, Sun.\n\nThings to know about both modes:
PORT_INFO_POINT_1=You can win a fight up to two times each day. Winning twice will give you a quest reward. Chances to win reset each day at 5am local time.
PORT_INFO_POINT_2=Only a victory drops loot and consumes a chance. There is a 10-minute cooldown after each victory before you can fight again.
PORT_INFO_POINT_3=As the difficulty increases, so does the quality and quantity of loot dropped. Level your team up to unlock harder difficulties.
THE_CODEBASE=The Codebase
CODEBASE_NO_YELLOW=Requires at least one hero at Yellow rank to enter.
HIGH_SCORE=High Score: {#ffe00f}%1$s{}
BEST_LEVEL=Best Rage Level: {#ffe00f}%1$s{}
THE_MEGAVIRUS=The Mega Virus
MEGAVIRUS_DESC=Fight the Mega Virus and earn Megabits!
MEGAVIRUS_DETAILS_HEADING=Fight Details:
WEAK_AGAINST=Vulnerable To:
RAGE_LEVELS=Rage Levels:
WEAKNESS_DESC_FMT=The Mega Virus is weak to %1$s effects!
WEAKNESS_MULT_FMT=+%1$s%%
HIGH_SCORE_HEADING=High:
FAV_HEADING_FMT=: +%1$s%% Chance
FINAL_LEVEL=Final Rage Level:
FINAL_SCORE=Final Score:
NEW_HIGH=New High
NO_CHANCES_TIMER_FMT=You've used all your chances for this Trial.  Come back for more in %1$s!
REMOVE_CODEBASE_CD_UPSELL=The "Remove Trials Cooldown" feature!
REDUCE_CODEBASE_CD_UPSELL=The "Reduce Trials Cooldown" feature!
WEAK_AGAINST_DESC=Use heroes that can take advantage of the Mega Virus's vulnerability to help you score more points and earn more rewards.
UPGRADE_CONF_TITLE=Upgrade?
UPGRADE_CONF_DESC=Use the items below to level up your Battle Badge?
UNLOCK_CONF_TITLE=Unlock?
UNLOCK_CONF_DESC=Use the items below to level up your Battle Badge?
ANNIVERSARY_TITLE=Happy Anniversary!
LEFT=Left
EVENT_TRIALS_DESC=Earn some Hero Chips by helping Fozzie fight the Creeps
HERO_CHIPS_WON=Hero Chips Won
CANT_REMOVE_HERO=This hero cannot be removed from your lineup.
DEFEAT_SPOTLIGHT_HEADING=Defeated, Try Again!
VULNERABILITY_HEADER=Vulnerability:
RAGE_LEVEL_HEADER=Rage Level:
TOP_TEN_FILTER=Top Ten
LAST_TEN_FILTER=Last Ten
CODEBASE_ATTACK_LOGS_TITLE=Attack Log
CODEBASE_ATTACK_LOGS_EMPTY=No Attack Logs available. Complete some battles and see their results here!
TRIAL_EVENT_DETAILS=Details
TRIAL_EVENT_RULES=Rules
TRIAL_EVENT_TOP_REWARDS=Final Stage Rewards
TRIAL_EVENT_WAVE_FORMAT=Wave: %1$d/%2$d
TRIAL_EVENT_HERO_REQ={#ffe00f}%1$s{} must be used
TRIAL_EVENT_HERO_CATEGORY_REQ=At least {#ffe00f}1 %1$s {}hero must be used
TRIAL_EVENT_HERO_CATEGORY_REQ_PLURAL=At least {#ffe00f}%2$d %1$s{} heroes must be used
TRIAL_EVENT_HERO_EXCLUDED={#ffe00f}%1$s{} cannot be used
TRIAL_EVENT_HERO_CATEGORY_EXCLUDED={#ffe00f}%1$s{} heroes cannot be used
TRIAL_EVENT_FRANCHISE_HEROES_RULE=Only {#ffe00f}%1$s{} heroes can be used
TRIAL_EVENT_RANK_REQ=At least {#ffe00f}1{} hero at {#%2$s}%1$s{} Rank or higher must be used
TRIAL_EVENT_RANK_REQ_PLURAL=At least {#ffe00f}%2$d{} heroes at {#%3$s}%1$s{} Rank or higher must be used
TRIAL_EVENT_RANK_REQ_EXCLUDE=Only heroes at {#%2$s}%1$s{} Rank or lower can be used
TRIAL_EVENT_LEVEL_REQ=At least {#ffe00f}1{} heroes at {#ffe00f}level %1$d{} or higher must be used
TRIAL_EVENT_LEVEL_REQ_PLURAL=At least {#ffe00f}%2$d{} heroes at {#ffe00f}level %1$d{} or higher must be used
TRIAL_EVENT_LEVEL_REQ_EXCLUDE=Only heroes at {#ffe00f}level %1$d{} or lower can be used
TRIAL_EVENT_STAR_REQ=At least {#ffe00f}1{} hero with {#ffe00f}%1$d stars{} or more must be used
TRIAL_EVENT_STAR_REQ_PLURAL=At least {#ffe00f}%2$d{} heroes with {#ffe00f}%1$d stars{} or more must be used
TRIAL_EVENT_STAR_REQ_EXCLUDE=Only heroes with {#ffe00f}%1$d stars{} or fewer can be used
TRIAL_EVENT_STAGE_N=Stage %1$d
TRIAL_EVENT_START_ICON_TEXT=START
TRIAL_EVENT_HEROES_EXCLUDED_REQ=None of these heroes can be used
TRIAL_EVENT_HEROES_INCLUDED_REQ=All of these heroes must be used
TRIAL_EVENT_HEROES_INCLUDED_GROUP_REQ=At least {#ffe00f}%1$d{} of these heroes must be used
TRIAL_EVENT_COMBINED_ROLE_TEAM_REQ_PLURAL=At least {#ffe00f}%1$d{} heroes that are both {#ffe00f}%2$s{} and {#ffe00f}%3$s Team{} must be used
TRIAL_EVENT_COMBINED_ROLE_TEAM_REQ=At least {#ffe00f}1{} hero that is both {#ffe00f}%1$s{} and {#ffe00f}%2$s Team{} must be used
TRIAL_EVENT_COMBINED_ROLE_TEAM_EXCLUDE=Heroes that are both {#ffe00f}%1$s{} and {#ffe00f}%2$s Team{} cannot be used
TRIAL_EVENT_TEAM_REQ=At least {#ffe00f}1 %1$s Team{} hero must be used
TRIAL_EVENT_TEAM_REQ_PLURAL=At least {#ffe00f}%1$d %2$s Team{} heroes must be used
TRIAL_EVENT_TEAM_REQ_EXCLUDE={#ffe00f}%1$s Team{} heroes cannot be used
TRIAL_EVENT_HAS_NOT_STARTED=This Trial has not started yet.
TRIAL_EVENT_NO_CHANCES_LEFT=You have no chances left on this Trial.
TRIAL_EVENT_ON_COOLDOWN=This Trial is on cooldown.
TRIAL_EVENT_LOCKED_HERO=You must unlock {#ffe00f}%1$s{} to continue
TRIAL_EVENT_LOCKED_HEROES=You must unlock more required heroes for this stage in order to continue
TRIAL_EVENT_LOCKED_HERO_RARITY=You must get {#ffe00f}%1$s{} to {#$3$s}%2$s{} Rank to continue
TRIAL_EVENT_LOCKED_HERO_LEVEL=You must get {#ffe00f}%1$s{} to {#ffe00f}level %2$d{} to continue
TRIAL_EVENT_LOCKED_HEROES_RARITY=You must have more required heroes for this stage at {#$2$s}%1$s{} Rank in order to continue
TRIAL_EVENT_LOCKED_HEROES_LEVEL=You must have more required heroes for this stage at {#ffe00f}level %1$d{} in order to continue
TRIAL_EVENT_LOCKED_HEROES_CATEGORY=You must unlock at least {#ffe00f}%1$d %2$s{} hero(es) to continue
TRIAL_EVENT_LOCKED_HEROES_FRANCHISES=You must unlock at least {#ffe00f}%1$d{} more heroes from the list of required Franchises to continue
TRIAL_EVENT_LOCKED_HEROES_SPECIFIC=You must unlock at least {#ffe00f}%1$d{} more heroes from the list of needed heroes to continue
TRIAL_EVENT_LOCKED_HEROES_TEAM_AND_ROLE=You must unlock at least {#ffe00f}%1$d{} hero(es) that are both {#ffe00f}%2$s{} and {#ffe00f}%3$s Team{}
TRIAL_EVENT_CAMPAIGN_TYPE=Campaign Trial
TRIAL_EVENT_WAVE_TYPE=Wave Trial
TRIAL_EVENT_SPOTLIGHT_TYPE=Spotlight Trial
FRANCHISE_TRIAL_EVENT_REQUIREMENT=Requires at least 1 {#ffe00f}%1$s{} Hero to participate.
RESET_TRIAL_EVENT_PROMPT=Reset Trial Chances?
RESET_TRIAL_AMOUNT_FORMAT=Receive {#ffe00f}%1$d{} more chances
RESETS_LEFT_YELLOW=Resets Left: {#ffe00f}%1$d{} / %2$d
TRIAL_EVENT_TOOLTIP_SUMMARY=This is a %1$s.
PAID_RESETS_LEFT=Paid Resets Left: {#ffe00f}%1$d{} / %2$d
RESETS_LEFT_ZERO=Resets Left: {#ffe00f}%1$d{}
PAID_RESETS_ZERO=Paid Resets Left: {#ffe00f}%1$d{}
TRIALS_SCREEN_NONE_AVAILABLE=No Trials Available
