
PROMO_NO_TEXT_ERROR=Please enter a valid code.
PROMO_INVALID_ERROR=Code is Invalid.
PROMO_REDEEMED_ERROR=Code has already been redeemed.
PROMO_EXPIRED_ERROR=Code has expired.
PROMOS_TITLE=Promos
EMAIL_CARD_TITLE=Email
PROMO_CARD_TITLE=Promo Codes
SUBMIT_BUTTON=Submit
CHANGE_BUTTON=Change
SIGN_UP_BUTTON=Sign Up
EMAIL_SUBSCRIBE_DESCRIPTION=Subscribe to Disney Heroes email and you'll receive special deals, update information, and more all sent directly to you!
EMAIL_EMPTY_INPUT=Enter your email
PROMO_DESCRIPTION=Have a code? Enter it here for rewards!
PROMO_EMPTY_INPUT=Enter your promo code
EMAIL_VERIFY_DESCRIPTION=Please verify your email address to receive {#6acbe9}%1$s %2$s{}
EMAIL_VERIFY_GENERAL_DESCRIPTION=Please verify your email address to continue receiving offers!
EMAIL_LINK_DESCRIPTION=Verification link has been sent to {#eccf34}%1$s{}
EMAIL_CHANGE_DESCRIPTION=Need to change your email?
EMAIL_THANKS_DESCRIPTION=Thank you for signing up! Keep an eye on your inbox for additional exclusive offers.
EMAIL_VERIFIED_DESCRIPTION=Verified email is: {#eccf34}%1$s{}
AVAILABLE_IN=Available in:
PROMOS_BUTTON=Promos
EMAIL_CONFIRMATION_TITLE=Email Confirmation
EMAIL_CONFIRMATION_INFO=Are you sure you want to sign up with:
CHANGE_EMAIL_TITLE=Change Your Email
CHANGE_EMAIL_INFO=Your current email is:
CHANGE_EMAIL_HINT=Enter new email
CONFIRM_BUTTON=Confirm
SIGN_UP_REWARD=%1$s for Sign Up
PROMO_REWARDS_TITLE=Promo Rewards
INVALID_EMAIL=Please enter a valid email address
EMAIL_IN_USE=This email has already been used. Please enter a different email.
REFERRAL_TITLE=Referral
REFERRAL_DESCRIPTION=Refer new players to Disney Heroes and earn Diamonds! The new player will earn 5000 Diamonds and VIP 5 for a Day!
REFERRAL_BUTTON=Copy Link
REFERRAL_REWARD=Referral %d: %d %s
REFERRAL_LINK_COPY=https://referral.disneyheroesgame.com?t=%s
