
EDIT_SUBCLASS=Edit Subclass
SUBCLASS_WINDOW_LOW_RARITY=Promote this Hero to Emerald to Unlock and Edit their Subclass! They'll also gain the stats detailed below! For more information about Emerald Rank, check out the How-To-Play.
SUBCLASS_WINDOW_STAT_GAIN_TITLE={#ffe00f}New Core and Level Scaling Stats{}
SUBCLASS_WINDOW_STAT_GAIN={#55fe87}+%1$d{}
SUBCLASS_WINDOW_SUBTITLE=%1$s is a {#%5$s}Tier %2$s{} - {#fedf0f}%3$s{} %4$s Hero
SUBCLASS_ROLE_FORMAT={#%3$s}Tier %1$d{} - {#fedf0f}%2$s{}
STAT_SELECTION_SLOT_TITLE=Stat %1$d Selection:
STAT_SELECTION_DROPDOWN_CHOICE=+%1$d %2$s
NORMAL_CRIT_DESCRIPTION={#fedf0f}Normal Critting:{} This Hero gains {#55fe87}%1$d{} Normal Crit and now has a base {#55fe87}%2$d%%{} chance to Normal Crit max level enemies.\n\nAnything between 101%%-200%% is converted into Super Crit chance.
FANTASTIC_CRIT_DESCRIPTION={#fedf0f}Fantastic Critting:{} This Hero gains {#55fe87}%1$d{} Fantastic Crit and now has a base {#55fe87}%2$d%%{} chance to Fantastic Crit max level enemies.\n\nAnything between 101%%-200%% is converted into Super Crit chance.
CRIT_DAMAGE_DESCRIPTION={#fedf0f}Hard Hitting:{} This Hero gains {#55fe87}%1$d{} Crit Damage and now has a base {#55fe87}%2$d%%{} increase in Critical Strike damage against max level enemies.
ARMOR_NEGATION_DESCRIPTION={#fedf0f}Armor Piercing:{} This Hero gains {#55fe87}%1$d{} Armor Negation and now at base ignores {#55fe87}%2$d%%{} of the Armor on max level enemies.
REALITY_NEGATION_DESCRIPTION={#fedf0f}Reality Shattering:{} This Hero gains {#55fe87}%1$d{} Reality Negation and now at base ignores {#55fe87}%2$d%%{} of the Reality on max level enemies.
TENACITY_DESCRIPTION={#fedf0f}Tenacious:{} This Hero gains {#55fe87}%1$d{} Tenacity and now has a base {#55fe87}%2$d%%{} reduction of Disable durations from max level skills cast by enemies.
EVASION_DESCRIPTION={#fedf0f}Evasive:{} This Hero gains {#55fe87}%1$d{} Evasion and now has a base {#55fe87}%2$d%%{} chance to avoid Disables from max level skills cast by enemies.
IMPROVED_HEALING_DESCRIPTION={#fedf0f}Better Healer:{} This Hero gains {#55fe87}100%%{} Improved Healing and now at base heals for {#55fe87}100%%{} more.
STAT_BREAKDOWN_TITLE=Stat Breakdown
STAT_BREAKDOWN_BASE_STAT=Base Stat:
STAT_BREAKDOWN_ENCHANTMENT=Enchantment:
STAT_BREAKDOWN_RED_SKILL=Red Skill:
STAT_BREAKDOWN_MEMORY_DISK=Memory Disk:
STAT_BREAKDOWN_MODS=Mods:
STAT_BREAKDOWN_PATCH_BONUS=Patch Bonus:
STAT_BREAKDOWN_SUBCLASS=Subclass:
STAT_BREAKDOWN_EMERALD_RANK=Emerald Rank:
STAT_BREAKDOWN_MAX_EFFECTIVENESS=The max effectiveness for this stat is {#ffe00f}%1$d%%{}.
DETAILED_STATS_ROLE_LIST=%1$s, %2$s, Tier %3$d %4$s
NORMAL_CRIT_ADJECTIVE=Normal Critting
FANTASTIC_CRIT_ADJECTIVE=Fantastic Critting
CRIT_DAMAGE_ADJECTIVE=Hard Hitting
ARMOR_NEGATION_ADJECTIVE=Armor Piercing
REALITY_NEGATION_ADJECTIVE=Reality Shattering
TENACITY_ADJECTIVE=Tenacious
EVASION_ADJECTIVE=Evasive
IMPROVED_HEALING_ADJECTIVE=Better Healer
DETAILED_STATS_AMBITION=Ambition:
SHOW_MAX_STAT_WARNING_PLAYER_PREF=Show Max Stat Warnings
OVER_MAX_STAT_PERCENTAGE=This exceeds the maximum amount by %1$d%%!
STAT_DOUBLE_PERCENT=(%1$d%% / {#b3e917}%2$d%%{})
STAT_SINGLE_PERCENT=(%1$d%%)
