
ENCHANT_CONFIRM_ITEM_CHANGE_BUTTON=Switch Badge
ENCHANT_CONFIRM_ITEM_INFO=Are you sure you want to start over enhancing a different badge?
ENCHANT_NO_GEAR_IN_SLOT=Equip a badge in that slot to start enhancement.
ENCHANT_WHITE_ITEM_ERROR=You can't enhance a white badge.
ENCHANT_AT_MAX_STARS=Badge Maxed!
ENCHANT_BUTTON=Enhance!
ENCHANT_CLEAR=Undo
ENCHANT_MAX=Max Enhance!
CONFIRM_MAX_ENCHANT=Are you sure you want to max enhance this Item?
ENCHANT_MATERIALS_EMPTY=Choose some materials before enhancing.
ENCHANT_POINTS_FLY_TEXT=%1$s Points
ENCHANTING_MATERIALS_HEADING=Materials
ENCHANTING_SORT_BUTTON=Sort
ENCHANTING_NO_MATERIALS=No Materials Available
ENCHANT_CHOOSE_GEAR_SLOT_ERROR=Choose a badge slot on the left to start enhancing.
ENCHANT_FULL_STARS_READY=Ready to Enhance!
ENCHANTING_TITLE=Enhancement
MATERIALS_RECOVERED_TITLE=Materials Salvaged!
MATERIALS_RECOVERED_INFO=Promotion removes all enhancements, but refunds some materials.
AUTO_ADD=Auto Add
SETTINGS=Settings:
MATERIAL=Material
USE_WITH_AUTO=Use with auto?
NUM_TO_SAVE=Number to Save
SD_CARDS=SD Cards
WHITE_BADGES=White Badges
GREEN_BADGES=Green Badges
BLUE_BITS=Blue Bits
BLUE_BADGES=Blue Badges
PURPLE_BITS=Purple Bits
PURPLE_BADGES=Purple Badges
ORANGE_BITS=Orange Bits
ORANGE_BADGES=Orange Badges
RED_BITS=Red Bits
RED_BADGES=Red Badges
YELLOW_BITS=Yellow Bits
YELLOW_BADGES=Yellow Badges
AUTO_FEATURE=Auto "Enhance Max" Feature
REACH_VIP_UNLOCK=Reach {#ffe00f}VIP Level 6{} to unlock:
SETTINGS_TITLE=Auto Enhance Settings
AUTO_ADD_FAILED=No items added. Try adjusting your Auto Enhance settings.
PB_ENCHANT_AT_MAX=Battle Badge Maxed!
PB_ALREADY_ENHANCED=Battle Badge is already enhanced!
PB_READY_TO_ENHANCE=Ready to enhance!
FREE_ENHANCE_TITLE=Enhance?
FREE_ENHANCE_DESC=There's no cost to enhance this Battle Badge since you don't already have one enhanced, but any additional Battle Badge enhancements will require you to spend materials.  Are you sure you'd like to continue?
UNLOCK_BB_TO_ENHANCE=Unlock this hero's Battle Badge to enhance it.
TOTAL_ENHANCED=Total Enhanced: {#17A2FF}%1$s{}
MAX_UPGRADE_BATTLE_BADGE=Enhance all
MAX_UPGRADE_BATTLE_BADGE_TOGGLE=Enhance all badges
MAX_UPGRADE_BATTLE_BADGE_TITLE=Enhance all badges?
MAX_UPGRADE_BATTLE_BADGE_INFO=This will enhance all badges for %1$s using the materials below. Continue?
MAX_UPGRADE_CONFIRM_COST=Cost
