
COMBAT_BACKGROUND_TITLE=Combat Background
SHOW_PREVIEW_LABEL=Show Preview
ESPORTS_ARENA_3=Arena
COLISEUM=Coliseum
CITY_CENTER_1=City Center
CITY_ROOFTOPS_2=City Rooftops
AGRABAH_MARKET_3=Agrabah Market
ARENDELLE_10=Arendelle
PARK_MIDWAY_12=Park Midway
HUB_PARK_4=Hub Park Day
HUB_PARK_9=Hub Park Night
