
EVENTS_WINDOW_TITLE=Events
IAPS_WINDOW_TITLE=DEALS
EVENT_CARD_COMPLETE=Event Complete
STARTS_IN_PREFIX=Starts in: %1$s
ENDS_IN_PREFIX=Ends in: %1$s
COMING_SOON=Coming Soon!
EVENT_DIRECT_BUY=%1$s %2$s
BUY_ORDINAL_FORMAT=%1$s Buy
DAILY_REWARDS_EVENT_TITLE=Free Rewards Every Day!
DAILY_REWARDS_CHANCES=Daily Chances Reset
DAILY_REWARDS_STAMINA=Free Stamina
DAILY_REWARDS_TRADER=Market Refreshed
DAILY_REWARDS_FIGHT_PIT=Arena Rewards
EVENT_DETAILED_INFO=Detailed Info
DAILY_REWARDS_TIME_ZONE=(All times listed are in your local timezone)
DAY_2_HERO_TITLE=Free Hero
DAY_2_HERO_TOMORROW_INFO=Come back tomorrow for a {#ffe00f}FREE{} 2-Star Hero!
DAY_2_HERO_CHOOSE_INFO=Thanks for playing Disney Heroes: Battle Mode. Here is your special reward. Pick a two-star hero of your choice!
DAY_2_HERO_CHOOSE_HELP=Select one hero for your reward.
DAY_2_HERO_CHOOSE_BUTTON=Pick Hero
DAY_2_HERO_CONFIRM=Are you sure you want to choose %1$s as your Free Hero?
DAY_2_HERO_NO_HEROES=There are no heroes available.
DAY_2_HERO_CONFIRM_ALREADY_HAVE=You already have %1$s! Are you sure you still want to pick it? You will receive 18 hero chips for this hero.
ACTIVATED_PREFIX=Activated: %1$s
BUFF_OVER=Today's Power Up Bonus is over.
COME_BACK_TOMORROW=Come back tomorrow to activate it again!
DIAMOND_BUNDLE_PURCHASE=Purchase complete. Collect your rewards from your mailbox!
BUY_BUNDLE=Buy Bundle
CONFIRM_PURCHASE=Buy %1$s for %2$d %3$s?
IN_STOCK_FORMAT=In Stock: %1$s
FIRST_PURCHASE_TITLE=First Purchase Deal!
FIRST_PURCHASE_INFO=Get more than 2x the normal amount of diamonds plus a ton of VIP Rings!
LIMITED_TIME_OFFER_BADGE=Limited Time Offer!
FIRST_IAP_TITLE_FORMAT=%1$s Deal!
FIRST_IAP_INFO=Get tons of bonus diamonds with your first purchase of this Diamond pack!
DAY_30_DEAL_TITLE=30-Day Deal!
FREE_OFFERS_TITLE=Free Diamonds Now!
FREE_OFFERS_INFO=Earn tons of free diamonds and even VIP Rings from our free daily offers and surveys!
MONTHLY_EVERY_DAY_INFO=%1$d every day for %2$d days
TOTAL_FORMAT=%1$s total!
EVENT_EXCLUSIVE_HERO=Special Event Exclusive
PERCENT_MORE_FREE=%1$d%% MORE FREE
SOLO_DEALS_FOOTNOTE_DEFAULT=This deal does not stack with any other packs or offers.
FIRST_PURCHASE_BONUS=1st Purchase Bonus!
FIRST_DIAMOND_BONUS=1st Diamond Bonus!
FIRST_PACK_BONUS=1st Pack Bonus!
USER_WISE_SURVEY_INVITE_MSG=Thanks for playing Disney Heroes: Battle Mode!  Would you be willing to help us improve the game by answering a few quick questions?
USER_WISE_SURVEY_INVITE_TITLE=BE OUR HERO!
BOOSTER_RESTART_TITLE=Restart for Rewards!
BOOSTER_RESTART_DESC=We have to restart the game to get your account Battle Mode Ready! Please wait while we get your awesome rewards delivered and your heroes ready for Action!
BOOSTER_PURCHASE_TITLE=Battle Boost Ready!
BOOSTER_PURCHASE_1=Team levels unlocked!
BOOSTER_PURCHASE_2={#ffe00f}%1$s{} Heroes boosted to {%2$s}%3$s{} with skills maxed!
BOOSTER_PURCHASE_3={#ffe00f}%1$s{} campaign chapters complete!
BOOSTER_PURCHASE_4={#ffe00f}%1$s{} modes unlocked!
