
SCREEN_TITLE=City Watch
SHOP_BUTTON=Shop
CHANGE_DIFFICULTY_BUTTON=Difficulty: %1$s
RESET_BUTTON=Reset (%1$d)
NO_EXPEDITION_RESETS_REMAINING_ERROR=You've used all your City Watch resets today.
EXPEDITION_ONE_RESET_LEFT=1 Reset Left Today
EXPEDITION_RESETS_LEFT=%1$d Resets Left Today
BOGO_INTRO_TEXT=Help! Creeps have invaded the city! Head over to %1$s to help clean them up!
BOGO_INTRO_TEXT_LATER_ROUNDS=Help! More creeps have invaded the city! Head over to %1$s to help clean them up!
BOGO_COMPLETE_TEXT=Great job, recruit! The city looks safe... for now. Check back later. I'm sure some new trouble will pop up.
FIGHT_BUTTON=Fight!
BOGO_REWARDS_TEXT=Nice work cleaning things up! Here are your rewards. Don't let it go to your head, rookie!
THANKS_BUTTON=Thanks!
ENTER_BUTTON=Enter!
GOLD_TOTAL_HEADING=%1$s Mode Total:
PIN_1_1=Canal Street
PIN_1_2=Flying Fish Road
PIN_1_3=Nautilus Trail
PIN_1_4=Jetsam Way
PIN_1_5=Flotsam Alley
PIN_1_6=Dory Street
PIN_1_7=Port Station
PIN_1_8=Dock 5B
PIN_1_9=Dock 7A
PIN_1_10=Treasure Road
PIN_2_1=Shell Game Station
PIN_2_2=West Village
PIN_2_3=Back Alley
PIN_2_4=Madison Avenue
PIN_2_5=7th Avenue
PIN_2_6=Market Street
PIN_2_7=5th Avenue
PIN_2_8=Center Station
PIN_2_9=Ceiling Street
PIN_2_10=Market Square
PIN_3_1=Avenue A
PIN_3_2=Center Station
PIN_3_3=Avenue D
PIN_3_4=Jumbeaux Road
PIN_3_5=Avenue M
PIN_3_6=Modway
PIN_3_7=Avenue S
PIN_3_8=Way Station
PIN_3_9=Avenue U
PIN_3_10=The 1-40
PIN_4_1=Hideaway Beach
PIN_4_2=Walnut Street
PIN_4_3=Narrow Way
PIN_4_4=Playbill Station
PIN_4_5=Prince Street
PIN_4_6=Seabright Station
PIN_4_7=Dandy Avenue
PIN_4_8=Sunny Cove Station
PIN_4_9=Haute Avenue
PIN_4_10=Oswalt Station
PIN_5_1=Central Square
PIN_5_2=Pin Street
PIN_5_3=Central Crossing
PIN_5_4=Lower City Center
PIN_5_5=Pine Street
PIN_5_6=Oodelally Alley
PIN_5_7=Bridgeway Station
PIN_5_8=Lower Middle Burroughs
PIN_5_9=Bay Station
PIN_5_10=Melody Road
PIN_6_1=Underground Hackerspace
PIN_6_2=Park Station
PIN_6_3=Magic Midway
PIN_6_4=Elle Bridge Park
PIN_6_5=University Road
PIN_6_6=Southern Station
PIN_6_7=Pride Street
PIN_6_8=Mystic Lane
PIN_6_9=By the Boardwalk
PIN_6_10=Never Never Road
DIFFICULTY_1=Easy
DIFFICULTY_2=Medium
DIFFICULTY_3=Hard
DIFFICULTY_4=Epic
DIFFICULTY_2_UNLOCK_ERROR=Beat an Easy City Watch to unlock Medium difficulty.
DIFFICULTY_2_ONLY_ON_RESET_ERROR=Try Medium difficulty the next time you reset your City Watch.
DIFFICULTY_3_UNLOCK_ERROR=Beat a Medium City Watch to unlock Hard difficulty.
DIFFICULTY_3_ONLY_ON_RESET_ERROR=Try Hard difficulty the next time you reset your City Watch.
DIFFICULTY_4_UNLOCK_ERROR=Beat a Hard City Watch to unlock Epic difficulty.
DIFFICULTY_4_ONLY_ON_RESET_ERROR=Try Epic difficulty the next time you reset your City Watch.
DIFF_BULLET_WEEKLY_WARD=1 Weekly Ward
DIFF_BULLET_WEEKLY_WARDS=%1$d Weekly Wards
DIFF_BULLET_EPIC_WARDS=1 Weekly and 1 Daily Ward
DIFF_BULLET_GOLD_REWARDS=Gold rewards
DIFF_BULLET_TOKEN_REWARDS=Token rewards
DIFF_BULLET_NO_SPECIAL_RULES=No special rules
DIFF_BULLET_GOLD_REWARDS_FORMAT={#ffe00f}%1$s{} Gold rewards
DIFF_BULLET_DISK_POWER_FORMAT={#ffe00f}%1$s{} Disk Power rewards
DIFF_BULLET_NO_REGEN=HP & Energy don't regen
DIFF_BULLET_EPIC_KEYS=Epic City Watch {#ffe00f}Keys{}
DIFF_BULLET_EPIC_SKILL_CHIPS=Red {#ffe00f}Skill Chips{}
DIFF_BULLET_RED_REQUIRED=Requires 1 Red Rank hero
EXPEDITION_RESET_WINDOW_TITLE=Reset
EXPEDITION_CHANGE_DIFFICULTY=Change Difficulty
EXPEDITION_CHOOSE_DIFFICULTY_FOR_NEXT=Choose a difficulty for your next City Watch:
EXPEDITION_RESET_DISCLAIMER=Note all rewards and special rules are cumulative.
RETRY_TITLE=Retry Attack?
RETRY_KEEP_BUTTON=Keep Result
RETRY_BUTTON=Retry Attack
RETRY_INFO=Retry this attack? You'll lose this result.
EXPEDITION_LOSS_WARNING=Retrying the attack will reset the fight and allow you to try again. If you keep the result, enemies will keep their remaining HP and you can use a second wave of heroes to try and defeat them.
MAP_LOAD_ISSUE_INFO_PLAYER=There was an issue loading the map. This has been reported and we're looking into it!
MAP_LOADING_TEXT=Scanning City Map
EXPEDITION_COMPLETE=Watch Complete!
ALL_HEROES_USED=You've used all your heroes for this City Watch.
REGION_CLEARED_TITLE=Region Cleared
CONSIDER_RAID_TITLE=Time to Raid!
CONSIDER_RAID_DESC=Your Raid Tickets are full/almost full. If you manually complete your next City Watch, you won't receive any additional Raid Tickets.
CONSIDER_RAID_DECLINE=Manual
RAID_CONTEST_DISCLAIMER=Warning: Raiding City Watch may not earn Contest Points because your Heroes do not fight.
CONFIRM_RAID_TITLE=Raid %1$s Difficulty
RESET_AND_RAID=Reset and Raid
RAIDING_DIFFULTY_NOT_UNLOCKED=Beat a %1$s City Watch to unlock Raiding.
EARN_RAID_TICKETS=Earn a %1$s by completing a full City Watch on %2$s difficulty.
USE_RESET_MSG=You will not be able to increase the difficulty of this City Watch unless you use a reset.
EPIC_KEY_WARNING=Any Epic City Watch Keys you used will be lost.
GET_EPIC_KEYS=Get Epic City Watch Keys by doing Hard City Watch
EPIC_REWARDS=Epic Rewards:
NEXT_RESET_IN=Your next City Watch reset is in: %1$s
EPIC_PREVENT_MERC=You need at least one Red rank hero in your lineup before hiring a mercenary.
GENERIC_TRY_RESET=Try this difficulty next time you reset your City Watch.
RESETS_FULL=Resets Full!
RED_SKILL_QUICK_ERROR=You need at least one Red rank hero in your lineup.
DEFEATED=Defeated
HEROES=HEROES:
OPPONENTS=OPPONENTS:
EPIC_RAID_REWARDS_TITLE=Epic Rewards
CHOOSE_CHIPS_TITLE=Choose Your Chips
CHOOSE_CHIPS_SUBTITLE=Pick up to five heroes to include for a chance at winning their Red Skill Chips
EPIC_RAID_REWARDS_INFO=Up to a total of %1$d Red Skill Chips randomly awarded between the heroes you choose.
PLUM_REGION_NAME=Downtown
GREEN_REGION_NAME=Oceanside
PURPLE_REGION_NAME=Seashore Flats
ORANGE_REGION_NAME=Uptown
BLUE_REGION_NAME=Middle Burroughs
YELLOW_REGION_NAME=Sunset Bay
