
FRIENDSHIP_LOCKED_INFO=To unlock this friendship, %1$s must be level %2$d and %3$s must be level %4$d. Both heroes must be rank %5$s or higher.
MAX_LEVEL=Max Level!
WALL_BUTTON=Wall
CAMPAIGN_BUTTON=Campaign
MISSIONS_BUTTON=Missions
GEAR_BUTTON=Disk
WALL_NEW_ENTRIES=New Entries
WALL_OLDER_ENTRIES=Older Entries
NO_AVAILABLE_FRIENDS=No friends available
NO_AVAILABLE_FRIENDS_LONG=No friends have been released for this hero yet.
FRIENDS_FEATURE=Friends
FRIEND_UNLOCK=%1$s and %2$s are now friends!
FRIEND_LEVEL_UP=%1$s and %2$s's friendship is now Level %3$d!
MISSION_UNLOCK=- New Mission unlocked: "%1$s"
EMOJI_UNLOCK=- New Emoji unlocked: "%1$s"
CHAPTER_UNLOCK=Episode %1$d %2$s Unlocked!
FRIEND_CAMPAIGN_CHAPTER_COMPLETE=Episode %1$d %2$s Complete!
FRIEND_CAMPAIGN_INTRO=Friend Campaign %1$s Started!
FRIEND_CAMPAIGN_COMPLETE=Friend Campaign %1$s Complete!
FRIEND_CAMPAIGN_SHORT_COMPLETE=Friend Campaign Complete!
REAL_GEAR_UNLOCK=- %1$s Unlocked!
UNLOCK_FEATURE_AT_LEVEL=Unlock %1$s at Friend Level %2$d
MISSION_LEVEL_UP="%1$s" Mission: Now Level %2$d!
MISSION_FIRST_STORY_NOTE="%1$s" Mission: First Update!
MISSION_STORY_NOTE="%1$s" Mission: Update!
REAL_GEAR_LEVEL_UP="%1$s" now level %2$d!
REAL_GEAR_EVOLVED="%1$s" now at %2$d stars!
REAL_GEAR_MAXED="%1$s" is maxed!
CHAPTER_X=Episode %1$d
CHAPTER_X_COLON=Episode %1$d:
LEVELS_COMPLETE=Complete
GO_BUTTON=Go!
CHAPTER_STATUS_COMPLETED=Friend Episode %1$d has already been completed.
CHAPTER_STATUS_FL_LOCKED=Reach Friend Level %1$d to unlock this Friend Episode.
CHAPTER_STATUS_PROGRESS_LOCKED=Complete the previous Friend Episode(s) to unlock this one.
LEVEL_STATUS_COMPLETED=This level has already been completed.
LEVEL_STATUS_FL_LOCKED=Reach Friend Level %1$d to unlock this level.
LEVEL_STATUS_NORMAL_CH_NOT_COMPLETE=Complete normal campaign Chapter %1$d Level %2$d to unlock this Friend Episode.
LEVEL_STATUS_PREVIOUS_LEVEL_NOT_COMPLETE=Complete the previous level to unlock this one.
LEVEL_STATUS_CH_TL_LOCKED=Increase your Team Level to %1$d to unlock this Friend Episode.
GO_BUTTON_FL_LOCKED=Unlock at Friend Level %1$d.
NEED_FRIEND_STAMINA=Looks like you need more Friend Stamina!
REAL_GEAR_EQUIP_BUTTON=Equip
REAL_GEAR_UNEQUIP_BUTTON=Unequip
REAL_GEAR_LEVEL_BUTTON=Level Up
REAL_GEAR_EVOLVE_BUTTON=Evolve
REAL_GEAR_LOCKED_INFO=Complete the %1$s/%2$s Friend Campaign to unlock!
REAL_GEAR_LOCKED_BUTTON=Locked
REAL_GEAR_LEVEL=Level
REAL_GEAR_JUICE_OWNED_FORMAT=Owned: %1$s
REAL_GEAR_STARS_HEADING=Stars
LEVEL_STATUS_NORMAL_CH_NOT_AVAILABLE=The normal chapter that corresponds to this Friend Campaign is not yet available.
REAL_GEAR_EQUIPPED=Equipped!
REAL_GEAR_EVOLVE_CONFIRM=Do you want to evolve "%1$s" to %2$s stars?
REAL_GEAR_LEVEL_CONFIRM=Do you want to level up "%1$s" to level %2$s?
REAL_GEAR_CONFIRM_COST_PREFIX=Cost:
REAL_GEAR_CONFIRM_COST_FORMAT={#38fb92}%1$s{} %2$s
REAL_GEAR_CONFIRM_UPGRADE_PREFIX=Upgrade:
REAL_GEAR_EVOLVE_GET_BITS_INFO=Add Stars to this Disk by collecting Memories. Get Memories from Missions or the Memory Market!
REAL_GEAR_EVOLVE_FL_INFO=Reach Friend Level %1$d to evolve again!
REAL_GEAR_EVOLVE_MAX_STARS_INFO=This Memory Disk is at max stars.
REAL_GEAR_LEVEL_MAXED=Maxed
ADD_MISSION_TITLE=Add A Mission
MISSION_REWARDS_PREFIX=Rewards:
FRIEND_XP_SHORT=FXP
MISSION_BUTTON_ACTIVE=Active!
MISSION_BUTTON_COLLECT=Collect
MISSION_BUTTON_START=Start
MISSION_SUCCESS_CHANCE=Success: %2$s%1$s%%
MISSION_COMPLETE=Complete!
MISSION_HERO_ANY=Any
MISSION_FILTER_STARTABLE=Startable
MISSION_FILTER_ALL=All
NO_MISSIONS_STARTABLE=You don't have any startable missions for this selection of heroes.
NO_MISSIONS=You don't have any unlocked missions for this selection of heroes.
SUCCESS_PERCENTAGE=%2$s%1$s%%
SUCCESS_PREFIX=Success:
DURATION_PREFIX=Duration:
MISSION_IN_USE_PREFIX=In Use:
MISSION_REQUIRES_PREFIX=Requires:
MISSION_DANGER_TITLE=Danger
MISSION_DANGER_INFO=Your chance of completing this Mission is less than 50%!
MISSION_DANGER_PURPLE_INFO=Increase your chances by improving your heroes' level, rank, stars, and badges.
MISSION_DANGER_CANCEL_BUTTON=Bail
MISSION_DANGER_START_BUTTON=Risk It
MISSION_SUCCESS=Success
MISSION_FAILURE=Failure
MISSION_SUCCESS_SUBTITLE=Mission Accomplished!
MISSION_FAILURE_SUBTITLE=Better Luck Next Time!
MISSION_RESTART_BUTTON=Restart
MISSION_CONTINUE_BUTTON=Continue
MISSION_NOTE_FOUND=Mission Update!
FRIEND_CAMPAIGN_COMPLETE_INFO=Campaign Complete!
MISSION_DURATION_PREFIX=Duration:
FRIENDSHIP_UNLOCKED_TITLE=Friendship Unlocked!
FRIENDSHIP_LEVEL_UP_TITLE=Friend Level Up!
MISSION_LEVEL_UP_TITLE=Mission Level Up!
OLD_REWARDS_HEADING=Old Rewards:
NEW_REWARDS_HEADING=New Rewards:
FRIENDSHIP_LOCKED_TITLE=Friendship Locked
FRIENDSHIP_LOCKED_SUBTITLE=To Unlock You Need:
HERO_TOOLTIP_NO_REAL_GEAR=None
FRIEND_CAMPAIGN=Friend Campaign
HERO_CHOOSER_ONLY_THESE_HEROES=Only these heroes are available for this fight.
CAMPAIGN_COMPLETE_TITLE=Friend Campaign Complete!
CAMPAIGN_COMPLETE_INFO={#ffe00f}Memory Disk Unlocked:{} %1$s
VIEW_DISK_BUTTON=View Disk
CANT_REMOVE_FRIEND_FROM_CHOOSER=This Hero is required for this fight.
GET_FRIEND_STAMINA_INFO=You can only get more Friend Stamina over time. Use it wisely!
FRIEND_STAMINA_FULL_INFO=Your Friend Stamina is full! You can use it in the Friend Campaigns!
FINISH_BUTTON=Speed Up
FINISH_CONFIRM=Do you want to finish %1$s for %2$s diamonds?
REAL_GEAR_LEVEL_MAXXED=Maxed
FRIENDS_TL_UNLOCK_ERROR=Reach Team Level %1$d to unlock Friend Campaigns.
REAL_GEAR_COMING_SOON_HEADING=Memory Disks are coming soon!
REAL_GEAR_COMING_SOON_INFO=You can unlock them by completing Friend Campaigns, but you can't equip or upgrade them yet.
ADD_WINDOW_FRIEND_1=Friend 1:
ADD_WINDOW_FRIEND_2=Friend 2:
NOT_FINISHABLE_YET=Your VIP level allows finishing when there is 1 hour left.
NOT_FINISHABLE_YET_MULTIPLE=Your VIP level allows finishing when there are %1$d hours left.
FILTER_PREFIX=Filter:
FILTER_STATUS_PREFIX=Status:
FILTER_REWARDS_PREFIX=Rewards:
FILTER_FRIENDS_PREFIX=Friends:
FILTER_CATEGORY_PREFIX=Category:
RESTART_CONFIRM=Restart?
RESTART_SPEND_TO_RESTART=You need these items to restart this Mission:
RESTART_NEED_ITEMS_TO_RESTART=You are missing item(s) required to start this Mission. Tap on a missing item to craft or get more of it.
MISSION_FAILURE_REFUNDED=The items used to start the Mission have been refunded:
COMPLETE_CAMPAIGN_TO_UNLOCK=Complete more normal campaign chapters to unlock more Friends Episodes.
MISSION_UNLOCKED=New Mission Unlocked:
CANCEL_MISSION_TITLE=Cancel Mission?
CANCEL_MISSION_CONFIRM=Are you sure you want to cancel "%1$s"? Any Mission progress will be lost, but if any Hero Chips were spent, they will be refunded.
BEST_FRIENDS_HEADING=Best Friends:
BEST_FRIENDS=You've graduated from Friend Daily Quests.  Collect Friend XP from Missions and Friend Campaign from now on!
CAMPAIGN_UNLOCKED_HEADING=Friend Campaign Unlocked:
COMPLETE_CAMPAIGN_FOR_MEMORY_DISK=Complete this Friend Campaign to unlock a Memory Disk!
MISSION_SORT_ANY=Any
MISSION_SORT_STARTABLE=Startable
MISSION_SORT_NOT_STARTABLE=Not Startable
MISSION_SORT_DISK_POWER=Disk Power
MISSION_SORT_MEMORIES=Memories
MISSION_COLLECT_AND_RESTART=Collect & Restart
MERCHANT_GEAR_BIT_NEXT_STAR=Next Star:
EMOJI_CONTENT_LOCKED=This emoji will become available in a future update.
FINDER_UNLOCKS=Unlocks:
FINDER_EASY=EASY
FINDER_MEDIUM=MEDIUM
FINDER_HARD=HARD
CHAPTER_SHORT_X=Ep.%1$d
SORT_UNLOCKED=Unlocked
HEADER_FRIENDSHIP=Friendship
HEADER_CAMPAIGN=Campaign
HEADER_DISK=Memory Disk
LEVEL_SHORT=Hero Lvl
LEVEL=Level
FINDER_SORT_DISK_LEVEL=Disk Level
SORT_LOCKED=Locked
SORT_COMPLETED=Completed
SORT_COMPLETED_EMPTY=You haven't completed any Friend Campaigns yet.
SORT_COMPLETED_EMPTY_FAVORITES=You haven't completed any Friend Campaigns yet that are favorited.
SORT_LOCKED_EMPTY=You don't have any locked Friend pairs.
SORT_LOCKED_EMPTY_FAVORITES=You don't have any favorited and locked Friend pairs.
SORT_UNLOCKED_EMPTY=You don't have any unlocked Friend Campaigns yet.
SORT_UNLOCKED_EMPTY_FAVORITES=You don't have any favorited and unlocked Friend Campaigns yet.
SORT_ALL_EMPTY_FAVORITES=You haven't favorited any Friend Campaigns yet.
COLLECT_ALL_BUTTON=Collect All
MISSIONS_READY_FORMAT=%1$s Missions Ready
ONE_MISSION_READY=1 Mission Ready
COLLECT_ALL_RESULTS_INFO=Here are the total rewards from your %1$s completed Missions:
RESTART_ALL_BUTTON=Restart All
RESTART_ALL_CONFIRM_TITLE=Restart All?
RESTART_ALL_CONFIRM_INFO=You need these items to restart your %1$s completed Missions:
NONE_OF_COLLECTED_MISSIONS_READY=None of the collected missions are ready to start.
COLLECTED_MISSION_NOT_READY=This mission is not ready to start.
MISSIONS_COLLECT_ALL_FAILED_INFO=You had %1$s failed Missions. Items used were refunded.
SPEED_UP_WINDOW_TITLE=Use Mission Speedups
SPEED_UP_TIME_FORMAT=Your "%1$s" Mission has [#ffe00f]%2$s[] remaining.
SPEED_UP_VIP_INSTANT_FINISH_HEADING=VIP Instant Finish
SPEED_UP_VIP_INSTANT_FINISH_INFO=Instantly finish any mission with {#ffe00f}%1$d hours{} or less remaining.
SPEED_UP_CONSUMABLE_HEADING=Speedup Consumable
CONSUMABLE_DURATION_FORMAT=Duration: {#ffe00f}%1$s{}
CONSUMABLE_OWNED_FORMAT=Owned: {#ffe00f}%1$s{}
USE_ONE_BUTTON=Use 1
VIP_INSTANT_FINISH_UPSELL_INFO=Increase your VIP Level to use Missions Instant Finish.
NEED_MORE_CONSUMABLES=You don't own any %1$s.
FRIEND_LEVEL=Friend Level
FAVORITES_ONLY_SWITCH_HEADING={i} Only:
FAVORITES_TOOLTIP=Tap the heart icon on a friendship to make it a favorite.  Setting this filter to "ON" will then display your favorite friendships.
MISSIONS_SINGLE_LETTER=M
FRIEND_FINDER_ARROW_TOOLTIP_WON=You won the previous battle on %1$s
FRIEND_FINDER_ARROW_TOOLTIP_LOST=You lost the previous battle on %1$s
SHOP_GEAR_EQUIPPED=Equipped
SHOP_GEAR_OWNED=Owned
BUYING_GEAR_EQUIPPED=This disk is currently equipped.
BUYING_GEAR_OWNED=You own this disk but it isn't equipped.
FRIEND_TAB_LOCKED=Unlock this friendship first! (Requires both Heroes to be unlocked.)
FRIEND_TAB_MISSIONS_LIMIT=At missions limit!  Cancel a mission to start a new one.
FRIEND_TAB_MISSIONS_ON_MISSION=A hero in this friendship is already on a mission. Cancel that mission first.
FRIEND_TAB_MISSIONS_CANT=A hero in this friendship is already on a mission.
DISK_MAX_STARS=Disk Max Stars
DISK_MAX_STARS_INCREASE=Disk max stars increased!
FRIEND_MISSION_CHOOSER=Choose Friends For Mission
STATE_NOT_STARTABLE=This hero has no friend missions to start!
STATE_USED=This hero is already on a mission!
NO_CLAIMABLE_REWARDS=No rewards to claim yet!
MISSIONS_FORMAT=%1$s/%2$s missions
LOW_ON_ITEMS_WARNING=WARNING: Low on items!
REWARDS_IN=Rewards In:
RESULTS_COLON=On Completion:
MISSION_LIMIT_MSG=Can't start another Mission because you're already running the maximum number of Missions.
MISSION_TYPE_LIMIT_MSG=At limit for this mission type. Cancel a different mission of this type first.
ADD_MISSION_BTN=Add Mission
CHOOSE_MISSION_TITLE=Choose a Mission Type
MISSION_SPEED=Mission Speed
EXCLAMATION_FORMAT=+%1$s%%!
POWER_UPS_TITLE=Power-Ups
COST_OVER_TIME=%1$s / {%2$s}%3$s{}
FRIEND_CAMPAIGN_GO_BTN_LOCK=Unlock both heroes in the friendship to access their campaign.
NEXT_REWARDS_IN=Next Rewards In:
MISSION_COMPLETE_CHIPS_SPENT=%1$s Missions Completed! (%2$s Hero Chips spent)
EVERY=Every {%1$s}%2$s{}:
DONT_GO_BELOW=Don't Go Below:
MISSION_CONTINUE_TO_USE=This mission will continue to use {#ffe00f}%1$s{} every {#ffe00f}%2$s{} until you have {#ffe00f}%3$s{} remaining
MISSION_REWARDS_TITLE=Mission Rewards
SOME_LOW_ON_ITEMS=Some Missions low on items!
COMPLETE_EP_1_FRIENDS=Complete Episode 1 of the %1$s/%2$s Friend Campaign to unlock!
COLLECT_MEMORIES_AT_MARKET=Collect {#ffe00f}%1$s{} more {#ffe00f}%2$s{} to Evolve. Get more from Missions or the Memory Market!
COLLECT_MEMORIES_AND_COMPLETE_CAMP=Advance in the Friend Campaign and collect {#ffe00f}%1$s{} more {#ffe00f}%2$s{} to Evolve. Get more from Missions or the Memory Market!
COMPLETE_CAMP_STAR_LIMIT=Complete more of the Friendship Campaign to increase the max Stars of this disk!
COMPLETE_CAMP_TO_UNLOCK=Complete more of the Friendship Campaign to unlock this Memory Disk!
MISSION_CANT_START_AT_LIMIT=Can't start! You're at the limit for Missions of this type.
MISSION_CANT_START_MISSING_COSTS=Can't start! You don't have the necessary items to start this mission.
NOT_ENOUGH_MISSION_SPEEDUPS=Not enough Hero Chips to support using this many speedups.
NOT_ENOUGH_SPEEDUP_ITEMS=Not enough Mission Speedups.
TIME_OF_REWARDS=%1$s of rewards
REWARD_TIMER_TOOLTIP=Your missions will run for up to {#ffe00f}%1$s{} before pausing. Claiming rewards will reset the timer. Increase your VIP level to increase the maximum time missions will run before pausing.
MAX_REWARDS=Max rewards ({#ff0012}%1$s{})
MISSION_RECENT_SORT=Recent
MISSION_SPEED_SORT=Speed
MISSION_TYPE_SORT=Type
CAMPAIGN_COMPLETED=Campaign completed!
MISSION_SPEED_EXPLANATION=Mission Speed affects how long it takes Heroes to complete Missions. Higher progression in the Friend Heroes increase this speed. Here's the breakdown of the Mission Speed for this Mission:\n\nStars ({#ffe00f}+%1$s%%{})\nRarity ({#ffe00f}+%2$s%%{})\nHero Levels ({#ffe00f}+%3$s%%{})\nNon-Red Skill Levels ({#ffe00f}+%4$s%%{})\nRed Skill Levels ({#ffe00f}+%5$s%%{})
REAL_GEAR_AT_MAX_NO_MISSION=Can't Start! This Friendship Disk is at max stars. Complete the Friend Campaign to unlock more max stars!
SPEEDUPS_USED_NOTIF=Speedups used! Tap the CLAIM ALL button to claim your rewards.
CONFIRM_ITEM_USE=Confirm Item Use
USE_POWERUPS=Use Power-Ups
EVERY_POWERUP=Every Power-Up makes all your heroes in this Friend Campaign {#ffe00f}stronger{}!
CURRENT_LEVEL_LINEBREAK=Current \n Level:
POWER_UP_AVAILABLE_LINEBREAK=Power-Ups \n Available:
NEW_TEAM_POWER=New Team Power:
RECOMMENDED_POWER_LINEBREAK=Recommended \n Power:
PLUS_POWER_LEVELS=+%1$d Power-Up Levels!
NOT_ENOUGH_POWER_UPS=Not enough Power-Up consumables owned!
MISSION_LIMIT_TOOLTIP_HEROES_VIP=Increase your Mission limit by {#ffe00f}%1$s{} when you unlock {#ffe00f}%2$s{} more Heroes and {#ffe00f}%3$s{} when you unlock {#ffe00f}VIP %4$s{}!
MISSION_LIMIT_TOOLTIP_HEROES=Increase your Mission limit by {#ffe00f}%1$s{} when you unlock {#ffe00f}%2$s{} more Heroes!
MISSION_LIMIT_TOOLTIP_VIP=Increase your Mission limit by {#ffe00f}%3$s{} when you unlock {#ffe00f}VIP %4$s{}!
MISSION_LIMIT_TOOLTIP_AT_MAX=At the maximum number of Missions from Hero unlocks!
MISSION_LIMIT_TOOLTIP=Unlock {#ffe00f}%1$s{} more Heroes to increase your Mission limit.\n\n{#ffe00f}VIP 9{} gives {#ffe00f}+5{} max Missions!
DIFFICULTY_COLON=Difficulty:
LEVEL_FORMAT_COLOR=Level {#ffe00f}%1$s{}
FRIEND_POWERUP_HEADER=For this Friendship Campaign, each Hero gains the following stats:
FRIEND_POWERUP_FOOTER=Each Hero also gains Max HP, Basic Damage, Skill Power, Armor, and Reality based on the stats of that hero.
MODIFY=Modify
