
SEARCH_GUILDS_TITLE=Find a Guild
CREATE_GUILD=Create Guild
CREATE_GUILD_ALREADY_IN_GUILD=You must leave your current guild to create a new one.
SEARCH_GUILDS_HINT=Search Guilds...
START_GUILD_SEARCH=Use the search box above to find a guild!
NO_RECOMMENDABLE_GUILDS_FOUND=We could not find any guilds to recommend.
NO_SEARCHED_GUILDS_FOUND=No Guilds Found
SEARCH_GO=Go
GUILD_MEMBER_COUNT={#ffe00f}%1$d{} / %2$d
REQUIRES_TEAM_LEVEL_FORMAT=Requires: TL {#ffe00f}%1$d{}
POLICY_APPLICATION=Application
POLICY_OPEN=Open
POLICY_PRIVATE=Private
POLICY_FORMAT=Type: {%1$s}%2$s{}
POLICY_PREFIX=Type & Min Level:
GUILD_NAME_LENGTH_ERROR=Guild name must be between 3 and 16 characters.
GUILD_NAME_INVALID=Letters and numbers only please!
GUILD_SETTINGS_CANNOT_EDIT_NAME=You cannot change your guild name.
CREATE_GUILD_MOTTO_HEADER=Motto:
OPTIONAL=(Optional)
CREATE_GUILD_COUNTRY=Country:
CREATE_GUILD_AVATAR=Emblem:
CREATE_GUILD_NAME_HEADER=Name:
CREATE_GUILD_EMBLEM_HEADER=Emblem:
CREATE_GUILD_MIN_LEVEL_HEADER=Min Level:
CREATE_GUILD_PRIVACY_HEADER=Privacy:
GUILD_SETTINGS_CRYPT_DIFFICULTY=Surge\nDifficulty:
CREATE_GUILD_TIME_ZONE=Time Zone:
CREATE_GUILD_AUTO_POST=Aid Request Auto-Post:
CREATE_GUILD_TACTICIAN_CHAT=Allow Tacticians in Guild Officers Chat:
GUILD_SETTINGS_PERMISSION_ERROR=You don't have permission to change that setting.
GUILD_TIME_ZONE_FORMAT=%1$s (%2$s)
LONG_TIME_ZONE_FORMAT=GMT%1$s (%2$s)
CHANGE_DIFFICULTY=Change Difficulty
POSSIBLE_LOOT=Possible Loot
CRYPT_DIFFICULTY_LOCKED=Complete the previous difficulty to unlock.
CRYPT_DIFFICULTY_LEGIONS=Waves: %1$s
CRYPT_DIFFICULTY_MAX_TOKENS=Max Tokens: %1$s
LOOT_RANGE=%1$d-%2$d
GUILD_NAME_PLACEHOLDER=My Great Guild
GUILD_MOTTO_PLACEHOLDER=Join if you are great!
CRYPT_TIMEZONE_CHANGE_START=With this time zone change, the Creep Surge will start at:
CRYPT_TIMEZONE_CHANGE_WARNING=Changing the guild time again within %1$d days may lose you a Creep Surge.
CRYPT_TIMEZONE_CHANGE_BONUS=You will get a bonus Creep Surge that starts at:
CRYPT_TIMEZONE_CHANGE_NEXT_START=Your next Creep Surge will not start until:
GUILD_LEADER=Leader:
GUILD_MEMBERS=Members:
GUILD_TIME_INFO=Guild time is currently used only for Creep Surges. It may also be used for new guild features in the future.
GUILD_TIME=Guild Time:
GUILD_TOTAL_POWER=Total Power:
GUILD_TEAM_POWER=Team Power:
GUILD_HERO_STARS=Hero Stars:
GUILD_FIGHT_PIT_WINS=Arena Wins:
GUILD_CAMPAIGN_KILLS=Campaign Kills:
GUILD_RAID_WINS=Raid Wins:
GUILD_SHOP=Shop
GUILD_HERO_JOB_BOARD=Mercenaries
GUILD_MEMBERS_FULL=This guild is currently full.
FIND_MORE_GUILDS=Other Guilds
GUILD_SETTINGS=Settings
LEAVE_GUILD_PROMPT=Leave Guild?
LEAVE_GUILD=Leave Guild
LEAVE_GUILD_CONFIRMATION=Are you sure you want to leave your guild?\n\n {#ffe00f}Note:{} Leaving your guild will start a 24 hour cooldown that may prevent you from earning or participating in certain rewards and activities during that time.{i}
JOIN_GUILD=Join Guild
UNABLE_TO_JOIN_GUILD_TL=Your team level is not high enough to join this guild.
UNABLE_TO_JOIN_GUILD_PRIVATE=You are unable to join this guild.
LEAVE_CURRENT_GUILD_APPLICATION_CONFIRM=Are you sure you want to leave your current guild to apply for this guild? \n\nYou will not be placed into this guild until your request has been accepted.\n\n {#ffe00f}Note:{} You will not join the new guild until your request has been accepted.  Leaving your guild will start a 24 hour cooldown that may prevent you from earning or participating in certain rewards and activities during that time.{i}
APPLIED_TO_GUILD_MESSAGE=You have applied to join %1$s.
LEAVE_CURRENT_GUILD_CONFIRMATION=Are you sure you want to leave your current guild to enter this one? \n\n{#ffe00f}Note:{} Leaving your guild will start a 24 hour cooldown that may prevent you from earning or participating in certain rewards and activities during that time.{i}
SORT_ONLINE=Online
SORT_TOTAL_POWER=Power
SORT_FIGHT_PIT=Arena
SORT_RANK=Rank
SORT_COLISEUM=Coliseum
SORT_INFLUENCE=Influence
SORT_CONTEST=Contest
INFLUENCE_LAST_WEEK=Last week:
INFLUENCE_THIS_WEEK=This week:
INFLUENCE_LIFETIME=Lifetime:
SORT_CHECKED_IN=Checked In
TL_SHORT=TL
MEMBER_SINCE_FORMAT=Joined: %1$s
ONLINE_NOW=Online
LAST_SEEN_FORMAT=Last Seen: %1$s
ROLE_MEMBER=Member
ROLE_RULER=Ruler
ROLE_OFFICER=Officer
ROLE_CHAMPION=Champion
ROLE_VETERAN=Veteran
GUILD_MEMBER_PROMOTE=Promote to %1$s
GUILD_MAKE_LEADER=Make Leader
GUILD_MEMBER_DEMOTE=Demote to %1$s
ARE_YOU_SURE_YOU_WANT_TO_DEMOTE=Are you sure you want to demote %1$s to %2$s?
GUILD_MEMBER_KICK=Kick
ARE_YOU_SURE_YOU_WANT_TO_KICK=Are you sure you want to kick %1$s?
GUILD_LEADER_INACTIVE=Your leader has been inactive for %1$s.
GUILD_LEADER_CHAMPION_TIME=Champions can claim the leadership after %1$s.
GUILD_LEADER_OFFICER_TIME=Officers can claim the leadership after %1$s.
GUILD_CANT_CLAIM_YET=You can't claim leadership yet.
GUILD_CANT_CLAIM_ROLE=You need to be a champion or officer to claim leadership.
ARE_YOU_SURE_YOU_WANT_TO_PROMOTE=Are you sure you want to Promote %1$s to %2$s?
PERMISSION_PROMOTE_LOWER=Promote players of a lower rank.
PERMISSION_DEMOTE_LOWER=Demote players of a lower rank.
PERMISSION_CLAIM_LEADER=Claim leadership when leader is inactive for %1$s.
PERMISSION_KICK_LOWER=Kick members of a lower rank.
PERMISSION_ACCEPT_NEW_MEMBER=Accept and deny new members.
PERMISSION_EDIT_DESCRIPTION=Edit the guild motto.
PERMISSION_EDIT_AVATAR=Edit the guild emblem.
PERMISSION_EDIT_ALL=Edit everything about the guild and disband it.
PERMISSION_MAKE_LEADER=Choose the guild leader.
PERMISSIONS_NONE=Have no special permissions, but can be promoted to a higher rank.
PERMISSION_EDIT_GUILD_WALL=Post to the guild wall.
PERMISSION_EDIT_CRYPT_DIFFICULTY=Edit the difficulty of the Creep Surge.
PERMISSION_DELETE_GUILD_WALL_POSTS=Delete guild wall posts.
PERMISSION_UPGRADE_PERK=Upgrade Guild Perks.
PERMISSION_DELETE_GUILD_CHATS=Delete guild chat messages.
PERMISSION_RENAME_GUILD=Change the guild's name.
PERMISSION_WAR_QUEUE=Queue for war.
PERMISSION_WAR_UNQUEUE=Unqueue for war.
PERMISSION_WAR_TARGETING=Mark war targets.
PERMISSION_WAR_MOVE_LINEUPS=Move own war lineup.
PERMISSION_WAR_MOVE_OTHER_LINEUPS=Move allies' war lineups.
PERMISSION_OFFICER_CHAT=Use your guild's "Guild Officers" chat channel.
GUILD_MEMBERS_CAN=Members:
GUILD_VETERANS_CAN=Veterans can:
GUILD_OFFICERS_CAN=Officers can:
GUILD_CHAMPIONS_CAN=Champions can:
GUILD_LEADERS_CAN=Leaders can:
PROMOTE_CONFIRM_TITLE=Promote?
ARE_YOU_SURE_YOU_WANT_TO_MAKE_LEADER=Are you sure you want to make %1$s the leader? Type "%2$s" if you are sure:
MAKE_LEADER_CONFIRM=This can NOT be undone!\nYou will NOT be the leader!
MAKE_LEADER_YES=yes
MAKE_LEADER_TYPE_YES=Type "%1$s" if you are sure:
DISBAND_GUILD=Disband
DISBAND_GUILD_CONFIRMATION=Are you sure you want to disband your guild?
GUILD_JOB_BOARD_SCREEN_TITLE=Mercenaries
JOB_BOARD_VIP_PERK=Another mercenary slot!
JOB_BOARD_HERO_ACTIVE_ERROR=%1$s will be done in %2$s.
JOB_BOARD_REWARD_IN=Reward in:
JOB_BOARD_REQUIRES_VIP=Requires VIP %1$d
JOB_BOARD_PICK_HERO=Pick Hero
MEMBERS_SCREEN_TITLE=Guild Members
CHECK_IN_BUTTON=Check In
PERKS_BUTTON=Perks
GUILD_CREATED_INFO=%1$s has been created.
UPDATE_TIME_ZONE_TITLE=Update Time Zone
CHOOSE_FLAG_TITLE=Choose Country
REGION_AMERICA=The Americas
REGION_EUROPE=Europe
REGION_ASIA=Asia
REGION_MIDDLE_EAST=Middle East
REGION_AFRICA=Africa
REGION_OCEANIA=Oceania
CREATING_GUILD=Creating guild
YOUR_GUILD_DISBANDED=Your guild has disbanded.
YOU_WERE_KICKED=You were kicked from your guild.
CHECK_IN_INFO=Check in each day to earn rewards. The more guild members who check in, the better the rewards!
GUILD_MEMBERS_COLON=GUILD MEMBERS:
CHECK_INS_TODAY=CHECK-INS TODAY:
NEXT_REWARD=NEXT REWARD:
GUILD_CHECKIN_TITLE=Guild Check-In
LEVEL_FORMAT=Level %1$d
MERCENARY_INFO=Post your best heroes here to help your guildmates and earn Guild Coins!
HIRED_HEROES=HIRED HEROES:
UNHIRED_HEROES=UNHIRED HEROES:
EARNED_THIS_WEEK=EARNED THIS WEEK:
CANT_UPDATE_INFO=Get promoted to Champion to be able to adjust guild settings!
CHECK_IN_CAPITALIZED=CHECK IN
JOB_BOARD_BUTTON=MERCENARIES
HIRE_HERO_WINDOW_TITLE=MERCENARY BOARD
NO_GUILD_MERCENARIES=No heroes available for hiring.
STATS_BUTTON=STATS
GUILD_CHEST_BUTTON=Guild Crate
FORTRESS_DIFFICULTY=Surge Difficulty:
FORTRESS_WINS=Surge Wins:
GUILD_STATS=GUILD STATS
MEMBERS=MEMBERS
LVL_FORMAT=Lvl %1$d
CHECK_IN=Check-in:
REWARD_HEADING=Reward:
VIEW_MERC_BOARD=View Merc Board
VIEW_MERCENARY=View Mercenary
CHECKIN_CANT_CLAIM=You need more check-ins to claim these rewards.
INFLUENCE_EARNED_WEEK=Influence Earned this Week:
INFLUENCE_EARNED_LIFETIME=Total Influence Earned:
CLAIM_CHECK_IN_FIRST=Check in before claiming this reward.
CLAIMED=Claimed
DEAD_MERCENARY_ERROR=This hero is KO'ed. It can no longer be used in %1$s.
NEXT_REWARD_MAX=MAX
BADGES=Badges:
VIEW_GUILDS=View Guilds
JOIN_GUILD_LOADING=Joining...
JOIN_GUID_REQUESTED=Requested
MORE=MORE
CHOOSE_MERC=Choose Merc
CHECKIN_INFO=The more guild members who check in, the better the rewards!
CHECKIN_TODAYS_REWARDS=Today's Rewards
CHECKIN_YESTERDAYS_REWARDS=Yesterday's Rewards
READY_TO_CLAIM=Ready to claim.
NOT_ENOUGH_MEMBERS=Not enough members.
GUILD_DISBANDED_INFO=%1$s has been disbanded.
JOIN_GUILD_TO_UNLOCK=Join a {#ffe00f}GUILD{} to unlock:
CHECK_IN_REWARDS_TITLE=Check-In Rewards
REWARDS_COUNTDOWN_PREFIX=Rewards available in:
PERK_UPSELL_TITLE=Get Perks!
PERK_UPSELL_INFO=Unlock more check-in rewards by upgrading your Guild Perks!
PERK_UPSELL_BUTTON=View Perks
CHECKED_IN=Checked In
DELETE_ALL_TEXT_BUTTON=Delete All
CHECK_IN_REWARDS_NUMBER=Your guild members checked in {#ffe00f}%1$d{} times yesterday!
GUILD_COIN_HOW_TO_GET=Earn Guild Coins when: \n1) your Mercenaries are hired 2) a guild member purchases Diamonds
CHANGE_GUILD_NAME_TITLE=Change Guild Name
CHANGE_GUILD_NAME_OLD_NAME=Old Name:
CHANGE_GUILD_NAME_NEW_NAME=New Name:
CHANGE_GUILD_NAME_BUTTON=Change Name
CHANGE_GUILD_NAME_WARNING=Are you sure that you want to change your guild name to "%1$s"?
CONTEST_POINTS_TITLE=Contest Points
WAR_BUTTON=War
HIRED_YOUR_HERO=%1$s hired your hero!
PERMISSION_EDIT_WAR_EXTRA_ATTACK_ROLE=Choose who can make extra war attacks.
ADVANCED_SEARCH=Advanced Search
SHOW_FULL_GUILDS=Show "Full" Guilds:
REQ_TEAM_LEVEL=Required Team Level:
GUILD_LEVEL_COLON=Guild Level:
FROM_COLON=From:
TO_COLON=To:
SEARCH_BUTTON=Search
GUILD_AVATAR_UNLOCK_CONTEST=Unlock more guild avatars by earning them in guild contests!
GUILD_HAS_NO_LEADER=Your guild has no leader!
CLAIM_LEADERSHIP=Claim Leadership
GUILD_EMBLEM_ITEM=This is an emblem for your guild.
GUILD_ASK_HELP=Ask For Aid:
XP_HELP_TITLE=Hero XP Help
XP_HELP_INFO=You can request XP Help %1$d times every 24 hours. Do you want to request help with this level?
XP_HELP_INFO_SINGULAR=You can request XP Help %1$d time every 24 hours. Do you want to request help with this level?
XP_HELP_RECENT=Hero XP Help will be available in: {#ffe00f}%1$s{}
XP_HELP_UNAVAILABLE=Help can only be requested for heroes below level {#ffe00f}%1$d{}.
HERO_HELP_TITLE=Guild Aid
SKILL_HELP_TITLE=Skill Level Help
SKILL_HELP_INFO=You can request Skill Help %1$d times every 24 hours. Do you want to request help with this level?
SKILL_HELP_INFO_SINGULAR=You can request Skill Help %1$d time every 24 hours. Do you want to request help with this level?
CANCEL_HELP_TITLE=Cancel Help Request?
CANCEL_HELP_INFO=Upgrading this skill will cancel your active help request.
CANCEL_HELP_INFO_CANCEL=If canceled, the next skill help request can be made in {#ffe00f}%1$s{}.
TIME_REMAINING=Time Remaining:
YOU_OWN_FORMAT=You Own: {#ffe00f}%1$s{}
SKILL_HELP_RECENT=Skill Help will be available in: {#ffe00f}%1$s{}
SKILL_HELP_UNAVAILABLE=Help can only be requested for skills level {#ffe00f}%1$d{} or below.
SKILL_HELP_ALL_SKILLS_MAX=Your skills are either at their max level or above the level at which you can request help.
SKILL_NO_HELP_NEEDED=Level up your hero to request more Skill Help.
SORT_DONATIONS=Donations
RED_SKILL_UNLOCK_MSG=%1$s has unlocked %2$s's Red Skill!
DONATIONS_THIS_WEEK=This Week:
ROLE_WARLORD=Tactician
GUILD_TACTITIANS_CAN=Tacticians can:
KICK_COOLDOWN_HEADER=Use Kick Cooldown:
NO_REQUESTS_ACTIVE=No one is requesting help at the moment, please check back later.
REQUEST_COMPLETE=%1$s's Help Request Complete!
CANCEL_WARNING_INFO=Do you want to level up this hero/skill? If you do, your guild donation request will be cancelled.
REQUEST_CHAT_MSG=%1$s Needs Help!
REQUEST_COUNTER_FORMAT={%1$s}%2$s{}/%3$s
REQUEST_MAIL_XP_FORMAT=+%1s XP
SEND_AID_BUTTON=Send Aid
GUILD_AID_CHAT_POSTS=Guild Aid Chat Posts
REQUEST_AID=Request Aid
STAMINA_HELP_RECENT=Stamina Help will be available in: {#ffe00f}%1$s{}
STAMINA_HELP_UNAVAILABLE=Help cannot be requested yet.
STAMINA_HELP_INFO=You can request Stamina Help %1$d times every 24 hours. Do you want to request help?
STAMINA_HELP_INFO_SINGULAR=You can request Stamina Help %1$d time every 24 hours. Do you want to request help?
STAMINA_HELP_TITLE=Stamina Help
AID_ALL=Aid All
HELPS=Helps %1$d!
NO_REQUESTS_FULFILLED=There are no requests of this type at the moment.
AID_ALL_PROMPT_INFO=This will send a donation to every request for %1$s and use the resource or items below. Are you sure you'd like to continue?
HERO_XP_AID_TITLE=Hero XP Aid
SKILL_LEVEL_AID_TITLE=Skill Level Aid
STAMINA_TITLE=Stamina Aid
AID_ALL_INFO=Donate to every request of a specific aid type at once! Tapping a button will ask you to confirm your donations.
NOT_ENOUGH_TO_DONATE=You don't have enough to make this donation.
DONATIONS_FULFILLED_NO_DONATE=You've already donated to all requests of this type.
STAMINA_PROMPT_INFO=The donated item(s) will then be converted into raw stamina and sent to the player who requested it.
PREMIUM_STAMINA_PROMPT_TITLE=DONATE PREMIUM STAMINA?
STAMINA_PROMPT_TITLE=DONATE STAMINA?
PREMIUM_PROMPT_INFO=Helping your guildmate with this donation will use a Premium Stamina item. Are you sure you'd like to continue?
PREMIUM_PROMPT_ALL_INFO=This will send a {#ffe00f}Premium Stamina{} donation to every request for Stamina Aid and use the items below. Are you sure you'd like to continue?
NO_MERC_SLOT=No Available Mercenary Slots.
NO_HERO_REPOST=No hero to repost. Post a new hero.
REPOST_MERC_TITLE=Repost Mercenaries
REPOST_MERC_TEXT=Repost these heroes to Mercenaries?
REPOST=Repost
AID_REQUEST_AUTO_POST=Aid Request Auto-Post:
GUILD_GIFTING_TITLE=Guild Gifting
GIVE=Give Gifts
CLAIM_YOUR_GIFTS=Claim Gifts
GIVE_EVERYONE=Everyone in your {#ffe000}Guild{}:
GIVE_YOU=Extra for {#ffe000}you{}:
ANONYMOUS=Anonymous?
ANONYMOUS_DONOR=Generous Guildy
ANONYMOUS_DONOR_YOU=Generous Guildy (You)
GIFTS_DELIVERED=Gifts Delivered!
PURCHASED=Purchased!
NO_ACTIVE_GUILD_GIFTING=No active Guild Gifting event. Check your mailbox for any unclaimed rewards.
NO_GIFTS_AVAILABLE=No Gifts to Claim.
BOUGHT_ALL_GIFTS=You've already purchased all Guild Gifts this event!
FROM_FORMAT=From Members (%1$d):
BEST_SURGE_SCORE=Best Surge Score:
PERMISSION_EDIT_WAR_BAN_PROTECT=Edit Ban and Protects for war.
