
JOIN_TITLE=Join a Heist
INVITED_LIST_HEADING=Heists you're invited to:
GUILD_LIST_HEADING=Heists hosted by your guild:
PUBLIC_LIST_HEADING=Open Heists:
PLAYERS=Players
VALUABLES=Valuables
DO_HEROES_MATCH=Heroes?
NEW_HEIST_BUTTON=New Heist
HEIST_TICKETS_OWNED_FORMAT=You own: {i} {#ffe00f}%1$s{}
FREE=Free
NO_HEISTS_FOUND=No heists currently available. Start your own and invite some friends!
LVL_SHORT=LVL %1$d
CREATE_HEIST_TITLE=Create a Heist
CREATE_HEIST_NAME=Heist Name:
CREATE_PUBLIC=Public:
CREATE_LEVEL=Level:
CREATE_START_BUTTON=Start
DEFAULT_HEIST_NAME_FORMAT=%1$s's Heist
CREATE_PUBLIC_INFO=Anyone can join a Public Heist without an invite. Private Heists require you to invite friends and guild members.
HERO_TOO_LOW_LEVEL=Your hero needs to be level %1$d to join this Heist.
HERO_TYPE_DISABLED=This hero is Off Duty. Off Duty heroes can't be used in any Heists today.
HERO_IN_USE_TOOLTIP_FORMAT=%1$s | {#3ec07b}%2$s{}
INVITE_PLAYERS_TITLE=Invite Players
INVITE_FILTER_HEADING=Players to Show:
INVITE_FILTER_ALL=All
INVITE_FILTER_GUILDMATES=Guildmates
INVITE_FILTER_FRIENDS=Friends
INVITE_BUTTON=Invite
JOIN_BUTTON=Join
INVITE_SENT=Invite Sent!
INVITE_ONLINE_DOT=Online
INVITE_TICKET_DOT=Has Ticket
INVITE_NO_PLAYERS_GUILD_IN_GUILD=No guild members found.
INVITE_NO_PLAYERS_GUILD_NOT_IN_GUILD=Join a Guild to see your Guild Members in this list.
INVITE_NO_PLAYERS_FRIENDS=Players you Friend in chat will show up here.
INVITE_NO_PLAYERS_ALL=Join a Guild or Friend players in chat to add to this list.
JOIN_CONFIRM_TITLE=Join Heist
JOIN_CONFIRM_INFO=Are you sure you want to join {#ffe00f}%1$s{} ?
JOIN_CONFIRM_COST_FORMAT=Cost: {i} %1$s
JOIN_CONFIRM_COST_FREE=Cost: FREE!
PLAYERS_HEADING=%1$d/%2$d Players
PLAYER_A_FORMAT=1)
PLAYER_B_FORMAT=2)
PLAYER_C_FORMAT=3)
PLAYER_D_FORMAT=4)
PLAYER_E_FORMAT=5)
POINT_OF_INTEREST=Point of Interest
OPEN_SPACE_TITLE=Open Space
OPEN_SPACE_PROMPT=Choose a hero to stand watch:
OPEN_SPACE_INFO=Standing watch means moving your Hero to this location to look for the Thief.
OPEN_SPACE_CONFIRM_INTERRUPT=Are you sure you want to interrupt this hero's action?
OPEN_SPACE_INTERRUPT_BUTTON=Interrupt
HERO_STATUS_INFO=Hero is %1$s!
STATUS_STAND_WATCH=Standing Watch
STATUS_RUN_TO_WATCH=Running to Watch
STATUS_WALK_TO_WATCH=Walking to Watch
STATUS_RUN_TO_GUARD=Running to Guard
STATUS_WALK_TO_GUARD=Walking to Guard
STATUS_RUN_TO_INVESTIGATE=Running to Investigate
STATUS_WALK_TO_INVESTIGATE=Walking to Investigate
STATUS_CHASE_THIEF=Chasing the Thief
STATUS_RUN_TO_COMBAT=Running to Combat
STATUS_INVESTIGATE=Investigating
STATUS_AMBUSH_WAIT=Waiting at Ambush
STATUS_AMBUSH_FIGHT=In an Ambush Fight
STATUS_HIDEOUT_WAIT=Waiting at Hideout
STATUS_HIDEOUT_FIGHT=Fighting at Hideout
STATUS_THIEF_WAIT=Waiting at Thief
STATUS_THIEF_FIGHT=Fighting the Thief
STATUS_REVIVING=Reviving
STATUS_AID_COMBAT=Aiding Combat
STATUS_IDLE=Resting
STATUS_GUARD=Guarding a Valuable
POI_CHOOSE_INVESTIGATE=Choose a hero to investigate:
POI_HERO_TRAVELING=%1$s is coming over to investigate.
POI_HERO_INVESTIGATING=%1$s is investigating.
AMBUSH_TOOLTIP=Ambush
FIGHTING=Fighting
HIDEOUT_TOOLTIP=Hideout
VALUABLE_STOLEN=Stolen!
THIEF_SPOTTED=Spotted!
THIEF_CAUGHT=Caught!
THIEF_ESCAPED=The Thief Escaped!
CANT_REMOVE_WAITING_HERO=That Hero is required for this fight.
OUTCOME_TITLE_WIN=You caught the thief!
OUTCOME_TITLE_LOSE=All valuables stolen!
HEIST_REWARDS_INFO=Heist Rewards:
VALUABLES_SAVED_BONUS=%1$d Valuables Saved:
HERO_FIGHTS_WON_BONUS=%1$d Hero Fight Wins:
VICTORY_BONUS=Victory:
DIFFICULTY_BONUS=Difficulty Bonus:
INVITE_CHAT=I've just started a Heist! Help me defend The City!
INVITE_CHAT_BUTTON=View Heist
INVITE_ALREADY_IN_HEIST=You can't join because you are currently in an active Heist!
INVITE_FULL=Sorry, that Heist is full now.
INVITE_DONE=That Heist is done already.
INVITE_COMPLETE_TEXT=Heist Complete
AMBUSH_CHAT=%1$s was ambushed and needs help!
SPOTTED_CHAT=%1$s spotted the Thief. It's time to stop her!
STOLEN_PREFIX=Stolen: %1$s
NEED_FIVE_HEROES=Choose 5 heroes for this Heist.
VALUABLE_HERO_TRAVELING=%1$s is coming over to stand watch.
VALUABLE_HERO_STANDING_WATCH=%1$s is standing watch.
VALUABLE_CHOOSE_STAND_WATCH=Choose a hero to stand watch:
NEED_MORE_TICKETS=Get another free Heist chance tomorrow or buy Heist Tickets from the City Watch shop.
CLUE_BAR_INFO=Collect clues to help find the thief's hideout. The more clues you find, the closer you get to cracking a case and reducing the white circle size. The thief's hideout is somewhere inside the white circle.
VALUABLE_BAR_INFO=Valuables remaining. The thief is stealing valuables inside the city. Find her hideout or catch her before she steals all of them.
DO_STAND_WATCH=Stand Watch
DO_IDLE=Rest
VICTORY_WINDOW_TEXT_SPOTTED=The Thief loses a life!
VICTORY_WINDOW_TEXT_SPOTTED_INFINITE=The Thief has infinite lives!
INFINITE_LIVES_TIP=Find the Hideout to win the Heist!
VICTORY_WINDOW_TEXT_AMBUSH=Ambush success! Bonus clues found!
THIEF_LIVES_REMAINING=%1$d Lives Remaining...
HIDEOUT_CALLOUT=Zeroing in on the Hideout!
PLAYER_JOINED_INFO=%1$s%2$s{} joined the Heist.
GUARD_BUTTON=Guard
DIFFICULTY_EASY=Easy
DIFFICULTY_MEDIUM=Medium
DIFFICULTY_HARD=Hard
DIFFICULTY_VERY_HARD=Very Hard
DIFFICULTY_FIVE=Super Hard
DIFFICULTY_FIVE_BODYGUARDS=Bodyguards Spawn
MIN_HERO_LEVEL=Min Hero Level: %1$s
VICTORY_HIDEOUT_CLEARED=Hideout Cleared!
TOAST_THIEF_CAUGHT=Thief Caught!
TOAST_HIDEOUT_FOUND=Hideout Found!
HEIST_FULL_JOIN_BUTTON_INFO=This Heist is already full. You can watch how it progresses, or find a different Heist to join.
TUTORIAL_HEIST_NAME=Tutorial Heist
TUTORIAL_HEIST_USER=Tutorial Player
CALL_TO_COMBAT=Call
CALL_TO_COMBAT_TIME_FORMAT=(%1$s)
OUTCOME_HIDEOUT_VICTORY=Cleared
HIDEOUT_FOUND_CHAT=%1$s found the Thief's Hideout. It's time to stop her!
OUTCOME_THIEF_VICTORY=Caught
LEAVE_TUTORIAL_TITLE=Leave Heist?
LEAVE_TUTORIAL_CONFIRMATION=If you leave the Heist, you'll have to restart this Tutorial.
TOAST_THIEF_DEFEATED=You Defeated the Thief!
TOAST_THIEF_VICTORY=The Thief was victorious!
TOAST_HEIST_OVER=Heist Over!
TOAST_HEIST_OVER_VIEW_RESULTS=View Results
DEFEAT_HIDEOUT=Defeated at the Hideout!
TUTORIAL_IN_PROGRESS_TITLE=Tutorial in Progress
TUTORIAL_IN_PROGRESS_TEXT=You must complete the Heist Tutorial before you can join an active Heist.
HEIST_LOBBY_CHAT_DISABLED=Join this Heist to chat.
HEIST_LOBBY_LEAVE_BUTTON=Leave
HEIST_LOBBY_OWNER_LEAVE_CONFIRM=Are you sure you want to leave the lobby? This will kick everyone from the Heist.
DIFFICULTY=Difficulty
CHOOSE_DIFFICULTY=Choose a difficulty for your next Heist.
TOKENS_INFLUENCE=Tokens and Guild Influence
TOKENS_FORMAT_LONG=%1$s Heist Tokens per Valuable saved
TOKENS_FORMAT_SHORT=+%1$s Tokens per Valuable
TOKENS_CIRCLE_FORMAT=+%1$s Tokens per White Circle
TOKENS_CIRCLE_FORMAT_LONG=%1$s Heist Tokens per White Clue Circle completed
INFLUENCE_FORMAT=%1$s Guild Influence
NO_RULES=No special rules
DISK_POWER=Disk Power
DISK_POWER_FORMAT=+%1$s Disk Power
INFINITE_LIVES=Thief has 10 lives
MORE_DISK_POWER=More Disk Power
SPRINT_ENERGY=Thief has infinite lives
THIEF_REGEN_HP=Thief gains "Second Wind"
CUMULATIVE_REWARDS=Note that all rewards and special rules are cumulative.
NOT_UNLOCKED_DIFFICULTY=Beat the previous difficulty to unlock this one.
HEIST_LOBBY_LINEUP_HEADING=Heist Lineup
BUTTON_KICK=Kick
KICK_CONFIRM=Are you sure you want to kick %1$s from the Heist?
HEIST_CHAT_ALREADY_IN_FIGHT=Finish your current fight before starting this one.
HEIST_LOBBY_WAS_CANCELLED=That Heist was cancelled.
HEIST_LOBBY_NO_PLAYERS_LEFT=Everyone has left that Heist Lobby.
HEIST_SPECTATORS_NO_REWARDS=Spectators don't receive rewards.
HEIST_LOBBY_YOU_WERE_KICKED=You were kicked from the lobby.
HEIST_AVAILABLE_HEROES=Available Heroes
HEIST_NO_AVAILABLE_HEROES=No Available Heroes
KICK_WINDOW_TITLE=Kick Player?
KICK_WINDOW_INFO=Choose a player to remove from the Heist
HEIST_YOU_WERE_KICKED=You were kicked from the Heist.
FOUND_HIDEOUT=You found the Hideout!
FOUND_HIDEOUT_TOOLTIP=Call for backup! \nThis battle will decide the outcome of the heist.
VICTORY_WHITE_CIRCLES=%1$d White Circles:
DIFFICULTY_TOKENS_PER_CIRCLE=%1$d Heist Tokens per Case Crack
SURRENDER_BUTTON=Surrender
SURRENDER_CONFIRM_TITLE=Surrender?
SURRENDER_CONFIRM_INFO=Surrendering will result in Defeat and will KO this team of Heroes. (Note combat is NOT currently paused.)
CONFIRM_START_TITLE=Begin Heist?
CONFIRM_START_INFO=Are you sure you want to start the Heist Session?
ACCOMPLICE_TOOLTIP_TITLE=Accomplice Found
ACCOMPLICE_TOOLTIP_INFO=Send a hero to apprehend:
BODYGUARD_TOOLTIP_TITLE=Bodyguard
BODYGUARD_TOOLTIP_INFO=Send a hero to eliminate:
ACCOMPLICE=Accomplice
ACTIVE_BODYGUARD_TOOLTIP=Active Bodyguard Wards
NO_ACTIVE_WARDS=There are currently no active bodyguard wards.
ACCOMPLICE_SPAWN=Accomplices spawn
BODYGUARD_SPAWN=Bodyguards spawn
ACCOMPLICE_DEFEATED=Accomplice defeated! Bonus clues found!
BODYGUARD_DEFEATED=Bodyguard defeated! Ward removed! Bonus clues found!
NEW_BODYGUARD_SPAWNED=New Bodyguard has appeared!
WARD_INCREASE_HP_DESC=The Thief's team has increased Max HP.
WARD_INCREASE_SP_DESC=The Thief's team has increased Skill Power
WARD_INCREASE_DAMAGE_DESC=The Thief's team has increased Basic Damage.
WARD_INCREASE_ARMOR_DESC=The Thief's team has increased Armor, making them take less damage from normal attacks.
WARD_INCREASE_REALITY_DESC=The Thief's team has increased Reality, making them take less damage from fantastic attacks.
WARD_DECREASE_ATTACK_SPEED_DESC=The players' team has reduced Attack Speed.
WARD_DECREASE_SP_DESC=The players' team has reduced Skill Power.
WARD_DECREASE_HEALING_DESC=Reduces how much the players' heroes heal from all sources.
WARD_TANKS_EXTRA_DAMAGE_DESC=The players' Tank heroes take extra damage.
WARD_DPS_LESS_DAMAGE_DESC=The players' Damage heroes take extra damage.
WARD_SUPPORT_LESS_ENERGY_DESC=The players' Support and Control heroes gain less energy.
WARD_IMMUNE_TO_DISABLES_DESC=The Thief's team is immune to disabling skills.
WARD_SHIELDED_DESC=The Thief's team gets a shield at the start of combat that lasts for a short duration.
FIND_HIDEOUT=Find the Hideout!
