
PRE_RELEASE_TITLE=New Heroes\nComing Soon
PRE_RELEASE_SUBTEXT_PLURAL=%1$s new Heroes are coming soon.\nSee if you can guess who they are!
PRE_RELEASE_SUBTEXT_SINGULAR=A new Hero is coming soon.\nSee if you can guess who they are!
POST_RELEASE_TITLE=New Heroes\nJoin the Battle
POST_RELEASE_BUTTON=Patch Notes
