
GEAR_HEADING=Badges
SUMMARY_HEADING=Summary
SKILLS_HEADING=Skills
FRIENDS_HEADING=Friends
STATS_HEADING=Stats
PROMOTE_BUTTON=Promote
HERO_ALREADY_MAX_RARITY=Hero already at max rank (for now)!
UNIT_LOAD_ISSUE_TITLE_DEV=Unit Load Issue
UNIT_LOAD_ISSUE_INFO_DEV=There was an issue loading the hero.\nTap for more info.
UNIT_LOAD_ISSUE_INFO=There was an issue loading the hero.
UNIT_LOAD_NEEDS_DOWNLOAD=Tap to download hero art.
ADD_XP_TOOLTIP=Tap and hold to add XP:
CONFIRM_PROMOTE_TITLE=Promote?
CONFIRM_PROMOTE_INFO=Are you ready to promote %1$s?
YES=Yes
CANCEL=Cancel
UNLOCKED_AT_RARITY=Unlocked at %1$s
UNLOCKABLE_AT_RARITY=Unlockable at %1$s
DETAILED_STATS_BUTTON=Detailed Stats
DETAILED_STATS_WINDOW_TITLE=Detailed Stats
UNLOCK_HEADING=Unlock
LEVEL_HEADING=Level
STARS_HEADING=Stars
POWER_FORMAT=Power {#3ec07b}%1$s{}
POWER_PREFIX=Power:
LEVEL_FORMAT=Level {#fe8e1d}%1$s{}
LOCKED_HEADING=Locked
FRACTION_FORMAT=%1$s / %2$s
NOT_UNLOCKED_HEADING=Not Unlocked Yet
NEW_HEROES_NOT_UNLOCKED_HEADING=New Heroes to Unlock!
ALL_HEROES_HEADING=All Heroes
SORT_DROPDOWN=Sort:
SORT_POWER=Power
SORT_LEVEL=Level
SORT_RARITY=Rank
SORT_STARS=Stars
SORT_ROLE=Role
SORT_NAME=Name
GEAR_ICON_GET=Get
GEAR_ICON_EQUIP=Equip
GEAR_ICON_CRAFT=Craft
GEAR_ICON_TOO_LOW_LEVEL=New
SKILL_POINTS_COUNTDOWN_FULL=Points Full!
SKILL_POINTS_COUNTDOWN_PREFIX=More In:
SKILL_POINTS_COUNTDOWN_FULL_PREFIX=Full In:
MORE_TOMORROW=More Tomorrow
USE=Use
RESOURCE_USES_LEFT_PREFIX=Uses Left:
RESOURCE_ITEMS_LEFT_PREFIX=Owned:
RESOURCE_BUYS_LEFT_PREFIX=Buys Left:
OK=Ok
FULL=Full
BUY_BUTTON_FORMAT=Buy %1$d
BUY_MAX_BUTTON_FORMAT=Buy Max %1$d
PURCHASE_HISTORY_HEADING=Purchase History
BUY_GOLD_WINDOW_TITLE=Buy Gold
DAILY_FRIEND_STAMINA_CHANCES_EXHAUSTED=You have used up your available buys for the day. You can buy more tomorrow!
DAILY_VIDEOS_EXHAUSTED=Come back tomorrow to watch more videos.
DAILY_CHANCES_EXHAUSTED=You've used all your chances for today.\nCome back tomorrow for more chances!
TEAM_LEVEL_LOCKED=%1$s unlocks at Team Level %2$d.
MORE_BUY_GOLD_USES=More "Get Gold" Uses
RESOURCE_CONVERSION_LUCKY=Lucky x%1$s!
RESOURCE_EVENT_COUNTDOWN=Stock up and save! Event ends in: %1$s.
RESOURCE_BONUS_EVENT_COUNTDOWN=Get more %1$s with each buy! Event ends in: %2$s.
BUY_SKILL_POINTS_WINDOW_TITLE=Get More Skill Points
BUY_BUTTON=Buy
USED_SKILL_POINT_CHANCES=You've used all your skill point instant refill chances for today.\nCome back tomorrow for more chances!
SPEND_MORE_SKILL_POINTS_FIRST=Spend some more points before purchasing!
NEED_MORE_DIAMONDS_FOR_SKILL_POINTS=You need more diamonds before you can convert them to skill points!
WATCH_VIDEO=Watch Video
BUY_FRIEND_STAMINA_WINDOW_TITLE=Get More Friend Stamina
BUY_STAMINA_WINDOW_TITLE=Get More Stamina
BUY_STAMINA_WINDOW_TITLE_RAID=Raid?
BUY_STAMINA_WINDOW_TITLE_FIGHT=Fight?
USED_STAMINA_BOOST_CHANCES=You've used all your stamina boost chances for today.\nCome back tomorrow for more chances!
BUY_FRIEND_STAMINA_IS_FULL=Your Friend Stamina is currently full.\nSpend some in a friend campaign!
BUY_STAMINA_IS_FULL=Your stamina is full.\nSpend some before you buy again!
NEED_MORE_DIAMONDS_FOR_STAMINA=You need more diamonds before you can convert them to stamina!
AUTOMATIC_PROMOTE_HERO_PROMPT=Would you like to automatically promote your hero to %1$s?
ITEMS_USED_HEADING=Items Used
RESOURCES_USED_HEADING=Resources Used
COLLECT_SOULSTONES_HERE_HEADING=Collect Here:
EVOLVE_CONFIRM_TITLE=Evolve?
EVOLVE_INFO=It's time to add a new star to %1$s!
EVOLVE_OUTCOME_TITLE=Awesome
EVOLVE_OUTCOME_INFO=Your hero has evolved!
NEW_BASE_STATS_HEADING=New Core Stats
EVOLVE_DELTA=(%1$s)
GET_MORE_DIAMONDS_TITLE=Get More Diamonds!
GET_MORE_DIAMONDS_DESC=Would you like to explore diamond deals now?
SHOP_DIAMONDS=Shop Diamonds
NOT_ENOUGH_DIAMONDS=Not enough diamonds!
PROMOTE_HELP_WINDOW_TITLE=Promoting Heroes
PROMOTE_HELP_WINDOW_INFO=Equip badges in all six slots to promote a hero!
PROMOTE_OUTCOME_TITLE=Awesome
STAT_MAX_HEALTH_PREFIX=Max HP:
NEW_SKILL_HEADING=New Skill Unlocked!
NEW_SKILL_UNLOCKABLE_HEADING=New Skill Unlockable!
HERO_PROMOTED_INFO=Your hero has been promoted!
LEVEL_UP=Level Up!
NEED_GOLD_TOO_LOW_LEVEL=Looks like you need gold, but "Get More Gold" unlocks at Team Level %1$d. Get some from the campaign!
VIP_MESSAGE_SKILL_POINT=Hero Skill Point Recharge
MORE_STAMINA_REFILLS=Additional Stamina Buys
REACH_VIP_TO_UNLOCK=Reach {#ffe00f}VIP Level %1$d{} to unlock:
SEE_VIP_BENEFITS=See All VIP Benefits!
INCREASE_VIP_TO_UNLOCK=Increase your {#ffe00f}VIP Level{} to unlock:
GEAR_WINDOW_TITLE=%1$s Badges
GEAR_WINDOW_HERO_AT_MAX_RARITY=This hero is at max rank. \nCheck back later after a new badge set is released!
LEVEL_FORMAT_WHITE=Level %1$s!
YOU_GOT_NEW_HERO=You got a new hero!
GENERIC_HERO_PICKER_MIN_LEVEL_ERROR=%1$s needs to be level %2$d or higher to be picked.
HERO_SORT=Sort
PICKER_SORT_LEVEL=Level
PICKER_SORT_POWER=Power
PICKER_SORT_RARITY=Rank
PICKER_SORT_ROLE=Role
PICKER_SORT_STARS=Stars
PICKER_SORT_EXPIRATION=Expiration
PICKER_SORT_PATCH_LEVEL=Patch
PICKER_EMPTY=There are no heroes which match the criteria.
NO_SKILLS_AVAILABLE=No skills available.
FRIEND_HERO_MUST_BE_USED=This hero must be used in this fight.
ROLE_TANK=Tank
ROLE_CONTROL=Control
ROLE_DAMAGE=Damage
ROLE_SUPPORT=Support
POWER_FORMAT_COLON=Power: %1$s
ROLE_FORMAT=Role: %1$s
NEED_LVL_FORMAT=Need Lvl %1$d
CANT_HIRE_ABOVE_TEAM_LVL=You cannot hire heroes above your team level.
HIRE_MERCENARY=Hire Mercenary
HIRE_HERO=Hire Hero
NOT_ENOUGH_GOLD=Not enough gold!
HIRED_BY=Hired By:
MODE=Mode:
TIME=Time:
HERO_ALREADY_HIRED=This hero has already been hired.
CHOOSE_HEROES_TITLE=Choose Your Heroes!
SKILL_MAXED=Skill Maxed!
HERO_TO_STONE_CONVERSION_FORMAT=%1$s is already on your team. We'll give you %2$d Hero Chips instead!
FAKE_STAT_ROLE=Role
FAKE_STAT_POSITION=Position
FAKE_STAT_TEAM=Trial Team:
STAT_CAPPED=(max: %1$s)
POSITION_FRONT=Front
POSITION_CENTRAL=Mid
POSITION_BACK=Back
TEAM_RED=Red
TEAM_BLUE=Blue
TEAM_YELLOW=Yellow
UNLOCK_COLON=Unlock:
SKILL_POWER_PREFIX=Skill Power:
BASIC_DAMAGE_PREFIX=Basic Damage:
BADGE_LIST=Badge List
INFO=Info
FRIENDS_SELECT_HERO=Level up and promote your heroes to unlock a friendship!
PICKER_EMPTY_SORT=There are no heroes available for hire.
MAXED=Maxed
VIEW=View:
MAX_CHIP_FORMAT=Max (+%1$d)
UNIT_ANIM_VICTORY=Victory
UNIT_ANIM_ATTACK=Attack
UNIT_ANIM_HIT=Hit
FORCE_TOUCH_LEARN_TITLE=3D Touch
FORCE_TOUCH_LEARN_INFO=Want to learn other ways to use 3D Touch in Disney Heroes?
DAMAGE_TYPE_FORMAT=%1$s Damage
FILTER=Filter
ALL=All
AVAILABLE=Available
HIRABLE=Hirable
SORT_TEAM=Team
SAVED_LINEUPS_TITLE=Saved Lineups
POWER_TWO_LINES=Power:\n%1$s
SELECT_BUTTON=Select
ADD_NEW_LINEUP_BUTTON=Add New Lineup
LINEUPS=Lineups
NO_SAVED_LINEUPS_INFO=You don't currently have any saved lineups.
MAX_SAVED_LINEUPS_INFO=You already have %1$d saved lineups. You can edit an existing lineup instead.
SAVE_LINEUP_CONFIRM_TITLE=Save Lineup?
SAVE_LINEUP_CONFIRM_INFO=You have made changes to this lineup.
DONT_SAVE_BUTTON=Don't Save
SAVE_BUTTON=Save
SET_YOUR_LINEUP_TITLE=Set Your Lineup
RARITY_CURRENT=(Current)
PLUS_FORMAT=+%1$d
TAP_TO_ADD_LEVELS=Or Tap to Add Levels:
NOT_ENOUGH_HERO_XP=You don't have enough Hero XP!
ADDITIONAL_STAT_BOOSTS=Additional Stat Boosts:
RED_SKILL_COMING_SOON=Red Skill Coming Soon!
RED_SKILL_UNLOCKED=Red Skill Unlocked!
SLIDE_TO_ADD_LEVELS=Slide to Add Levels:
CONFIRM_LEVELS=Max Hero XP Level
CONFIRM_LEVELS_INFO=This will level your hero either up to your current Team Level or up to the highest level possible using the XP items below. Are you sure you'd like to continue?
MAX_SKILLS=+MAX
MAX_SKILLS_TITLE=Max Hero Skills
MAX_SKILLS_INFO=These skills will be upgraded using the items below. Would you like to continue?
MAX_SKILLS_COST=Cost:
FAVORITE_STAGE_INFO=This heart helps you remember the last stage you went to for this badge.
PRIME_BADGE=Battle \nBadge
SKILL_TAGS=Skill \nTags
CHARGED_BATTLE=Is Charged in battle when:
WHEN_CHARGED=When Charged:
PRIME_BADGE_NO_NEWLINE=Battle Badge
BATTLE_BADGE_RARITY_LOCKED=Promote to {#fef850}Yellow{} to unlock the Battle Badge
BATTLE_BADGE_SEMICOLON=Battle Badge:
BATTLE_BADGE_LEVEL=Your Battle Badge has been upgraded!
PATCH_TALENTS=Patch Talents
REAL_GEAR=Real Gear
SOURCES=Sources
NEW_BUFF_STATS=New Buff Stats
POWER_PROMOTE=Power Promote
POWER_PROMOTE_ALL_BADGES=All Badges
POWER_PROMOTE_LOADING=Please wait while we complete the promotion of %1$s!\nPlease do not close the game while this is happening.
POWER_PROMOTE_RESULTS=Power Promote Results
POWER_PROMOTION=Power Promote
YOU_SPEND=You Spend:
POWER_PROMOTING_TITLE=Power Promoting!
POWER_PROMOTE_CONFIRMATION=Are you sure you want to promote {#ffe00f}%1$s{} from {%4$s}%2$s{} to {%5$s}%3$s{}?\nThe items below will be consumed.
POWER_PROMOTE_QUESTION=Power Promote?
POWER_PROMOTE_NUMBER_RARITIES=%1$+d Rank
PLURAL_POWER_PROMOTE_NUMBER_RARITIES=%1$+d Ranks
YOU_WILL_SPEND=You will spend:
POWER_PROMOTE_NOT_ENOUGH_RESOURCE=You will need additional %1$s equal to:
CRAFT_ALL=Craft All
CRAFT_ALL_QUESTION=Craft All?
MAX_SKILLS_ADD_RED=Add Red Skill Cost?
MAX_SKILLS_ADD_RED_INFO=Would you like to have your Red Skill added to your Max Hero Skills costs?  If you choose "No", you can still add it from the Settings menu at a later time.
MASS_LEVEL_UP_SELECT=Mass Level Up
MASS_LEVEL_UP_LABEL=Level Up Heroes to
MASS_LEVEL_UP_CONFIRM=Mass Level Up
MASS_LEVEL_UP_CONFIRM_INFO=This will level up your heroes to the chosen level %d using the XP items below. Are you sure you want to continue?
MASS_LEVEL_UP_ENOUGH_XP=You don't have enough xp drinks.
MAX_UPGRADE_REAL_GEAR=Max Selected Disk
SELECT_HERO_FILTER=Hero Filters
FILTERS_SELECTED=Filters Selected
HEROES_IN_FILTER=Heroes in Filter
UNLOCKED_COLON=Unlocked:
LOCKED_COLON=Locked:
GENERAL=General
NEGATIVE_EFFECTS=- Effects
POSITIVE_EFFECTS=+ EFFECTS
NEGATIVE_STATS=- Stats
POSITIVE_STATS=+ Stats
FRANCHISES=Franchises
NEGATIVE_EFFECTS_DESC=Heroes in these filters generally apply these negative status effects to enemies.
POSITIVE_EFFECTS_DESC=Heroes in these filters generally apply these positive status effects to themselves and/or allies.
NEGATIVE_STATS_DESC=Heroes in these filters generally apply these stat decreases to enemies.
POSITIVE_STATS_DESC=Heroes in these filters generally apply these stat increases to themselves and/or allies.
FRANCHISES_DESC=Heroes in these filters belong to a particular Franchise.
PATCH_TALENTS_DESC=Heroes in these filters have the selected patch talents.
CLEAR_ALL=Clear All:
TOTAL_SKILL_CHIPS_REWARD=Total Skill Chips: [#ffe00f]%1$s[]
PARENTHESIS_FORMAT=(%1$s)
POWER_PROMOTE_NO_LOOT=No Extra Loot
LINEUP_FORMAT=Lineup: %1$s/%2$s
CHOOSE_FROM_LIST=Choose some heroes from the list below!
GENERIC_RED_SKILL_DELTA=+<lvl> Level
DAMAGE_TYPE=Damage Type
CURRENT_FILTER=Current Filter:
NEG_EFFECT_HEADING=These status effects correspond to the - Effects Filters.
POS_EFFECT_HEADING=These status effects correspond to the + Effects Filters.
NEG_STAT_HEADING=These status effects correspond to the - Stat Filters.
POS_STAT_HEADING=These status effects correspond to the + Stat Filters.
PATCH_TALENTS_HEADING=These status effects correspond to the Patch Talents Filters.
CLEAR_ALL_NO_COLON=Clear All
TAP_ON_HERO=Tap on a Hero for details!
VIEW_CRATE=View Crate
WHITE_SKILL=White Skill
GREEN_SKILL=Green Skill
BLUE_SKILL=Blue Skill
PURPLE_SKILL=Purple Skill
RED_SKILL=Red Skill
NOT_PATCHABLE=Not Patchable
SAVED_LINEUP_DEFAULT_FORMAT=Team %1$s
SAVED_LINEUP_REAL_GEAR_CHANGED=Memory Disk has been changed for: %1$s
SAVED_LINEUP_STAT_SLOTS_CHANGED=Stat Slots have been changed for: %1$s
TRAITS=Traits
TRAITS_DESC=traits is a category like Cats, Dragons, etc
POSITION=Position
FULL_DAMAGE_TYPE=Full Damage Type
RELEASE_DATE=Release Date
SKILL_POWER=Skill Power
BASIC_DAMAGE=Basic Damage
MAX_HP=Max Hp
ARMOR=Armor
REALITY=Reality
PICKER_MOD_SORT_LEVEL=Level
PICKER_MOD_SORT_TIER=Tier
PICKER_MOD_SORT_ATTUNMENT=Attunment
PICKER_MOD_SORT_NEWEST=Newest
