
HERO_FILTERS_CARD_COUNT=7
HERO_FILTERS_CARD_1_BULLET_ORDER=A,A1,B,B1,B2,B3,B4,C,C1,D,D1,D2,E,E1,E2,F,F1
HERO_FILTERS_CARD_2_TYPE=GENERAL_FILTERS
HERO_FILTERS_CARD_3_TYPE=NEG_EFFECT_FILTERS
HERO_FILTERS_CARD_4_TYPE=POS_EFFECT_FILTERS
HERO_FILTERS_CARD_5_TYPE=NEG_STAT_FILTERS
HERO_FILTERS_CARD_6_TYPE=POS_STAT_FILTERS
HERO_FILTERS_CARD_7_TYPE=PATCH_TALENTS_FILTERS
HERO_FILTERS_TUTORIALS=HERO_FILTERS
HEIST_CARD_COUNT=13
HEIST_CARD_1_BULLET_ORDER=1,1B,2,2B,2C
HEIST_CARD_2_BULLET_ORDER=1,1B,1C,2,2B,2C,3,3B,4,4B,4C,5,5B
HEIST_CARD_3_BULLET_ORDER=1,1B,2,2B,3,3B,4,4B,4C
HEIST_CARD_4_BULLET_ORDER=1,1B,1C,2,2B,3,3B,3C,4,4B,4C,4D,4E,5,5B,5C,5D
HEIST_CARD_5_BULLET_ORDER=1,1B,1C,1D,1E,2,2B,2C,3,3B,3C,3D,4,4B,4C,4D
HEIST_CARD_6_BULLET_ORDER=1,1B,2,2B,2C,2D,2E,2F,3,3B,3C,3D
HEIST_CARD_7_BULLET_ORDER=1,1B,2,2B,2C,2D,2E,3,3B,3C,3D,3E,3F,4,4B
HEIST_CARD_8_BULLET_ORDER=1,1B,1C,1D,2,2B,2C,2D,2E,2F,2G,3,3B,3C,3D
HEIST_CARD_9_BULLET_ORDER=1,1B,1C,2,2B
HEIST_CARD_10_BULLET_ORDER=1,2,3,3B,3C,3D
HEIST_CARD_11_BULLET_ORDER=1,2,3
HEIST_CARD_12_TYPE=HEIST_BODYGUARD_LIST
HEIST_CARD_13_BULLET_ORDER=1,1B,2,2B,3,3B,3C,4
HEIST_TUTORIALS=HEIST, HEIST_NARRATION, HEIST_TICKET, HEIST_INVITE, HEIST_END_TIPS
GUILD_CARD_COUNT=5
GUILD_CARD_1_BULLET_ORDER=1,2,3,4,5,6
GUILD_CARD_1_ICON=GUILD_BENEFITS
GUILD_CARD_2_BULLET_ORDER=1
GUILD_CARD_2_ICON=GUILD_TOKENS
GUILD_CARD_3_BULLET_ORDER=1,2,3,4
GUILD_CARD_3_ICON=RANK_CROWN
GUILD_CARD_4_BULLET_ORDER=A1,M1,V1,T1,T2,T3,O1,O2,O3,O4,O5,O6,O7,C1,C2,C3,C4,C5,C6,C7,C8,C9,C10,L1,L2,L3,C11
GUILD_CARD_4_ICON=NONE
GUILD_CARD_5_BULLET_ORDER=1,2,3,3B,3C,3D,3E
GUILD_CARD_5_ICON=NONE
GUILD_TUTORIALS=GUILDS, GUILD_CHECKIN, GUILD_MERCENARY
WAR_CARD_COUNT=9
WAR_CARD_1_BULLET_ORDER=A,B,B1,C
WAR_CARD_2_BULLET_ORDER=A,B,C,D
WAR_CARD_3_BULLET_ORDER=A,A1,B,B1,C
WAR_CARD_4_BULLET_ORDER=A,A1,B,B1,C,C1,C2,C3
WAR_CARD_5_BULLET_ORDER=A,B,B1,C,C1,D,E,E1
WAR_CARD_6_BULLET_ORDER=A,A1,A2,A3,B,B1,B2,B3,B4,B5,C,D,D1,D2,D3
WAR_CARD_7_BULLET_ORDER=A,B,C,D
WAR_CARD_8_TYPE=WAR_SABOTAGE
WAR_CARD_9_TYPE=WAR_CAR_BONUSES
WAR_TUTORIALS=WAR_INTRO, WAR_PREPARE, WAR_START, WAR_SABOTAGE, WAR_ACTIVE, WAR_BOXES
WAR_BP_CARD_COUNT=3
WAR_BP_CARD_1_BULLET_ORDER=A,B,B1,B2,C,D,D1,D2
WAR_BP_CARD_2_BULLET_ORDER=A,A1,A2,A3,A4,A5,A6,A7,B
WAR_BP_CARD_3_BULLET_ORDER=A,B,B1,B2
CHALLENGES_CARD_COUNT=6
CHALLENGES_CARD_1_BULLET_ORDER=1,1B,2,2B,2C,3,3B
CHALLENGES_CARD_2_BULLET_ORDER=1,1B,2,2B,2C
CHALLENGES_CARD_3_BULLET_ORDER=1,2,2B,3,3B
CHALLENGES_CARD_4_BULLET_ORDER=1,1B,2,2B
CHALLENGES_CARD_5_BULLET_ORDER=1,1B,2,2B,2C
CHALLENGES_CARD_6_BULLET_ORDER=1,1B,1C,2,2B,2C
CHALLENGES_TUTORIALS=CHALLENGES_INTRO, CHALLENGES_OTHER, CHALLENGES_PICK_EM, CHALLENGES_BUY_SLOT, CLAIM_CHALLENGES
FORCE_TOUCH_CARD_COUNT=1
FORCE_TOUCH_CARD_1_BULLET_ORDER=A,B,C,D,E
JOB_BOARD_CARD_COUNT=1
JOB_BOARD_CARD_1_BULLET_ORDER=A,B,C,D
GUILD_PERKS_CARD_COUNT=1
GUILD_PERKS_CARD_1_ICON=GUILD_BENEFITS
GUILD_PERKS_CARD_1_BULLET_ORDER=1,2,3,4
CHAT_RULES_CARD_COUNT=1
CHAT_RULES_CARD_1_BULLET_ORDER=1,2,3,4,5,6,7,8,9,10,11,12
CHAT_RULES_CARD_1_ICON=NONE
CHAT_RULES_TUTORIALS=CHAT_TRANSLATE
HERO_STATS_CARD_COUNT=4
HERO_STATS_CARD_1_BULLET_ORDER=1,2,3
HERO_STATS_CARD_1_ICON=NONE
HERO_STATS_CARD_2_BULLET_ORDER=1,2,3,4
HERO_STATS_CARD_2_ICON=NONE
HERO_STATS_CARD_3_BULLET_ORDER=1,2,3,4,5,6,7,8,8A,12,9,10,11,13,14,15,16,17
HERO_STATS_CARD_3_ICON=NONE
HERO_STATS_CARD_4_BULLET_ORDER=1,2,3,4
HERO_STATS_CARD_4_ICON=NONE
ENCHANTING_CARD_COUNT=4
ENCHANTING_CARD_1_BULLET_ORDER=1,2,3
ENCHANTING_CARD_1_ICON=ENCHANTING
ENCHANTING_CARD_2_BULLET_ORDER=1,2
ENCHANTING_CARD_2_ICON=ENCHANTING
ENCHANTING_CARD_3_BULLET_ORDER=2,3
ENCHANTING_CARD_3_ICON=ENCHANTING
ENCHANTING_CARD_4_BULLET_ORDER=1,2
ENCHANTING_CARD_4_ICON=ENCHANTING
ENCHANTING_TUTORIALS=ENCHANTING, AUTO_ENHANCE_SETTINGS
IAP_PURCHASING_CARD_COUNT=4
IAP_PURCHASING_CARD_1_BULLET_ORDER=1,2,3,4
IAP_PURCHASING_CARD_1_ICON=PURCHASING_ICON
IAP_PURCHASING_CARD_2_BULLET_ORDER=1,2,2A
IAP_PURCHASING_CARD_2_ICON=PURCHASING_ICON
IAP_PURCHASING_CARD_3_BULLET_ORDER=1,2,2A,2B
IAP_PURCHASING_CARD_3_ICON=VIP_ABOUT
IAP_PURCHASING_CARD_4_BULLET_ORDER=1,2,3
IAP_PURCHASING_CARD_4_ICON=MONTHLY_DEAL_CALENDAR
SILVER_CHEST_CARD_COUNT=1
SILVER_CHEST_CARD_1_BULLET_ORDER=1,1A,1B,1C,2,2A
SILVER_CHEST_CARD_1_ICON=CHEST_SILVER_ICON
GOLD_CHEST_CARD_COUNT=1
GOLD_CHEST_CARD_1_BULLET_ORDER=1,1A,1B,1C,1D,2,2A
GOLD_CHEST_CARD_1_ICON=CHEST_GOLD_ICON
SOCIAL_CHEST_CARD_COUNT=1
SOCIAL_CHEST_CARD_1_BULLET_ORDER=3,3A,1,1A,1B,1C,2,2A,2B,2C
SOCIAL_CHEST_CARD_1_ICON=NONE
SOUL_CHEST_CARD_COUNT=1
SOUL_CHEST_CARD_1_BULLET_ORDER=1,1A,1B,2,2A,2B
SOUL_CHEST_CARD_1_ICON=CHEST_SOUL_ICON
CRYPT_CARD_COUNT=4
CRYPT_CARD_1_BULLET_ORDER=1,2,3,4
CRYPT_CARD_1_ICON=CRYPT_ABOUT
CRYPT_CARD_2_BULLET_ORDER=1,2,3,4
CRYPT_CARD_2_ICON=CRYPT_HEROES
CRYPT_CARD_3_BULLET_ORDER=1,1A,2,2A,3,4
CRYPT_CARD_3_ICON=CRYPT_THREE_SKULLS
CRYPT_CARD_4_BULLET_ORDER=1,2,3,4
CRYPT_CARD_4_ICON=CRYPT_STRATEGY
EXPEDITION_CARD_COUNT=6
EXPEDITION_CARD_1_BULLET_ORDER=1,2,3
EXPEDITION_CARD_1_ICON=EXPEDITION_ABOUT
EXPEDITION_CARD_2_BULLET_ORDER=1,2,3
EXPEDITION_CARD_2_ICON=EXPEDITION_HARD_MODE
EXPEDITION_CARD_3_BULLET_ORDER=1,2,3
EXPEDITION_CARD_3_ICON=EXPEDITION_HARD_MODE
EXPEDITION_CARD_4_BULLET_ORDER=1,2,2B,3,4
EXPEDITION_CARD_4_ICON=EXPEDITION_HARD_MODE
EXPEDITION_CARD_5_TYPE=INVASION_BREAKER_LIST
EXPEDITION_CARD_6_BULLET_ORDER=1,2,3,4,4B
EXPEDITION_CARD_6_ICON=EXPEDITION_HARD_MODE
EXPEDITION_TUTORIALS=CITY_WATCH, CITY_WATCH_RESET
FIGHT_PIT_CARD_COUNT=2
FIGHT_PIT_CARD_1_TYPE=ARENA_LEAGUES
FIGHT_PIT_CARD_1_ICON=NONE
FIGHT_PIT_CARD_2_ICON=CONTEST_RANK
FIGHT_PIT_CARD_2_BULLET_ORDER=1,2,3,4,5
FIGHT_PIT_TUTORIALS=FIGHT_PIT, ARENA_DEFENSE
CAMPAIGN_CARD_COUNT=3
CAMPAIGN_CARD_1_BULLET_ORDER=1,2,2A,2B,2C
CAMPAIGN_CARD_1_ICON=NONE
CAMPAIGN_CARD_2_BULLET_ORDER=1,1A,2
CAMPAIGN_CARD_2_ICON=NONE
CAMPAIGN_CARD_3_BULLET_ORDER=1,2,2A,3
CAMPAIGN_CARD_3_ICON=NONE
CAMPAIGN_TUTORIALS=ELITE_CAMPAIGN
VIP_CARD_COUNT=3
VIP_CARD_1_BULLET_ORDER=A,B,C,D
VIP_CARD_1_ICON=VIP_ABOUT
VIP_CARD_2_BULLET_ORDER=A,B,C,D
VIP_CARD_2_ICON=VIP_HOW_TO_GET
VIP_CARD_3_BULLET_ORDER=1,2,3,4,5,6,8,9,10,43,44,45,11,12,13,14,15,17,18,19,20,21,22,24,26,27,28,29,30,42,31,32,34,35,37,38,40,41,42,46,47,48,49,50,51
VIP_CARD_3_ICON=NONE
FRIENDS_CARD_COUNT=4
FRIENDS_CARD_1_BULLET_ORDER=1,1A,1B,1C,2,2A
FRIENDS_CARD_2_BULLET_ORDER=1,1A,1B,2,2A,2B,3,3A,4,4A,5,5A,5B
FRIENDS_CARD_3_BULLET_ORDER=1,1A,2,2A,2B,3,3A,3B,3C,4,4A,4B,4C,5,5A
FRIENDS_CARD_4_BULLET_ORDER=1,1A,1B,2,2A,2B,3,3A,3B,3C,4,4A,4B,4C,4D
FRIENDS_TUTORIALS=NEW_FRIENDSHIP
COLISEUM_CARD_COUNT=2
COLISEUM_CARD_1_TYPE=ARENA_LEAGUES
COLISEUM_CARD_1_ICON=NONE
COLISEUM_CARD_2_ICON=CONTEST_RANK
COLISEUM_CARD_2_BULLET_ORDER=1,2,3,4
COLISEUM_TUTORIALS=COLISEUM
CONTESTS_CARD_COUNT=4
CONTESTS_CARD_1_BULLET_ORDER=1,2
CONTESTS_CARD_1_ICON=CONTEST_ICON
CONTESTS_CARD_2_BULLET_ORDER=1,2
CONTESTS_CARD_2_ICON=CONTEST_CURRENCY
CONTESTS_CARD_3_BULLET_ORDER=1,2
CONTESTS_CARD_3_ICON=CONTEST_PROGRESS
CONTESTS_CARD_4_BULLET_ORDER=1,2
CONTESTS_CARD_4_ICON=CONTEST_RANK
CONTESTS_TUTORIALS=SERVER_CONTEST
FRIEND_STAMINA_CARD_COUNT=1
FRIEND_STAMINA_CARD_1_BULLET_ORDER=1,2,3,4
FRIEND_STAMINA_CARD_1_ICON=NONE
AIR_DROP_CARD_COUNT=1
AIR_DROP_CARD_1_BULLET_ORDER=1,1B,2,3,4
AIR_DROP_CARD_1_ICON=NONE
DIAMOND_CRATE_UPGRADES_CARD_COUNT=1
DIAMOND_CRATE_UPGRADES_CARD_1_BULLET_ORDER=1,2,2B,3,4
DIAMOND_CRATE_UPGRADES_CARD_1_ICON=CHEST_GOLD_ICON
VIDEOS_CARD_COUNT=1
VIDEOS_CARD_1_BULLET_ORDER=1,1B,3,3B,4
VIDEOS_CARD_1_ICON=NONE
MODS_CARD_COUNT=2
MODS_CARD_1_BULLET_ORDER=A,B
MODS_CARD_1_ICON=NONE
MODS_CARD_2_BULLET_ORDER=A,C,C1,D,D1,E,E1,F,F1,F2
MODS_CARD_2_ICON=NONE
MODS_TUTORIALS=MOD_EQUIP, MOD_LEVEL, MOD_ADVANCEMENT, MOD_DISASSEMBLY, MOD_CHOOSE_UPGRADE, MOD_IMPROVE_UPGRADE, RECOMMENDED_MODS
MODS_UPDATE_1_CARD_COUNT=2
MODS_UPDATE_1_CARD_1_BULLET_ORDER=A,B,B1,C
MODS_UPDATE_1_CARD_1_ICON=NONE
MODS_UPDATE_1_CARD_2_BULLET_ORDER=A,C,C1,D,D1,D2,E,E1,F,F1,F2
MODS_UPDATE_1_CARD_2_ICON=NONE
MODS_UPDATE_1_TUTORIALS=MOD_EQUIP, MOD_LEVEL, MOD_ADVANCEMENT, MOD_DISASSEMBLY, MOD_CHOOSE_UPGRADE, MOD_IMPROVE_UPGRADE, RECOMMENDED_MODS
MODS_UPDATE_2_CARD_COUNT=5
MODS_UPDATE_2_CARD_1_BULLET_ORDER=A,B,B1,C
MODS_UPDATE_2_CARD_1_ICON=NONE
MODS_UPDATE_2_CARD_2_BULLET_ORDER=A,C,C1,D,D1,D2,E,E1,F,F1,F2
MODS_UPDATE_2_CARD_2_ICON=NONE
MODS_UPDATE_2_CARD_3_BULLET_ORDER=A,B,C
MODS_UPDATE_2_CARD_3_ICON=NONE
MODS_UPDATE_2_CARD_4_BULLET_ORDER=A,B,B1,B2,C,C1
MODS_UPDATE_2_CARD_4_ICON=NONE
MODS_UPDATE_2_CARD_5_TYPE=MOD_UPGRADES_LIST
MODS_UPDATE_2_TUTORIALS=MOD_EQUIP, MOD_LEVEL, MOD_ADVANCEMENT, MOD_DISASSEMBLY, MOD_CHOOSE_UPGRADE, MOD_IMPROVE_UPGRADE, RECOMMENDED_MODS
MODS_UPDATE_3_CARD_COUNT=5
MODS_UPDATE_3_CARD_1_BULLET_ORDER=A,B,B1,C
MODS_UPDATE_3_CARD_1_ICON=NONE
MODS_UPDATE_3_CARD_2_BULLET_ORDER=A,B,C,C1,D,D1,D2,E,E1
MODS_UPDATE_3_CARD_2_ICON=NONE
MODS_UPDATE_3_CARD_3_BULLET_ORDER=A,B,C
MODS_UPDATE_3_CARD_3_ICON=NONE
MODS_UPDATE_3_CARD_4_BULLET_ORDER=A,B,B1,B2,C,C1
MODS_UPDATE_3_CARD_4_ICON=NONE
MODS_UPDATE_3_CARD_5_TYPE=MOD_UPGRADES_LIST
MODS_UPDATE_3_CARD_6_BULLET_ORDER=A,B,B1,C
MODS_UPDATE_3_CARD_6_ICON=NONE
MODS_UPDATE_3_TUTORIALS=MOD_EQUIP, MOD_LEVEL, MOD_ADVANCEMENT, MOD_DISASSEMBLY, MOD_CHOOSE_UPGRADE, MOD_IMPROVE_UPGRADE, RECOMMENDED_MODS
INVASION_CARD_COUNT=11
INVASION_CARD_1_TYPE=INVASION_INTRO
INVASION_CARD_2_TYPE=INVASION_FEATURED_CONTENT
INVASION_CARD_3_BULLET_ORDER=A,A2,A3,B,B1,C,C1,D,D1,D2
INVASION_CARD_3_ICON=NONE
INVASION_CARD_4_BULLET_ORDER=A,A2,A1,B,B1,B2,C,C1,C2,C3,C4,D,D1,D2
INVASION_CARD_4_ICON=NONE
INVASION_CARD_5_BULLET_ORDER=A,A1,B,B1,C
INVASION_CARD_5_ICON=NONE
INVASION_CARD_6_BULLET_ORDER=A,B,B1,C,C1,D,D1,D2,E
INVASION_CARD_6_ICON=NONE
INVASION_CARD_7_BULLET_ORDER=A,A1,B,B1,C,C1
INVASION_CARD_7_ICON=NONE
INVASION_CARD_8_BULLET_ORDER=A,A1,B,C,C1,D,D1,E,E1
INVASION_CARD_8_ICON=NONE
INVASION_CARD_9_BULLET_ORDER=A,A1,A2,B,C,C1,D,D1
INVASION_CARD_9_ICON=NONE
INVASION_CARD_10_TYPE=INVASION_BREAKER_LIST
INVASION_CARD_11_TYPE=INVASION_ITEMS_LIST
INVASION_TUTORIALS=INVASION_BOSS, INVASION_BREAKER, INVASION_SUPPLY,INVASION_REVIVE,INVASION_BREAKER_QUEST,INVASION_WARD,INVASION_BREAKER_GET_BOOSTS,INVASION_BREAKER_HAS_BOOSTS,INVASION_RANKINGS,INVASION_STAMINA,INVASION_AUTO_QUICK_FIGHT
COLLECTIONS_CARD_COUNT=5
COLLECTIONS_CARD_1_BULLET_ORDER=1,1A,1B,2,2A,2B,2C,3,3A,3B,3C,3D
COLLECTIONS_CARD_2_BULLET_ORDER=1,1A,1B,2,2A,2B,3,3A,3B,3C
COLLECTIONS_CARD_3_BULLET_ORDER=1,1A,1B,2,2A,2B,2C,3,3A,3B,3C,4,4A,4B,4C
COLLECTIONS_CARD_4_BULLET_ORDER=1,1A,1B,2,2A,2B,2C,2D,3,3A,3B,3C,3D
COLLECTIONS_CARD_5_TYPE=COLLECTIONS_BUFF_LIST
COLLECTIONS_TUTORIALS=COLLECTIONS_UNLOCK,COLLECTIONS_INTRO,COLLECTIONS_DETAIL,COLLECTIONS_TIER_DETAIL,COLLECTIONS_HERO_MASTERED,COLLECTIONS_LEVEL_COMPLETE,COLLECTIONS_PROGRESS
COSMETIC_COLLECTIONS_CARD_COUNT=1
COSMETIC_COLLECTIONS_CARD_1_BULLET_ORDER=1,1A,1B,2,2A,2B,2C,3,3A,3B,3C,3D
COSMETIC_COLLECTIONS_TUTORIALS=COSMETICS
HALL_OF_FAME_CARD_COUNT=1
HALL_OF_FAME_CARD_1_BULLET_ORDER=1,1A,1B,2,2A,2B,3,3A,3B,3C,4,4A,4B,4C,5,5A,5B
AUTO_ENHANCE_SETTINGS_CARD_COUNT=1
AUTO_ENHANCE_SETTINGS_CARD_1_BULLET_ORDER=1,1A,2,2A,2B,2C,3,3A,3B,3C,4,4A,4B,4C,4D
RED_SKILLS_CARD_COUNT=1
RED_SKILLS_CARD_1_BULLET_ORDER=1,2
RED_SKILLS_TUTORIALS=RED_SKILL
DONATIONS_CARD_COUNT=5
DONATIONS_CARD_1_BULLET_ORDER=1,1A,2,2A
DONATIONS_CARD_2_BULLET_ORDER=1,1A,2,2A,3,3A
DONATIONS_CARD_3_BULLET_ORDER=1,1A,1B,2,2A,3,3A
DONATIONS_CARD_4_BULLET_ORDER=1,1A,2,2A,3,3A
DONATIONS_CARD_5_BULLET_ORDER=1,1A,2,2A,3,3A
DONATIONS_TUTORIALS=DONATION
DAILY_HERO_CRATES_CARD_COUNT=1
DAILY_HERO_CRATES_CARD_1_BULLET_ORDER=1,1A,2,2A,2B,2C,2D,2E,3,3A
BATTLE_PASS_CARD_COUNT=3
BATTLE_PASS_CARD_1_BULLET_ORDER=1,1A,2,2A
BATTLE_PASS_CARD_2_BULLET_ORDER=1,1A,2,2A
BATTLE_PASS_CARD_3_BULLET_ORDER=1,1A,2,2A,3,3A,3B
BATTLE_PASS_TUTORIALS=BATTLE_PASS
CHALLENGER_SEASONS_CARD_COUNT=6
CHALLENGER_SEASONS_CARD_1_TYPE=ARENA_LEAGUES
CHALLENGER_SEASONS_CARD_2_BULLET_ORDER=1,1A,2,2A,3,3A,4,4A
CHALLENGER_SEASONS_CARD_3_BULLET_ORDER=1,1A,2,2A,2B,3,3A,4,4A
CHALLENGER_SEASONS_CARD_4_BULLET_ORDER=1,1A,2,2A,3,3A,4,4A,5,5A
CHALLENGER_SEASONS_CARD_5_BULLET_ORDER=1,1A,1B,2,2A,2B,3,3A
CHALLENGER_SEASONS_CARD_6_BULLET_ORDER=1,1A,1B,2,2A,2B,2C
CHALLENGER_SEASONS_TUTORIALS=CHALLENGER_PROMOTION,CHALLENGER_LEADERBOARD,CHALLENGER_RESULTS,CHALLENGER_NEXT_WEEK_DEFENSE,COLISEUM,FIGHT_PIT
GUILD_GIFTING_CARD_COUNT=1
GUILD_GIFTING_CARD_1_BULLET_ORDER=1,1A,2,2A,2B,3,3A,4,4A,4B,4C
SURGE_CARD_COUNT=4
SURGE_CARD_1_BULLET_ORDER=1,2,3,4
SURGE_CARD_2_BULLET_ORDER=1,1A,2,2A,3,3A,3B,4
SURGE_CARD_3_BULLET_ORDER=1,2,3,4,5,5A,5B,6,6A,6B
SURGE_CARD_4_BULLET_ORDER=1,2,3,4
SURGE_TUTORIALS=SURGE
BATTLE_BADGE_CARD_COUNT=4
BATTLE_BADGE_CARD_1_BULLET_ORDER=1,2,3,4
BATTLE_BADGE_CARD_2_BULLET_ORDER=1,2,3,4
BATTLE_BADGE_CARD_3_BULLET_ORDER=1,2
BATTLE_BADGE_CARD_4_BULLET_ORDER=1,2,2A,3
BATTLE_BADGE_TUTORIALS=BATTLE_BADGE
THE_CODEBASE_CARD_COUNT=4
THE_CODEBASE_CARD_1_BULLET_ORDER=1,2,3,3A,4,4A,5,5A
THE_CODEBASE_CARD_2_BULLET_ORDER=1,1A,1B,2,3,4,4A
THE_CODEBASE_CARD_3_BULLET_ORDER=1,1A2,3,3A,4,4A,5,5A,6,7
THE_CODEBASE_CARD_4_BULLET_ORDER=1,2,3,4,4A,5,6
THE_CODEBASE_TUTORIALS=CODEBASE,CODEBASE_INTRO
WISH_CRATE_CARD_COUNT=5
WISH_CRATE_CARD_1_BULLET_ORDER=1,2,3,4
WISH_CRATE_CARD_2_BULLET_ORDER=1,2
WISH_CRATE_CARD_3_BULLET_ORDER=1,2,3,3A,3B,3C
WISH_CRATE_CARD_4_BULLET_ORDER=1,1A,1B,1C,1D,1E,2,2A,2B,2C,2D
WISH_CRATE_CARD_5_BULLET_ORDER=1,2,3,3A,4,4A,5,5A,5B,7,7A,7B
EVENT_TRIALS_CARD_COUNT=1
EVENT_TRIALS_CARD_1_BULLET_ORDER=1,2,2A,3
POWER_PROMOTE_CARD_COUNT=1
POWER_PROMOTE_CARD_1_BULLET_ORDER=1,1A,2,2A,2B,3,3A,3B
TRIALS_CARD_COUNT=2
TRIALS_CARD_1_BULLET_ORDER=1,2,3
TRIALS_CARD_2_BULLET_ORDER=1,1A,1B,1C,1D,1E,2,2A,2B,2C,2D,3,4
TEAM_TRIALS_CARD_COUNT=2
TEAM_TRIALS_CARD_1_BULLET_ORDER=1,2,2A,2B,3,4,5
TEAM_TRIALS_CARD_2_BULLET_ORDER=1,2
TEAM_TRIALS_CARD_2_TYPE=TEAM_TRIALS_REWARDS_AND_HEROES
PRIZE_WALL_CARD_COUNT=1
PRIZE_WALL_CARD_1_BULLET_ORDER=1,2,3,4
PRIZE_WALL_CARD_2_BULLET_ORDER=
TRIAL_EVENT_CARD_COUNT=1
TRIAL_EVENT_CARD_1_BULLET_ORDER=1,2,3,4,5,6,7,8,9
TRIAL_EVENT_CUSTOM_CARD_COUNT=1
TRIAL_EVENT_CUSTOM_CARD_1_TYPE=TRIAL_EVENT_CUSTOM_INFO
TRIAL_EVENT_TUTORIALS=TRIAL_EVENTS, TRIAL_EVENTS_SUBTRIAL, TRIAL_EVENTS_STAGE, TRIAL_EVENTS_STAGE_SELECT
SKILL_TAGS_CARD_COUNT=1
SKILL_TAGS_CARD_1_BULLET_ORDER=1,1A,1B,2,2A
BATTLE_PASS_V2_CARD_COUNT=3
BATTLE_PASS_V2_CARD_1_BULLET_ORDER=1,1A,2,2A
BATTLE_PASS_V2_CARD_2_BULLET_ORDER=1,1A,2,2A,2B,3,3A
BATTLE_PASS_V2_CARD_3_BULLET_ORDER=1,1A,2,2A,3,3A,3B,4,4A,4B
BATTLE_PASS_V2_TUTORIALS=BATTLE_PASS
BATTLE_PASS_V2_PREMIUM_CARD_COUNT=1
BATTLE_PASS_V2_PREMIUM_CARD_1_BULLET_ORDER=1,1A,1B,1C
PATCHED_HEROES_CARD_COUNT=3
PATCHED_HEROES_CARD_1_BULLET_ORDER=1,1A,1B,1C,1D,1E,2,2A,2B,2C,2D,2E,2F,3,3A,3B,3C,3D,3E,3F,4,4A,4B,4C,4D,4E,4F,4G
PATCHED_HEROES_CARD_2_BULLET_ORDER=1,1A,1B,1C,1D,1E,1F,2,2A,2B,2C,2D,3,3A,3B,3C,3D
PATCHED_HEROES_CARD_3_TYPE=PATCH_TALENTS_INFO
EMERALD_RANK_CARD_COUNT=3
EMERALD_RANK_CARD_1_BULLET_ORDER=1,1A,2,2A,2B,2C,2D
EMERALD_RANK_CARD_2_BULLET_ORDER=1,1A,1B,1D,1E,2,2A,2B,2C,2D,3,3A,3B,3C,4,4A,4B,4C,5,5A,5B,5C
EMERALD_RANK_CARD_3_BULLET_ORDER=1,1A,2,2A,3,3A,4,4A,5,5A,6,6A,7,7A,8,8A
