
FILTER_ALL=All
FILTER_MISC=Misc
FILTER_STONES=Chips
FILTER_GEAR=Badges
FILTER_SHARD=Bits
FILTER_SCROLLS=Plans
FILTER_GEAR_BITS=Memories
FILTER_TRASH=Credits
FILTER_THREAD=Costume Threads
FILTER_EPIC_CHIPS=Skill Chips
FILTER_COUPONS=Purchase Vouchers
NO_ITEMS_MATCH_FILTER=No items match the current selected filter.
NO_ITEMS=You don't have any items yet. Collect them from the campaign!
OWNED_FORMAT=Owned: {#ffe00f}%1$s{}
VALUE_FORMAT=Value: {i} {#ffe00f}%1$s{}
BUTTON_USE=Use
BUTTON_SELL=Sell
SELECT_AMOUNT=Select Amount
USE_XP_ITEMS_IN_HERO_SCREEN=You can use XP drinks by pressing the "+" EXP button on the hero details screen.
SELL_AMOUNT_FORMAT={#ffe00f}%1$s{} for {i} {#ffe00f}%2$s{}
HERO_USES_HEADING=Can be equipped by these heroes:
MATERIAL_USES_HEADING=Used to craft these badges:
NO_CURRENT_USES=No current uses.
PURPLE_ITEM_UPDATE=This item is coming in a future update!
CONSUMABLE_USED_NOTIF=%1$s now active for the next %2$s!
PORT_RESET_DESCRIPTION_EXTRA=Once you've used all of your Port chances, you'll be able to use this item from the Port screen!
TRIALS_RESET_DESCRIPTION_EXTRA=Note:  Use this item from the Trials screen once you've used up all of your Team Trial chances.  This item cannot be used to reset The Codebase or any other non-Team Trial.
NO_FRAGS=You don't have any Mod Fragments yet. Collect them from Invasion!
BUTTON_USE_X=Use %1$s
BUTTON_USE_ALL=Use All
FILTER_CURRENCY=Tokens
VIEW_SHOP_BUTTON=View Shop
SHOP_LOCKED_TEAM_LEVEL=Can be exchanged for exclusive items.
FILTER_EMOJIS=Emojis
FILTER_AVATAR=Special Avatar Items
PREMIUM_STAMINA_INFO={#fc3caa}%1$d{}/%2$d have {#fc3caa}+%3$d%%{} bonus for the next {#fc3caa}%4$s{}
BONUS_TIME_REMAINING=Bonus Time Remaining:
ODD_SET_1=Odds: 35.6% hero chips, 32% badges, 14.2% gold, 11.1% full heroes, 7.1% hero xp.
ODD_SET_2=Odds: 100% badges.
PREROLL_EXCLUDES_DISCLAIMER=These items are chosen when the chest is received. Excludes heroes that are: Event exclusive, monthly Sign-in, Guild Crate featured, or VIP Crate featured.
BADGE_EXCLUDES_DISCLAIMER=These items are chosen when the chest is received and cannot give out the most recent rarity of badges. If a badge cannot be found, you earn Badge Tokens.
ODD_SET_3=Odds: 32% hero chips, 28.8% badges, 12.8% gold, 20% full heroes, 6.4% hero XP.
GUARANTEE_EXCLUDE_DISCLAIMER=Guarantees at least 1 full hero. Excludes heroes that are: Event exclusive, monthly Sign-in, Guild Crate featured, or VIP Crate featured.
EXCLUDES_DISCLAIMER=Excludes heroes that are: Event exclusive, monthly Sign-in, Guild Crate featured, or VIP Crate featured.
CATEGORY_HIDDEN=Hidden
CATEGORY_GEAR=Badge
CATEGORY_MISC=Miscellaneous
CATEGORY_STONE=Hero Chip
CATEGORY_HERO=Full Hero
CATEGORY_REEL=Badge Plan
CATEGORY_SHARD=Badge Bit
CATEGORY_TRASH=Credits
CATEGORY_GEAR_BIT=Memory Disk Bit
CATEGORY_GUILD_TROPHY=Guild Trophy
CATEGORY_COSTUME=Costume
CATEGORY_THREAD=Costume Thread
CATEGORY_INVASION_CONSUMABLE=Invasion
CATEGORY_CODE_FRAGMENT=Mod Fragment
CATEGORY_MOD_UPGRADE=Mod Upgrade
CATEGORY_EMOJI=Hero Emoji
CATEGORY_SPECIAL_AVATAR=Special Avatar
CATEGORY_COLLECTION_AVATAR=Collection Avatar
CATEGORY_AVATAR_BORDER=Avatar Border
CATEGORY_POSTER=Guild Poster Avatar
CATEGORY_EPIC_CHIP=Red Skill Chip
CW_RESETS_FULL=Max City Watch Resets reached.
CW_RESETS_DISPLAY=City Watch Resets: %1$d / %2$d
FILTER_CHESTS=Crates
FILTER_MEGABITS=Megabits
BUY_CHEST_SLIDER_TITLE=Slide to Add Crates
USE_ALL_CONFIRMATION_TITLE=Use All?
USE_ITEM_SLIDER_TITLE=Slide to Use %1$s
