
NUM_TIPS=88
TIP_1=In City Watch you can store energy on your heroes. Take advantage of this to charge abilities and use them in hard fights!
TIP_2=Emperor Zurg and Sulley make a great scare pair.
TIP_3=Sometimes it's best to not use auto. Timing your abilities just right can make all the difference.
TIP_4=Stuck in a tough fight? Enhance your badges for an extra boost!
TIP_5=Watch out! Heroes like Hades, Sally, and Judy Hopps can revive for an extra life in battle.
TIP_6=Most teams should have one of each role: damage, tank, support, and control. But there are always exceptions to the rule!
TIP_7=When attacking in Coliseum you can win individual fights by running out of time and having more HP than the opponent.
TIP_8=Tap "i"-buttons to get more info about game modes and features.
TIP_9=Heroes gain energy when they attack, when they take damage, and from some skills.
TIP_10=Shields are a great way to proactively protect your Heroes from big attacks.
TIP_11=Hero portraits with a "C" on them indicate that you'll advance a collection by winning fights with that hero.
TIP_12=Want to see what your Invasion Power-Ups give? Go to the hero screen and tap the flame icon in the lower left.
TIP_13=If you're not sure what an item does, tap on it for more info.
TIP_14=Hero skills make all the difference in combat. Sometimes your strongest team isn't the best for a particular fight. Try mixing it up!
TIP_15=When heroes have more than 100% chance to Crit, they'll gain a chance to "Super Crit" for 3x damage.
TIP_16=If a Hero takes more than 15% of their max HP from a single attack, they'll flinch and have their attacks interrupted.
TIP_17=Participate in more Disney Heroes discussions by visiting our forums. Access them by tapping your avatar from the main screen.
TIP_18=If someone is being rude, you can block their chats by tapping on their message and then tapping the block button.
TIP_19=At VIP 3 and higher, you no longer need raid tickets to raid!
TIP_20=Wards are modifiers to battle in Invasion and higher difficulties of City Watch. Learn which ones are easiest for you to deal with.
TIP_21=Invasion is a group effort. Try to have many people from your guild attack a bot before defeating it.
TIP_22=Invasion has supply crates which you can spend diamonds to gain Invasion bonuses and more mods.
TIP_23=Don't overlook mods. They have significant stat bonuses which will turn the tide in battle.
TIP_24=Don't worry about attuning mods to specific heroes. You can always reattune that mod to a new hero later.
TIP_25=Any skills with a fail chance really benefit from levels. Prioritize these types of skills first if you're short on gold.
TIP_26=Hiring mercenaries in City Watch and Creep Surge is great way to test out new heroes.
TIP_27=Don't use weak heroes in Trials just because you have them. You can't earn 3 stars if any of your Heroes get KO'd!
TIP_28=The Black Market and Mega Mart don't show up every day, but are a good place to get hero chips and other resources when they do.
TIP_29=In Heist, be mindful when calling heroes which are protecting valuables. Those heroes are protecting the valuables for a reason!
TIP_30=In Creep Surge you want to beat districts using as little power as possible.
TIP_31=Refreshing shops is a great way to get items faster. At VIP 4 you even get a free market refresh every day.
TIP_32=Use the "Repost Mercenaries" button to make posting mercenaries even easier.
TIP_33=You can adjust which chat channels show previews and red dots by going to your settings.
TIP_34=Friendship Mission speed is increased through Hero Rarity, stars, Hero level, and Skill levels.
TIP_35=Not sure what Friendship Disk provides the best ability for a hero? Ask your Guild or Global Chat for advice.
TIP_36=We have a welcoming community. If you have any questions, try asking your Guild or Global Chat.
TIP_37=Completing daily quests is almost a mini-game of itself. Try to find a pattern that lets you finish them efficiently.
TIP_38=Upgrade your Battle Pass with a Premium Pass to get chips for strong heroes and other rewards!
TIP_39=The Weekly Quest is very important. Not only does it give you a lot of Stamina, but you can gain rare double drop items too!
TIP_40=Be patient in Heist. Waiting to make sure enough heroes are close to a fight is more important than starting that fight unprepared.
TIP_41=Different heroes excel in different game modes. Learn these strengths and weaknesses to improve your performance!
TIP_42=Gain Guild Influence primarily by spending stamina, participating in Creep Surge, and completing Quests.
TIP_43=Heroes gain powerful new skills at Red rank. To unlock Red skills you'll need to earn skill chips from Epic City Watch.
TIP_44=Avoid crafting badge components individually by unlocking Power Crafting at VIP 5!
TIP_45=At VIP 4 you can instantly open Video Crates.
TIP_46=Want to try out a specific hero? Ask your guild to post that hero as a mercenary.
TIP_47=Don't neglect Collections! They're a great long-term goal for increasing your heroes' power.
TIP_48=Missions are an important source of Memories and Disk Power. Try to find the best mission combinations to maximize your rewards!
TIP_49=Memory Disks grant powerful bonus effects for your heroes. Make sure to invest in Friendships to unlock Memory Disks.
TIP_50=In Guild War you don't have to play on Auto. Try turning it off and see if you can time skills for the win.
TIP_51=You can beat hard Invasion Breaker fights by using a bunch of boosts or removing Wards. But you'll have to decide what's better!
TIP_52=Some Heroes can be useful in Invasion even if they're not one of the featured Heroes that week.
TIP_53=Support Heroes are great at healing, protecting, and buffing your team.
TIP_54=Tank Heroes generally are on the front of the battlefield and are good at staying alive. They'll help protect Heroes behind them.
TIP_55=Control Heroes disrupt the enemy's team, which helps your team perform more effectively.
TIP_56=Damage Heroes are often the centerpiece of your team since they directly help you win. Try to build teams that complement them.
TIP_57=Heroes take different positions in the battlefield: Back, Mid, and Front. This order influences which heroes will be attacked first.
TIP_58=Need assistance? Access Support by tapping your avatar from the main screen, then tap the Support button.
TIP_59=Armor reduces Normal Damage and Reality reduces Fantastic Damage. Nothing can reduce True Damage though.
TIP_60=City Watch uses the power of your top 5 heroes to choose enemies. Note that you can't unequip Disks or Mods to make enemies easier!
TIP_61=Invisible heroes can't be directly attacked, but will still be affected by skills that damage all enemies in an area.
TIP_62=The Beast's rage prevents him from being KO'd for 10 seconds. Try skills that remove buffs or use a lot of disables to defeat him!
TIP_63=View what each status effect icon means by pausing during battle and then tapping the icons button.
TIP_64=Some skills impact an area. Use these against teams that are clumped together or use knockbacks to make clumps yourself!
TIP_65=Melee basic attacks deal damage to all nearby enemies. Use knockbacks to force melee enemies to walk back into range to attack!
TIP_66=Not sure what Mods to use? Tap the "Recommend" button on the Mods page for advice.
TIP_67=Don't be afraid to ask for Guild Aid if you need it. Your Guild wants to help you succeed.
TIP_68=There are three types of Guild Aid requests: Skill Level, Hero Level, and Stamina.
TIP_69=Contests run every weekend and are an important source of resources.
TIP_70=Gain Hero Chips by using the Elite Campaign. You'll have a limited number of chances, but don't be afraid to spend Diamonds for more.
TIP_71=Challenger tier of Arena or Coliseum introduces seasonal play: This is a new way to test your skills and earn unique rewards.
TIP_72=Remember to thank your Guild members when you receive a Guild Gift!
TIP_73=Guild leadership spends Guild Influence on Guild Perks. If there's a Guild Perk you want, make sure to talk to your Guild about it!
TIP_74=Start of combat effects are very potent. Use them to gain early advantages in battle!
TIP_75=Hercules can be invincible frequently. Try dealing a lot of damage at once or preventing him from gaining energy to defeat him!
TIP_76=While alive, Megara prevents her frontmost ally from being defeated. Use Heroes that target the backline to defeat her quickly!
TIP_77=Merlin can quickly turn your entire team into Squirrels! Try using Timon and Pumbaa to block him from gaining energy from crits.
TIP_78="Disable" refers to stuns, charms, silences, freezes, and blinds.
TIP_79="Debuff" refers to any negative status effect, including disables.
TIP_80=View which badges your heroes need in the future by tapping the "Badges List" button on the Badge screen.
TIP_81=When looking at a hero's details, you can tap their image to see them animate!
TIP_82=In Arena, power isn't everything. Try to fight enemy lineups that your team will be good against. It's possible to pull off impressive wins!
TIP_83=Heroes with ranged basic attacks can stay farther away from danger and don't have to move as much to attack.
TIP_84=You can post heroes in chat and even spar with other players' Heroes! Sparring is a great way to practice.
TIP_85=It's important to have a strong healer for City Watch and Invasion to keep your Heroes healthy across many fights.
TIP_86=Coliseum forces you to balance your powerful heroes across 3 teams. Use this to experiment with different types of lineups!
TIP_87=Equipped items are remembered when a defense is set. If you change equipped Disks or Mods, you should update your defense.
TIP_88=During battle, heroes who have their Attack Speed increased are limited to a 300% gain.
