
UPSELL_FIGHT_PIT=Fight other players head to head! Arena unlocks at Team Level %1$d.
UPSELL_TRADER=Buy and sell badges, hero chips and other items! The Market unlocks by completing Chapter 2.
UPSELL_GUILDS=Hire Mercenaries, unlock powerful Perks, battle in the Creep Surge and more! Guilds unlock at Team Level %1$d.
UPSELL_ENCHANTING=Power up your badges with big stat boosts! Enhancement unlocks at Team Level %1$d.
UPSELL_PORT=Battle for tons of XP or Gold each day! The Port unlocks at Team Level %1$d.
UPSELL_TEAM_TRIALS=Fight to earn extra blue, purple, and orange badges! Team Trials unlocks at Team Level %1$d.
UPSELL_CRYPT=Work with your guild to clear the city before time runs out! Creep Surge unlocks at Team Level %1$d.
UPSELL_EXPEDITION=Earn gold, tokens, and more as you battle through increasingly hard enemies! City Watch unlocks at Team Level %1$d.
UPSELL_COLISEUM=Pit your top 3 teams of heroes against other players! Coliseum unlocks at Team Level %1$d.
UPSELL_CHALLENGES=Complete weekly challenges to win custom stickers! Unlocks at Team Level %1$d.
UPSELL_MEGA_MART=Buy resources and tokens for gold and diamonds! The Mega Mart can be found rarely when raiding. The Mega Mart can only be found every %2$d hours.
UPSELL_BLACK_MARKET=Buy hero chips, memories, and more for gold and diamonds! The Black Market can be found occasionally when raiding.  The Black Market can only be found every %2$d hours.
CONTESTS_NO_OPEN_CONTESTS=No contest is running right now. Check back later!
VIEW_ITEM_INVENTORY=View Inventory
CAMPAIGN=Campaign
GUILDS=Guilds
RANKINGS=Rankings
SIGN_IN=Sign In
TRADER=Market
FIGHT_PIT=Arena
COLISEUM=Coliseum
CHESTS=Crates
EXPEDITION=City  Watch
CRYPT=Surge
CHOOSE_NAME=Choose Name
COLISEUM_COMING_SOON=Prepare your heroes! The Coliseum is coming soon!
PORT=The Port
TEAM_TRIALS=Trials
DEBUG=Debug
ENCHANTING=Enhancement
MISSIONS=Missions
SKIP_TUTORIAL=Skip Tutorial
UPSELL_MISSIONS=Have your Heroes go on Missions to generate you resources over time! Unlocks at Team Level %1$d.
MEGA_MART=Mega Mart
BLACK_MARKET=Black Market
UPSELL_RANKINGS=See where you rank among the top players and guilds! Rankings available at Team Level %1$d.
HEIST=Heist
UPSELL_HEIST=Catch the Thief with 4 other players! Heist available at Team Level %1$d.
CONSUMABLES_TITLE=Consumables
CONSUMABLES_EMPTY=You don't have any active consumable items right now.
AIRDROP=Video
UPSELL_AIRDROP=Get a daily shipment of goodies! Unlocks at Team Level %1$d.
FREE_DIAMONDS=Get Diamonds for FREE!
HEIST_COMING_SOON=The Heist is coming soon!
GUILD_CONTEST_JOIN_GUILD=Join a Guild to participate in the current contest!
CHALLENGES=Challenges
GUILD_WAR=Guild War
UPSELL_GUILD_WAR_LOCKED=Battle other guilds for status and rewards in Guild War. Unlocks at Team Level %1$d.
UPSELL_GUILD_WAR_NO_GUILD=Join a guild to battle other guilds for status and rewards in Guild War.
GUILD_WAR_COMING_SOON=Guild War is coming soon!
INVASION=Invasion!
UPSELL_INVASION=Defend the city from giant robots with your guild. Invasion unlocks at Team Level %1$d.
COLLECTIONS=Collections
UPSELL_COLLECTIONS=Complete collections to earn permanent hero stat buffs, plus custom avatar badges and borders! Unlocks at Team Level %1$d.
COLLECTIONS_COMING_SOON=Collections is coming soon!
NEXT_MONTH_SIGN_IN=Next Month's Sign-In
UPSELL_WISHING_WELL=Unlock the Wish Crate at Team Level %1$d or VIP %2$d.
SKIP_TUTORIAL_TITLE=Skip Tutorial?
SKIP_TUTORIAL_INFO=You'll skip the introductory story and basics, but be able to jump right into the game.
WISHING_WELL=Wishing Crate
VIP=VIP
