
MERCHANT_NO_LONGER_AVAILABLE=Shop no longer available.
SHOP_BONUS_EVENT_ITEMS=%1$dx Items!
MERCHANT_CRYPT=Surge Shop
MERCHANT_FIGHT_PIT=Arena Shop
MERCHANT_EXPEDITIONS=City Watch Shop
MERCHANT_MEGA_MART=Mega Mart
MERCHANT_BLACK_MARKET=Black Market
MERCHANT_COLISEUM=Coliseum Shop
MERCHANT_MEMORY=Memory Market
MERCHANT_GEAR=Badge Bazaar
MERCHANT_NORMAL=Market
MERCHANT_WAR=War Shop
ACTION_REFRESH=Refresh
MERCHANT_REFRESH_TOO_FAST=You tried to refresh too soon, please wait a moment.
MERCHANT_WILL_LEAVE=Shop will leave in:
TRADER_NEXT_REFRESH_TODAY=Refreshes today at:
TRADER_NEXT_REFRESH_TOMORROW=Refreshes tomorrow at:
TRADER_NOT_ENOUGH_TO_PURCHASE=You don't have enough %1$s to pay the Market!
TRADER_NOT_ENOUGH_TO_REFRESH=You don't have enough %1$s to refresh the Market!
SOUL_STONE=Hero Chip
MERCHANT_AUTOSELL_TITLE=Sell Your Credits!
SELL_ALL=Sell All!
MERCHANT_AUTOSELL_INFO=Some items are useless to heroes. Sell them to the Market to earn gold!
OWNED_COLON=Owned:
TOTAL_SELL_VALUE=Total Sell Value:
FREE_NOW_AMOUNT=Free x%1$d
REFRESH_NOW=Refresh Now!
BUYS_LEFT=Buys Left:
USE_REFRESH_ITEM=Use Refresh
MISSING_SHOP_REFRESH_ITEM=You need a Shop Refresh item to do that.
MERCHANT_REFRESH_QUESTION=Do you want to refresh the %1$s?
GENERIC_PURCHASE_SALE=Sale! {#ffe00f}%1$d%%{} Off!
TRADER_BUY_IT=Buy it!
UNTIL_UNLOCK=Until Unlock:
UNTIL_EVOLVE=Until Evolve:
TRADER_QUANTITY=Quantity: {#ffe00f}x%1$,d{}
TRADER_OWNED=Owned: {#ffe00f}%1$,d{}
TRADER_CRAFTABLE=Craftable: {#ffe00f}%1$,d{}
TRADER_CRAFTABLE_MANY=Craftable: {#ffe00f}Lots{}
HERO_NEEDS_ITEM_SLOT_FORMAT={#ffe00f}%1$s{} needs this item.
HERO_NEEDS_ITEM_CRAFTING_FORMAT={#ffe00f}%1$s{} needs this item for crafting.
OTHER_HEROES_NEED_FORMAT={#ffe00f}%1$s{} other heroes need this item.
MEGA_MART_VIP_PERK=Permanent access to the Mega Mart!
BLACK_MARKET_VIP_PERK=Permanent access to the Black Market!
UNLOCK_PERMANENTLY=Unlock Permanently
UNLOCK_MERCHANT_ACTION=Unlock the %1$s?
CANT_REFRESH_THAT_MERCHANT=You can't manually refresh the %1$s.
NO_MORE_VIP_MERCHANT_REFRESHES=You have no more free refreshes for the %1$s.
NO_MORE_VIDEO_MERCHANT_REFRESHES=You have no more video refreshes for the %1$s.
MERCHANT_FOUND=%1$s Found!
TRADER_UNLOCKED=You've Unlocked the Market!
VISIT_MERCHANT=Visit
MERCHANT_HEIST=Heist Shop
MERCHANT_AIRDROP=Air Drop
TRADER_NEXT_REFRESH_DAY=Refreshes %1$s at:
TRADER_NEXT_REFRESH_DAY_NEXT_WEEK=Refreshes next %1$s at:
MERCHANT_CHALLENGE=Challenge Shop
MERCHANT_INVASION=Invasion Shop
