
ARMOR=+%1$s Armor (%2$s%% of Max HP)
REALITY=+%1$s Reality (%2$s%% of Max HP)
SHIELDS=+%1$s Starting Shield (%2$s%% of Max HP)
SKILL_LEVEL_2=+%1$s Green Skill Levels
SKILL_LEVEL_3=+%1$s Blue Skill Levels
SKILL_LEVEL_4=+%1$s Purple Skill Levels
ATTACK_SPEED=+%1$s%% Attack Speed
NORMAL_CRIT=+%1$s Normal Crit
FANTASTIC_CRIT=+%1$s Fantastic Crit
NORMAL_CRIT_NEGATION=+%1$s%% Normal Crit Negation
FANTASTIC_CRIT_NEGATION=+%1$s%% Fantastic Crit Negation
HP=+%1$s Max HP
SKILL_POWER=+%1$s Skill Power
BASIC_DAMAGE=+%1$s Basic Damage
ARMOR_TOOLTIP=This mod effect increases the equipped hero's maximum armor. Armor reduces the amount of damage a Hero takes from Normal Damage.
REALITY_TOOLTIP=This mod effect increases the equipped hero's reality. Reality reduces the amount of damage a Hero takes from Fantastic Damage.
SHIELDS_TOOLTIP=This mod effect gives the equipped hero a temporary shield at the start of battle.
SKILL_LEVEL_2_TOOLTIP=This mod effect increases the level of the equipped hero's green skill.
SKILL_LEVEL_3_TOOLTIP=This mod effect increases the level of the equipped hero's blue skill.
SKILL_LEVEL_4_TOOLTIP=This mod effect increases the level of the equipped hero's purple skill.
ATTACK_SPEED_TOOLTIP=This mod effect increases the equipped hero's attack speed.
NORMAL_CRIT_TOOLTIP=This mod effect increases the equipped hero's normal crit. Normal crit increases the chance that your attacks that do Normal Damage will result in a critical strike.
FANTASTIC_CRIT_TOOLTIP=This mod effect increases the equipped hero's fantastic crit. Fantastic crit increases the chance that your attacks that do Fantastic Damage will result in a critical strike.
NORMAL_CRIT_NEGATION_TOOLTIP=This mod effect increases the equipped hero's normal crit negation. Normal crit negation decreases the Normal Crit multiplier.
FANTASTIC_CRIT_NEGATION_TOOLTIP=This mod effect increases the equipped hero's fantastic crit negation. Fantastic crit negation decreases the fantastic Crit multiplier.
ARMOR_DESC=Increases armor equal to a percent of their max HP.
REALITY_DESC=Increases reality equal to a percent of thier max HP.
SHIELDS_DESC=Gives the hero a shield equal to a percent of their max HP. The shield lasts for %1$d seconds.
SKILL_LEVEL_2_DESC=Increases the level of the hero's green skill. This can go above the max level.
SKILL_LEVEL_3_DESC=Increases the level of the hero's blue skill. This can go above the max level.
SKILL_LEVEL_4_DESC=Increases the level of the hero's purple skill. This can go above the max level.
ATTACK_SPEED_DESC=Increases the attack speed of the hero.
NORMAL_CRIT_DESC=Increases the normal crit stat of the hero.
FANTASTIC_CRIT_DESC=Increases the fantastic crit stat of the hero.
NORMAL_CRIT_NEGATION_DESC=Increases the normal crit negation stat of the hero.
FANTASTIC_CRIT_NEGATION_DESC=Increases the fantastic crit negation stat of the hero.
ARMOR_NAME=Armor
REALITY_NAME=Reality
SHIELDS_NAME=Shield
SKILL_LEVEL_2_NAME=Green Skill
SKILL_LEVEL_3_NAME=Blue Skill
SKILL_LEVEL_4_NAME=Purple Skill
ATTACK_SPEED_NAME=Attack Speed
NORMAL_CRIT_NAME=Normal Crit
FANTASTIC_CRIT_NAME=Fantastic Crit
NORMAL_CRIT_NEGATION_NAME=Normal Crit Negation
FANTASTIC_CRIT_NEGATION_NAME=Fantastic Crit Negation
