
MODS=Mods
MODS_COLON=Mods:
NO_MODS=You don't have any mods yet. Collect them from the Tournament Event.
MODS_RED=Red Team Mods
MODS_BLUE=Blue Team Mods
MODS_YELLOW=Yellow Team Mods
MOD_NAME_TIER=%1$s %2$s Mod +%3$s
MOD_NAME=%1$s %2$s Mod
MOD_BASIC_DAMAGE=BD
MOD_HP=HP
MOD_HP_BD=HP / BD
MOD_HP_SP=HP / SP
MOD_SP=SP
MOD_LEVEL=Level %1$s
MOD_LEVEL_MAX_SMALLER=/ %1$s
MOD_ATTUNED_TO=Attuned to %1$s
MOD_EQUIPPED_TO=Equipped to %1$s
MOD_DISASSEMBLE=Disassemble
MOD_LEVEL_UP=Level Up
MOD_ADVANCE=Advance
MOD_CAPACITY_TITLE=Too Many Mods!
MOD_CAPACITY_BODY=You just recieved a mod but you can't hold any more. Your new mod will be waiting in your mailbox for the next 5 days. Go to your mods and disassemble an existing mod to make room for your new mod. {#d53d94}If you don't you will lose your new mod in 5 days{}.
MOD_REATTUNE_BODY=Are you sure you want to equip this mod to %1$s? It will cost you hero chips and doing so will also Attune it to %1$s preventing you from being able to equip it to another hero?
MOD_REATTUNE_TITLE=Attune & Equip
MOD_LEVEL_UP_MESSAGE=Level up this mod to level %1$s to give it:
MOD_LEVEL_UP_NO_FORMAT=Level up this mod to give it:
NO_INVENTORY_MODS=You don't have any mods yet. Earn more!
MOD_SELECT_EMPTY=Select a Mod on the right.
MOD_LIST_EMPTY=No available %1$s mods for this hero. Unequip a %1$s mod from another hero or earn more.
MOD_SHOW_ATTUNED=You have %1$s %2$s mods attuned to other heroes
ABOUT_MODS=About Mods
UPGRADE_RARITY_TO_EQUIP_MODS=Promote to Purple +1 to Equip Mods
SHOW_BUTTON=Show
MOD_ADVANCE_COST=Costs:
MOD_TIER_MAX_LEVEL=+%1$s Max Levels
MOD_ADVANCE_MESSAGE=Advance this Mod to +%1$s to give it:
MOD_ADVANCE_MESSAGE_ONE=Advance this Mod to
MOD_ADVANCE_MESSAGE_TWO=to give it:
MOD_ADVANCE_ATTUNE=Attune Mod to %1$s
ADVANCE_WILL_ATTUNE=Advancing this mod will Attune it to %1$s. You won't be able to move this Mod to another hero without spending more Hero Chips of that hero.
FRAGS=Frags
EQUIP_TO_ADVANCE=Equip To Advance
MUST_EQUIP_MESSAGE=You must equip this mod to a Hero before you can Advance it. Go to the Hero Details Screen to equip mods to Heroes.
ADVANCE_QUESTION=Advance?
MOD_NO_HEROES_TO_EQUIP=You don't have any heroes to equip this mod to.
MOD_DISASSEMBLE_DESTROY={#fc3caa}Destroy{} this mod to get %1$s Mod Fragments
MOD_DISASSEMBLE_IMPROVE=Improve the mod to improve what you get
MOD_AT_LEVEL=At level %1$d
MOD_AT=At +%1$d
MOD_TIER_MAXED=Tier Maxed!
MOD_DISASSEMBLE_COMING_SOON=Disassembly of this mod is coming soon
MOD_LEVEL_MAXED=Level Maxed!
DISASSEMBLE_QUESTION=Disassemble Now?
DISASSEMBLE_MESSAGE=Are you sure you want to disassemble this mod? \n It can not be undone.
SLOT_LOCKED=Promote %1$s to %2$s to unlock this slot.
UPGRADE_MOD=Upgrade Mod
UPGRADE_CHOICE_MSG=Choose one upgrade to add to this mod. Each mod can only have one upgrade.
UPGRADE_LEVEL_TIER_MSG=Advance mod to +%1$d, level it up to level %2$d
UPGRADE_LEVEL_MSG=Level up mod to level %1$d
IMPROVE_UPGRADE=Improve Upgrade
MOD_UPGRADE_PIECES=Mod Upgrade Pieces
UPGRADE_METER_TOOLTIP=Earn Mod Upgrade Pieces in the Invasion. Use them to add extra effects to your Mods.
UPGRADE_ADD=Add
SELECT_UPGRADE=Select Upgrade
UPGRADE_CONFIRM_MSG=Are you sure you want to upgrade this Mod to add %1$s? Once you add an extra effect, you can't change it later.
MOD_FRAGMENTS=Mod Fragments
MOD_UPGRADES=Mod Upgrades
CURRENT_MODS=Current Mods:
RECOMMENDED_MODS=Recommended Mods:
BEST_POSSIBLE=Best Possible
RECOMMENDED_MODS_TITLE=Recommended Mods
RECOMMENDED_MODS_SUBTITLE=Based on the {%1$s}%2$s{} mods you have available, we recommend equipping the following:
EQUIP_MODS_BTN=Equip Mods
RECOMMEND=Recommend
PLUS_POWER_FORMAT=+%1$s {#ffe00f}Power{}
RECOMMENDED_MODS_EMPTY=Your equipped mods are the best currently available.
REC_MODS_EQUIP_EMPTY=You've already equipped the best mods currently available.
REC_MODS_NO_AVAILABLE=There are no available mods to recommend. Unequip {%1$s}%2$s{} mods from other heroes or earn more.
MODS_AVAILABLE={#ffe00f}%1$s{} Mods Available
REC_MODS_NONE_TO_EQUIP=There are no recommended mods to equip.
BEST_POSSIBLE_MSG=Out of all possible mod configurations; You may not own these mods
PLUS_LEVELS=+%1$s Levels
