
DISNEY_HEROES=Disney Heroes
NOTIFICATION_TITLE_LAPSED_CATCH_UP=%1$d Free Stamina
NOTIFICATION_LAPSED_CATCH_UP=Next 24 hours only!
NOTIFICATION_FIGHT_PIT_PROMOTE=Congrats! You were just promoted to %1$s %2$s!
NOTIFICATION_COLISEUM_PROMOTE=Congrats! You were just promoted to %1$s %2$s!
NOTIFICATION_FREE_STAMINA=Hurry...Claim your free stamina now!
NOTIFICATION_STORE_RESTOCK=New items are on sale at the Market!
NOTIFICATION_STAMINA_FULL=Your stamina is full. Time to head back to the campaign!
NOTIFICATION_POWER_POINTS_FULL=Your skill points are full. Time to upgrade your heroes!
NOTIFICATION_FIGHT_PIT_REWARDS_WARNING=Arena and Coliseum ranking rewards will be sent in 5 minutes!
NOTIFICATION_TITLE_FREE_STAMINA=Free Stamina
NOTIFICATION_TITLE_STORE_RESTOCK=Market Refreshed
NOTIFICATION_TITLE_STAMINA_FULL=Full Stamina
NOTIFICATION_TITLE_POWER_POINTS_FULL=Full Skill Points
NOTIFICATION_TITLE_FIGHT_PIT_REWARDS_WARNING=Arena & Coliseum Rewards
NOTIFICATION_TITLE_REMOVAL=Removal
NOTIFICATION_TITLE_FIGHT_PIT_DEMOTION_WARNING=Arena Demotion
NOTIFICATION_TITLE_FIGHT_PIT_PROMOTION=Arena Promotion
NOTIFICATION_TITLE_COLISEUM_DEMOTION_WARNING=Coliseum Demotion
NOTIFICATION_TITLE_COLISEUM_PROMOTION=Coliseum Promotion
NOTIFICATION_TITLE_CRYPT_RAID_ENDING=Creep Surge
NOTIFICATION_CRYPT_RAID_ENDING=Creep Surge ending in 2 hours!
NOTIFICATION_CRYPT_RAID_REWARDS=Creep Surge rewards are here. Time to collect your Surge Tokens!
NOTIFICATION_TITLE_SERVER_UPDATES=Updates and Events
NOTIFICATION_TITLE_GUILD_CHAT=Guild Chat
NOTIFICATION_TITLE_GUILD_WALL_CHAT=Guild Wall
NOTIFICATION_TITLE_GUILD_WAR_CHAT=War Chat
NOTIFICATION_TITLE_GUILD_OFFICER_CHAT=Officer Chat
NOTIFICATION_TITLE_PRIVATE_CHAT=Private Chat
ALL_PUSH_NOTIFICATIONS=All Notifications
NEW_PLAYER_NOTIFICATION=Free stuff! Log in now to claim your Welcome Week and Daily Sign-in Rewards!
COLISEUM_PROMOTE_DANGER=Your Coliseum promotion is in danger! Someone has passed you on the rankings list.
FIGHT_PIT_PROMOTE_DANGER=Your Arena promotion is in danger! Someone has passed you on the rankings list.
COLISEUM_PROMOTE_LOST=Uh oh... you were bumped from your promotion slot. Time to get back in the Coliseum!
FIGHT_PIT_PROMOTE_LOST=Uh oh... you were bumped from your promotion slot. Time to get back in the Arena!
GUILD_CHAT_NOTIF=%1$s: %2$s
PUSH_NOTIF_HEROES_POSTED=[Heroes posted]
PM_NOTIF=%1$s: %2$s
NOTIFICATION_TITLE_FRIEND_STAMINA_FULL=Full Friend Stamina
NOTIFICATION_FRIEND_STAMINA_FULL=Your friend stamina is full. Come spend some time in the friend campaign!
NOTIFICATION_TITLE_FREE_CRATE=Free Crate
NOTIFICATION_FREE_DIAMOND_CRATE=You have a free Diamond Crate waiting for you!
NOTIFICATION_FREE_GUILD_CRATE=You have a free Guild Crate waiting for you!
NOTIFICATION_FREE_VIP_CRATE=You have a free VIP Crate waiting for you!
NOTIFICATION_TITLE_HEIST_INVITE=Heist Invitation
NOTIFICATION_HEIST_INVITE=You have been invited to a Heist by %1$s. Log in to join it!
NOTIFICATION_TITLE_ML_DIAMOND_BUNDLE=Diamond Bundles
NOTIFICATION_ML_DIAMOND_BUNDLE=Diamond Bundles expiring in 1 hour!
NOTIFICATION_TITLE_INVASION_STARTED=Invasion Started
NOTIFICATION_INVASION_STARTED=A new Invasion has started! Time to join the battle.
NOTIFICATION_TITLE_INVASION_STAMINA_FULL=Full Invasion Stamina
NOTIFICATION_INVASION_STAMINA_FULL=Your Invasion stamina is full. Come back and earn more Breakers!
NOTIFICATION_TITLE_INVASION_SHOP_REFRESH=Invasion Shop Refresh
NOTIFICATION_INVASION_SHOP_REFRESH=The Invasion shop has been refreshed. Spend your Boss Tech!
NOTIFICATION_TITLE_ML_IAP_BUNDLE=Special Offers
NOTIFICATION_ML_IAP_BUNDLE=A Special Offer is expiring in 1 hour!
NOTIFICATION_TITLE_CA_SEASON_WEEKLY_UPDATE=Season Update
NOTIFICATION_CA_SEASON_WEEKLY_UPDATE=A new season week has started in the Arena and Coliseum!
NOTIFICATION_TITLE_CA_SEASON_DEFENSE_REMINDER=Prepare Your Challenger Defense
NOTIFICATION_CA_SEASON_DEFENSE_REMINDER=The next Challenger Seasons week begins in %1$s
NOTIFICATION_TITLE_BLACK_MARKET_EXPIRE=Black Market
NOTIFICATION_BLACK_MARKET_EXPIRE=The Black Market is open! Check it out before it closes up shop soon!
NOTIFICATION_TITLE_MEGA_MART_EXPIRE=Mega Mart
NOTIFICATION_MEGA_MART_EXPIRE=The Mega Mart is open! Check it out before it closes up shop soon!
NOTIFICATION_TITLE_WEEKLY_QUEST_REWARDS=Weekly Quest Rewards
NOTIFICATION_WEEKLY_QUEST_REWARDS=Log in today to claim your weekly rewards!
NOTIFICATION_TITLE_PREMIUM_STAMINA_EXPIRATION=Premium Stamina Expiration
NOTIFICATION_PREMIUM_STAMINA_EXPIRATION=Your Premium Stamina is about to expire!
