
COMPLETE_FORTIFICATION=Complete Fortification
COMPLETE_FORTIFICATION_DESCRIPTION=This Hero is Immune to Study and Pierce for the first <immuneStudyPierceTime> seconds of combat.
COMPLETE_FORTIFICATION_DELTA=+<immuneStudyPierceTime> Seconds
BOLD_STURDINESS=Bold Sturdiness
BOLD_STURDINESS_DESCRIPTION=This Hero is Immune to Scare and Shatter for the first <immuneScareShatterTime> seconds of combat.
BOLD_STURDINESS_DELTA=+<immuneScareShatterTime> Seconds
DAUNTLESS=Dauntless
DAUNTLESS_DESCRIPTION=This Hero is Immune to Stun and Freeze for the first <immuneStunFreezeTime> seconds of combat.
DAUNTLESS_DELTA=+<immuneStunFreezeTime> Seconds
STOUT_SENSES=Stout Senses
STOUT_SENSES_DESCRIPTION=This Hero is Immune to Blind and Silence for the first <immuneBlindSilenceTime> seconds of combat.
STOUT_SENSES_DELTA=+<immuneBlindSilenceTime> Seconds
SELF_PURIFICATION=Self-Purification
SELF_PURIFICATION_DESCRIPTION=This Hero is Immune to Curse and Sap for the first <immuneCurseSapTime> seconds of combat.
SELF_PURIFICATION_DELTA=+<immuneCurseSapTime> Seconds
STOIC_DETERMINATION=Stoic Determination
STOIC_DETERMINATION_DESCRIPTION=This Hero is Immune to Charm and Hex for the first <immuneCharmHexTime> seconds of combat.
STOIC_DETERMINATION_DELTA=+<immuneCharmHexTime> Seconds
NIMBLE=Nimble
NIMBLE_DESCRIPTION=This Hero is Immune to Slows for the first <immuneSlowTime> seconds of combat.|Slows include Snares as well as reductions in Movement and Attack Speed.
NIMBLE_DELTA=+<immuneSlowTime> Seconds
RELENTLESS=Relentless
RELENTLESS_DESCRIPTION=This Hero and allies are Immune to Knockbacks for the first <immuneKnockbackTime> seconds of combat.
RELENTLESS_DELTA=+<immuneKnockbackTime> Seconds
HEAL_SHARE=Heal Share
HEAL_SHARE_DESCRIPTION=When this Hero is Healed, all allies are also Healed for <healSharePercent> of that HP. Healing from this Talent cannot trigger other copies of this Talent.
HEAL_SHARE_DELTA=+<healSharePercent> Healing
SHIELD_SHARE=Shield Share
SHIELD_SHARE_DESCRIPTION=When this Hero is Shielded, all allies are also Shielded for <shieldSharePercent> of that Shield HP for <shieldDuration> seconds. Shielding from this Talent cannot trigger other copies of this Talent.
SHIELD_SHARE_DELTA=+<shieldSharePercent> Shielding
ARMOR_SHARE=Armor Share
ARMOR_SHARE_DESCRIPTION=When this Hero gains Armor, all allies gain <armorSharePercent> of that Armor for <armorDuration> seconds. Armor gains from this Talent cannot trigger other copies of this Talent.
ARMOR_SHARE_DELTA=+<armorSharePercent> Armor
REALITY_SHARE=Reality Share
REALITY_SHARE_DESCRIPTION=When this Hero gains Reality, all allies gain <realitySharePercent> of that Reality for <realityDuration> seconds. Reality gains from this Talent cannot trigger other copies of this Talent.
REALITY_SHARE_DELTA=+<realitySharePercent> Reality
ARMOR_BLIGHT=Armor Blight
ARMOR_BLIGHT_DESCRIPTION=Enemies damaged by this Hero lose <armorReducePercent> Armor for <debuffDuration> seconds.
ARMOR_BLIGHT_DELTA=+<armorReducePercent> Armor Reduction
REALITY_BLIGHT=Reality Blight
REALITY_BLIGHT_DESCRIPTION=Enemies damaged by this Hero lose <realityReducePercent> Reality for <debuffDuration> seconds.
REALITY_BLIGHT_DELTA=+<realityReducePercent> Reality Reduction
HEALTH_DRAIN=Health Drain
HEALTH_DRAIN_DESCRIPTION=This Hero Heals for <healPercent> of the damage they deal.
HEALTH_DRAIN_DELTA=+<healPercent> Healing
TANK_AGGRESSIVE=Tank Aggressive
TANK_AGGRESSIVE_DESCRIPTION=This Hero deals <damageVsTankPercent> more damage to Tank Role enemies.
TANK_AGGRESSIVE_DELTA=+<damageVsTankPercent> Damage
SUPPORT_AGGRESSIVE=Support Aggressive
SUPPORT_AGGRESSIVE_DESCRIPTION=This Hero deals <damageVsSupportPercent> more damage to Support Role enemies.
SUPPORT_AGGRESSIVE_DELTA=+<damageVsSupportPercent> Damage
CONTROL_AGGRESSIVE=Control Aggressive
CONTROL_AGGRESSIVE_DESCRIPTION=This Hero deals <damageVsControlPercent> more damage to Control Role enemies.
CONTROL_AGGRESSIVE_DELTA=+<damageVsControlPercent> Damage
DAMAGE_AGGRESSIVE=Damage Aggressive
DAMAGE_AGGRESSIVE_DESCRIPTION=This Hero deals <damageVsDpsPercent> more damage to Damage Role enemies.
DAMAGE_AGGRESSIVE_DELTA=+<damageVsDpsPercent> Damage
DOMINANCE=Dominance
DOMINANCE_DESCRIPTION=When this Hero triggers Weakness, their damage is amplified by an additional <damagePercent> per stack.
DOMINANCE_DELTA=+<damagePercent> Damage
CRUELTY=Cruelty
CRUELTY_DESCRIPTION=When this Hero applies Curse, target Healing is Reduced by an additional <cursePercent>.
CRUELTY_DELTA=+<cursePercent> Reduced Healing
DEVASTATING_SAP=Devastating Sap
DEVASTATING_SAP_DESCRIPTION=When this Hero applies Sap, target Energy gains are Reduced by an additional <sapPercent>.
DEVASTATING_SAP_DELTA=+<sapPercent> Reduced Energy
ARMOR_DEBILITATION=Armor Debilitation
ARMOR_DEBILITATION_DESCRIPTION=When this Hero Debuffs enemies, those enemies lose <reduceArmorPercent> Armor for <debuffDuration> seconds. This can happen to each enemy once every <reduceCooldown> seconds.
ARMOR_DEBILITATION_DELTA=+<reduceArmorPercent> Armor Reduction
REALITY_DEBILITATION=Reality Debilitation
REALITY_DEBILITATION_DESCRIPTION=When this Hero Debuffs enemies, those enemies lose <reduceRealityPercent> Reality for <debuffDuration> seconds. This can happen to each enemy once every <reduceCooldown> seconds.
REALITY_DEBILITATION_DELTA=+<reduceRealityPercent> Reality Reduction
POWER_DEBILITATION=Power Debilitation
POWER_DEBILITATION_DESCRIPTION=When this Hero Debuffs enemies, those enemies lose <reduceBdSpPercent> Basic Damage and Skill Power for <debuffDuration> seconds. This can happen to each enemy once every <reduceCooldown> seconds.
POWER_DEBILITATION_DELTA=+<reduceBdSpPercent> Basic Damage and Skill Power Reduction
SPEED_DEBILITATION=Speed Debilitation
SPEED_DEBILITATION_DESCRIPTION=When this Hero Debuffs enemies, those enemies lose <reduceSpeedPercent> Movement and Attack Speed for <debuffDuration> seconds. This can happen to each enemy once every <reduceCooldown> seconds.
SPEED_DEBILITATION_DELTA=+<reduceSpeedPercent> Speed Reduction
PREDICTIVE_DEBILITATION=Predictive Debilitation
PREDICTIVE_DEBILITATION_DESCRIPTION=When this Hero Debuffs enemies, those enemies lose <reduceTenEvasPercent> Tenacity and Evasion for <debuffDuration> seconds. This can happen to each enemy once every <reduceCooldown> seconds.
PREDICTIVE_DEBILITATION_DELTA=+<reduceTenEvasPercent> Tenacity and Evasion Reduction
DAMAGE_DEBILITATION=Damage Debilitation
DAMAGE_DEBILITATION_DESCRIPTION=When this Hero Debuffs enemies, those enemies deal <reduceDmgDealtPercent> Reduced Damage for <debuffDuration> seconds. This can happen to each enemy once every <reduceCooldown> seconds.
DAMAGE_DEBILITATION_DELTA=+<reduceDmgDealtPercent> Reduced Damage
SILENCING_ATTACKS=Silencing Attacks
SILENCING_ATTACKS_DESCRIPTION=Basic Attacks from this Hero apply Silence to enemies struck for <silenceDuration> seconds.
SILENCING_ATTACKS_DELTA=+<silenceDuration> seconds
ARMOR_BENEVOLENCE=Armor Benevolence
ARMOR_BENEVOLENCE_DESCRIPTION=Buffs and Heals from this Hero also grant <increaseArmorPercent> Armor for <buffDuration> seconds. This can happen to each Hero once every <increaseCooldown> seconds.
ARMOR_BENEVOLENCE_DELTA=+<increaseArmorPercent> Armor
REALITY_BENEVOLENCE=Reality Benevolence
REALITY_BENEVOLENCE_DESCRIPTION=Buffs and Heals from this Hero also grant <increaseRealityPercent> Reality for <buffDuration> seconds. This can happen to each Hero once every <increaseCooldown> seconds.
REALITY_BENEVOLENCE_DELTA=+<increaseRealityPercent> Reality
POWER_BENEVOLENCE=Power Benevolence
POWER_BENEVOLENCE_DESCRIPTION=Buffs and Heals from this Hero also grant <increaseBdSpPercent> Basic Damage and Skill Power for <buffDuration> seconds. This can happen to each Hero once every <increaseCooldown> seconds.
POWER_BENEVOLENCE_DELTA=+<increaseBdSpPercent> Basic Damage and Skill Power
SPEED_BENEVOLENCE=Speed Benevolence
SPEED_BENEVOLENCE_DESCRIPTION=Buffs and Heals from this Hero also grant <increaseSpeedPercent> Movement and Attack Speed for <buffDuration> seconds. This can happen to each Hero once every <increaseCooldown> seconds.
SPEED_BENEVOLENCE_DELTA=+<increaseSpeedPercent> Movement and Attack Speed
PRECISION_BENEVOLENCE=Precision Benevolence
PRECISION_BENEVOLENCE_DESCRIPTION=Buffs and Heals from this Hero also grant Precise for <preciseDuration> seconds.
PRECISION_BENEVOLENCE_DELTA=+<preciseDuration> seconds
BLINDING_ATTACKS=Blinding Attacks
BLINDING_ATTACKS_DESCRIPTION=Basic Attacks from this Hero apply Blind to enemies struck for <blindDuration> seconds.
BLINDING_ATTACKS_DELTA=+<blindDuration> seconds
CLOAKING_ATTACKS=Cloaking Attacks
CLOAKING_ATTACKS_DESCRIPTION=Every <attackAmt> Basic Attacks, this Hero gains Invisibility for <invisDuration> seconds.
CLOAKING_ATTACKS_DELTA=+<invisDuration> seconds
FRENZIED_VENGEANCE=Frenzied Vengeance
FRENZIED_VENGEANCE_DESCRIPTION=When this Hero falls below <healthPercent> of their Max HP, they Cleanse themself and go Berserk for <berserkDuration> seconds. While this Hero is Berserk, if an enemy is KO'd, this Hero is Healed up to <healPercent> of their Max HP. This can happen once every <berserkCooldown> seconds.
FRENZIED_VENGEANCE_DELTA=+<healPercent> Healing
INVINCIBLE_RETRIBUTION=Invincible Retribution
INVINCIBLE_RETRIBUTION_DESCRIPTION=Once per wave when this Hero falls below <healthPercent> of their Max HP, they become Invincible for <invincibleDuration> seconds. When this happens, other allies gain <increaseBdSpPercent> Basic Damage and Skill Power for the rest of the wave. These Basic Damage and Skill Power Increases cannot be Removed.
INVINCIBLE_RETRIBUTION_DELTA=+<increaseBdSpPercent> Basic Damage and Skill Power
REFLECTIVE_REFUGE=Reflective Refuge
REFLECTIVE_REFUGE_DESCRIPTION=When this Hero falls below <healthPercent> of their Max HP, they gain Reflect for <reflectDuration> seconds and are Healed for <healPercent> of their Max HP. This can happen once per <reflectCooldown> seconds.
REFLECTIVE_REFUGE_DELTA=+<reflectDuration> seconds
REFLECTION_WEAKEN=Reflection Weaken
REFLECTION_WEAKEN_DESCRIPTION=When this Hero would damage or Debuff enemies with Reflect, that Reflect is Removed and those enemies gain <weakAmt> stacks of Weakness for <weakDuration> seconds. This can happen to each enemy once every <weakCooldown> seconds.
REFLECTION_WEAKEN_DELTA=+<weakAmt> Stacks of Weakness
EXTREME_ACCURACY=Extreme Accuracy
EXTREME_ACCURACY_DESCRIPTION=When this Hero triggers Precise, targets have their Tenacity Reduced by <tenacityReducePercent> and are Sapped for <debuffDuration> seconds. Invisible targets also have their Invisibility Removed.
EXTREME_ACCURACY_DELTA=+<tenacityReducePercent> Tenacity Reduction
HAUNT=Haunt
HAUNT_DESCRIPTION=When this Hero gains Invisibility, all enemies are Sapped and Cursed for <sapCurseDuration> seconds. This can happen once every <sapCurseCooldown> seconds. While Invisible, this Hero deals <increasedDamagePercent> Increased Damage to enemies below <healthPercent> of their Max HP.
HAUNT_DELTA=+<increasedDamagePercent> Increased Damage
INVINCIBLE_MOMENTUM=Invincible Momentum
INVINCIBLE_MOMENTUM_DESCRIPTION=While Invincible, Basic Attacks from this Hero deal an additional <trueDamagePercent> of their Max HP as True Damage. When this Hero loses Invincibility, all enemies are Stunned for <stunDuration> seconds. This can happen once every <stunCooldown> seconds.
INVINCIBLE_MOMENTUM_DELTA=+<trueDamagePercent> True Damage
ENABLING_SHIELD=Enabling Shield
ENABLING_SHIELD_DESCRIPTION=While Shielded, this Hero is Immune to Disables. When a Disable would be applied, this Hero instead gains <shieldPercent> of their Max HP as a Shield for <shieldDuration> seconds. This can happen once every <shieldCooldown> seconds.\n\nDisables include Stun, Freeze, Blind, Silence, and Charm.
ENABLING_SHIELD_DELTA=+<shieldPercent> Shielding
DEVASTATING_BLOWS=Devastating Blows
DEVASTATING_BLOWS_DESCRIPTION=When this Hero damages Shielded enemies, those enemies lose all Shielding and are Shattered and Pierced for <shatterPierceDuration> seconds. This can happen once every <shatterPierceCooldown> seconds.
DEVASTATING_BLOWS_DELTA=+<shatterPierceDuration> seconds
SHREWD_STRIKES=Shrewd Strikes
SHREWD_STRIKES_DESCRIPTION=Damage from this Hero ignores <ignorePercent> of enemy Damage Reduction.
SHREWD_STRIKES_DELTA=+<ignorePercent> Reduction Ignored
CORRUPTED_DOSE=Corrupted Dose
CORRUPTED_DOSE_DESCRIPTION=When this Hero damages an enemy who had been Healed within the last <healRecencyTime> seconds, that enemy is Cursed for <curseDuration> seconds.|If enemies are Healed while Cursed, they take <trueDamagePercent> of their Max HP as True Damage. Each enemy can be damaged this way once every <damageCooldown> seconds.
CORRUPTED_DOSE_DELTA=+<trueDamagePercent> True Damage
BOUNTIFUL_GROWTH=Bountiful Growth
BOUNTIFUL_GROWTH_DESCRIPTION=This Hero is Immune to Reductions in Max HP. Once per wave, when this Hero benefits from Heal over Time for <goalDuration> total seconds, they gain <growthPercent> Max HP and continue Healing for <healPercent> of their Max HP each second for the rest of the wave. These Buffs cannot be Removed.
BOUNTIFUL_GROWTH_DELTA=+<growthPercent> Max HP
FREEZE_FRACTURE=Freeze Fracture
FREEZE_FRACTURE_DESCRIPTION=When this Hero Freezes enemies, those enemies are also Shattered for <shatterDuration> seconds.|When enemies Frozen by any source remain Frozen for <goalDuration> seconds, those enemies take <fantasticDamagePercent> of their Max HP as Fantastic Damage. Each enemy can take damage this way once every <damageCooldown> seconds.
FREEZE_FRACTURE_DELTA=+<fantasticDamagePercent> Fantastic Damage
AUGMENTED_STUN=Augmented Stun
AUGMENTED_STUN_DESCRIPTION=Stuns from this Hero Reduce enemy Tenacity by <tenacityReducePercent>, and prevent enemies from being Cleansed for their duration. Enemies Stunned by this Hero also gain <weakAmt> stacks of Weakness for <weakDuration> seconds.
AUGMENTED_STUN_DELTA=+<weakAmt> stacks of Weakness
DEVIOUS_PLOT=Devious Plot
DEVIOUS_PLOT_DESCRIPTION=This Hero starts combat Invisible for <initInvisDuration> seconds. Each time an enemy is KO'd, this Hero gains <increaseBdSpPercent> Basic Damage and Skill Power for the rest of the wave, and gains Invisibility for <koInvisDuration> seconds.
DEVIOUS_PLOT_DELTA=+<increaseBdSpPercent> Basic Damage and Skill Power
ATTENTIVE_HONING=Attentive Honing
ATTENTIVE_HONING_DESCRIPTION=This Hero is Immune to Distract. This Hero favors an enemy players choose at the start of each wave. When this Hero uses "<skill1>", players can choose a new favored enemy. If on Auto, this Hero chooses the enemy with the least HP.|When this Hero damages the favored enemy, <trueDamagePercent> of that damage is converted into True Damage.
ATTENTIVE_HONING_DELTA=+<trueDamagePercent> True Damage
EXHAUSTING_ATTACKS=Exhausting Attacks
EXHAUSTING_ATTACKS_DESCRIPTION=Basic Attacks from this Hero Remove <removeBuffAmt> random Buffs from targets hit, and apply <fatigueAmt> stacks of Fatigue. While Fatigued from any source, enemies deal <reduceDmgDealtPercent> less damage.
EXHAUSTING_ATTACKS_DELTA=+<reduceDmgDealtPercent> Damage Reduction
FORTIFYING_CLEANSE=Fortifying Cleanse
FORTIFYING_CLEANSE_DESCRIPTION=Cleanses from this Hero also grant <hardyAmt> stacks of Hardy. Each Hero can gain Hardy this way once every <hardyCooldown> seconds. While this Hero or allies benefit from Hardy, they take <reduceDmgTakenPercent> Reduced Damage.
FORTIFYING_CLEANSE_DELTA=+<reduceDmgTakenPercent> Damage Reduction
INVINCIBLE_REJUVENATION=Invincible Rejuvenation
INVINCIBLE_REJUVENATION_DESCRIPTION=When this Hero loses their last stacks of Hardy or Fatigue, they become Immune to Debuffs and gain Invincibility for <invincibleDuration> seconds. During this time, this Hero Heals for <healPercent> of their Max HP each second. This can happen once every <invincibleCooldown> seconds.
INVINCIBLE_REJUVENATION_DELTA=+<healPercent> Healing
FRUITFUL_REVENGE=Fruitful Revenge
FRUITFUL_REVENGE_DESCRIPTION=When this Hero is KO'd, all of their allies get Cleansed and Heal for <healPercent> of their Max HP. The enemy responsible for the KO has all of their Hardy Stacks removed, gains <weaknessStackAmt> stacks of Weakness, and becomes Hexed for <weaknessHexDuration> seconds. These Weakness and Hex effects cannot be removed by Cleanse.| This Talent triggers once per wave and can only happen when this Hero has at least one surviving ally.
FRUITFUL_REVENGE_DELTA=+<healPercent> Healing
TIRELESS=Tireless
TIRELESS_DESCRIPTION=This Hero and all allies are Immune to Fatigue. When enemies would apply stacks of Fatigue, they instead lose <removeBuffAmt> random Buffs. This can happen to each enemy once every second.
TIRELESS_DELTA=+<removeBuffAmt> Buffs Removed
TENDERIZE=Tenderize
TENDERIZE_DESCRIPTION=When this Hero Heals or Buffs allies, all enemies lose <removeHardyAmt> stacks of Hardy. For each stack of Hardy Removed this way, enemies also lose a Random Buff.
TENDERIZE_DELTA=+<removeHardyAmt> Stacks Removed
LACERATE=Lacerate
LACERATE_DESCRIPTION=When this Hero deals non-Damage Over Time damage, they also deal <bonusDmgPercent> of that damage as additional Damage Over Time across the next <debuffDuration> seconds.|When this Hero deals Damage Over Time, the damage is increased by <dotAmplifyPercent>, stretched across <dotAmplifyPercent> more time. Each time enemies suffer from Damage Over Time, they also lose <reduceSpeedPercent> Movement and Attack Speed for <debuffDuration> seconds.
LACERATE_DELTA=+<dotAmplifyPercent> Damage and Duration
ALLURING_LOYALTY=Alluring Loyalty
ALLURING_LOYALTY_DESCRIPTION=Charms from this Hero cannot be Cleansed.|When this Hero Heals or Buffs allies, the enemy with the highest Basic Damage is Charmed for <charmDuration> seconds. This can happen once every <charmCooldown> seconds.|While any enemy is Charmed by any source, this Hero, all allies, and Charmed enemies gain <increaseSpeedPercent> Movement and Attack Speed.
ALLURING_LOYALTY_DELTA=+<increaseSpeedPercent> Movement and Attack Speed
