
PATCH_TAB=Patch
PATCH_POWER=Patch Power:
MULTIPLIER=Multiplier:
PATCH_LEVEL=Patch Level:
POWER_PROGRESSION=Patch Power Progress:
PATCH_POWER_DESC=Patch many Heroes to increase your Patch Power! Patch Power multiplies the Core Stats granted by Patch Levels, and sets your Max Patch Level.
FROM_PATCH_POWER=From Patch Power:
FROM_PATCH_LEVEL=From Patch Level:
PATCH_ESSENCE=Patch Essence
COLLECT_HERE=Collect here:
TRIALS=Trials
DIAMOND_CRATE=Diamond Crate
MAX_HP=Max HP
BASIC_DAMAGE=Basic Damage
SKILL_POWER=Skill Power
ARMOR=Armor
REALITY=Reality
UPGRADE_WINDOW_SUBTITLE=New Core Stats
UPGRADE_CONFIRM_WINDOW_TITLE=Upgrade
UPGRADED_WINDOW_TITLE=Hero Upgraded
BONUS=Bonus
PATCH_TALENT_PAGE_LOCKED=You will learn this talent at patch level [#f2dd52ff]%1$d[].
PATCH_TALENT_PAGE_UNLOCKED=Next level of this talent will be available at patch level [#f2dd52ff]%1$d[].
PATCH_TALENT_PAGE_MAX=The max level of this talent has been reached.
PATCH_TALENTS=Patch Talents:
HEROES=(%1$s Heroes)
MERGE_DESC=Merge Trial is a Franchise Trial featuring 2-3 Franchises
MAJOR_DESC=This is a Franchise Trial featuring 1 Franchise.
UNITY_DESC=Unity Trial is a Franchise Trial, showcasing all of this season's Featured Franchises.
FEATURED_FRANCHISES=Featured Franchises:
PATCH_SORT_POWER_MILESTONE=Gain [#f2dd52ff]%1$s[] more Patch Levels to reach Patch Power [#f2dd52ff]%2$s[]!
PATCH_POWER_GAINED=Patch Power increased!
