
SELF_BOOST=<stat>: <amt>
SELF_BOOST_PER_ALLY_ROLE=<stat> per <role> Role Hero: <amt>
SELF_BOOST_PER_ALLY_COLOR=<stat> per <team> Team Hero: <amt>
ALLY_ROLE_BOOST=<stat> to <role> Role Heroes: <amt>
ALLY_COLOR_BOOST=<stat> to <team> Team Heroes: <amt>
EFFECT_ENERGIZED=Energized: <amt> Energy on each Basic Attack for <duration> seconds
EFFECT_ATTACK_SPEED=Attack Speed: <amt> Attack Speed for <duration> seconds.
EFFECT_ATTACK_MOVE_SPEED=Attack and Move Speed: <amt> Speed for <duration> seconds.
EFFECT_SELF_HOT=Heal Over Time: <amt> of Max HP Healed over <duration> seconds.
EFFECT_TEAM_HOT=Team Heal Over Time: <amt> of Max HP Healed for Heroes over <duration> seconds.
EFFECT_SELF_SHIELD=Shield: <amt> of Max HP becomes a Shield that lasts <duration> seconds.
EFFECT_TEAM_SHIELD=Team Shield: <amt> of Max HP becomes a Shield for Heroes that lasts <duration> seconds.
EFFECT_ENERGY_GAIN=Energy Gain: <amt> Energy Gained
EFFECT_SELF_HEAL=Heal: <amt> of Max HP Healed
EFFECT_TEAM_HEAL=Team Heal: <amt> of Max HP Healed for Allies
EFFECT_NORMAL_CRIT=Normal Crit: <amt> Normal Crit
EFFECT_FANTASTIC_CRIT=Fantastic Crit: <amt> Fantastic Crit
EFFECT_ARMOR_NEGATION=Armor Negation: <amt> Armor Negation
EFFECT_REALITY_NEGATION=Reality Negation: <amt> Reality Negation
EFFECT_CRIT_DAMAGE=Crit Damage: <amt> Crit Damage
EFFECT_TENACITY=Tenacity: <amt> Tenacity
EFFECT_EVASION=Evasion: <amt> Evasion
EFFECT_HARDY=Hardy: <amt> Stacks of Hardy
EFFECT_REFLECT=Reflect: <duration> seconds of Reflect
EFFECT_INVISIBILITY=Invisibility: <duration> seconds of Invisibility
EFFECT_INVINCIBILITY=Invincibility: <duration> seconds of Invincibility
EFFECT_PRECISE=Precise: <duration> seconds of Precise
EFFECT_BERSERK=Berserk: <duration> seconds of Berserk
TRIGGER_ALLY_KO_AMOUNT=%1$s or more allies get KO'd.
TRIGGER_BASIC_ATTACK_AMOUNT=Heroes perform %1$s or more Basic Attacks.
TRIGGER_BLIND_AMOUNT=Blind is applied to %1$s enemies.
TRIGGER_CHARM_AMOUNT=Charm is applied to %1$s enemies.
TRIGGER_CURSE_AMOUNT=Curse is applied to %1$s enemies.
TRIGGER_DOT_AMOUNT=Damage over Time is applied to %1$s enemies.
TRIGGER_FATIGUE_AMOUNT=%1$s stacks of Fatigue are applied to enemies.
TRIGGER_FROZEN_AMOUNT=Frozen is applied to %1$s enemies.
TRIGGER_HARDY_AMOUNT=%1$s stacks of Hardy are applied to heroes.
TRIGGER_INVINCIBLE_AMOUNT=Invincible is applied to %1$s heroes.
TRIGGER_KNOCK_BACK_AMOUNT=%1$s enemies are knocked back.
TRIGGER_PERCENT_MAX_HP=Any hero reaches %1$s% of their Max HP.
TRIGGER_REFLECT_AMOUNT=Reflect is applied to %1$s heroes.
TRIGGER_SAP_AMOUNT=Sap is applied to %1$s enemies.
TRIGGER_SCARE_AMOUNT=Scare is applied to %1$s enemies.
TRIGGER_SHIELD_AMOUNT=Shield is applied to %1$s heroes.
TRIGGER_SILENCE_AMOUNT=Silence is applied to %1$s enemies.
TRIGGER_SKILL1_AMOUNT=Heroes use their White skill %1$s times.
TRIGGER_SKILL2_AMOUNT=Heroes use their Green skill %1$s times.
TRIGGER_SKILL3_AMOUNT=Heroes use their Blue skill %1$s times.
TRIGGER_STUDY_AMOUNT=Study is applied to %1$s enemies.
TRIGGER_STUN_AMOUNT=Stun is applied to %1$s enemies.
TRIGGER_TIME=%1$s seconds of combat have elapsed.
TRIGGER_SLOW_AMOUNT=Slow is applied to %1$s enemies.
TRIGGER_INVISIBLE_AMOUNT=Invisible is applied to %1$s heroes.
TRIGGER_WEAKNESS_AMOUNT=Weakness is applied to %1$s heroes.
TRIGGER_PIERCE_AMOUNT=Pierce is applied to %1$s enemies.
TRIGGER_SHATTER_AMOUNT=Shatter is applied to %1$s enemies.
