
STAGE_NUMBER=Stage: [#f2dd52ff]%1$d[]
START_PRIZE_WALL=Start
RESET_PRIZE_WALL=Next
GRAND_PRIZE_HEADER=Grand Prize
CHEST_CONTAINS=Chest Contains:
GRAND_PRIZE_MAX_INFO=Prizes have reached maximum Rewards!
GRAND_PRIZE_REWARD_INFO=These are the possible Grand Prize rewards!
GRAND_PRIZE_REWARD_SPLIT=or
GRAND_PRIZE_PROGRESS=Prizes upgrade at stage [#f2dd52ff]%1$d[]
MORE_CREDITS_HEADER=More Tokens
DAILY_QUESTS_COMPLETE=All Daily Quests Complete!
DAILY_QUESTS_INFO=Complete more quests to earn more tokens!
VIEW_QUESTS=View Quests
VIEW_DEALS=View Deals
FALLBACK_EVENT_NAME=Prize Wall
DAILY_QUESTS_TITLE=Prize Wall Daily Quests
REFRESHES_IN_HEADER=Refreshes in %1$s
SPECIAL_DEALS_TITLE=Special Deals!
DAILY_QUEST_COMPLETE=This quest has already been completed for the Day
GRAND_PRIZE_INFO=Find the Grand Prize to reset the wall and improve future Grand Prizes!
DEALS_IN_STOCK=In Stock: %1$d
PRIZE_WALL_HAS_NOT_STARTED=This event has not started yet
PRIZE_WALL_HERO_QUESTS=Hero Quests
PRIZE_WALL_REFRESHES_REMAINING=Refreshes Remaining: %1$d
