
com.perblue.heroes.daily_30=30 Day Deal
com.perblue.heroes.daily_90=90 Day Deal
com.perblue.heroes.daily_180=180 Day Deal
com.perblue.heroes.daily_360=360 Day Deal
com.perblue.heroes.daily_mega_30=30 Day Mega Deal
com.perblue.heroes.daily_mega_90=90 Day Mega Deal
com.perblue.heroes.daily_mega_180=180 Day Mega Deal
com.perblue.heroes.daily_mega_360=360 Day Mega Deal
com.perblue.heroes.diamonds1=Fistful of Diamonds
com.perblue.heroes.diamonds2=Pouch of Diamonds
com.perblue.heroes.diamonds6=Sack of Diamonds
com.perblue.heroes.diamonds3=Box of Diamonds
com.perblue.heroes.diamonds7=Shipment of Diamonds
com.perblue.heroes.diamonds4=Chest of Diamonds
com.perblue.heroes.diamonds5=Motherlode of Diamonds
com.perblue.heroes.first_diamonds1=Special Fistful of Diamonds
com.perblue.heroes.first_diamonds2=Special Pouch of Diamonds
com.perblue.heroes.first_diamonds6=Special Sack of Diamonds
com.perblue.heroes.first_diamonds3=Special Box of Diamonds
com.perblue.heroes.first_diamonds7=Special Shipment of Diamonds
com.perblue.heroes.first_diamonds4=Special Chest of Diamonds
com.perblue.heroes.first_diamonds5=Special Motherlode of Diamonds
com.perblue.heroes.dash_deal=Dash Deal
com.perblue.heroes.nonstacking_1a=Special Offer
com.perblue.heroes.nonstacking_1b=Special Offer
com.perblue.heroes.nonstacking_1c=Special Offer
com.perblue.heroes.nonstacking_3a=Special Offer
com.perblue.heroes.nonstacking_3b=Special Offer
com.perblue.heroes.nonstacking_3c=Special Offer
com.perblue.heroes.nonstacking_5a=Special Offer
com.perblue.heroes.nonstacking_5b=Special Offer
com.perblue.heroes.nonstacking_5c=Special Offer
com.perblue.heroes.nonstacking_7a=Special Offer
com.perblue.heroes.nonstacking_7b=Special Offer
com.perblue.heroes.nonstacking_7c=Special Offer
com.perblue.heroes.nonstacking_10a=Special Offer
com.perblue.heroes.nonstacking_10b=Special Offer
com.perblue.heroes.nonstacking_10c=Special Offer
com.perblue.heroes.nonstacking_20a=Special Offer
com.perblue.heroes.nonstacking_20b=Special Offer
com.perblue.heroes.nonstacking_20c=Special Offer
com.perblue.heroes.nonstacking_30a=Special Offer
com.perblue.heroes.nonstacking_30b=Special Offer
com.perblue.heroes.nonstacking_30c=Special Offer
com.perblue.heroes.nonstacking_50a=Special Offer
com.perblue.heroes.nonstacking_50b=Special Offer
com.perblue.heroes.nonstacking_50c=Special Offer
com.perblue.heroes.nonstacking_70a=Special Offer
com.perblue.heroes.nonstacking_70b=Special Offer
com.perblue.heroes.nonstacking_70c=Special Offer
com.perblue.heroes.nonstacking_100a=Special Offer
com.perblue.heroes.nonstacking_100b=Special Offer
com.perblue.heroes.nonstacking_100c=Special Offer
com.perblue.heroes.diamonds8=Box of Diamonds
com.perblue.heroes.diamonds9=Shipment of Diamonds
com.perblue.heroes.battle_pass=Diamond Quest : Premium Pass
com.perblue.heroes.nonstacking_15a=Special Offer
com.perblue.heroes.nonstacking_15b=Special Offer
com.perblue.heroes.nonstacking_15c=Special Offer
com.perblue.heroes.nonstacking_35a=Special Offer
com.perblue.heroes.nonstacking_35b=Special Offer
com.perblue.heroes.nonstacking_35c=Special Offer
