
VIP_LEVEL=Level:
SEE_BENEFITS=Benefits
TITLE_PURCHASING_SCREEN=Diamonds
DAYS_LEFT=Days Left
RENEW=Renew
FEW_DAYS_LEFT=Only {#ffff00}%1$d days{} left!
EVERY_DAY=%1$d Every Day!
DAILY_DEAL_RENEW_INFO=Renew when there are %1$d days left.
GET_DIAMONDS=Get Diamonds
VIP_LEVEL_TITLE=Level [orange]%1$d[]
NEW_FEATURES=New Features
DAILY_PERKS=Daily Perks
BONUS_DIAMONDS=Bonus Diamonds
VIP_BONUS_DIAMONDS_FORMAT={#ffe00f}%1$s{} for every 100 VIP Rings you earn from purchases
VIP_PROGRESS_BAR_LABEL=%1$s / %2$s VIP Rings
SEE_DEALS=See Deals
MONTHLY_DEALS_TITLE=Daily Deals
MEGA_MONTHLY_DEALS_TITLE=Mega Daily Deals
VIP_BENEFITS_TITLE=VIP Benefits
VIEW_DEALS=View Deals
ONE_TIME_OFFER=One Time Offer!
MAXED=Maxed
BONUS_DIAMONDS_SPELLED_OUT={#ffe00f}%1$s{} diamonds for every 100 VIP Rings you earn
MONTHLY_CARD_INFO=Lots of Diamonds and VIP Rings with purchase!
STARTING_PURCHASE=Starting Purchase
IAP_ERROR_PURCHASE_IN_PROGRESS=Error: Purchase in Progress
IAP_ERROR_SERVICE_DOWN=Error: Purchasing Service Down
APPLE_USER_CAN_NOT_PURCHASE=Error: Apple User Unable to Make Purchase
APPLE_COULD_NOT_FIND_PRODUCT=Error: Apple Cannot Find Product
GENERIC_COULD_NOT_FIND_PRODUCT=Error: Could not find product on store
PURCHASING_NOT_SET_UP=Error: Purchasing not initialized
CONNECT_GOOGLE_TO_PURCHASE=You need to log in to your Google Play account to make a purchase.
SALE_EXCLAMATION=Sale!
IOS_PURCHASING_UPGRADE=Purchasing is no longer supported on iOS 6. Please update to iOS 7 or 8.
PURCHASE_COMPLETE=Purchase Complete!
COMPLETING_PURCHASE=Completing purchase...
TAPJOY_TITLE=Tapjoy
TAPJOY_INFO=Complete offers to earn free diamonds!
TAPJOY_BUTTON=View Offers
FYBER_TITLE=Fyber
FYBER_INFO=Complete offers to earn free diamonds!
FYBER_BUTTON=View Offers
IRONSOURCE_TITLE=ironSource
OFFERS_NOT_IMPLEMENTED=These offers are not currently available.
PURCHASING_MONTHLY_DIAMONDS_INSTANTLY=instantly
PURCHASING_MONTHLY_DIAMONDS_DAILY_DIAMONDS=Every Day
PURCHASING_MONTHLY_DIAMONDS_TOTAL=Total!
VIP_FEATURE_SILVER_CHEST_GENERATION=Reduced Gold Crate Cooldown
VIP_FEATURE_SILVER_CHEST_REMOVE_COOLDOWN=No Gold Crate Cooldown
VIP_FEATURE_TEAM_TRIALS_COOLDOWN=Reduced Trials Cooldown
VIP_FEATURE_PORT_COOLDOWN=Reduced Port Cooldown
VIP_FEATURE_STARTING_HERO_LEVEL=Heroes Start at Level {#ffe00f}%1$s{}
VIP_FEATURE_FRIENDSHIP_DAILY_QUEST_FRIEND_XP_AMOUNT={#ffe00f}%1$s{} Friend XP from Friend Quests
VIP_FEATURE_SKILL_POINT_STORAGE={#ffe00f}%1$s{} Skill Point Cap
VIP_FEATURE_FIGHT_PIT_CHANCES_PER_RESET={#ffe00f}%1$s{} Arena Attacks
VIP_FEATURE_COLISEUM_CHANCES_PER_RESET={#ffe00f}%1$s{} Coliseum Attacks
VIP_FEATURE_DAILY_GOLD_BUYS=Get More Gold {#ffe00f}%1$sx{}
VIP_FEATURE_DAILY_STAMINA_BUYS=Get More Stamina {#ffe00f}%1$sx{}
VIP_FEATURE_FREE_STAMINA_HOURS=Collect Stamina Quests: {#ffe00f}%1$s{} Hours
VIP_FEATURE_FREE_STAMINA_AMOUNT={#ffe00f}+%1$s%%{} Stamina from Daily Stamina Quests
VIP_FEATURE_DAILY_RAID_TICKETS={#ffe00f}%1$s{} Free Raid Tickets
VIP_FEATURE_BUY_SKILL_POINTS=Reset Skill Points
VIP_FEATURE_DAILY_ELITE_RESETS=Reset Elite Campaign {#ffe00f}%1$sx{}
VIP_FEATURE_FAST_FORWARD=Enhanced Fast Forward & Auto
VIP_FEATURE_CLEAR_FIGHT_PIT_COOLDOWN=Skip Arena Cooldown with
VIP_FEATURE_CLEAR_COLISEUM_COOLDOWN=Skip Coliseum Cooldown with
VIP_FEATURE_DAILY_FIGHT_PIT_RESETS=Reset Arena {#ffe00f}%1$sx{}
VIP_FEATURE_DAILY_COLISEUM_RESETS=Reset Coliseum {#ffe00f}%1$sx{}
VIP_FEATURE_VIP_CHAT=VIP Chat
VIP_FEATURE_RAID_10=Multi-Raiding
VIP_FEATURE_RAID_PORT=Raid Port
VIP_FEATURE_RAID_TEAM_TRIALS=Raid Team Trials
VIP_FEATURE_QUICK_PROMOTE=Power Promote
VIP_FEATURE_CRYPT_TOKEN_BONUS_PERCENT={#ffe00f}+%1$s%%{} Tokens from Creep Surge
VIP_FEATURE_CRYPT_GOLD_BONUS_PERCENT={#ffe00f}+%1$s%%{} Gold from Creep Surge
VIP_FEATURE_GUILD_CHECK_IN_GOLD_BONUS_PERCENT={#ffe00f}+%1$s%%{} Gold from Guild Check-in
VIP_FEATURE_GUILD_CHECK_IN_HERO_XP_BONUS_PERCENT={#ffe00f}+%1$s%%{} Hero XP from Guild Check-in
VIP_FEATURE_REINFECTION_GEAR_JUICE_BONUS_PERCENT={#ffe00f}+%1$s%%{} Disk Power from Infected Fights
VIP_FEATURE_EXPEDITION_TOKEN_BONUS_PERCENT={#ffe00f}+%1$s%%{} Tokens from City Watch
VIP_FEATURE_EXPEDITION_GOLD_BONUS_PERCENT={#ffe00f}+%1$s%%{} Gold from City Watch
VIP_FEATURE_USE_SOUL_CHEST=VIP Crate
VIP_FEATURE_EXPEDITION_GEAR_JUICE_BONUS_PERCENT={#ffe00f}+%1$s%%{} Disk Power from City Watch
VIP_FEATURE_MERCENARY_SOCIAL_BUCKS_BONUS_PERCENT={#ffe00f}+%1$s%%{} Guild Coins from Mercs
VIP_FEATURE_GUILD_CHECK_IN_SOCIAL_BUCKS_BONUS_PERCENT={#ffe00f}+%1$s%%{} Guild Coins from Guild Check-in
VIP_FEATURE_GUILD_CHECK_IN_STAMINA_BONUS_PERCENT={#ffe00f}+%1$s%%{} Stamina from Guild Check-in
VIP_FEATURE_STAMINA_STORAGE={#ffe00f}+%1$s%%{} Extra Stamina Storage
VIP_FEATURE_DAILY_FREE_MERCHANT_RESETS=Free Market Resets {#ffe00f}%1$sx{}
VIP_FEATURE_GOLD_BUY_MIN_MULT=Min {#ffe00f}%1$sx{} from Get More Gold
VIP_FEATURE_GUILD_CHECK_IN_DIAMOND_BONUS_PERCENT={#ffe00f}+%1$s%%{} Diamonds from Guild Check-in
VIP_FEATURE_FRIENDSHIP_MISSION_GEAR_JUICE_BONUS_PERCENT={#ffe00f}+%1$s%%{} Disk Power from Missions
VIP_FEATURE_EXTRA_CHEST_ITEMS=Extra Item from Crates
VIP_FEATURE_DAILY_PORT_RESETS=Reset Port {#ffe00f}%1$sx{}
VIP_FEATURE_DAILY_TEAM_TRIALS_RESETS=Reset Team Trials {#ffe00f}%1$sx{}
VIP_FEATURE_EXPEDITION_EXTRA_RAID_TICKETS={#ffe00f}+%1$s{} Raid Tickets from City Watch
VIP_FEATURE_HEIST_TOKEN_BONUS_PERCENT={#ffe00f}+%1$s%%{} Tokens from Heist
VIP_FEATURE_DAILY_VIDEO_FOR_VIP=Daily Video Skip {#ffe00f}%1$sx{}
VIP_FEATURE_OPEN_VIDEO_CRATE=Instantly Open Video Crates
VIP_FEATURE_REMOVE_COLISEUM_ATTACK_COOLDOWN=Remove Coliseum Cooldown
VIP_FEATURE_DOUBLE_PORT_REWARDS=Double Port Rewards
VIP_FEATURE_REMOVE_PORTS_COOLDOWN=Remove Ports Cooldown
VIP_FEATURE_REMOVE_TRIALS_COOLDOWN=Remove Trials Cooldown
VIP_FEATURE_SKILL_POINT_COST_FREE=Skills less than level {#ffe00f}%1$s{} do not cost Skill Points
VIP_FEATURE_RAID_ALL_CHAPTERS=Raid All Chapter Nodes
VIP_FEATURE_MASS_LEVEL_UP=Mass level up
PROMOTED_PURCHASE_FINISH_TUTORIAL=It looks like you'd like to purchase the Incredible Dash Deal. Please finish the tutorial first.
PROMOTED_PURCHASE_FINISHED_TUTORIAL=You can now purchase the Incredible Dash Deal. Open the events window now!
PROMOTED_PURCHASE_EXPIRED=We're sorry, but your Incredible Dash Deal has already expired.
DASH_DEAL_COMPLETED_PURCHASE=Purchase Complete! Check your mailbox for rewards.
OFFERS_SURVEYS=Offers and Surveys
THEOREM_TITLE=TheoremReach
THEOREM_INFO=Complete surveys to earn free diamonds!
THEOREM_BUTTON=View Surveys
PLAYBACK_REWARDS_TITLE=Playback Rewards
PLAYBACK_REWARDS_INFO=Complete offers to earn free diamonds!
PLAYBACK_REWARDS_BUTTON=View Offers
PLAYBACK_REWARDS_TOOLTIP=For every 5 diamonds earned, get rewarded an additional 1 VIP ring!
SURVEYS=Surveys
VIP_LEVEL_OFFER=LEVEL
VIP_FEATURE_CRYPT_RAID_TICKETS_PER_BATTLE={#ffe00f}%1$s{} Raid Tickets from Creep Surge
VIP_FEATURE_MAX_CRYPT_RAIDS_PER_MEMBER={#ffe00f}%1$s{} Max Raids per Creep Surge
VIP_FEATURE_QUICK_CRAFT=Quick Craft Badges
VIP_FEATURE_POWER_CRAFT=Power Craft Badges
VIP_FEATURE_AUTO_ENHANCE_MAX=Auto Enhance Max
DIAMONDS_EVERY_DAY=Diamonds Every Day!
DIAMONDS_DAILY=Get %1$s diamonds daily!
RECEIVE=Receive
INSTANTLY=instantly
RECEIVE_BONUS_INSTANTLY=Receive an instant bonus:
TOTAL_BONUS_DIAMONDS=%1$s total
PLUS_BONUS_ON_PURCHASE=Plus bonus diamonds and VIP rings with purchase!
STARTS_AT=Starts at: %1$s
VIP_FEATURE_RAID_WITHOUT_TICKETS=Raiding no longer costs Raid Tickets!
OUT_OF_RAID_TICKETS=Out of Raid Tickets
BUY_DAILY_DEAL=Buy the {#ffe00f}Daily Deal{} to get VIP %1$s and Unlock {#ffe00f}%2$s{}!
BUY_MEGA_DAILY_DEAL=Buy the {#ffe00f}Mega Daily Deal{} to get VIP %1$s and Unlock {#ffe00f}%2$s{}!
GET_DAILY_DEAL=Get Daily Deal
UNLIMITED_RAIDING=Unlimited Raid Tickets
UNLOCK_MULTI_RAID=Unlock Multi-Raid
WITH_PURCHASE_DETAIL=*with ANY purchase. One time only!
INSTANT_BONUSES=Instant Bonuses:
PURCHASED_REWARDS=Rewards!
DELAYED_PURCHASE_MESSAGE=Please wait, your purchased items will be delivered shortly.
DELAYED_PURCHASE_SUCCESS=Your purchased items have arrived!  Please check your mailbox.
PURCHASE_REWARDS_INFO_BTN=The VIP Rings displayed are auto added to your total at purchase so we can calculate any VIP Bonus Diamond rewards in your mailbox. Any purchase bonuses are also sent to your mailbox.
VIP_FEATURE_MAX_MISSIONS_BONUS={#ffe00f}+%1$s{} Max Missions
VIP_FEATURE_MAX_MISSION_AWAY_TIME=Mission Away Time {#ffe00f}%1$s{}
VIP_FEATURE_DISKS_START_UNLOCKED=Disks start unlocked
VIP_FEATURE_SKIP_FRIEND_EPISODES=Friendship Campaign: Skip {#ffe00f}1{} Episode
VIP_FEATURE_SKIP_FRIEND_STAGES=Friendship Campaign: Skip {#ffe00f}%1$s{} Stage(s) per Episode
VIP_FEATURE_FRIENDSHIP_CAMPAIGN_LOOT_MULT=Friendship Campaign: Loot {#ffe00f}%1$sx{}
VIP_FEATURE_CODEBASE_COOLDOWN=Reduced Codebase Cooldown
VIP_FEATURE_REMOVE_CODEBASE_COOLDOWN=Remove Codebase Cooldown
VIP_FEATURE_USE_WISH_CHEST=Wish Crate
VIP_FEATURE_QUICKFIGHT_WITHOUT_TAX=Quick Fight Tax Removed
