
SORT_PLAYER_TOTAL_POWER=Total Power
SORT_PLAYER_TEAM_POWER=Team Power
SORT_PLAYER_TOTAL_STARS=Total Stars
SORT_PLAYER_FIGHT_PIT=Arena
SORT_PLAYER_COLISEUM=Coliseum
SORT_PLAYER_LEGACY_FIGHT_PIT=Arena: Legacy
SORT_PLAYER_LEGACY_COLISEUM=Coliseum: Legacy
SORT_GUILD_TOTAL_POWER=Total Power
SORT_GUILD_TEAM_POWER=Team Power
SORT_GULD_TOTAL_STARS=Total Stars
SORT_MY_RANK=My Rank
SORT_TOP_100=Top 100
SORT_MY_GUILD=My Guild
CANT_JOIN_GUILD=Reach Team Level %1$d to join a guild!
JOIN_A_GUILD=Join a Guild!
GUILD_MEMBERS_FORMAT=%3$s%1$,d{} / %2$,d Members
SCORE_HEADING=Score
NA_RANK=n/a
ARENA_POWER_HEADING=Power
SORT_GUILD=Guild
SORT_PLAYER=Player
N_A=N/A
RANKING_RANK_TWOLINES=Rank\n%1$s
RANKING_RANK=Rank %1$s
RANKING_RANK_RANGE=Rank %1$s-%2$s
RANKING_TOP_TWOLINES=Top\n%1$s
RANKING_TOP=Top %1$s
NO_RANKED_PLAYERS=There are currently no ranked players.  Reach Team Level %1$s to be ranked!
NO_RANKED_FIGHT_PIT_PLAYERS=There are currently no ranked players.  Arena unlocks at Team Level %1$s!
NO_RANKED_COLISEUM_PLAYERS=There are currently no ranked players.  Coliseum unlocks at Team Level %1$s!
NO_RANKED_GUILDS=There are currently no ranked Guilds.  Reach Team Level %1$s to create or join a Guild
LAST_SEASON=Last Season
LAST_X_SEASONS=Last %1$d Seasons
ALL_TIME=All Time
SUBJECT_HEADER=Subject:
TYPE_HEADER=Type:
VIEW_HEADER=View:
