
DIAMONDS=Diamonds
DIAMONDS_DESCRIPTION=Use diamonds to buy gold, stamina, and more!
GOLD=Gold
GOLD_DESCRIPTION=Use gold to upgrade your heroes' skills, buy new items, and more!
STAMINA=Stamina
STAMINA_DESCRIPTION=Use stamina to battle and raid in the campaign!
TEAM_XP=Team XP
TEAM_XP_DESCRIPTION=Team XP increases your team level, which unlocks new features!
SKILL_POINTS=Skill Points
SKILL_POINTS_DESCRIPTION=Spend skill points to level up your heroes' skills!
VIP_TICKETS=VIP Rings
VIP_TICKETS_DESCRIPTION=VIP rings increase your VIP level!
SILVER_CHEST=Gold Crate
SILVER_CHEST_DESCRIPTION=Open crates to receive items!
GOLD_CHEST=Diamond Crate
GOLD_CHEST_DESCRIPTION=Open crates to receive items!
SOCIAL_CHEST=Guild Chest
SOCIAL_CHEST_DESCRIPTION=Open crates to receive items!
SOUL_CHEST=VIP Crate
SOUL_CHEST_DESCRIPTION=Open crates to receive items!
FIGHT_TOKENS=Arena Tokens
FIGHT_TOKENS_DESCRIPTION=Use arena tokens to purchase items from the Arena shop!
FREE_DIAMONDS=Diamonds
FREE_DIAMONDS_DESCRIPTION=Use diamonds to buy gold, stamina, and more!
PAID_DIAMONDS=Diamonds
PAID_DIAMONDS_DESCRIPTION=Use diamonds to buy gold, stamina, and more!
EXPEDITION_TOKENS=City Watch Tokens
EXPEDITION_TOKENS_DESCRIPTION=Use City Watch tokens to buy items from the City Watch shop!
CRYPT_TOKENS=Surge Tokens
CRYPT_TOKENS_DESCRIPTION=Use Surge tokens to buy items from the Surge shop!
COLISEUM_TOKENS=Coliseum Tokens
COLISEUM_TOKENS_DESCRIPTION=Use Coliseum tokens to buy items from the Coliseum shop!
FRIEND_XP=Friend XP
FRIEND_XP_DESCRIPTION=Use friend XP to level up your friendships!
FRIEND_STAMINA=Friend Stamina
FRIEND_STAMINA_DESCRIPTION=Use friend stamina to progress through friend campaigns!
GEAR_JUICE=Disk Power
GEAR_JUICE_DESCRIPTION=Use disk power to level up memory disks!
SOCIAL_BUCKS=Guild Coins
SOCIAL_BUCKS_DESCRIPTION=Use guild coins to buy guild crates!
GUILD_INFLUENCE=Guild Influence
GUILD_INFLUENCE_DESCRIPTION=Use guild influence to upgrade guild perks.
HEIST_TICKETS=Heist Ticket
HEIST_TICKETS_DESCRIPTION=Use a Heist Ticket to join a Heist!
HEIST_TOKENS=Grime Medals
HEIST_TOKENS_DESCRIPTION=Use Grime Medals on the Limited-Time Captain Grime Crate!
MEMORY_TOKENS=Memory Tokens
MEMORY_TOKENS_DESCRIPTION=Use Memory Tokens to buy items from the Memory Market!
WAR_TOKENS=War Tokens
WAR_TOKENS_DESCRIPTION=Use War Tokens to buy items from the War Shop!
CHALLENGE_TOKENS=Challenge Tokens
CHALLENGE_TOKENS_DESCRIPTION=Use Challenge Tokens to buy items from the Challenge Shop!
MOD_POWER=Mod Power
MOD_POWER_DESCRIPTION=Use Mod Power to Level Up your Mods!
GEAR_TOKENS=Badge Tokens
GEAR_TOKENS_DESCRIPTION=Use Badge Tokens to buy items from the Badge Bazaar!
INVASION_STAMINA=Invasion Stamina
INVASION_STAMINA_DESCRIPTION=Use Invasion Stamina to fight off the Invasion. Invasion Stamina is reset each Invasion.
BREAKER=Breakers
BREAKER_DESCRIPTION=Use Breakers to fight Invasion Bosses. Get more Breakers in the Breaker Quest.
BOSS_TECH=Boss Tech
BOSS_TECH_DESCRIPTION=Use Boss Tech to buy items from the Invasion Shop!
INVASION_POINTS=Invasion Points
INVASION_POINTS_DESCRIPTION=Unlock new rewards in the Invasion as you collect more Invasion Points.
MASTERY_TOKENS=Mastery Tokens
MASTERY_TOKENS_DESCRIPTION=Use Mastery Tokens to buy avatar items from the Hero Mastery Shop!
GUILD_CONTEST_POINTS=Guild Contest Tokens
GUILD_CONTEST_POINTS_DESCRIPTION=Earn Guild Contest Tokens from Guild Contests and use them to unlock exclusive Guild Perks!
CITY_WATCH_EPIC_KEYS=Epic City Watch Key
CITY_WATCH_EPIC_KEYS_DESCRIPTION=Use to start an Epic City Watch.
CITY_WATCH_RESETS=Reset City Watch
CITY_WATCH_RESETS_DESCRIPTION=Use to start a new City Watch.
QUEST_POINTS=Quest Points
QUEST_POINTS_DESCRIPTION=Earn quest points to earn rewards in Diamond Quest!
COLISEUM_KEYS=Coliseum Keys
COLISEUM_KEYS_DESCRIPTION=Use Coliseum Keys to unlock fights against other Challengers
FIGHT_PIT_KEYS=Arena Keys
FIGHT_PIT_KEYS_DESCRIPTION=Use Arena Keys to unlock fights against other Challengers
COSMETIC_COLLECTION_POINTS=Cosmetic Points
COSMETIC_COLLECTION_POINTS_DESCRIPTION=Used to level up Cosmetic Rewards Level
COMP_COSMETIC_POINTS=Cosmetic Points
COMP_COSMETIC_POINTS_DESCRIPTION=Used to level up Cosmetic Rewards Level
PRIZE_TOKENS=Prize Wall Tokens
PRIZE_TOKENS_DESCRIPTION=Use Prize Wall Tokens to earn rewards from the Prize Wall Event
