
CHAT_JOIN_GUILD=joined guild.
KICKED_GUILD_MESSAGE=was kicked from your guild by %1$s.
LEFT_GUILD_MESSAGE=left your guild.
DEMOTED_GUILD_MESSAGE=demoted %1$s to %2$s.
PROMOTED_GUILD_MESSAGE=promoted %1$s to %2$s.
HERO_CHAT_INITIAL_CHAT=No one has posted yet! Share your strategies and comments on this hero!
YOU_ARE_CHAT_SILENCED=You are currently chat silenced.
PERBLUE_SUPPORT=PerBlue Support
