
COMMUNITY_HEADING=Community
SUPPORT_BUTTON=Support
FORUMS_BUTTON=Forums
WHATS_NEW_BUTTON=What's New
PLAYER_HEADING=Player
STATS_HEADING=Stats
ACCOUNTS_BUTTON=Accounts
SETTINGS_BUTTON=Settings
OPTIONS_HEADING=Options
TEAM_LEVEL_FORMAT=Team Level: {#3ec07b}%1$s{}
MAX_TEAM_LEVEL_FORMAT=Max Team Level: {#3ec07b}%1$s{}
ACCOUNT_ID_FORMAT=Account ID: {#3ec07b}%1$s{}
SERVER_FORMAT=Server: {#3ec07b}(%1$d) %2$s{}
VIP_LEVEL_FORMAT=VIP Level: {i} {#3ec07b}%1$s{}
CURRENT_MAX_LEVEL=Max Level (for now!)
VERSION_FORMAT=Client Version: {#3ec07b}%1$s{}
BLOCKED_LIST=Blocked List
CHOOSE_LANGUAGE_TITLE=Choose Language
SUPPORT_INFO=Welcome to Disney Heroes support!
SUPPORT_QUICK_HELP=Quick Help
SUPPORT_BUGS=Bugs & Suggestions
SUPPORT_CUSTOMER_SERVICE=Customer Service
SUPPORT_BUTTON_FAQ=FAQs
SUPPORT_BUTTON_ACCOUNTS=Account Recovery
SUPPORT_BUTTON_BUG=Report A Bug
SUPPORT_BUTTON_IDEA=Share an Idea
SUPPORT_BUTTON_PAYMENT=Payment Issues
SUPPORT_BUTTON_REPORT=Report Player
SUPPORT_BUTTON_OTHER=Other Issues
SUPPORT_BUTTON_TICKETS=My Tickets
SWITCH_ON=ON
SWITCH_OFF=OFF
CHAT_PREVIEWS=Chat Previews / Chat Red Dot
CHAT_GUILD=Guild
CHAT_VIP=VIP
CHAT_GUILD_WALL=Guild Wall
CHAT_GUILD_OFFICER=Guild Officers
CHAT_PERSONAL_MESSAGE=PM
CHAT_GLOBAL=Global
CHAT_HEIST=Heist
CHAT_WAR=War
CHAT_ANNOUNCEMENTS=Announcements
PERSONAL_MESSAGES=Private Chat / Friends
BLOCKED_LIST_FULL_BUTTON=View Blocked List
VIEW_BLOCKED_PLAYERS=View Your Blocked Players
MUSIC=Music
CHARACTER_EFFECTS=Character Effects
EVERYTHING_ELSE=Everything Else
SOUNDS=Sounds
PUSH_NOTIFICATIONS=Push Notifications
TIME_ZONE=Time Zone
CURRENT_TIME_ZONE=Current Time Zone: {#3ec07b}%1$s{}
UPDATE=Update
GUILD_PRIVATE_CHAT=Guild members need to be Friends to Private Chat.
GLOBAL_PRIVATE_CHAT=Other Players need to be Friends to Private Chat.
CHANGE_NAME_WINDOW_TITLE=What's your new name?
YOUR_NAME=Your Name
CHANGE_NAME_BUTTON=Change Name
NAME_TOO_SHORT=Name is too short.
NAME_TOO_LONG=Name is too long.
NAME_IS_INVALID=Name contains invalid characters or reserved words.
TOO_SHORT=Too Short
TOO_LONG=Too Long
NAME_INVALID_CHARACTERS=Invalid Characters
NAME_OK=Ok
CONFIRM_NAME=Confirm
CHANGE_YOUR_NAME=change your name
RANDOM_BUTTON=Random
UPDATE_TIME_ZONE_TITLE=Update Time Zone
OLD_TIME_ZONE_PREFIX=Old Time Zone:
NEW_TIME_ZONE_PREFIX=New Time Zone:
SHORT_TIME_ZONE_FORMAT=GMT%1$s
TIME_ZONE_UPDATE_INFO=You can update your time zone every 30 days.
TIME_ZONE_MATCHES=Your game time zone matches your device's time zone.
TIME_ZONE_WAIT_TIME=You can update your time zone again in %1$d days.
BLOCKED_LIST_TITLE=Blocked List
NO_USERS_CURRENTLY_BLOCKED=You do not have any users blocked. Tap a user in chat and select "block" to block them.
UNBLOCKED_BUTTON=Unblocked
UNBLOCK_BUTTON=Unblock
CHOOSE_AVATAR_TITLE=Choose Avatar
SPECIAL_AVATARS=Special Avatars
STARTING_HERO_AVATARS=Starting Hero Avatars
PURPLE_HERO_AVATARS=Hero Avatars
COLLECTION_AVATARS=Collection Avatars
HERO_SKILL_AVATARS=Hero Skill Avatars
AVATAR_ITEMS_FORMAT=%1$s%2$s{} Badge Avatars
PLAYER_AVATAR_WINDOW_INFO=Unlock more avatars by opening cosmetic crates from events!
GUILD_AVATAR_WINDOW_INFO=Unlock more emblems by upgrading Guild Perks to reach a higher guild level!
GUILD_AVATAR_HEADING=Guild Level %1$d Emblems
ALL_SOUND=All Sound
FORCE_TOUCH_HEADING=3D Touch
FORCE_TOUCH_BUTTON=View Info
PM_LIST_PERMISSION=Players can send you friend requests from Rankings and Guild Member lists.
PM_SETTING_CHANGE=This change may take awhile to take effect. If someone is having problems messaging you, they may have to restart the app.
CHANGE_TIMEZONE_CONFIRMATION=Are you sure you want to change your timezone? This could affect your ability to collect rewards from features like Daily Sign-In, etc.
CHANGE_TIMEZONE_TITLE=Change timezone?
PARENT_CONTROLS=Parental Controls
CHAT_BLOCK_TOGGLE=Chat Block
INPUT_PIN_UNLOCK=Please input your 4-digit numeric pin to unlock chat.
INPUT_PIN_LOCK=Please set a 4-digit numeric pin to block chat.
SET_PIN=Set Pin
NUMERIC_ONLY=Please enter numerical digits only.
INVALID_PIN=Please choose a pin that contains more than one number.
CONTEST_EMBLEMS=Guild Contest Emblems
OTHER=Other
MAIN_SCREEN_SIDEBAR=Sidebar stays open on the main menu.
POWER_CRAFT_NEEDED_BUTTON=Needed button considers Power Crafting
CONFIRMATION_POPUPS=Confirmation Popups
RESET_CONFIRMATION_TOGGLES=Reset all "Don't Ask Again" toggles
MAX_SKILLS_INCLUDE_RED=Add Red Skill cost to +MAX
VFX_INTENSITY=Reduce the intensity of VFX on some screens.
CHAT_CHANNELS=Chat Channels
SHOW_GLOBAL_CHAT=Show Global Chat
SHOW_VIP_CHAT=Show VIP Chat
SHOW_MAX_STAT_WARNING=Show Max Stat Warnings for Subclasses
ALTERNATE_HERO_AVATARS=Alternate Hero Avatars
DISCORD_BUTTON=Discord
VIP_BUTTON=VIP
AUTO_CHANGE_RG=Automatically Change Lineup Memory Disks
AUTO_CHANGE_EMERALD_SLOT=Automatically Change Lineup Stat Slots
PATCH_NOTES_BUTTON=Patch Notes
HIDE_DAMAGE_VALUES=Hide Damage Values
HIDE_VFX=Hide Visual Effects
