
DESC_TESTING=Testing Server
DESC_NONE=
DESC_AMERICAS=Americas
DESC_EURASIA=Eurasia, Africa & Australia
1=Number One Dime
2=You Can Fly!
3=Triton's Trident
4=Sugar Rush
5=Cursed Coin
6=Notre Dinner Bell
7=Safety Helmet
8=Last Resort
9=Stone Guardian
10=Sorcerer's Hat
11=Black Cauldron
12=Kimmunicator
13=Escape Plan
14=Raspbeary Cake
15=Deus Ex Calibur
16=Jewel of Atlantis
17=Golden Flower
18=Chief's Stone
19=Sliver of Hope
20=Stylin' Penguin
21=Close Shave
22=Mysterious Journal
23=Ukulele
24=Pixie Dust
25=Space Adventure
26=Locked Door
27=Irresistibly Shiny
28=Tiny Terrarium
29=Sweeter Tooth
30=Garden Song
31=Happy Pancake
32=Unicorn Dreams
33=Rocket Pop
34=Tsumdere
35=Sun Crown
36=New Car Smell
37=Polka Dots
38=Infinity Sided Die
39=Bullies are Gross
40=Token of Raditude
