
SIGNIN_WINDOW_TITLE=Daily Sign-in
MISSING_SIGN_IN_HERO_INFO=This month's hero is not yet available, so we've put diamonds on those days. We'll retroactively award Hero Chips once the hero becomes available.
SIGNIN_INFO_DETAILS=Sign in to earn rewards. VIP players earn 2x rewards on certain days! Daily sign-in rewards reset at 5:00AM each day. Missed rewards can't be reclaimed.
SIGNIN_GET_AT_X_ATTENDANCES=Receive this award on your %1$s sign-in this month!
SIGNIN_NORMAL_TAGLINE=Sign in every day for a new reward! The {#ffe00f}more{} you sign in, the {#ffe00f}better{} the rewards!
SIGNIN_VIP_REQ_TAGLINE=Earn {#ffe00f}2x{} rewards with VIP %1$d!
GET_VIP=Get VIP
HERO_TO_STONE_CONVERSION_FORMAT=%1$s is already on your team. We'll give you {#ffe00f}%2$d Hero Chips{} instead!
SIGNIN_TODAYS_REWARD=Today's Reward
SIGNIN_VIP_MET_TAGLINE={#ffe00f}%1$dx{} rewards today!
THIS_MONTH_HEADING=This Month
NEW_USER_MORE_REWARDS=More rewards coming at the beginning of next month!
