
STAT_GROUP_HEADING_CORE=Core Stats
STAT_GROUP_HEADING_OTHER=Other Stats
STAT_REQUIRED_LEVEL=Requires Level
STAT_SALE_PRICE=Sale Price
STAT_EXP_GIVEN=XP Given
STAT_ENCHANT_POINTS=Enchant Energy
STAT_POWER=Power
STAT_BASIC_DAMAGE=Basic Damage
STAT_SKILL_POWER=Skill Power
STAT_HP_MAX=Max HP
STAT_ENERGY_MAX=Max Energy
STAT_HP_REGEN=Hp Regen
STAT_ENERGY_REGEN=Energy Regen
STAT_ENERGY_STARTING=Starting Energy
STAT_ARMOR=Armor
STAT_REALITY=Reality
STAT_ARMOR_NEGATION=Armor Negation
STAT_REALITY_NEGATION=Reality Negation
STAT_NORMAL_CRIT=Normal Crit
STAT_FANTASTIC_CRIT=Fantastic Crit
STAT_NORMAL_CRIT_NEGATION=Normal Crit Negation
STAT_FANTASTIC_CRIT_NEGATION=Fantastic Crit Negation
STAT_TENACITY=Tenacity
STAT_EVASION=Evasion
STAT_CONSERVATION=Conservation
STAT_IMPROVED_HEALING=Improved Healing
STAT_COOLDOWN_REDUCTION=Cooldown Reduction
STAT_BONUS_BASIC_DAMAGE=Bonus Basic Damage
STAT_ATTACK_SPEED_SCALAR=Attack Speed
STAT_MOVEMENT_SPEED_SCALAR=Movement Speed
STAT_DISABLE_LENGTH_SCALAR=Disable Length
STAT_STUN_LENGTH_SCALAR=Stun Length
STAT_SILENCE_LENGTH_SCALAR=Silence Length Scalar
STAT_SHIELD_SIZE_SCALAR=Shield HP
STAT_SHIELD_SIZE_ADDER=Shield Size Adder
STAT_SHIELD_LENGTH_SCALAR=Shield Length
STAT_NORMAL_DAMAGE_DONE_SCALAR=Normal Damage Done
STAT_FANTASTIC_DAMAGE_DONE_SCALAR=Fantastic Damage Done
STAT_ALL_DAMAGE_DONE_SCALAR=All Damage Done
STAT_NORMAL_DAMAGE_TAKEN_SCALAR=Normal Damage Taken Scalar
STAT_FANTASTIC_DAMAGE_TAKEN_SCALAR=Fantastic Damage Taken Scalar
STAT_ALL_DAMAGE_TAKEN_SCALAR=All Damage Taken Scalar
STAT_ENERGY_GAIN_SCALAR=Energy Gain
STAT_DAMAGE_REDUCTION=Damage Reduction
STAT_LIFE_STEAL=Life Steal
STAT_DODGE=Dodge
STAT_NORMAL_PROWESS=Normal Prowess
STAT_FANTASTIC_PROWESS=Fantastic Prowess
STAT_CRIT_DAMAGE=Crit Damage
STAT_AMBITION=Ambition
STAT_STAT_LEVEL_MODIFIER=Level Modifier
STAT_DEFENSE_LEVEL_MODIFIER=Defense Level Modifier
STAT_WHITE_SKILL_MODIFIER=White Skill Modifier
STAT_GREEN_SKILL_MODIFIER=Green Skill Modifier
STAT_BLUE_SKILL_MODIFIER=Blue Skill Modifier
STAT_PURPLE_SKILL_MODIFIER=Purple Skill Modifier
STAT_RED_SKILL_MODIFIER=Red Skill Modifier
STAT_GEAR_LEVEL_MODIFIER=Real Gear Level Modifier
STAT_FURY=Fury
STAT_MOVEMENT_SPEED_SCALAR_STRENGTH=Movement Speed Scalar Strength
STAT_ATTACK_SPEED_SCALAR_STRENGTH=Attack Speed Scalar Strength
STAT_MOVEMENT_SPEED_DEBUFF_SCALAR_STRENGTH=Movement Speed Debuff Scalar Strength
STAT_ATTACK_SPEED_DEBUFF_SCALAR_STRENGTH=Attack Speed Debuff Scalar Strength
STAT_TRUE_DAMAGE_DONE_SCALAR=True Damage Done Scalar
STAT_ADDITIONAL_CRIT_CHANCE=Additional Crit Chance
STAT_STUDY_LENGTH_SCALAR=Study Length Scalar
STAT_COOLDOWN_DELAY=Cooldown Delay
