
STARTER_CHALLENGES_TITLE=Starter
STARTER_CHALLENGES_DESC=A series of 5 relatively easy challenges for beginners.
WEEKLY_CHALLENGES_SUMMER_2018_TITLE=Weekly
WEEKLY_CHALLENGES_SUMMER_2018_DESC=All Weekly Challenges, past and present.
CITY_PATROL_TITLE=City Patrol
CITY_PATROL_DESC=Keep the City safe by completing these 5 City Watch challenges.
ON_A_MISSION_TITLE=On a Mission
ON_A_MISSION_DESC=Master this set of 5 Friend Mission challenges.
SURGE_OF_POWER_TITLE=Surge of Power
SURGE_OF_POWER_DESC=Finish this set of 5 Creep Surge challenges and feel the power!
THE_ULTIMATE_CHALLENGE_TITLE=The Ultimate Challenge
THE_ULTIMATE_CHALLENGE_DESC=Beat this set of 5 difficult challenges for the ultimate accomplishment.
PICK_EM_CHALLENGES_TITLE=Pick 'Em
PICK_EM_CHALLENGES_DESC=All Pick 'Em challenges, past and present.
