
CHAPTER_2=Chapter 2
CHAPTER_3=Chapter 3
CHAPTER_4=Chapter 4
CHAPTER_5=Chapter 5
CHAPTER_6=Chapter 6
CHAPTER_7=Chapter 7
CHAPTER_8=Chapter 8
CHAPTER_9=Chapter 9
CHAPTER_10=Chapter 10
CHAPTER_11=Chapter 11
CHAPTER_12=Chapter 12
CHAPTER_13=Chapter 13
CHAPTER_14=Chapter 14
CHAPTER_15=Chapter 15
CHAPTER_16=Chapter 16
CHAPTER_17=Chapter 17
CHAPTER_18=Chapter 18
CHAPTER_19=Chapter 19
CHAPTER_20=Chapter 20
CHAPTER_21=Chapter 21
CHAPTER_22=Chapter 22
CHAPTER_23=Chapter 23
CHAPTER_24=Chapter 24
CHAPTER_25=Chapter 25
CHAPTER_26=Chapter 26
CHAPTER_27=Chapter 27
CHAPTER_28=Chapter 28
CHAPTER_29=Chapter 29
CHAPTER_30=Chapter 30
CHAPTER_31=Chapter 31
CHAPTER_32=Chapter 32
CHAPTER_33=Chapter 33
CHAPTER_34=Chapter 34
CHAPTER_35=Chapter 35
CHAPTER_36=Chapter 36
CHAPTER_37=Chapter 37
CHAPTER_38=Chapter 38
CHAPTER_39=Chapter 39
CHAPTER_40=Chapter 40
CHAPTER_41=Chapter 41
CHAPTER_42=Chapter 42
CHAPTER_43=Chapter 43
SKILL_UPGRADE=Skill Upgrade
FIGHT_PIT=Arena
ELITE_CAMPAIGN=Elite Campaign
ALCHEMY=Buy More Gold
ENCHANTING=Enhancement
WORLD_CHANNEL=Global Chat
TEAM_TRIALS=Team Trials
TEAM_TRIALS_2=Team Trials: Medium
TEAM_TRIALS_3=Team Trials: Hard
TEAM_TRIALS_4=Team Trials: Very Hard
TEAM_TRIALS_5=Team Trials: Super Hard
TEAM_TRIALS_6=Team Trials: Insane
TEAM_TRIALS_7=Team Trials: Ridiculous
TEAM_TRIALS_8=Team Trials: Shocking
TEAM_TRIALS_9=Team Trials: Impossible
TEAM_TRIALS_10=Team Trials: Challenging
TEAM_TRIALS_11=Team Trials: Absurd
TEAM_TRIALS_12=Team Trials: Ludicrous
TEAM_TRIALS_13=Team Trials: Turn Back
TEAM_TRIALS_14=Team Trials: Hopeless
TEAM_TRIALS_15=Team Trials: Unpossible
TEAM_TRIALS_16=Team Trials: Strenuous
TEAM_TRIALS_17=Team Trials: Unbeatable
TEAM_TRIALS_18=Team Trials: Preposterous
TEAM_TRIALS_19=Team Trials: Never Been Done
TEAM_TRIALS_20=Team Trials: Daunting
TEAM_TRIALS_21=Team Trials: Inconceivable
TEAM_TRIALS_22=Team Trials: Outrageous
TEAM_TRIALS_23=Team Trials: Uncanny
TEAM_TRIALS_24=Team Trials: Sisyphean
TEAM_TRIALS_25=Team Trials: Surreal
TEAM_TRIALS_26=Team Trials: Foolhardy
TEAM_TRIALS_27=Team Trials: Mind Bending
TEAM_TRIALS_28=Team Trials: Tyrannical
TEAM_TRIALS_29=Team Trials: Try Hard
TEAM_TRIALS_30=Team Trials: Warp Speed
TEAM_TRIALS_31=Team Trials: Get Good
TEAM_TRIALS_32=Team Trials: Non-Euclidean
TEAM_TRIALS_33=Team Trials: Moonshot
TEAM_TRIALS_34=Team Trials: Infinitesimal
TEAM_TRIALS_35=Team Trials: Extinction-Level Event
TEAM_TRIALS_39=Team Trials: Git Gud
TEAM_TRIALS_40=Team Trials: Impassible
TEAM_TRIALS_41=Team Trials: Unfair
TEAM_TRIALS_42=Team Trials: Mega Hard
TEAM_TRIALS_43=Team Trials: Vicious
TEAM_TRIALS_44=Team Trials: Monumental
TEAM_TRIALS_45=Team Trials: Frightening
TEAM_TRIALS_46=Team Trials: Scary
TEAM_TRIALS_47=Team Trials: Unreal
TEAM_TRIALS_48=Team Trials: Heroic
TEAM_TRIALS_49=Team Trials: Gutsy
TEAM_TRIALS_50=Team Trials: Fearless
TEAM_TRIALS_51=Team Trials: Cruel
TEAM_TRIALS_52=Team Trials: Ppppffft.
TEAM_TRIALS_53=Team Trials: Cursed
TEAM_TRIALS_54=Team Trials: Overpowered
TEAM_TRIALS_55=Team Trials: Tumultuous
TEAM_TRIALS_56=Team Trials: Yikes
TEAM_TRIALS_57=Team Trials: Bonkers
TEAM_TRIALS_58=Team Trials: Eesh
TEAM_TRIALS_59=Team Trials: Please Don't
TEAM_TRIALS_60=Team Trials: Regrettable
TEAM_TRIALS_61=Team Trials: Unspeakable
TEAM_TRIALS_62=Team Trials: Grim
TEAM_TRIALS_63=Team Trials: Pyrrhic
TEAM_TRIALS_64=Team Trials: Outlandish
TEAM_TRIALS_65=Team Trials: Exhausting
TEAM_TRIALS_66=Team Trials: Merciless
TEAM_TRIALS_67=Team Trials: Bedraggling
TEAM_TRIALS_68=Team Trials: Sleep-Depriving
TEAM_TRIALS_69=Team Trials: Beastly
TEAM_TRIALS_70=Team Trials: Polarizing
TEAM_TRIALS_71=Team Trials: Demoralizing
TEAM_TRIALS_72=Team Trials: Distressing
TEAM_TRIALS_73=Team Trials: Onerous
TEAM_TRIALS_74=Team Trials: Fatiguing
TEAM_TRIALS_75=Team Trials: Paradoxical
TEAM_TRIALS_76=Team Trials: Unyielding
TEAM_TRIALS_77=Team Trials: Arduous
TEAM_TRIALS_78=Team Trials: Rigorous
TEAM_TRIALS_79=Team Trials: Intense
TEAM_TRIALS_80=Team Trials: Tremendous
TEAM_TRIALS_81=Team Trials: Formidable
TEAM_TRIALS_82=Team Trials: Prodigious
TEAM_TRIALS_83=Team Trials: Inexorable
TEAM_TRIALS_84=Team Trials: Insuperable
TEAM_TRIALS_85=Team Trials: Preeminent
TEAM_TRIALS_86=Team Trials: Impervious
TEAM_TRIALS_87=Team Trials: Unshakeable
TEAM_TRIALS_88=Team Trials: Resolute
TEAM_TRIALS_89=Team Trials: Inviolable
TEAM_TRIALS_90=Team Trials: Herculean
TEAM_TRIALS_91=Team Trials: Unflinching
EXPEDITION=City Watch
BLACK_MARKET=Black Market
GUILDS=Guilds
MEGA_MART=Mega Mart
PORT=The Port
PORT_2=The Port: Medium
PORT_3=The Port: Hard
PORT_4=The Port: Very Hard
PORT_5=The Port: Super Hard
PORT_6=The Port: Insane
PORT_7=The Port: Ridiculous
PORT_8=The Port: Shocking
PORT_9=The Port: Impossible
PORT_10=The Port: Challenging
PORT_11=The Port: Absurd
PORT_12=The Port: Ludicrous
PORT_13=The Port: Turn Back
PORT_14=The Port: Hopeless
PORT_15=The Port: Unpossible
PORT_16=The Port: Strenuous
PORT_17=The Port: Unbeatable
PORT_18=The Port: Preposterous
PORT_19=The Port: Never Been Done
PORT_20=The Port: Daunting
PORT_21=The Port: Inconceivable
PORT_22=The Port: Outrageous
PORT_23=The Port: Uncanny
PORT_24=The Port: Sisyphean
PORT_25=The Port: Surreal
PORT_26=The Port: Foolhardy
PORT_27=The Port: Mind Bending
PORT_28=The Port: Tyrannical
PORT_29=The Port: Try Hard
PORT_30=The Port: Warp Speed
PORT_31=The Port: Get Good
PORT_32=The Port: Non-Euclidean
PORT_33=The Port: Moonshot
PORT_34=The Port: Infinitesimal
PORT_35=The Port: Extinction-Level Event
PORT_39=The Port: Git Gud
PORT_40=The Port: Impassible
PORT_41=The Port: Unfair
PORT_42=The Port: Mega Hard
PORT_43=The Port: Vicious
PORT_44=The Port: Monumental
PORT_45=The Port: Frightening
PORT_46=The Port: Scary
PORT_47=The Port: Unreal
PORT_48=The Port: Heroic
PORT_49=The Port: Gutsy
PORT_50=The Port: Fearless
PORT_51=The Port: Cruel
PORT_52=The Port: Ppppffft.
PORT_53=The Port: Cursed
PORT_54=The Port: Overpowered
PORT_55=The Port: Tumultuous
PORT_56=The Port: Yikes
PORT_57=The Port: Bonkers
PORT_58=The Port: Eesh
PORT_59=The Port: Please Don't
PORT_60=The Port: Regrettable
PORT_61=The Port: Unspeakable
PORT_62=The Port: Grim
PORT_63=The Port: Pyrrhic
PORT_64=The Port: Outlandish
PORT_65=The Port: Exhausting
PORT_66=The Port: Merciless
PORT_67=The Port: Bedraggling
PORT_68=The Port: Sleep-Depriving
PORT_69=The Port: Beastly
PORT_70=The Port: Polarizing
PORT_71=The Port: Demoralizing
PORT_72=The Port: Distressing
PORT_73=The Port: Onerous
PORT_74=The Port: Fatiguing
PORT_75=The Port: Paradoxical
PORT_76=The Port: Unyielding
PORT_77=The Port: Arduous
PORT_78=The Port: Rigorous
PORT_79=The Port: Intense
PORT_80=The Port: Tremendous
PORT_81=The Port: Formidable
PORT_82=The Port: Prodigious
PORT_83=The Port: Inexorable
PORT_84=The Port: Insuperable
PORT_85=The Port: Preeminent
PORT_86=The Port: Impervious
PORT_87=The Port: Unshakeable
PORT_88=The Port: Resolute
PORT_89=The Port: Inviolable
PORT_90=The Port: Herculean
PORT_91=The Port: Unflinching
COLISEUM=Coliseum
TRADER=Market
RANKINGS=Rankings
CRYPT_RAID=Creep Surge
FAST_FORWARD=Fast Forward
FRIENDSHIPS=Friendships
SOCIAL_CHEST=Guild Crate
AUTO_FF_AB_TEST=Fast Forward
AUTO_FIGHT=Auto Fight
HEIST=Heist
AIRDROP=Air Drop
CHALLENGES=Challenges
VIDEO_CRATES=Video Crates
DAILY_VIDEOS=Daily Videos
WAR=Guild War
INTERSTITIALS=Interstitials
MODS=Mods
GEAR_MARKET=Badge Bazaar
INVASION=Invasion
MEMORY_MARKET=Memory Market
SAVED_LINEUPS=Saved Lineups
COLLECTIONS=Collections
BATTLE_PASS=Diamond Quest
SURGE_OBJECTIVES=Creep Surge Bonuses
MISSIONS=Missions
CODEBASE=The Codebase
SPOTLIGHT_TRIAL=Spotlight Trial
FRANCHISE_TRIALS=Franchise Trials
PATCHED_HEROES=Patched Heroes
WISH_CHEST=Wish Crate
