
RETIRE_AIRDROP_TITLE=Air Drop Retiring
RETIRE_AIRDROP_DESC=Thanks for purchasing Air Drop! We will be retiring this feature from Disney Heroes going forward, so we're giving you the rest of your Air Drop rewards right now.
VIDEOS_SCREEN_TITLE=Daily Videos
VIDEOS_SCREEN_TAG=Watch Videos for Raid Tickets and Perks
VIDEOS_SCREEN_TAG_NO_TICKETS=Watch Videos for Perks
VIDEOS_SCREEN_DISCLAIMER=Perks reset each day at 5am
VIDEOS_SCREEN_DISCLAIMER_FORMAT=Perks reset each day at %1$s
FAST_FORWARD_PERK=Fast Forward
AUTO_ANY_PERK=Auto Any
RAID_MODES_PERK=Raid Port & Trials
MULTI_RAID_PERK=Multi-Raid in Campaign
CLAIMED=Claimed!
HAVE_VIP_PERKS=All other perks come with VIP Level %1$d
WATCH_BUTTON=Watch
VIDEO_CRATE_TITLE=Video Crate
VIDEO_CRATE_FOUND_TITLE=Video Crate Found!
VIDEO_CRATE_NO_VIP=Watch an ad to open this Crate!
VIDEO_CRATE_WITH_VIP=Open this Crate for free rewards!
OPEN_NOW_BUTTON=Open Now
VIDEO_CRATE_TITLE_FULL=Full on Video Crates
VIDEO_CRATE_FULL=You can't hold any more Video Crates.
DOUBLE_REWARDS=Get 2x Rewards!
REWARDS_DOUBLED=Rewards\nDoubled
WATCH_NOW_BUTTON=Watch now!
WATCH_LATER_BUTTON=Watch later
WATCH_LATER_INFO_POPUP=Your Video Crate can be found in your Items. You can store up to 3 Video Crates.
OPEN_LATER_BUTTON=Open later
VIDEO_CARD_DESCRIPTION=Watch videos for raid tickets, diamonds and more!
VIDEO_CARD_BUTTON=View
UNLOCKED_RAID_MODES_PERK=Unlocked Raid Port & Trials
UNLOCKED_MULTI_RAID_PERK=Unlocked Multi-Raid in Campaign
WAR_END_OF_SEASON_REWARDS=End of Season Rewards
