
SUMMARY_BUILDING_VS=VS
SUMMARY_STATE_NOT_QUEUED=Protect Phase (Not in Queue)
SUMMARY_STATE_QUEUED=Protect Phase (Queued)
SUMMARY_STATE_PREP=Sabotage Phase
SUMMARY_STATE_ACTIVE=Battle Phase
SUMMARY_STATE_VICTORY=Victory
SUMMARY_STATE_DEFEAT=Defeat
SUMMARY_NEXT_WAR=Next War
SUMMARY_STATE_BYE=Bye
STARTS_IN_FORMAT=Ends in: %1$s
ENDS_IN_FORMAT=Ends in: %1$s
TOGGLE_WARS=Wars
TOGGLE_SEASONS=Seasons
WAR_BOXES_EMPTY=Rank up to earn more War Boxes!
WAR_BOX_TITLE=%1$s War Box
WAR_BOXES_HEADING=War Boxes
WAR_BOXES_HEADING_FORMAT=War Boxes:
WAR_BOXES_OPEN_BUTTON=Open
WAR_BOXES_LEFT_FORMAT=%1$s left
WAR_BOXES_CLAIM_FORMAT=Claim %1$s
WAR_RANK_LEAGUE_FORMAT=Rank: %1$s
LOG_TITLE=War Logs
LOG_FIRST_ATTACKS=First Attacks
LOG_EXTRA_ATTACK=Extra Attack
LOG_EXTRA_ATTACKS=Extra Attacks
LOG_WINS=Wins
LOG_LOSSES=Losses
LOG_CLEAN_SWEEPS=Clean Sweeps
LOG_INTACT_PLAYERS=Intact Players
LOG_SUMMARY=Summary
OUTCOME_ATTACKS=Normal Attacks: %1$s/%2$s
LOG_ATTACKS=Attacks
LOG_DEFENSES=Defenses
LOG_MEMBERS=Members
LOG_POWER=Power:
LOG_DEFENSES_EMPTY=No defenses have been made this war.
LOG_ATTACKS_EMPTY=No attacks have been made this war.
LOG_MEMBERS_EMPTY=No guild members have participated in this war.
LEAGUE_UNRANKED=Unranked
LEAGUE_COPPER=Copper
LEAGUE_BRONZE=Bronze
LEAGUE_SILVER=Silver
LEAGUE_GOLD=Gold
LEAGUE_PLATINUM=Platinum
LEAGUE_CHALLENGER=Challenger
LEAGUE_LEGENDARY=Legendary
TOP_GUILDS_BUTTON=Top Guilds
POSTER=Poster
NO_POSTER=No Poster
SEASON_STARTS_IN_HEADING=Season starts in:
SEASON_ENDS_IN_HEADING=Season ends in:
MMR=MMR
MMR_FORMAT=MMR: %1$s
QUEUED_INFO_LEAGUE_RANK_FORMAT=Rank: %1$s, %2$s
QUEUED_INFO_NEXT_WAR_FORMAT=Next War Starts in: %1$s
QUEUED_INFO_YOUR_LINEUP=Your Lineup
BATTLEFIELD_CURRENT_WAR=Current War
BATTLEFIELD_NEXT_WAR=Next War
BATTLEFIELD_PAST_WAR=Past War
AUTO_BUTTON=Auto
QUEUE_FOR_WAR=Queue for war?
REDUCE_ATTACKER_HP_FLAT=Boomer
REDUCE_ATTACKER_HP_FLAT_DESC=Reduces attacker HP
REDUCE_ATTACKER_HP_FLAT_DETAIL=Max HP of each attacker is reduced by %1$s or up to %2$s%% of the attacker's max HP
REDUCE_ATTACKER_BD_AND_SP_FLAT=Attack Ripper
REDUCE_ATTACKER_BD_AND_SP_FLAT_DESC=Reduces attacker damage and skill power
REDUCE_ATTACKER_BD_AND_SP_FLAT_DETAIL=Basic Damage and Skill Power of each attacker is reduced by %1$s
INCREASE_DEFENDER_ARMOR_FLAT=Mr. I Scream
INCREASE_DEFENDER_ARMOR_FLAT_DESC=Increases defender armor
INCREASE_DEFENDER_ARMOR_FLAT_DETAIL=Armor of each defender is increased by %1$s
INCREASE_DEFENDER_REALITY_FLAT=Tow Up
INCREASE_DEFENDER_REALITY_FLAT_DESC=Increases defender reality
INCREASE_DEFENDER_REALITY_FLAT_DETAIL=Reality of each defender is increased by %1$s
INCREASE_DEFENDER_SP_FLAT=Flaming Classic
INCREASE_DEFENDER_SP_FLAT_DESC=Increases defender skill power
INCREASE_DEFENDER_SP_FLAT_DETAIL=Skill Power of each defender is increased by %1$s
INCREASE_DEFENDER_BD_FLAT=Think Tank
INCREASE_DEFENDER_BD_FLAT_DESC=Increases defender basic damage
INCREASE_DEFENDER_BD_FLAT_DETAIL=Basic Damage of each defender is increased by %1$s
POINT_PER_CLEAN_SWEEP=Sharky
POINT_PER_CLEAN_SWEEP_DESC=Increases points per clean sweep
POINT_PER_CLEAN_SWEEP_DETAIL_PLURAL=Every attack that clears all three lineups in a single battle grants the attacking guild %1$s points
POINT_PER_CLEAN_SWEEP_DETAIL_SINGLE=Every attack that clears all three lineups in a single battle grants the attacking guild 1 point
POINT_PER_DEFENSE_WIN=Off Roader
POINT_PER_DEFENSE_WIN_DESC=Increases points per defense win
POINT_PER_DEFENSE_WIN_DETAIL_PLURAL=Every time a defending lineup is victorious, %1$s points are granted to the defending guild
POINT_PER_DEFENSE_WIN_DETAIL_SINGLE=Every time a defending lineup is victorious, 1 point is granted to the defending guild
POINT_PER_FULL_DEFENSE=Roller Diva
POINT_PER_FULL_DEFENSE_DESC=Increases points per clean defense
POINT_PER_FULL_DEFENSE_DETAIL_PLURAL=At the end of the war, the guild will receive %1$s points for each player with three undefeated lineups
POINT_PER_FULL_DEFENSE_DETAIL_SINGLE=At the end of the war, the guild will receive 1 point for each player with three undefeated lineups
CAR_TARGET_SWITCH_HEADING=Target?
CAR_REMAINING_PLAYERS_FORMAT=Remaining: %1$d/%2$d
CAR_EDIT_BUTTON=Edit
CAR_EMPTY_SLOT_HEADING=Slot %1$d
CAR_MOVE_ME_BUTTON=Move me here
CAR_MOVE_OTHERS_HERE_BUTTON=Move others here
CAR_ADD_SLOT_HEADING=Add a slot
CAR_ADD_SLOT_INFO=Add another lineup by upgrading your Guild Perks!
CAR_VIEW_PERKS_BUTTON=View Perks
CAR_ADD_DEFENDERS_BUTTON=Add Defenders
CLEAR_LINEUP_CONFIRM_TITLE=Clear Lineup?
CLEAR_LINEUP_CONFIRM_INFO=Are you sure you want to remove this lineup from this room?
SELECT_DEFENDER_TITLE=Select Defender
MOVE_BUTTON=Move
NOT_IN_ROOM=Not in room
SEASON_RANKINGS=Season Rankings
SABOTAGE=Sabotage
SABOTAGE_TITLE=Sabotage!
NO_RANKINGS_YET=No guilds have reached %1$s yet.
SABOTAGE_LINEUP_EMPTY=This lineup does not have any heroes.
SABOTAGE_DOES_NOT_AFFECT_HERO=This sabotage does not affect this hero.
TEAM_KOED=Team KO'ed
SABOTAGE_DESC_REDUCE_HP_PERCENT=-%1$s HP
SABOTAGE_DESC_REDUCE_BASIC_DAMAGE_PERCENT=-%1$s Basic Damage
SABOTAGE_DESC_REDUCE_SKILL_POWER_PERCENT=-%1$s Skill Power
SABOTAGE_DESC_REDUCE_ENERGY_GAIN_PERCENT=-%1$s Energy Gain Percent
SABOTAGE_DESC_DELAY_ARRIVAL=Arrival delayed by %1$s seconds
SABOTAGE_DESC_REDUCE_SPEED_PERCENT=-%1$s Movement Speed
SABOTAGE_DESC_REDUCE_F_CRIT_FLAT=-%1$s Fantastic Crit Chance
SABOTAGE_DESC_REDUCE_N_CRIT_FLAT=-%1$s Normal Crit Chance
SABOTAGE_DESC_REDUCE_ARMOR_PERCENT=-%1$s Armor
SABOTAGE_DESC_REDUCE_REALITY_PERCENT=-%1$s Reality
SABOTAGE_DESC_REDUCE_WHITE_LEVELS=White Skill Level -%1$s
SABOTAGE_DESC_REDUCE_GREEN_LEVELS=Green Skill Level -%1$s
SABOTAGE_DESC_REDUCE_BLUE_LEVELS=Blue Skill Level -%1$s
SABOTAGE_DESC_REDUCE_PURPLE_LEVELS=Purple Skill Level -%1$s
SABOTAGE_DESC_REDUCE_ARMOR_NEGATION_FLAT=-%1$s Armor Negation
SABOTAGE_DESC_REDUCE_REALITY_NEGATION_FLAT=-%1$s Reality Negation
SABOTAGE_DESC_HALF_DISK_STARS=-%1$s Memory Disk Stars
SABOTAGE_DESC_REDUCE_DISK_LEVELS=Memory Disk Level -%1$s
SABOTAGE_DESC_REDUCE_PATCH_LEVELS=Patch Level -%1$s
SABOTAGE_DESC_DISABLE_BATTLE_BADGE=Battle Badge Disabled
SABOTAGE_DESC_REDUCE_RED_LEVELS=Red Skill Level -%1$s
SABOTAGE_DESC_DISABLE_RED=Red Skill Disabled
SABOTAGE_DESC_DISABLE_REAL_GEAR=Memory Disk Disabled
SABOTAGE_DESC_REDUCE_EVASION=-%1$s Evasion
SABOTAGE_DESC_REDUCE_TENACITY=-%1$s Tenacity
SELECT_REWARD=Select a Reward!
START_BATTLE=Let's Battle!
NO_OFF_DUTY_HEROES=No banned heroes
OFF_DUTY_HEROES=Banned Heroes
HERO_TYPE_DISABLED=This hero is banned. Banned heroes can't be used in war today.
SABOTAGE_TYPES=Types
SABOTAGE_COST=Cost
SABOTAGE_DESC_LONG_REDUCE_HP_PERCENT=Reduces the target's HP
SABOTAGE_DESC_LONG_REDUCE_BASIC_DAMAGE_PERCENT=Reduces the target's basic damage
SABOTAGE_DESC_LONG_REDUCE_SKILL_POWER_PERCENT=Reduces the target's skill power
SABOTAGE_DESC_LONG_REDUCE_ENERGY_GAIN_PERCENT=Reduces the energy gained by the target
SABOTAGE_DESC_LONG_DELAY_ARRIVAL=Delays the arrival of the target
SABOTAGE_DESC_LONG_REDUCE_SPEED_PERCENT=Reduces the movement speed of the target
SABOTAGE_DESC_LONG_REDUCE_F_CRIT_FLAT=Reduces the target's fantastic crit chance
SABOTAGE_DESC_LONG_REDUCE_N_CRIT_FLAT=Reduces the target's normal crit chance
SABOTAGE_DESC_LONG_REDUCE_ARMOR_PERCENT=Reduces the target's armor
SABOTAGE_DESC_LONG_REDUCE_REALITY_PERCENT=Reduces the target's reality
SABOTAGE_DESC_LONG_REDUCE_WHITE_LEVELS=Reduces the level of the target's white skill
SABOTAGE_DESC_LONG_REDUCE_GREEN_LEVELS=Reduces the level of the target's green skill
SABOTAGE_DESC_LONG_REDUCE_BLUE_LEVELS=Reduces the level of the target's blue skill
SABOTAGE_DESC_LONG_REDUCE_PURPLE_LEVELS=Reduces the level of the target's purple skill
SABOTAGE_DESC_LONG_REDUCE_ARMOR_NEGATION_FLAT=Reduces the target's armor negation
SABOTAGE_DESC_LONG_REDUCE_REALITY_NEGATION_FLAT=Reduces the target's reality negation
SABOTAGE_DESC_LONG_HALF_DISK_STARS=Reduces the stars on the target's memory disk
SABOTAGE_DESC_LONG_REDUCE_DISK_LEVELS=Reduces the target's memory disk level
SABOTAGE_DESC_LONG_REDUCE_PATCH_LEVELS=Reduces the target's patch level
SABOTAGE_DESC_LONG_DISABLE_BATTLE_BADGE=Disables the target's battle badge
SABOTAGE_DESC_LONG_REDUCE_RED_LEVELS=Reduces the level of the target's red skill
SABOTAGE_DESC_LONG_DISABLE_RED=Disables the target's red skill
SABOTAGE_DESC_LONG_DISABLE_REAL_GEAR=Disables the target's memory disk
SABOTAGE_DESC_LONG_REDUCE_EVASION=Reduces the target's evasion
SABOTAGE_DESC_LONG_REDUCE_TENACITY=Reduces the target's tenacity
LINEUPS_DEFEATED=Lineups Defeated
ROOMS_DEFEATED=Rooms Defeated
DEFENSIVE_WINS=Defensive Wins
CLEAN_DEFENSES=Clean Defenses
OUTCOME_VICTORY=War Victory!
OUTCOME_DRAW=War Tied!
OUTCOME_DEFEAT=War Defeat!
OUTCOME_BYE=We could not find a match for your guild, so you automatically win.
OUTCOME_SCORING=Scoring
EXTRA_ATTACK_OUT=Out of extra attacks
EXTRA_ATTACK_OUT_INFO=Your guild doesn't have any extra attacks left.
EXTRA_ATTACK_USED=Already used extra attack
EXTRA_ATTACK_USED_INFO=You've already used an extra attack in this war. You can only use one extra attack per war.
EXTRA_ATTACK=Extra Attack?
EXTRA_ATTACK_INFO=You've already made one attack this war. Use one of your guild's {#ffe00f}%1$s{} remaining extra attacks to make a second attack?
CLOSE=Close
NO_PLAYERS_ASSIGNED_TO_CAR=There are no players assigned to this car.
CAR_NOT_ATTACKABLE=Room Closed
CAR_NOT_ATTACKABLE_INFO=You must first defeat a room on the floor below to gain access to this room.
CAR_LINEUPS_DEFEATED=This player has been defeated.
PROMOTION_REWARD=+ 3 War Boxes
LEAGUE_RANK_FORMAT=%1$s, %2$s
RESULTS_FINAL_RANK=Final Rank
RESULTS_SEASON_UNDERWAY=Season Now Underway!
RESULTS_TOP_POSTER=Top Poster
RESULTS_SEASON_COMPLETE=Season Complete!
NO_MEMBERS_AVAILABLE_TO_MOVE=There are no available players in your guild to move to this car.
OFFICERS_CAN_MOVE_PLAYERS_TO_THIS_SLOT=No defender assigned. Officers and above can move players to this slot.
WAR_NOT_ACTIVE_NO_LOGS_YET=This war does not have any logs yet.
ENEMIES_IN_THIS_LINEUP_DEFEATED=All the enemies in this lineup have been defeated.
GARAGE_LEVEL_UNLOCKED=Level %1$s Unlocked!
MEMBER_ALREADY_UNDER_ATTACK=This member is already under attack!
BOX_SAMPLE_CONTENTS=Sample Contents:
LEGENDARY_REWARD=Legendary Reward
WAR_SABOTAGE_RESOURCE_TOOLTIP=Spend %1$s to sabotage heroes in this war.
SABOTAGED_BY_HEADING=Sabotaged By:
GUILD_NO_POSTERS=This Guild has not won any War Posters yet.
EARN_POSTER_AT_LEGENDARY=Earn Poster at Legendary
MEMBER_SORT_POWER=Power
MEMBER_SORT_ATTACKS=Attacks
MEMBER_SORT_SABOTAGES=Sabotages
MEMBER_SORT_ONLINE=Online
WRONG_CAR_TITLE=Wrong Car!
WRONG_CAR_INFO=Your guild wants you to attack a different car on this floor. Ignore your guild or attack the right car?
RIGHT_CAR_BUTTON=Right Car
IGNORE_GUILD_BUTTON=Ignore Guild
WAR_REWARD_FORMAT=Top %1$s%% Rewards:
EXTRA_ATTACK_SETTING=Extra Attack Rank:
EXTRA_ATTACK_SETTING_INFO=Select what rank players have to be in order to use an extra attack in war.
WAR_ALL_LEAGUES=All Leagues
WIN_A_WAR=Win a War to reach the next league.
WAR_LEAGUE_REWARDS=%1$s Rewards:
WAR_PICK_ONE=You can pick one from each row.
WAR_SEASON_END_REWARDS=Season End Top Rewards:
WAR_SEASON_END_REWARD=Season End Top Reward:
WAR_LEGENDARY_PICK_ONE=Values increase at higher ranks inside legendary.
WAR_DEFENDING=Defending:
WAR_LINEUP_NOT_SET=Not Set!
WAR_READY_NO_ROOM=Ready but not in a room
POSTER_AVATAR=POSTER_AVATAR
FINAL_RANK=Final Rank:
FINAL_WIN_LOSS=Final W/L Record:
FINAL_WIN_LOSS_TIE=Final W/L/T Record:
FINAL_MMR=Final MMR:
RATIO_FORMAT=%1$s - %2$s
RATIO_FORMAT_WITH_TIE=%1$s - %2$s - %3$s
SUMMARY_EXTRA_ATTACKS=Extra Attacks: %1$s/%2$s
SUMMARY_DISCONNECTS=Disconnected: %1$s/%2$s
QUEUE_CONFIRM_TITLE=Queue for War?
QUEUE_CONFIRM_INFO=Are you sure you want to ADD your guild to the queue for the next War?
DEQUEUE_CONFIRM_TITLE=Exit War Queue?
DEQUEUE_CONFIRM_INFO=Are you sure you want to REMOVE your guild from the War queue?
AUTO_QUEUE_CONFIRM_TITLE=Auto Queue for War?
AUTO_QUEUE_CONFIRM_INFO=Are you sure you want to AUTO QUEUE your guild for future Wars?
CONFIRM=Confirm
WAR_CHANGE_TITLE=War Changes
WAR_CHANGE_QUEUED=%1$s queued the guild for war.
WAR_CHANGE_UNQUEUED=%1$s unqueued the guild for war.
WAR_CHANGE_TARGET=%1$s has changed targets.
WAR_CHANGE_MOVE_USER=%1$s has moved %2$s's lineup to %3$s.
WAR_CHANGE_MOVE_SELF=%1$s has moved their lineup to %2$s.
WAR_CHANGE_DEFENSE=%1$s has changed their war defense lineup.
WAR_LEAGUE_GENERIC_FORMAT=%1$s League
WAR_RATING_DELTA=%1$s MMR
RANK_OR_HIGHER_FORMAT=%1$s and below
END_OF_SEASON_REWARDS_TITLE=End of Season Rewards
END_OF_SEASON_REWARDS_INFO=Your End of Season Rewards have been sent to your Mailbox!
UNRANKED_GUILD_INFO=Your Guild is Unranked
SPARS_BUTTON=SPAR
SPARS_CHARGES=Spars Amount: %1$s/%2$s
CHOOSE_BAN_BUTTON=Select Bans
CHOOSE_BAN_BUTTON_OFF=Banned Heroes
WAR_BAN_SCREEN_TITLE=WAR BAN
WAR_BAN_SCREEN_DESCRIPTION=
WAR_BAN_SCREEN_EMPTY=No eligible Heroes to be Banned
CHOOSE_PROTECT_BUTTON=Select Protects
CHOOSE_PROTECT_BUTTON_OFF=Protected Heroes
WAR_PROTECT_SCREEN_TITLE=WAR PROTECT
WAR_PROTECT_SCREEN_DESCRIPTION=
WAR_PROTECT_SCREEN_EMPTY=No eligible Heroes to be Protected
SUMMARY_STATE_PREP_BAN=Ban Phase
SUMMARY_STATE_PREP_PROTECT=Protect Phase
SUMMARY_STATE_PREP_END=Phase Ended
START_WINDOW_BAN_LABEL=Banned Heroes
START_WINDOW_BAN_EMPTY=No banned heroes
START_WINDOW_PROTECT_LABEL=Protected Heroes
START_WINDOW_PROTECT_EMPTY=No protected heroes
