
S_OPEN_AIRDROP=You've unlocked the Air Drop feature! Let's check it out.
S_EXPLAIN_1=Air Drop is a special deal that gives you 30 days of valuable rewards for a low monthly price.
S_EXPLAIN_2=Air Drop is similar to Daily Deal: both give daily rewards. But they're separate deals and can be combined for ultimate value!
S_EXPLAIN_3=Note that when you purchase Air Drop, you must return each day to claim your reward or you lose it.
S_EXPLAIN_4=To find out more about Air Drop, tap the info button.
