
DIALOG_1=UPPER_RIGHT,NONE
DIALOG_2=UPPER_RIGHT,NONE
DIALOG_3=LOWER_MIDDLE,NONE
DIALOG_4=LOWER_LEFT,NONE
DIALOG_5=LOWER_MIDDLE,NONE
DIALOG_6=LOWER_RIGHT,NONE
DIALOG_7=LOWER_MIDDLE,NONE
DIALOG_8=LOWER_MIDDLE,NONE
