
DIALOG_1=You can now Auto Add materials to badges!
DIALOG_2=Let's take a look at the Auto Add settings first.
DIALOG_3=This window lets you control which materials are consumed when you use Auto Add.
DIALOG_4=This column shows all the materials you have available.
DIALOG_5=This column shows whether Auto Add will consume a particular type of material.
DIALOG_6=This column shows how many units of a material will be protected from being consumed.
DIALOG_7=So if you set Blue Bits to 10, Auto Add will always leave 10 bits of every blue badge remaining after using it.
DIALOG_8=Try it a few times with simple settings to get the hang of it... better safe than sorry. Happy enhancing!
