
DIALOG_1=Looks like The Inventor has given you a powerful new tool to help fight the Mega Virus...the Battle Badge!
DIALOG_2=However, you'll need to unlock Battle Badges before you can use them.
DIALOG_3=To unlock a Battle Badge, collect Megabits that match the Role of the hero who owns it.
DIALOG_4=You can earn Megabits by fighting the Mega Virus in The Codebase Trial.
