
DIALOG_1=Battle Pass events are a new way for you to earn lots of rewards!
DIALOG_2=Everyone can earn Free rewards by just playing the game and progressing through the reward levels.
DIALOG_3=To make reward level progress, you'll need to earn Quest Points.
DIALOG_4=To earn Quest Points, complete and claim Daily quests.
DIALOG_5=You'll be limited on the amount of Quest Points you can earn per day, so make sure to hit your limit daily.
DIALOG_6=To make the most out of your Daily Quest points, you'll need to purchase the Premium Pass.
DIALOG_7=This grants you access to the premium rewards track which has tons of value!
DIALOG_8=The Premium Pass may be purchased at any time during the event. Doing so will unlock all of the Premium Rewards up to your currently completed level!
DIALOG_9=By owning the Premium Pass you'll also have the option to automatically unlock all the rewards by spending some diamonds towards the end of the event!
DIALOG_10=For more information, make sure to check out all the details here.
