
DIALOG_1=UPPER_RIGHT,NONE
DIALOG_2=LOWER_LEFT,NONE
DIALOG_3=LOWER_MIDDLE,NONE
DIALOG_4=UPPER_MIDDLE,NONE
DIALOG_5=LEFT,NONE
DIALOG_6=LOWER_MIDDLE,NONE
DIALOG_7=LOWER_MIDDLE,NONE
DIALOG_8=LOWER_MIDDLE,NONE
DIALOG_9=LOWER_MIDDLE,NONE
DIALOG_10=LOWER_MIDDLE,NONE
DIALOG_11=LOWER_MIDDLE,NONE
