
DIALOG_1=Nice job unlocking your first Battle Badge!  Now it's time to see it in action.
DIALOG_2=To activate the Battle Badge during a fight, you'll need to charge it first.
DIALOG_3=The way to charge it is different for each hero, but don't worry, you and your allies can help charge each other's badges!
DIALOG_4=As soon as a Battle Badge is charged, its buffs are activated.
DIALOG_5=Each badge has three buffs. The first two are always available to activate, but the third requires the badge to be enhanced.
DIALOG_6=Your buffs can become even more powerful by leveling up your Battle Badge.
DIALOG_7=To increase its level, collect Megabits by fighting the Mega Virus in The Codebase Trial.
DIALOG_8=For more information, make sure to check out all the details here.
