
DIALOG_1=Diamond Quest events are a new way for you to earn lots of rewards!
DIALOG_2=Everyone can earn Free rewards by just playing the game and progressing up in reward levels.
DIALOG_3=To make reward level progress, you'll need to earn Quest Points.
DIALOG_4=To earn Quest Points, complete and claim Daily quests.
DIALOG_5=You'll be limited to earning 10 Quest Points per day, so make sure to hit your limit daily.
DIALOG_6=To make the most out of your Daily Quest points, you'll need to unlock Premium Rewards.
DIALOG_7=Premium Rewards contain the highest value rewards like newer hero chips and loads of Diamonds!
DIALOG_8=To gain access to Premium Rewards, you'll need to buy the Premium Pass.
DIALOG_9=If you're not sure you want the Premium Pass right away, don't worry...
DIALOG_10=Unlock the Premium Pass at any time during the event and collect all of the Premium rewards up to your current level!
DIALOG_11=For more information, make sure to check out all the details here.
