
DIALOG_1=Battle Pass season ends soon, but don't worry if you don't have enough time to collect all of the Premium Rewards!
DIALOG_2=By owning the Premium Pass you have access to the Buyout!
DIALOG_3=This becomes available towards the end of each Battle Pass season and allows you to spend diamonds to instantly collect all remaining rewards!
DIALOG_4=Use the Buyout to make sure you don't miss out on valuable rewards! \n\nFor more information, make sure to check out all the details here.
