
DIALOG_1=Looks like it's time to enhance your first Battle Badge...let's check it out!
DIALOG_2=Battle Badges can be temporarily enhanced just like hero badges.
DIALOG_3=Enhancing a Battle Badge will increase the stats of its first two buffs AND allow its 3rd buff to be activated in battle!
DIALOG_4=To enhance it, you can visit the Enhancements screen by tapping the Battle Badge icon.
DIALOG_5=Battle Badges require two resources to enhance them: Megabits and Hero XP.
DIALOG_6=The costs will increase or decrease based on the total number of Battle Badges currently enhanced. When none are enhanced, the first one is always free!
DIALOG_7=The enhancement on a Battle Badge will only be reset whenever you level up that badge.
DIALOG_8=For more information, make sure to check out all the details here.
