
DIALOG_1=After each fight, you'll now get a breakdown of the points you earned.
DIALOG_2=You'll earn Fight Points for both winning fights and taking advantage of scoring bonuses.
DIALOG_3=You can see how many points you earned for each bonus by tapping the info button.
DIALOG_4=Your Best Score shows your current high score against that opponent and is used when totaling your points to determine ranking.
DIALOG_5=As long as you have fight chances available, you can keep fighting an opponent to improve your Best Score.
