
TAP_MAIN_SCREEN_ICON=You've unlocked the Challenges feature! Let's check it out.
WEEKLY_DIALOG_1=Challenges are mini quests or contests. Completing one earns you a unique sticker for your book.
WEEKLY_DIALOG_2=Every Wednesday morning, everyone on the server gets the same two Weekly Challenges to complete.
WEEKLY_DIALOG_3=Some are easy, some are hard. But you have a whole week to complete them!
WEEKLY_DIALOG_4=Feel free to try and complete this week's Weekly Challenges, if you still can.
STARTER_DIALOG_1=For now, let's try a Starter Challenge. These you can definitely do.
STARTER_DIALOG_2=This first Starter Challenge requires you to 3-star stages in the Normal Campaign.
STARTER_DIALOG_3=If you complete this Starter Challenge, you can move right on to the next one.
STARTER_DIALOG_4=There are 5 in all. Good luck!
