
SELECT_FREE_PICK_EM_SLOT=LOWER_RIGHT,NONE
SELECT_PICK_EM_BOOK=LOWER_RIGHT,NONE
PRICE_DIALOG=LOWER_RIGHT,NONE
SELECT_PICK_EM_CHALLENGE=LOWER_RIGHT,NONE
ACTIVATE_PICK_EM_CHALLENGE=LOWER_RIGHT,NONE
NICE_WORK=LOWER_RIGHT,NONE
