
TAP_MAIN_SCREEN_ICON=LOWER_RIGHT,NONE
WEEKLY_DIALOG_1=LOWER_RIGHT,NONE
WEEKLY_DIALOG_2=LOWER_RIGHT,NONE
WEEKLY_DIALOG_3=LOWER_RIGHT,NONE
WEEKLY_DIALOG_4=LOWER_RIGHT,NONE
STARTER_DIALOG_1=LOWER_LEFT,NONE
STARTER_DIALOG_2=LOWER_LEFT,NONE
STARTER_DIALOG_3=LOWER_LEFT,NONE
STARTER_DIALOG_4=LOWER_LEFT,NONE
