
S_OPEN_WINDOW=Did you know you can view other players' challenges and sticker collections?
S_EXPLAIN=This window shows how many challenges a player has completed.
S_OPEN_BOOK=You can also view another player's sticker books.
