
SELECT_FREE_PICK_EM_SLOT=You're a challenge pro now! Let's try a Pick 'Em Challenge.
SELECT_PICK_EM_BOOK=The Pick 'Em Book has a variety of challenges.
PRICE_DIALOG=You can purchase Pick 'Em Challenges for %1$s Diamonds each.
SELECT_PICK_EM_CHALLENGE=We'll give one to try for free. Pick any challenge you like!
ACTIVATE_PICK_EM_CHALLENGE=Good choice! Now let's start it.
NICE_WORK=Nice work. Good luck completing your challenge!
