
DIALOGUE_1=Now you can prepare your defense for the next week during the final 24 hours of the current one.
DIALOGUE_2=There's no cooldown, so feel free to update your defensive lineup as much as you like.
DIALOGUE_3=You'll also be able to preview next week's new Rules and Bonuses so you can plan your defense properly.
