
DIALOG_1=Promoting between divisions is now a bit easier than it was before.
DIALOG_2=Getting kicked out of a promotion slot used to add time back on to your timer.
DIALOG_3=Now getting kicked out of a slot will simply freeze your timer!
DIALOG_4=Whenever you occupy a promotion slot again, your timer will unfreeze and pick up where it left off.
