
DIALOG_1=Welcome to the new Challenger Season!
DIALOG_2=Challenger Seasons is a new format where you compete over four weeks to be crowned the Season Champion!
DIALOG_3=To become the champ, you'll need to fight your way through seven divisions and earn the top rank.
DIALOG_4=But to get to the top you're going to need to earn Fight Points.
DIALOG_5=These are Opponent Keys, which are used to unlock opponents.
DIALOG_6=You'll get a few at the beginning of each day... let's try using one now.
DIALOG_7=When you unlock an opponent, you'll get 3 chances to fight them and earn the best Fight Score possible. Try fighting the opponent you just unlocked.
DIALOG_8=Before you enter a fight, make sure you're aware of the current rules and scoring bonuses.
DIALOG_9=Each season starts with a new set of Division Rules that affect both attackers and defenders.
DIALOG_10=As you promote, every other higher division will unlock and add a new Division Rule.
DIALOG_11=Fight Point Bonuses are a great way to add some extra points to your Fight Score and new bonuses are selected at the start of each season.
DIALOG_12=If you have the right heroes to take advantage of them, bonus points can make a big difference on the Leaderboard.
DIALOG_13=If your goal is to become the Season Champion, you're going to need to be the best and promote your way to the top.
DIALOG_14=There are two types of promotion slots.  Platinum colored slots will promote you up two divisions, while Gold slots will promote you up one.
DIALOG_15=The number of available promotion slots will change based on the number of players currently in your leaderboard.
DIALOG_16=At the end of each day and every week, ranked players will receive rewards.  You can see the types and amounts of rewards on the Rewards screen.
DIALOG_17=During the fourth and final week of the season, the players who make it to Division I will compete to be crowned Season Champion! Do you have what it takes to be the best?
