
POINT_TO_CITY_WATCH=LEFT,NONE
CITY_WATCH_INFO=RIGHT,NONE
POINT_TO_CITY=LOWER_MIDDLE,NONE
POINT_TO_FIGHT=LEFT,NONE
HERO_CHOOSER_INFO=UPPER_LEFT,NONE
REWARDS_WINDOW=UPPER_RIGHT,NONE
POINT_TO_NEXT_BATTLE=LEFT,NONE
