
S_EXPLAIN_1=Congrats, you finished a challenge! Let's complete it and get a new sticker.
S_COMPLETE_CHALLENGE=Now tap the Claim button.
S_EXPLAIN_2=Nice work. Don't forget to check out all the other fun challenges... and earn some more stickers!
