
DIALOG_1=Inventor, are you seeing this?  It looks like a portal to The Codebase just appeared!
DIALOG_2=Yes...almost like an invitation.  I suspect a trap, but we may not get another chance to confront the Mega Virus.  Are you and the other heroes ready?
DIALOG_3=Always.  Everyone, now's our chance, let's make it count!
DIALOG_4=No one's sure if the Mega Virus can be beaten, but it's definitely not invulnerable...
DIALOG_5=Add heroes to your lineup that can take advantage of it's vulnerability and you'll score more points and earn more rewards.
DIALOG_6=The more points you score against the Mega Virus, the more Megabits it'll drop for you to collect.
DIALOG_7=You can boost the drop chance of one specific type before the start of each battle!
DIALOG_8=The Mega Virus is incredibly powerful, so make sure to review all the data The Inventor has collected on its abilities before fighting it.
