
DIALOG_1=The Rage Meter tracks how many points you've earned from damaging the Mega Virus and making it angry.
DIALOG_2=Every minor level you reach will cause the Mega Virus to drop Megabits and increase one of its stats.
DIALOG_3=Every 5th level will award an even larger number of Megabits but also activates a new skill on the Mega Virus!
DIALOG_4=Hit the Mega Virus with something it's vulnerable against to increase the Rage Multiplier and reach levels faster.
DIALOG_5=The angrier it gets, the more points you earn and the more Megabits it drops.  Good luck!
