
TAP_COLISEUM=UPPER_LEFT,NONE
TAP_OPPONENT=UPPER_LEFT,NONE
SET_LINEUP_ONE=UPPER_LEFT,NONE
TAP_FIGHT=UPPER_MIDDLE,NONE
VICTORY=UPPER_LEFT,NONE
LOSS_A=UPPER_LEFT,NONE
LOSS_B=UPPER_LEFT,NONE
LINEUP_INFO=UPPER_LEFT,NONE
