
TAP_COLISEUM=You've unlocked the Coliseum!
TAP_OPPONENT=Participants in the Coliseum will set and battle with 3 teams of heroes.
SET_LINEUP_ONE=You will need to have at least one hero on each team. Set some heroes now!
TAP_FIGHT=Now you're ready to fight!
VICTORY=You won all three battles! Remember to adjust your Defenses with lots of strong heroes.
LOSS_A=Better luck next time! You must win all three battles to advance in the Coliseum.
LOSS_B=Try to keep your top 15 heroes battle-ready to have the best shot in the Coliseum.
LINEUP_INFO=You can preview an opponent's defenses by tapping the info button. Use this to find weak lineups!
