
TAP_COLLECTION_CARD=UPPER_LEFT,NONE
TAP_CLAIM_BUTTON=UPPER_MIDDLE,NONE
DIALOGUE_1=UPPER_RIGHT,NONE
TAP_BACK_BUTTON=UPPER_LEFT,NONE
TAP_DETAILS_BUTTON=UPPER_MIDDLE,NONE
DIALOGUE_2=RIGHT,NONE
DIALOGUE_3=LEFT,NONE
DIALOGUE_4=UPPER_MIDDLE,NONE
