
DIALOGUE_1=This screen shows which heroes are eligible to be mastered.
DIALOGUE_2=For the Bronze Tier, you need to own at least 5 heroes who are 3 stars or higher.
DIALOGUE_3=Then you must master 5 of those heroes.
TAP_MASTERY_INFO=Tap the info button to see how to master a hero.
DIALOGUE_4=To master a Hero, you must win 20 fights with them, but only in specific modes.
DIALOGUE_5=Only City Watch, Creep Surge, and Invasion count for mastery. (You'll unlock some of these modes later.)
DIALOGUE_6=That's it. Time to master some heroes. Good luck!
