
TAP_COLLECTION_CARD=Nice work! You've completed a collection level!
TAP_CLAIM_BUTTON=Let's claim your reward!
DIALOGUE_1=You've now unlocked Bronze II! Notice that you must win 30 fights with your heroes to complete this level.
TAP_BACK_BUTTON=You've also unlocked Silver I!
TAP_DETAILS_BUTTON=Let's take a look...
DIALOGUE_2=Master 3 heroes to complete Silver I
DIALOGUE_3=Note that you can make progress toward 2 different levels at the same time!
DIALOGUE_4=Using a 4-star hero will award progress for both Bronze II and Silver I. Good luck!
