
TAP_COLLECTION_CARD=Nice work! You've mastered a hero!
TAP_DETAILS_BUTTON=Let's view the Bronze Tier Details.
DIALOGUE_1=You've mastered 1 hero in this Collection! Master a few more to complete Bronze I and earn the next reward!
