
DIALOGUE_1=Each collection has 4 tiers: Bronze, Silver, Gold, and Platinum.
DIALOGUE_2=These correspond to 3, 4, 5 and 6-star heroes.
DIALOGUE_3=Over time, you can gain levels in each of the four tiers. Each time you do, you earn rewards!
DIALOGUE_4=You gain levels by "mastering" heroes! You need to master 5 heroes to complete Bronze Tier Level I.
TAP_TIER_DETAILS=Let's learn about how mastering heroes works.
