
DIALOGUE_1=New Cosmetics Collections! Let's check it out.
DIALOGUE_2=You can now collect Cosmetics for rewards here!
DIALOGUE_3=Let's see which Emojis you've collected. You can get more Cosmetics by opening Cosmetic Crates.
DIALOGUE_4=Nice, you've completed a Cosmetics Set! Claiming this will earn you loot and Reward Level points to help you level up!
DIALOGUE_5=Let's see what you gained by leveling up!
DIALOGUE_6=Each Cosmetics Rewards level increases your heroes' core stats. Some levels give extra special bonuses!
DIALOGUE_7=Let's go check out the other Collections.
DIALOGUE_8=You can collect Cosmetics for rewards here!
DIALOGUE_9=Let's go check out the other Collections.
DIALOGUE_10=Let's go back.
DIALOGUE_11=Let's check out the other Collections.
DIALOGUE_12=You can master Heroes to make them stronger here!
DIALOGUE_13=That's it. Time to collect some cosmetics and master some heroes. Good luck!
