
DIALOGUE_1=UPPER_LEFT,NONE
DIALOGUE_2=UPPER_RIGHT,NONE
DIALOGUE_3=LOWER_MIDDLE,NONE
DIALOGUE_4=LOWER_MIDDLE,NONE
DIALOGUE_5=UPPER_LEFT,NONE
DIALOGUE_6=LOWER_MIDDLE,NONE
DIALOGUE_7=UPPER_MIDDLE,NONE
DIALOGUE_8=UPPER_LEFT,NONE
DIALOGUE_9=UPPER_LEFT,NONE
DIALOGUE_10=UPPER_LEFT,NONE
DIALOGUE_11=UPPER_LEFT,NONE
DIALOGUE_12=UPPER_LEFT,NONE
DIALOGUE_13=UPPER_LEFT,NONE
