
CRAFTING_WINDOW_CANT_CRAFT=This is where you will craft badges for your heroes. Come back when you have the necessary pieces to make this badge!
CRAFTING_WINDOW=You don't have that badge yet, but it looks like you can make it.
EQUIP_ITEM=Nice! Now that badge can be equipped.
NEED_MORE_PIECES=Looks like you're missing some key components.
POINT_TO_AREA=If you take your team to this area, you should be able to get more.
