
TIP=Looks like you are having some difficulty winning this fight. This screen looks at your heroes and recommends an upgrade to help you win.
TAP_SHOW_ME=The "Show me" button automatically takes you to the recommended upgrades. Try tapping it now.
