
DIALOG_1=Everyone can use a helping hand from time to time.
DIALOG_2=Now you can ask your fellow guild members to help progress your heroes!
DIALOG_3=You can ask for help completing your next Hero XP level.
DIALOG_4=You can get help with progressing a Hero Skill.
DIALOG_5=Or simply request some Stamina to help earn your hero's badges!
DIALOG_6=Regardless of the aid you need, you can request each type from your guild once every 20 hours.
DIALOG_7=Regardless of the aid you need, you can request each type from your guild once every 20 hours.
DIALOG_8=Don't forget though that help is a two-way street!
DIALOG_9=Visit the Guild Aid screen within your guild to see who else could use a hand.
DIALOG_10=Help other guild members out by donating XP items and gold to their heroes too!
DIALOG_11=For more information check out the details here.
