
DIALOG_1=Congratulations, you've just promoted your first Hero to Emerald Rank!
DIALOG_2=You now have the ability to edit this Hero's Subclass, let's check it out!
DIALOG_3=Subclasses are primarily made up of two things, Emerald Stat Tiers and Stat Selections.
DIALOG_4=Emerald Stat Tiers range from 1-3 and are predetermined for each Hero. You can find a Hero's Tier assignment here.
DIALOG_5=These Tiers control how many Stat Selections you can make for a Hero, with Tier 1 Heroes having the most and Tier 3 Heroes having the least.
DIALOG_6=Selecting Stats is your choice! Craft your Hero's Subclass by choosing the Level Scaling Stats you think work best!
DIALOG_7=When choosing stats, these sections will explain how much of the chosen stat your Hero will gain.
DIALOG_8=They'll also display the base effectiveness it will have against other max level enemies in combat.
DIALOG_9=If you don't want to make a choice right away that's ok, Heroes come with default Stats already selected so you can jump right into battle!
DIALOG_10=But, if you want to put your own personal stamp on a Hero feel free to experiment since changing Stat Selections is free!
DIALOG_11=If you want more information to make your Stat Selections you can reference a Hero's Detailed Stats screen by tapping here.
DIALOG_12=If you ever select a stat that a Hero already has maxed out you will be notified with a red triangle icon here. When this happens you should consider selecting a different stat for the Hero.
DIALOG_13=If you don't want to see these warnings you can turn them off by using the toggle here or in the Settings menu.
DIALOG_14=If you need more information about Emerald or Subclasses you can reference the How-To-Play here.
DIALOG_15=That's it for now! Create some Subclasses and start fighting!
