
OPEN_ENCHANTING=Looks like you can now enhance your Badges.
SELECT_HERO=You can choose which Hero's badges you want to enhance here.
CHOOSE_ITEM=Select this item to Enhance.
CHOOSE_VOID_DUST=We've got a lot of these items in reserve, let's use two of them to enhance this badge.
TAP_ENHANCE=Once the square is full, we can enhance!
