
OPEN_MAIN_MENU=You've unlocked a new evolution level!
EVOLVE_TO_SIX_STARS=You can now evolve 5 star heroes to 6 stars.
EVOLVE_NOW=Evolve your hero now!
COLLECT_CHIPS=Collect chips to evolve your hero!
