
TAP_FIGHT_PIT=You've unlocked the Arena!
TAP_OPPONENT=What are you waiting for?! Let's go!
CHOOSE_HERO=Select Heroes by tapping on their portraits.
OUTCOME_VICTORY=Wowee! Victory is SWEET!
OUTCOME_DEFEAT=Aww, corn nuts. Don't worry, we'll get 'em next time!
