
CHAP_CLEAR_DIALOGUE_1=The area is clear! Well done, team!
CHAP_CLEAR_DIALOGUE_2=That's one down and...a whole lot more to go.
CHAP_CLEAR_DIALOGUE_3=Aww, don't worry buddy. If we take 'em one by one we'll get the City cleared in no time!
CHAP_CLEAR_DIALOGUE_4=I guess we should get moving, then.
