
TAP_SIDE_MENU=UPPER_LEFT,NONE
TAP_HEROES=LOWER_LEFT,NONE
TAP_WALL=LOWER_LEFT,NONE
CLOSE_WALL=LOWER_LEFT,NONE
EXPLAIN_DAILY_QUEST=LOWER_LEFT,NONE
EQUIP_RALPH_AND_VANELLOPE=UPPER_MIDDLE,NONE
TAP_CONTINUE_B=UPPER_MIDDLE,NONE
