
TAP_SIDE_MENU=Looks like these heroes have been spending a lot of time together.
TAP_HEROES=Let's see what they have to say about that.
TAP_WALL=Now that you unlocked their Friendship, you can check out their Friend Wall.
CLOSE_WALL=As these heroes spend more time together, this wall will record their dialogue & accomplishments!
EXPLAIN_DAILY_QUEST=Friends will earn points through different modes and by completing Daily Quests.
EQUIP_RALPH_AND_VANELLOPE=Use these heroes together to complete their Daily Quest.
TAP_CONTINUE_B=Make sure to complete their Quest everyday to gain Friend Points and Rewards!
