
TAP_SIDE_MENU=LOWER_LEFT,NONE
CLOSE_QUESTS=LOWER_LEFT,NONE
TAP_CAMPAIGN_ICON=LOWER_LEFT,NONE
REAL_GEAR_INFO=LOWER_RIGHT,NONE
TAP_GO=UPPER_LEFT,NONE
TAP_NODE=LOWER_LEFT,NONE
STAMINA_INFO=RIGHT,NONE
TAP_NEXT=RIGHT,NONE
TAP_FIGHT=LEFT,NONE
FIGHT_LOSS=LOWER_MIDDLE,NONE
FIGHT_WIN=LEFT,NONE
SECOND_FIGHT=RIGHT,NONE
