
HAS_MISSION_UNLOCKED=All right! Looks like you've unlocked a Mission.
MISSIONS_INFO_DIALOGUE=Missions are a great way to level up your Friendships.
MISSIONS_INFO_DIALOGUE_2=Missions take time to complete, but your heroes will still be available for battle.
COME_BACK_LATER=Come back later when the Mission is complete to see if it was successful.
MISSIONS_INFO_DIALOGUE_FINAL=Missions reward Friend XP. As your Friendship levels up, you'll unlock more Missions.
