
TAP_SIDE_MENU=Wow, these heroes have become even closer than they were before!
CLOSE_QUESTS=Now that their Friendship is level 3, you've unlocked a special Friendship Campaign.
TAP_CAMPAIGN_ICON=Each Friendship has its own Campaign.
REAL_GEAR_INFO=Complete this story to unlock a Memory Disk which will grant your heroes special powers.
TAP_GO=Start the story in Episode 1.
TAP_NODE=Each episode consists of five increasingly difficult battles at specific locations in the City.
STAMINA_INFO=Friendship Campaigns have their own special Friend Stamina.
TAP_NEXT=Make sure to spend your Friend Stamina whenever it is full!
TAP_FIGHT=Only the heroes that are friends can fight.
FIGHT_LOSS=Looks like your heroes need to be stronger for this battle...
FIGHT_WIN=Nice Work! Completing the Friend Campaign is the fastest way to level up a friendship.
SECOND_FIGHT=The episode continues. Each fight earns you Friend XP and makes progress towards unlocking Missions and Memory Disks.
