
TAP_GUILDS=You can now join a Guild!
GUILDS_INFO=Joining a Guild gives you guild chat, guild-only game modes, bonus rewards, and loot crates every day!
VIEW_GUILD=You can view stats of different guilds.
JOIN_INFO=Join a guild or you will miss out on guild-only rewards. Most guilds love to have new players!
GUILD_INDECISION=Choose a guild to join! Tap the gear icon to customize your search.
