
TAP_CHECK_IN=Check in with your guild to help everyone in your guild earn rewards.
CHECK_IN=The more people who check in, the bigger everyone's reward will be tomorrow.
INVITE_MORE_PLAYERS=Invite more players to your Guild so you can claim more rewards each day.
CHECKIN_INFO=Come back tomorrow to claim your reward!
