
TAP_GUILDS=Your guild needs your help!
TAP_MERCS=You can now share your Heroes with other people in your guild.
TAP_SLOT=You also get Guild Coins for posting your Heroes.
TAP_HERO=You can still use heroes you post, so there is no reason not to post your best hero.
CLOSING_REMARK=Post a Mercenary every day. Rewards will be delivered to your Mailbox.
