
UNLOCK_1_1=UPPER_LEFT,MR_INCREDIBLE
UNLOCK_1_2=LOWER_LEFT,CHIEF_BOGO
UNLOCK_1_3=UPPER_LEFT,MR_INCREDIBLE
UNLOCK_2_1=UPPER_LEFT,MR_INCREDIBLE
UNLOCK_2_2=LOWER_LEFT,CHIEF_BOGO
UNLOCK_3_1=UPPER_LEFT,MR_INCREDIBLE
UNLOCK_3_2=LOWER_LEFT,CHIEF_BOGO
UNLOCK_3_3=UPPER_LEFT,MR_INCREDIBLE
UNLOCK_3_4=LOWER_LEFT,CHIEF_BOGO
UNLOCK_4_1=UPPER_LEFT,MR_INCREDIBLE
UNLOCK_4_2=LOWER_LEFT,CHIEF_BOGO
UNLOCK_4_3=UPPER_LEFT,MR_INCREDIBLE
UNLOCK_4_4=LOWER_LEFT,CHIEF_BOGO
