
UNLOCK_1_1=These Thieves are smart, but I think we've got the upper hand on them.
UNLOCK_1_2=Glad to hear it, because we've just gotten calls about a whole new round of thefts.
UNLOCK_1_3=You mean there's more? All right! Bring it on!
UNLOCK_2_1=You know Chief, I'm starting to think these thefts are somehow connected.
UNLOCK_2_2=Good instincts, Mr. Incredible. I've had officers Hopps and Wilde interviewing the victims and they've already got a few theories.
UNLOCK_3_1=Have Judy and Nick figured out anything about the thefts?
UNLOCK_3_2=Well, they've confirmed that all the stolen items had either purely personal value or were considered iconic in the City.
UNLOCK_3_3=That's odd. This place is filled with stuff worth tons of money. Why are the thieves trying to take mementos and store signs ?
UNLOCK_3_4=That's what we're trying to find out. If we can uncover a motive, I'm confident we can find the perpetrator behind these thefts.
UNLOCK_4_1=Any luck on finding a motive for these attempted thefts, Chief?
UNLOCK_4_2=Believe it or not, Yax has a pretty interesting theory...
UNLOCK_4_3=Yax? Did I hear you correctly?
UNLOCK_4_4=You certainly did. He thinks these thefts may connect to some of the data he's pulled from the different files around the City.
