
S_NOT_ENOUGH_HEROES=You need to have 5 heroes at level 50 to participate in the Heist!
S_TAP_HEIST=You can now participate in the Heist!
S_NARRATION_A=I'm here, Chief. What's the problem?
S_NARRATION_B=Thanks for coming in. We've had a spree of robberies across the City and the phones are ringing off the hook. Clawhauser can barely keep up.
S_NARRATION_C=Robberies? That's a cake walk. Don't worry. I got ya covered.
S_TAP_VIEW=Let's learn how a Heist works!
S_EXP_IN_PROGRESS=The Heist is a mode where you and 4 other players search the city for a notorious Thief.
S_TAP_JOIN=Join this Heist to help "Tutorial Player" catch the Thief.
S_CHOOSE_HEIST_HEROES=To join a Heist you need 5 heroes. You can't use heroes that another player is using.
S_EXP_VALUABLES=The Thief is after Valuables scattered around the city. If she steals them all, you lose!
S_EXP_BLACK_CIRCLE=The black circle shows the last known location of the Thief.
S_WAIT_FOR_THIEF_SPOTTED=Heroes have a chance to spot the Thief when near her. Look, one has spotted her now!
S_EXP_PULLING_HEROES=After catching the Thief, any player can fight her. "Tutorial Player" will start this fight.
S_WAIT_FOR_ESCAPE=The four closest heroes are rushing over to help. That includes some of your heroes.
S_EXP_LIVES=The Thief has 5 lives; she loses one each time you catch and defeat her. Reduce her to 0 lives to win!
S_EXP_CLUES=Collecting clues helps narrow down the search zone for the Thief's hideout.
S_INVESTIGATE_POI=Search for Clues at Points of Interest (POIs).
S_POI_EXPANDED=Choose a hero to investigate. Travel time to the POI is shown under the hero.
S_MOVING_TO_INVESTIGATE=Heroes will use energy to run. When they run out of energy, they will slow to walk. Energy is regained over time.
S_WAIT_FOR_CIRCLE=The white circle shows the possible location of the Thief's hideout.
S_EXP_HIDEOUT=You may need to investigate many POIs to find the Thief's Hideout.
S_EXPLAIN_FIGHT_BUTTON=You found the Thief's Hideout!
S_TAP_FIGHT=You can also win the Heist by defeating the Thief in her Hideout.
S_CALL_HEROES=Portraits of nearby heroes are shown in combat. Tap them to call them to battle!
S_VICTORY_A=Congratulations on catching your first Thief.
S_VICTORY_B=Now you're all set to join a real Heist with your friends, guild members, or other players.
