
S_NOT_ENOUGH_HEROES=RIGHT,NONE
S_TAP_HEIST=UPPER_RIGHT,NONE
S_NARRATION_A=LOWER_LEFT,MR_INCREDIBLE
S_NARRATION_B=UPPER_LEFT,CHIEF_BOGO
S_NARRATION_C=LOWER_LEFT,MR_INCREDIBLE
S_TAP_VIEW=LEFT,NONE
S_EXP_IN_PROGRESS=LOWER_LEFT,NONE
S_TAP_JOIN=RIGHT,NONE
S_CHOOSE_HEIST_HEROES=UPPER_LEFT,NONE
S_EXP_VALUABLES=LOWER_RIGHT,NONE
S_EXP_BLACK_CIRCLE=RIGHT,NONE
S_WAIT_FOR_THIEF_SPOTTED=LOWER_LEFT,NONE
S_EXP_PULLING_HEROES=LOWER_LEFT,NONE
S_WAIT_FOR_ESCAPE=LOWER_LEFT,NONE
S_EXP_LIVES=LOWER_LEFT,NONE
S_EXP_CLUES=LOWER_RIGHT,NONE
S_INVESTIGATE_POI=LOWER_LEFT,NONE
S_POI_EXPANDED=UPPER_RIGHT,NONE
S_MOVING_TO_INVESTIGATE=LOWER_RIGHT,NONE
S_WAIT_FOR_CIRCLE=LOWER_RIGHT,NONE
S_EXP_HIDEOUT=UPPER_RIGHT,NONE
S_EXPLAIN_FIGHT_BUTTON=UPPER_RIGHT,NONE
S_TAP_FIGHT=UPPER_LEFT,NONE
S_CALL_HEROES=UPPER_LEFT,NONE
S_VICTORY_A=UPPER_LEFT,NONE
S_VICTORY_B=RIGHT,NONE
