
DIALOG_1=Hero Filters allow you to easily filter your Hero collection to find specific types of Heroes. Let's check it out!
DIALOG_2=There are several Filter Types, each with their own Individual Filters. You can swap between Filter Types with these buttons.
DIALOG_3=Create your own Hero Filters by toggling any combination of Individual Filters ON.
DIALOG_4=You can check how many Heroes are in your Hero Filter here. You'll even be able to see if there are Heroes you haven't unlocked yet!
DIALOG_5=Hero Filters can be applied to the "Heroes" and "Choose Your Heroes!" screens to find the perfect Hero for the job!
