
MAIN_SCREEN_DIALOG_1=Okay, lady, you'd better explain what's goin' on right now, because this game is no longer fun!
MAIN_SCREEN_DIALOG_2=This is some kind of GAME to you?
MAIN_SCREEN_DIALOG_3=Yes! Of course it's -- Ugh! I don't have time to explain everything. My friend's in trouble!
MAIN_SCREEN_DIALOG_4=My family is out there too!
MAIN_SCREEN_DIALOG_5=You're right. So, what do we do?
MAIN_SCREEN_DIALOG_6=We regroup and survey the area.
TAP_CHESTS=You've got some loot from that battle.
TAP_GOLD_CHEST=Frozone has joined your team!
CLOSE_HERO_REWARD=Frozone! Am I glad to see you.
CLOSE_GOLD_CHEST_REWARD=Elastigirl! Can you explain what in the greater good is going on here?
CLOSE_GOLD_CHEST_REWARD_RESPONSE=I was hoping you'd be able to tell us, actually.
TAP_SILVER_CHEST=You've found another crate.
CLOSE_SILVER_CHEST_REWARDS=Is it a medal?
OPEN_MENU=You've received a badge! Badges are equippable items that give your heroes a stats boost.
TAP_FROZONE=Frozone could use a boost. Let's give it to him.
CLOSE_HERO_LIST=Now that we have proper reinforcements, let's scout the area.
OPEN_CAMPAIGN=Ready when you are!
TAP_CHAPTER_1=The problem has spread across the entire city.
TAP_NODE_1=Let's go back to the rooftops.
TAP_THROUGH_CAMPAIGN_DETAILS=These guys look like serious trouble. Time to put them on ice.
EQUIP_HEROES=Select all three of your heroes before starting this fight.
TAP_FIGHT_ON_HERO_CHOOSER=I'm ready. Let's do this!
