
MAIN_SCREEN_DIALOG_1=LOWER_LEFT,RALPH
MAIN_SCREEN_DIALOG_2=UPPER_LEFT,ELASTIGIRL
MAIN_SCREEN_DIALOG_3=LOWER_LEFT,RALPH_NERVOUS
MAIN_SCREEN_DIALOG_4=UPPER_LEFT,ELASTIGIRL
MAIN_SCREEN_DIALOG_5=LOWER_LEFT,RALPH
MAIN_SCREEN_DIALOG_6=UPPER_LEFT,ELASTIGIRL
TAP_CHESTS=LOWER_MIDDLE,NONE
TAP_GOLD_CHEST=LOWER_MIDDLE,NONE
CLOSE_HERO_REWARD=UPPER_LEFT,ELASTIGIRL
CLOSE_GOLD_CHEST_REWARD=UPPER_LEFT,FROZONE
CLOSE_GOLD_CHEST_REWARD_RESPONSE=LOWER_LEFT,ELASTIGIRL
TAP_SILVER_CHEST=UPPER_MIDDLE,NONE
CLOSE_SILVER_CHEST_REWARDS=UPPER_LEFT,RALPH
OPEN_MENU=UPPER_MIDDLE,NONE
TAP_FROZONE=LOWER_MIDDLE,NONE
CLOSE_HERO_LIST=UPPER_LEFT,ELASTIGIRL
OPEN_CAMPAIGN=UPPER_LEFT,RALPH
TAP_CHAPTER_1=LOWER_LEFT,ELASTIGIRL
TAP_NODE_1=UPPER_LEFT,RALPH
TAP_THROUGH_CAMPAIGN_DETAILS=UPPER_LEFT,FROZONE
EQUIP_HEROES=UPPER_MIDDLE,NONE
TAP_FIGHT_ON_HERO_CHOOSER=UPPER_LEFT,RALPH
