
GATE_DIALOG_1=I can't believe you talked me into this.
GATE_DIALOG_2=Aww, come on, Ralph! How often do we get to try a game in BETA?
BETA_KEY_DIALOG_1=We gotta use this key!
BETA_KEY_DIALOG_2=Uh...I dunno, kid. Looks like there's somethin' seriously wrong. I've never seen an entrance like this before.
BROKEN_GATE_DIALOG_2=Fortune favors the bold, Stinkbrain! You can follow me or get left behind.
BROKEN_GATE_DIALOG_3=All right, fine. But don't say I didn't warn you...because I AM warning you!
COMAT_1_PRELOAD_DIALOG_1=Wowee! Look at this soda soaker, Ralph!
COMAT_1_PRELOAD_DIALOG_2=Aw, man! This is my only shirt...
COMAT_1_PRELOAD_DIALOG_3=Are you kidding?! You look amazing!!
POST_LOGO_DIALOG_1=Whoa. This doesn't look good.
POST_LOGO_DIALOG_2=What's wrong with this place?
POST_PAN_BACK_DIALOG_1=You!!! Where is my family? What have you done with them?!
POST_PAN_BACK_DIALOG_2=Why do people always assume I'm the bad guy?
POST_GLITCH_DIALOG_1=Bob! Thank goodness you're safe. I was so worried!
POST_GLITCH_DIALOG_2=Grrr...
POST_GLITCH_DIALOG_3=Wait... Bob, is that you?
POST_GLITCH_DIALOG_4=He doesn't look so good...
POST_GLITCH_DIALOG_5=Bob, if it's really you, please snap out of it!
ACTIVE_1=I'm gonna wreck him!
ACTIVE_2=It's Lollipop Slam time!
ACTIVE_3=Honey, I  don't want to hurt you, but I will STOP YOU if I have to!
POST_COMBAT_DIALOG_1=Okay, you gotta tell us, lady - what is going on?
POST_COMBAT_DIALOG_2=I'm not sure, but we have to do something!
POST_COMBAT_DIALOG_3=My family's missing, villains are everywhere, and Bob...
DIALOG_OVER_BLACK_1=Hey, who turned out the lights?
DIALOG_OVER_BLACK_2=I have a bad feeling about this...
COMBAT_2_PRE_DIALOG_1=Kid! What's happened to you?!
COMBAT_2_PRE_DIALOG_2=Attack! Attack!
COMBAT_2_LOW_HP=We need to regroup! Run!!
