
GATE_DIALOG_1=INTRO_RALPH,RALPH
GATE_DIALOG_2=INTRO_VAN,VANELLOPE_ADORABLE
BETA_KEY_DIALOG_1=INTRO_VAN,VANELLOPE_ADORABLE
BETA_KEY_DIALOG_2=INTRO_RALPH_IMAGE,RALPH_NERVOUS
BROKEN_GATE_DIALOG_2=INTRO_VAN_IMAGE,VANELLOPE_ADORABLE
BROKEN_GATE_DIALOG_3=INTRO_RALPH_IMAGE,RALPH
COMAT_1_PRELOAD_DIALOG_1=UPPER_LEFT,VANELLOPE
COMAT_1_PRELOAD_DIALOG_2=LOWER_LEFT,RALPH
COMAT_1_PRELOAD_DIALOG_3=UPPER_LEFT,VANELLOPE
POST_LOGO_DIALOG_1=UPPER_LEFT,RALPH_NERVOUS
POST_LOGO_DIALOG_2=LOWER_LEFT,VANELLOPE_SAD
POST_PAN_BACK_DIALOG_1=UPPER_LEFT,ELASTIGIRL
POST_PAN_BACK_DIALOG_2=UPPER_LEFT,RALPH
POST_GLITCH_DIALOG_1=LOWER_LEFT,ELASTIGIRL
POST_GLITCH_DIALOG_2=UPPER_RIGHT,MR_INCREDIBLE_CREEP
POST_GLITCH_DIALOG_3=LOWER_LEFT,ELASTIGIRL_UPSET
POST_GLITCH_DIALOG_4=UPPER_LEFT,VANELLOPE
POST_GLITCH_DIALOG_5=LOWER_LEFT,ELASTIGIRL
ACTIVE_1=UPPER_LEFT,RALPH
ACTIVE_2=UPPER_LEFT,VANELLOPE
ACTIVE_3=UPPER_LEFT,ELASTIGIRL
POST_COMBAT_DIALOG_1=UPPER_LEFT,RALPH
POST_COMBAT_DIALOG_2=LOWER_LEFT,ELASTIGIRL
POST_COMBAT_DIALOG_3=LOWER_LEFT,ELASTIGIRL
DIALOG_OVER_BLACK_1=UPPER_LEFT,RALPH_NERVOUS
DIALOG_OVER_BLACK_2=LOWER_LEFT,ELASTIGIRL
COMBAT_2_PRE_DIALOG_1=LOWER_LEFT,RALPH
COMBAT_2_PRE_DIALOG_2=UPPER_RIGHT,VANELLOPE_CREEP
COMBAT_2_LOW_HP=LOWER_LEFT,ELASTIGIRL
