
DIALOG_1=Oh my land! A giant robot has appeared in the City!
DIALOG_2=Buckle up, short stack. Looks like it's not here to play tea party.
DIALOG_3=Bosses are invincible unless you use Breakers to fight them!
DIALOG_4=Get Breakers by defeating the ever-stronger Breaker Fights.
