
DIALOG_1=You now have access to Auto Quick Fight.
DIALOG_2=Auto Quick Fight allows you to easily Quick Fight multiple Breaker Fights in a row. Let's check it out!
DIALOG_3=Auto Quick Fight allows you to easily Quick Fight multiple Breaker Fights in a row. Let's check it out!
DIALOG_4=Select your Heroes and start the fight. Your Heroes will automatically Quick Fight Breaker Fights until you either run out of Invasion Stamina, lose a fight, or complete an entire Breaker Quest Wave.
DIALOG_5=Once Auto Quick Fight finishes you'll see a summary of all rewards gained and how much Invasion Stamina was used.
