
DIALOG_1=You have enough Breakers to attack a Boss!
DIALOG_2=These are the Bosses your Guild has discovered. Attack and defeat them for loot!
DIALOG_3=Use a Breaker to Attack the Boss!
DIALOG_4=Congrats, you beat a Boss! It's time to claim your loot!
DIALOG_WINDOW_5=When a Boss is defeated, you earn rewards based on your contributions. Attack each Boss to maximize your rewards!
DIALOG_6=You've earned a Power-Up! Now, apply it to a Hero!
DIALOG_7_WINDOW=A Power-Up can affect either a single Hero or the entire Featured Team.
DIALOG_8_WINDOW=Select a Hero or Team to greatly strengthen with a Power-Up!
DIALOG_9=Check out the Invasion Item Shop!
DIALOG_10=You earn Boss Tech by defeating Bosses.
DIALOG_11=During each Invasion, you can buy useful items here with Boss Tech and Diamonds!
DIALOG_12=Claim your free, daily power-ups.
BOSS_INTRO=These are the Bosses your Guild has discovered. Bosses spawn at the same rank as the guild members that discover them. Attack and defeat them for loot!
RARITY_INFO=A Boss's rank displays in the lower left corner of its portrait.
LEVEL_INFO=A Boss's level and mark are shown in the upper left corner.
POINTS_INFO=You can attack any Boss you want but defeating higher ranked Bosses will generally award more Invasion Points. Try attacking one now!
