
DIALOG_1=UPPER_LEFT,NONE
DIALOG_2=UPPER_LEFT,NONE
DIALOG_3=UPPER_LEFT,NONE
DIALOG_4=UPPER_LEFT,NONE
DIALOG_WINDOW_5=UPPER_LEFT,NONE
DIALOG_6=UPPER_MIDDLE,NONE
DIALOG_7_WINDOW=UPPER_LEFT,NONE
DIALOG_8_WINDOW=UPPER_LEFT,NONE
DIALOG_9=UPPER_MIDDLE,NONE
DIALOG_10=UPPER_MIDDLE,NONE
DIALOG_11=UPPER_MIDDLE,NONE
DIALOG_12=UPPER_LEFT,NONE
BOSS_INTRO=UPPER_LEFT,NONE
RARITY_INFO=UPPER_LEFT,NONE
LEVEL_INFO=UPPER_LEFT,NONE
POINTS_INFO=UPPER_LEFT,NONE
