
INTRO=These are the Bosses your Guild has discovered. Bosses spawn at the same rank as the guild members that discover them. Attack and defeat them for loot!
RARITY_INFO=A Boss's rank displays in the lower left corner of its portrait.
LEVEL_INFO=A Boss's level and mark are shown in the upper left corner.
POINTS_INFO=You can attack any Boss you want but defeating higher ranked Bosses will generally award more Invasion Points. Try attacking one now!
