
DIALOG_1=The side menu now stays open by default. This should make it easier to access those menu items!
DIALOG_2=If you want the original controls, you can change them back in settings under "Other."
