
DIALOG_1=This hero has an equipped mod that you can advance!
DIALOG_2=Advancing a mod increases its power and its maximum level.
DIALOG_3=It costs mod fragments and hero chips to advance a mod. Earn mod fragments from the Invasion!
DIALOG_NOT_ATTUNED=Advancing a mod for the first time will attune it to your hero. You must spend hero chips to equip a mod that is attuned to another hero.
DIALOG_4=Keep advancing your mods to give your heroes an edge in combat!
