
DIALOG_1=You can Upgrade this Mod to give it more effects!
DIALOG_2=Choose any of the Upgrades to permanently add that extra effect to your Mod!
DIALOG_3=The types of Upgrades available depend on the Mod's shape.
