
DIALOG_1=You've unlocked the ability to disassemble your mods!
DIALOG_2=Disassembling a mod will destroy it; in return, you'll get rare mod fragments!
DIALOG_3=The more improved a mod is, the better the rewards you'll get.
DIALOG_NOT_ATTUNED=Use disassembly to clear up inventory space or get mod fragments for your favorite mods!
