
DIALOG_1=You can make this Hero stronger with Mods.
DIALOG_2=Here is an empty Mod Slot.
DIALOG_3_WINDOW=Heroes can only Equip Mods that match their Team Color.
DIALOG_4_WINDOW=Equip this Mod to gain its benefits! It's free to unequip.
