
DIALOG_1=You have enough Mod Power to Level Up one of your Mods.
DIALOG_2=First, select the Mod to Level Up.
DIALOG_3_WINDOW=Leveling Up this Mod will make its stats even stronger
DIALOG_4_WINDOW=Use Mod Power to Level-up your Mod.
