
DIALOG_1=You've unlocked Friendships!
DIALOG_2=Friendships give access to Memory Disks: Powerful items which augment your Heroes.
DIALOG_3=Progress in the Friend Campaign to unlock the Disk and increase its potential.
DIALOG_4=Each Friend Campaign also follows a unique story that can be reviewed on the Friend Wall.
DIALOG_5=Lastly, send Friends on Missions to earn Friendship related resources.
