
NEW_HERO_1=This is placeholder text to test if the narrator has been created correctly, and if it displays. What will actually go here is a brief introduction to this new hero. Hero 1
NEW_HERO_2=This is placeholder text to test if the narrator has been created correctly, and if it displays. What will actually go here is a brief introduction to this new hero. Hero 2
