
DIALOG_1=The Inventor's hidden devkit has granted you the ability to Patch your Heroes! Check out the new Patch Tab.
DIALOG_2=Increase this Hero's Patch Level to increase their Core Stats: Basic Damage, Armor, Max HP, Skill Power, and Reality.
DIALOG_3=Spend Patch Essence to increase Patch Level. Gather Patch Essence from Franchise Trials.
DIALOG_4=Patch Power shows your current maximum Patch Level and increases the multiplier for Core Stat bonuses.
DIALOG_5=Increase the Patch Level of multiple Heroes to increase your Patch Power!
DIALOG_6=Patch Levels Unlock and Upgrade Patch Talents!
