
POINT_TO_PORT=You've unlocked The Port! It's a great place to earn extra Gold and Hero XP.
POINT_TO_WAREHOUSE=The Warehouse is open today. Let's earn some Gold!
POINT_TO_DOCKS=The Docks are open today. Let's earn some XP!
WAREHOUSE_ENEMY_INFO=Enemies in The Port have damage immunities. Warehouse enemies resist normal damage.
DOCKS_ENEMY_INFO=Enemies in The Port have damage immunities. Docks enemies resist fantastic damage.
WAREHOUSE_CHOOSER_INFO=Choose heroes that do lots of fantastic damage. Study your heroes' skills to learn their strengths!
DOCKS_CHOOSER_INFO=Choose heroes that do lots of normal damage. Study your heroes' skills to learn their strengths!
