
POINT_TO_PORT=RIGHT,NONE
POINT_TO_WAREHOUSE=UPPER_RIGHT,NONE
POINT_TO_DOCKS=LEFT,NONE
WAREHOUSE_ENEMY_INFO=UPPER_RIGHT,NONE
DOCKS_ENEMY_INFO=UPPER_RIGHT,NONE
WAREHOUSE_CHOOSER_INFO=UPPER_LEFT,NONE
DOCKS_CHOOSER_INFO=UPPER_LEFT,NONE
