
DIALOG_1=Congratulations! You've unlocked Power Promote which adds a quick way to promote any hero to the Rank you want.
DIALOG_2=Tap on the Power Promote Button to get started!
DIALOG_3=The Power Promote slider allows you to easily target any new rank that you're eligible to promote to.
DIALOG_4=It uses both your resources and items to automatically farm and craft all of the badges you'll need to get there.
DIALOG_5=You can tap the info buttons next to each Stamina, Hero XP, or Gold cost to see how your resources are spent.
DIALOG_6=When you're short on a resource, tapping the info button will tell you how much more you need to Power Promote to that Rank.
DIALOG_7=Go ahead and give it a try! For more information, make sure to check out all the details here.
