
DIALOG_1=Welcome to the Prize Wall! Each square on the grid contains a prize behind it, and one square has a special Grand Prize!
DIALOG_2=Tap on each square one at a time to open them. Each square costs one token to open.
DIALOG_3=Every stage has one Grand Prize somewhere on it!  If you find it, you can advance to a fresh wall and have a chance to find another Grand Prize all over again.
