
DIALOGUE_1=Looks like one of your heroes has a full set of badges.
TAP_PROMOTE=You can now promote them to make them even more powerful.
TAP_CONFIRM=Promotions give stat boosts and unlock even more powerful badges that you can equip.
FINAL_MSG=All right! Let's get wreckin'!
