
DIALOG_1=You can now Quick Fight in the Friend Campaign!
DIALOG_2=A Quick Fight is not a Raid. Combat does occur behind the scenes, so you can still lose a Quick Fight.
DIALOG_3=If you lose a Quick Fight, you will need to fight the battle normally.
DIALOG_4=Don't worry! Quick Fights won't skip over any story dialogs from the campaign.
DIALOG_5=Remember, Quick Fights are not raids! If you keep losing, either play the fight manually or level up your heroes.
