
TAP_VIEW_DISK=LOWER_LEFT,NONE
CANT_EQUIP_REAL_GEAR=LOWER_RIGHT,NONE
CANT_EQUIP_REAL_GEAR_COMING_SOON=LOWER_RIGHT,NONE
EQUIP_MEMORY_DISK=LOWER_LEFT,NONE
RALPH_IS_STRONGER=LOWER_LEFT,NONE
ONE_DISK_INFO=LOWER_MIDDLE,NONE
ADD_STARS_INFO=LOWER_RIGHT,NONE
LEVEL_UP_INFO=LOWER_LEFT,NONE
FINAL_REMARK=LOWER_MIDDLE,NONE
