
TAP_VIEW_DISK=Memory Discs are earned by completing Friend Campaigns. They grant special powers and stat boosts!
CANT_EQUIP_REAL_GEAR=Your hero needs to be Purple rank and the Friend Campaign must be completed to equip a Memory Disc.
CANT_EQUIP_REAL_GEAR_COMING_SOON=Your hero needs to be Purple rank to equip a Memory Disc. Purple rank will be available soon!
EQUIP_MEMORY_DISK=Equip the Memory Disc to make this Hero stronger.
RALPH_IS_STRONGER=Time for some serious wreckin'!
ONE_DISK_INFO=Heroes can only have one Disc equipped at a time, but changing them is free.
ADD_STARS_INFO=You can add stars to your Disc by adding more memories.
LEVEL_UP_INFO=Increasing the Disc's Power will level it up.
FINAL_REMARK=Memory Discs are unique to each Friendship. Complete more Friendship Campaigns to earn more!
