
DIALOG_1=It looks like your hero could use some help with their mods.
DIALOG_2=If you're having problems deciding which mods to equip to your hero, you can now ask for a recommendation!
DIALOG_3=Recommended Mods will suggest the best available mods for that hero based on your current inventory.
DIALOG_4=You can also see a suggestion of the best overall mods for that hero by tapping on the "Best Possible" tooltip.
DIALOG_5=Tap the "Equip Mods" button to have your recommended mods automatically equipped to your hero. Remember, you can always change individual mods afterwards from the Mods tab by just tapping on each one.
