
DIALOG_1=Looks like you're getting stronger!
DIALOG_2=You can now unlock Red Skills for your Red heroes.
DIALOG_3=Unlike previous skills, you'll need to unlock the Red Skill before you can use it.
DIALOG_4=Unlocking a Red Skill uses Hero Chips and a new resource, Red Skill Chips.
DIALOG_5=Earn Red Skill Chips by playing City Watch on Epic difficulty
DIALOG_6=Epic difficulty is now available in City Watch!
DIALOG_7=Play Epic difficulty to earn Red Skill Chips which are used to unlock and upgrade Red hero skills.
DIALOG_8=To play, you'll need to own at least one Red hero PLUS have enough Epic Keys.
DIALOG_9=Earn Epic Keys when you clear regions in the Hard difficulty.
DIALOG_10=Make sure you have at least one of your own Red heroes in your lineup.
DIALOG_11=After that, you can use any combination of Red rank heroes or Mercenaries.
DIALOG_12=After clearing a region, one of your heroes will be randomly selected from each of the winning teams and awarded Red Skill Chips.  The number of Red Skill Chips awarded will increase based on the number of your heroes in that fight.
DIALOG_13=Clearing regions will randomly award Red Skill Chips to one of your heroes from each fight.
DIALOG_14=The more of your own Red heroes in your lineup, the more Red Skill Chips you'll earn for that fight.
