
DIALOG_1=UPPER_LEFT,NONE
DIALOG_2=UPPER_LEFT,NONE
DIALOG_3=UPPER_LEFT,NONE
DIALOG_4=UPPER_LEFT,NONE
DIALOG_5=UPPER_RIGHT,NONE
DIALOG_6=UPPER_LEFT,NONE
DIALOG_7=UPPER_RIGHT,NONE
DIALOG_8=UPPER_LEFT,NONE
DIALOG_9=UPPER_LEFT,NONE
DIALOG_10=UPPER_LEFT,NONE
DIALOG_11=UPPER_RIGHT,NONE
DIALOG_12=UPPER_RIGHT,NONE
DIALOG_13=UPPER_RIGHT,NONE
DIALOG_14=UPPER_LEFT,NONE
