
INFECTED_STATE=Uh oh. It looks like the virus has infected this area of the City!
INFECTION_INFO=Oh no! The virus has struck again! Let's clear that infection.
CLEARING_INFO=Clearing Infected Levels earns you Disk Power that you can use to upgrade Memory Disks.
