
DIALOG_1=Co-Op server contests are a new type of contest where you'll work together with everyone else on your server to win the Progress rewards.
DIALOG_2=Community Progress is the total amount of points that everyone has contributed to the contest.
DIALOG_3=Whenever the community reaches a new Progress Reward tier, everyone will be awarded the prize as long as they've contributed to the contest.
DIALOG_4=The points you contribute will also count towards your ranking. The higher the rank you achieve the better the rewards you can earn.
