
OPEN_SIDE_MENU=Looks like you can upgrade a Hero Skill.
OPEN_HEROES_MENU=Elastigirl could use an upgrade.
USED_SKILL_POINTS=Wow! I don't know what happened, but I actually feel stronger!
NO_MORE_SKILL_POINTS=Looks like you've spent all your skill points.
SKILL_POINTS_DIALOGUE=You can buy them here, or wait for them to replenish.
