
DIALOG_1=Check it out, a new Trial!
DIALOG_2=Help Fozzie take out the Creeps and earn some of his Hero Chips along the way.
DIALOG_3=Your lineup is limited to three heroes for this battle, but all of them, including Fozzie, are maxed out!
DIALOG_4=Try out different combinations to see who he teams up with the best...Wocka Wocka!
