
TAP_SURGE=Creeps are surging into the city! Let's take a look at the new Creep Surge mode.
EARN_POINTS=Participate in Surge to earn points for your Guild. More points means more gold for everybody!
DISTRICT_INFO=Clear creeps from districts like this one to earn Guild points AND personal gold.
WAVE_BONUS=Work with your Guild to clear regions of like-colored districts to earn bonuses. Clear 3 regions to complete a wave and earn mega bonus points!
TAP_FIGHT=Let's beat some creeps!
ONE_FIGHT=In Surge heroes can only be used in one battle per day. Choose wisely!
BONUS_INFO=Surge now has bonus goals you can complete to earn extra gold.
BONUS_LIMITED=Each bonus can apply to only 2 fights per Surge. Try harder fights to get more rewards!
RAID_DISCLAIMER=Note that bonuses only apply to Fights and Quick Fights, not Raids.
