
TAP_SURGE=LOWER_LEFT,NONE
EARN_POINTS=LOWER_LEFT,NONE
DISTRICT_INFO=LOWER_LEFT,NONE
WAVE_BONUS=LOWER_LEFT,NONE
TAP_FIGHT=LEFT,NONE
ONE_FIGHT=LEFT,NONE
BONUS_INFO=RIGHT,NONE
BONUS_LIMITED=RIGHT,NONE
RAID_DISCLAIMER=RIGHT,NONE
