
TAP_TEAM_TRIALS=You've unlocked Team Trials.
TAP_OPEN_TEAM=Here your heroes learn to fight as a team.
TAP_NEXT=Each team only lets certain heroes in.
SELECT_HEROES=Pick from this team's heroes.
FINAL_REMARKS=Team Trials are a great way to earn Badges. Make sure to do them every day.
