
DIALOG_1=Each stage will show you any and all special rules in detail
DIALOG_2=All of the enemies are listed here and you can use the arrows to navigate between any waves.
DIALOG_3=At the bottom you can also find all the rewards you will receive for beating the stage.
DIALOG_4=You can always press the Information Button for more details on how the particular trial works. Good luck!
