
DIALOG_1=Some Event Trials will have different stages you can select
DIALOG_2=This screen shows the differences between rules and rewards for all stages.
DIALOG_3=Select the stage that you think you can beat!
