
OPEN_SIDE_MENU=We've got a bunch of these chip things with Vanellope's face on them.
OPEN_HEROES_SCREEN=Hey, it looks like they fit together!
UNLOCKED_DIALOGUE_A=RALPH! Aw man, it is so good to see you!
UNLOCKED_DIALOGUE_B=Kid! You're okay! That means...
UNLOCKED_DIALOGUE_C=We can save my family! Welcome back, young lady. Do you remember anything at all?
UNLOCKED_DIALOGUE_D=Lemme see... Nope. Though there's something about this that feels familiar...
XP_1=Looks like Vanellope could use a boost. Let's give her an EXP potion.
XP_2=Well, I am a bit parched...
XP_3=Hey, you got more powerful, kid!
XP_4=Sweet!
