
OPEN_SIDE_MENU=UPPER_LEFT,RALPH
OPEN_HEROES_SCREEN=UPPER_LEFT,RALPH
UNLOCKED_DIALOGUE_A=LOWER_LEFT,VANELLOPE
UNLOCKED_DIALOGUE_B=UPPER_LEFT,RALPH
UNLOCKED_DIALOGUE_C=UPPER_LEFT,ELASTIGIRL
UNLOCKED_DIALOGUE_D=LOWER_LEFT,VANELLOPE
XP_1=UPPER_MIDDLE,NONE
XP_2=LOWER_LEFT,VANELLOPE
XP_3=UPPER_LEFT,RALPH
XP_4=UPPER_LEFT,VANELLOPE
