
DIALOG_1=Time to attack in War!
DIALOG_2=Choosing which room to attack is important. This one looks good.
DIALOG_3=Here you can page through the enemies defending this room.
DIALOG_4=You only get one free attack in each war, so choose an enemy you feel confident you can beat.
DIALOG_5=War attacks have special modifiers. Tap here to see the details.
DIALOG_6=Car modifiers apply to all combat until your guild defeats all the defenders in that car's room.
DIALOG_7=Each fight is three separate fights. So choose which heroes will fight which enemies.
DIALOG_8=Now that you've made your attack, you've done your part!
DIALOG_9=Your guild has a limited number of Extra Attacks. Ask your guild leaders if you should use one of them.
