
DIALOG_1=Yo, V! Come here, I've got a surprise for you.
DIALOG_2=Oooo. You know I love surprises, Shank! What is it?
DIALOG_3=Well, we haven't had a lot of time for Slaughter Race since we got pulled into this game, so I thought I'd bring a little bit of home into the City. Whaddya think?
DIALOG_4=I love it! I love it! I love it!
DIALOG_5=Guild War is the place for your guild to compete against other guilds, for prizes and ranking.
