
DIALOG_1=You can prepare for the next war here.
DIALOG_2=Here you can see the 9 rooms your guild is trying to defend in war.
DIALOG_3=Here is the room that your heroes are currently defending.
DIALOG_4=Let's look at one of the rooms
DIALOG_5=Each room has one car that modifies combat or scoring. Tap here for details.
DIALOG_6=Guild Perks upgrade the strength of these modifiers.
DIALOG_7=Let's find an open spot in this room for your heroes to defend.
DIALOG_8=Tap here to set your heroes to defend this car.
DIALOG_9=Tap here to edit your lineup.
DIALOG_10=Make sure your three best teams are set to defend in war.
DIALOG_11=Over here you can see if your guild is queued for the next war.
