
DIALOG_0=You can now Sabotage the other Guild's heroes!
DIALOG_1=The first day of war is spent sabotaging the enemy Guild.
DIALOG_2=You can look at the enemy defenders here.
DIALOG_3=Each room has one car that modifies combat or scoring. Tap here for details.
DIALOG_4=These modifiers last until all defenders in the room are defeated.
DIALOG_5=Each room has one or more players defending it. Tap here look at one of them.
DIALOG_6=Here you can sabotage defenders using tokens from other game modes.
DIALOG_7=Tokens you spend will be refunded if you lose the war.
DIALOG_8=You can only sabotage on the first day of war, so plan ahead with your guild.
DIALOG_9=Once the second day of war starts, you can start attacking.
