
DIALOG_1=Each War, your Guild will fight against another Guild over two days.
DIALOG_2=Now that your Guild is ranked, random heroes will be off duty, which mean that can't be used to attack.
DIALOG_3=These banned heroes are the same for both Guilds in the war.
DIALOG_4=Also, the available sabotages change as you rank up in war.
