
DIALOG_1=You've unlocked the Wish Crate! This crate is unique because it lets you choose which hero chips the crate awards. Check it out now!
DIALOG_2=The Wish Crate is a great way to earn rewards for the specific hero that you want! Once you select a hero, the crate will then only award items for that hero.
DIALOG_3=With each wish you'll have a chance to win hero specific items or even a Jackpot of chips for the hero of your choice! The more wishes you make, the better your chances get!
DIALOG_4=Let's choose a hero!
DIALOG_5=You can choose any hero, including heroes you haven't unlocked yet, with a few exceptions like the Sign In Hero or Exclusive Heroes.
DIALOG_6=The Wish Crate can award hero chips in either jackpot or normal amounts and each has their own probability to drop.
DIALOG_7=The starting chances to win a normal amount of chips will depend on how recent the hero is, but starting chances for the Jackpot will always be the same.
DIALOG_8=Go ahead and pick any hero you want!
DIALOG_9=Here you can see your starting chances for the hero that you've chosen.
DIALOG_10=Each time you win something other than hero chips, both the normal and Jackpot chances will increase.
DIALOG_11=Each time you win a normal amount of hero chips, the chances for winning normal chips will reset and your Jackpot chances will increase by a larger amount.
DIALOG_12=Whenever you win a Jackpot, both the normal and Jackpot chances will be reset to their starting values.
DIALOG_13=You can boost your Jackpot chances even faster with an EXTRA bonus when you buy 10 Wish Crates at a time!
DIALOG_14=Don't forget, you can reset the hero you've wished for at any time, BUT doing so will also reset your normal and Jackpot chances to their starting values.
DIALOG_15=For more information about the Wish Crate, its chances and rewards, make sure to check out all the details here.
