/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_perblue_heroes_cspine_Native */

#ifndef _Included_com_perblue_heroes_cspine_Native
#define _Included_com_perblue_heroes_cspine_Native
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_perblue_heroes_cspine_Native
 * Method:    Spine_init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_perblue_heroes_cspine_Native_Spine_1init
  (JNIEnv *, jclass);

/*
 * Class:     com_perblue_heroes_cspine_Native
 * Method:    getLastSpineError
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_perblue_heroes_cspine_Native_getLastSpineError
  (JNIEnv *, jclass);

/*
 * Class:     com_perblue_heroes_cspine_Native
 * Method:    printUsedHandleReport
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_perblue_heroes_cspine_Native_printUsedHandleReport
  (JNIEnv *, jclass);

/*
 * Class:     com_perblue_heroes_cspine_Native
 * Method:    Atlas_create
 * Signature: ([BZ)I
 */
JNIEXPORT jint JNICALL Java_com_perblue_heroes_cspine_Native_Atlas_1create
  (JNIEnv *, jclass, jbyteArray, jboolean);

/*
 * Class:     com_perblue_heroes_cspine_Native
 * Method:    Atlas_dispose
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_perblue_heroes_cspine_Native_Atlas_1dispose
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_perblue_heroes_cspine_Native
 * Method:    Atlas_getParams
 * Signature: (II[I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_perblue_heroes_cspine_Native_Atlas_1getParams
  (JNIEnv *, jclass, jint, jint, jintArray);

/*
 * Class:     com_perblue_heroes_cspine_Native
 * Method:    Atlas_getTexture
 * Signature: (II)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_perblue_heroes_cspine_Native_Atlas_1getTexture
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_perblue_heroes_cspine_Native
 * Method:    SkeletonData_create
 * Signature: ([BI)I
 */
JNIEXPORT jint JNICALL Java_com_perblue_heroes_cspine_Native_SkeletonData_1create
  (JNIEnv *, jclass, jbyteArray, jint);

/*
 * Class:     com_perblue_heroes_cspine_Native
 * Method:    SkeletonData_dispose
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_perblue_heroes_cspine_Native_SkeletonData_1dispose
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_perblue_heroes_cspine_Native
 * Method:    SkeletonData_getAnimationDurations
 * Signature: (I)[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_perblue_heroes_cspine_Native_SkeletonData_1getAnimationDurations
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_perblue_heroes_cspine_Native
 * Method:    SkeletonData_getAnimationID
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_perblue_heroes_cspine_Native_SkeletonData_1getAnimationID
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     com_perblue_heroes_cspine_Native
 * Method:    SkeletonData_getAnimationNames
 * Signature: (I)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_perblue_heroes_cspine_Native_SkeletonData_1getAnimationNames
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_perblue_heroes_cspine_Native
 * Method:    SkeletonData_getBoneID
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_perblue_heroes_cspine_Native_SkeletonData_1getBoneID
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     com_perblue_heroes_cspine_Native
 * Method:    SkeletonData_getBoneNames
 * Signature: (I)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_perblue_heroes_cspine_Native_SkeletonData_1getBoneNames
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_perblue_heroes_cspine_Native
 * Method:    SkeletonData_getSkinNames
 * Signature: (I)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_perblue_heroes_cspine_Native_SkeletonData_1getSkinNames
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_perblue_heroes_cspine_Native
 * Method:    SkeletonData_getSlotNames
 * Signature: (I)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_perblue_heroes_cspine_Native_SkeletonData_1getSlotNames
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_perblue_heroes_cspine_Native
 * Method:    SkeletonData_getStats
 * Signature: (ILcom/perblue/heroes/cspine/NativeSkeletonDataStats;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_perblue_heroes_cspine_Native_SkeletonData_1getStats
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     com_perblue_heroes_cspine_Native
 * Method:    SkeletonData_getVertexWeightReport
 * Signature: (II)[Lcom/perblue/heroes/cspine/VertexWeightReportEntry;
 */
JNIEXPORT jobjectArray JNICALL Java_com_perblue_heroes_cspine_Native_SkeletonData_1getVertexWeightReport
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_perblue_heroes_cspine_Native
 * Method:    Skeleton_create
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_perblue_heroes_cspine_Native_Skeleton_1create
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_perblue_heroes_cspine_Native
 * Method:    Skeleton_dispose
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_perblue_heroes_cspine_Native_Skeleton_1dispose
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_perblue_heroes_cspine_Native
 * Method:    Skeleton_update
 * Signature: (IF)V
 */
JNIEXPORT void JNICALL Java_com_perblue_heroes_cspine_Native_Skeleton_1update
  (JNIEnv *, jclass, jint, jfloat);

/*
 * Class:     com_perblue_heroes_cspine_Native
 * Method:    Skeleton_updateWorldTransform
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_perblue_heroes_cspine_Native_Skeleton_1updateWorldTransform
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_perblue_heroes_cspine_Native
 * Method:    Skeleton_setToSetupPose
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_perblue_heroes_cspine_Native_Skeleton_1setToSetupPose
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_perblue_heroes_cspine_Native
 * Method:    Skeleton_setColor
 * Signature: (IFFFF)V
 */
JNIEXPORT void JNICALL Java_com_perblue_heroes_cspine_Native_Skeleton_1setColor
  (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     com_perblue_heroes_cspine_Native
 * Method:    Skeleton_setTintBlack
 * Signature: (IFFF)V
 */
JNIEXPORT void JNICALL Java_com_perblue_heroes_cspine_Native_Skeleton_1setTintBlack
  (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat);

/*
 * Class:     com_perblue_heroes_cspine_Native
 * Method:    Skeleton_setSkin
 * Signature: (ILjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_perblue_heroes_cspine_Native_Skeleton_1setSkin
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     com_perblue_heroes_cspine_Native
 * Method:    Skeleton_setSlotEyeState
 * Signature: (III)Z
 */
JNIEXPORT jboolean JNICALL Java_com_perblue_heroes_cspine_Native_Skeleton_1setSlotEyeState
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     com_perblue_heroes_cspine_Native
 * Method:    Skeleton_getBoneTransform
 * Signature: (II[FI)V
 */
JNIEXPORT void JNICALL Java_com_perblue_heroes_cspine_Native_Skeleton_1getBoneTransform
  (JNIEnv *, jclass, jint, jint, jfloatArray, jint);

/*
 * Class:     com_perblue_heroes_cspine_Native
 * Method:    Skeleton_getBoneTransforms
 * Signature: (I[II[FI)V
 */
JNIEXPORT void JNICALL Java_com_perblue_heroes_cspine_Native_Skeleton_1getBoneTransforms
  (JNIEnv *, jclass, jint, jintArray, jint, jfloatArray, jint);

/*
 * Class:     com_perblue_heroes_cspine_Native
 * Method:    Skeleton_setBoneTransform
 * Signature: (IIFFFFFFF)V
 */
JNIEXPORT void JNICALL Java_com_perblue_heroes_cspine_Native_Skeleton_1setBoneTransform
  (JNIEnv *, jclass, jint, jint, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     com_perblue_heroes_cspine_Native
 * Method:    Skeleton_getPosedBounds
 * Signature: (I[F)V
 */
JNIEXPORT void JNICALL Java_com_perblue_heroes_cspine_Native_Skeleton_1getPosedBounds
  (JNIEnv *, jclass, jint, jfloatArray);

/*
 * Class:     com_perblue_heroes_cspine_Native
 * Method:    Skeleton_getVertices
 * Signature: (ILjava/nio/FloatBuffer;Ljava/nio/ShortBuffer;Ljava/nio/ShortBuffer;)I
 */
JNIEXPORT jint JNICALL Java_com_perblue_heroes_cspine_Native_Skeleton_1getVertices
  (JNIEnv *, jclass, jint, jobject, jobject, jobject);

/*
 * Class:     com_perblue_heroes_cspine_Native
 * Method:    Skeleton_getVerticesAndBounds
 * Signature: (ILjava/nio/FloatBuffer;Ljava/nio/ShortBuffer;Ljava/nio/ShortBuffer;[F)I
 */
JNIEXPORT jint JNICALL Java_com_perblue_heroes_cspine_Native_Skeleton_1getVerticesAndBounds
  (JNIEnv *, jclass, jint, jobject, jobject, jobject, jfloatArray);

/*
 * Class:     com_perblue_heroes_cspine_Native
 * Method:    Skeleton_getVerticesAndBoundsGlitched
 * Signature: (ILjava/nio/FloatBuffer;Ljava/nio/ShortBuffer;Ljava/nio/ShortBuffer;[F)I
 */
JNIEXPORT jint JNICALL Java_com_perblue_heroes_cspine_Native_Skeleton_1getVerticesAndBoundsGlitched
  (JNIEnv *, jclass, jint, jobject, jobject, jobject, jfloatArray);

/*
 * Class:     com_perblue_heroes_cspine_Native
 * Method:    AnimationStateData_create
 * Signature: (IF)I
 */
JNIEXPORT jint JNICALL Java_com_perblue_heroes_cspine_Native_AnimationStateData_1create
  (JNIEnv *, jclass, jint, jfloat);

/*
 * Class:     com_perblue_heroes_cspine_Native
 * Method:    AnimationStateData_dispose
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_perblue_heroes_cspine_Native_AnimationStateData_1dispose
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_perblue_heroes_cspine_Native
 * Method:    AnimationStateData_setMix
 * Signature: (IIIF)V
 */
JNIEXPORT void JNICALL Java_com_perblue_heroes_cspine_Native_AnimationStateData_1setMix
  (JNIEnv *, jclass, jint, jint, jint, jfloat);

/*
 * Class:     com_perblue_heroes_cspine_Native
 * Method:    AnimationState_create
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_perblue_heroes_cspine_Native_AnimationState_1create
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_perblue_heroes_cspine_Native
 * Method:    AnimationState_dispose
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_perblue_heroes_cspine_Native_AnimationState_1dispose
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_perblue_heroes_cspine_Native
 * Method:    AnimationState_update
 * Signature: (IF)V
 */
JNIEXPORT void JNICALL Java_com_perblue_heroes_cspine_Native_AnimationState_1update
  (JNIEnv *, jclass, jint, jfloat);

/*
 * Class:     com_perblue_heroes_cspine_Native
 * Method:    AnimationState_apply
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_perblue_heroes_cspine_Native_AnimationState_1apply
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_perblue_heroes_cspine_Native
 * Method:    AnimationState_setAnimation
 * Signature: (IIIZ)I
 */
JNIEXPORT jint JNICALL Java_com_perblue_heroes_cspine_Native_AnimationState_1setAnimation
  (JNIEnv *, jclass, jint, jint, jint, jboolean);

/*
 * Class:     com_perblue_heroes_cspine_Native
 * Method:    AnimationState_addAnimation
 * Signature: (IIIZF)I
 */
JNIEXPORT jint JNICALL Java_com_perblue_heroes_cspine_Native_AnimationState_1addAnimation
  (JNIEnv *, jclass, jint, jint, jint, jboolean, jfloat);

/*
 * Class:     com_perblue_heroes_cspine_Native
 * Method:    AnimationState_clearTracks
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_perblue_heroes_cspine_Native_AnimationState_1clearTracks
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_perblue_heroes_cspine_Native
 * Method:    AnimationState_getCurrentAnimationID
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_perblue_heroes_cspine_Native_AnimationState_1getCurrentAnimationID
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_perblue_heroes_cspine_Native
 * Method:    AnimationState_getCurrentAnimationTime
 * Signature: (II)F
 */
JNIEXPORT jfloat JNICALL Java_com_perblue_heroes_cspine_Native_AnimationState_1getCurrentAnimationTime
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_perblue_heroes_cspine_Native
 * Method:    AnimationState_nextEvent
 * Signature: (I[I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_perblue_heroes_cspine_Native_AnimationState_1nextEvent
  (JNIEnv *, jclass, jint, jintArray);

#ifdef __cplusplus
}
#endif
#endif
