/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_perblue_heroes_cparticle_Native */

#ifndef _Included_com_perblue_heroes_cparticle_Native
#define _Included_com_perblue_heroes_cparticle_Native
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_perblue_heroes_cparticle_Native
 * Method:    getLastParticleError
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_perblue_heroes_cparticle_Native_getLastParticleError
  (JNIEnv *, jclass);

/*
 * Class:     com_perblue_heroes_cparticle_Native
 * Method:    Effect_create
 * Signature: ([BI)I
 */
JNIEXPORT jint JNICALL Java_com_perblue_heroes_cparticle_Native_Effect_1create
  (JNIEnv *, jclass, jbyteArray, jint);

/*
 * Class:     com_perblue_heroes_cparticle_Native
 * Method:    Effect_clone
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_perblue_heroes_cparticle_Native_Effect_1clone
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_perblue_heroes_cparticle_Native
 * Method:    Effect_dispose
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_perblue_heroes_cparticle_Native_Effect_1dispose
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_perblue_heroes_cparticle_Native
 * Method:    Effect_getVertices
 * Signature: (ILjava/nio/FloatBuffer;Ljava/nio/ShortBuffer;)I
 */
JNIEXPORT jint JNICALL Java_com_perblue_heroes_cparticle_Native_Effect_1getVertices
  (JNIEnv *, jclass, jint, jobject, jobject);

/*
 * Class:     com_perblue_heroes_cparticle_Native
 * Method:    Effect_getVerticesAboveZ
 * Signature: (IFLjava/nio/FloatBuffer;Ljava/nio/ShortBuffer;)I
 */
JNIEXPORT jint JNICALL Java_com_perblue_heroes_cparticle_Native_Effect_1getVerticesAboveZ
  (JNIEnv *, jclass, jint, jfloat, jobject, jobject);

/*
 * Class:     com_perblue_heroes_cparticle_Native
 * Method:    Effect_getVerticesBelowZ
 * Signature: (IFLjava/nio/FloatBuffer;Ljava/nio/ShortBuffer;)I
 */
JNIEXPORT jint JNICALL Java_com_perblue_heroes_cparticle_Native_Effect_1getVerticesBelowZ
  (JNIEnv *, jclass, jint, jfloat, jobject, jobject);

/*
 * Class:     com_perblue_heroes_cparticle_Native
 * Method:    Effect_start
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_perblue_heroes_cparticle_Native_Effect_1start
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_perblue_heroes_cparticle_Native
 * Method:    Effect_reset
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_perblue_heroes_cparticle_Native_Effect_1reset
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_perblue_heroes_cparticle_Native
 * Method:    Effect_kill
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_perblue_heroes_cparticle_Native_Effect_1kill
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_perblue_heroes_cparticle_Native
 * Method:    Effect_stopEmitting
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_perblue_heroes_cparticle_Native_Effect_1stopEmitting
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_perblue_heroes_cparticle_Native
 * Method:    Effect_setPositionXY
 * Signature: (IFF)V
 */
JNIEXPORT void JNICALL Java_com_perblue_heroes_cparticle_Native_Effect_1setPositionXY
  (JNIEnv *, jclass, jint, jfloat, jfloat);

/*
 * Class:     com_perblue_heroes_cparticle_Native
 * Method:    Effect_setPositionXYZ
 * Signature: (IFFF)V
 */
JNIEXPORT void JNICALL Java_com_perblue_heroes_cparticle_Native_Effect_1setPositionXYZ
  (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat);

/*
 * Class:     com_perblue_heroes_cparticle_Native
 * Method:    Effect_setRotation
 * Signature: (IF)V
 */
JNIEXPORT void JNICALL Java_com_perblue_heroes_cparticle_Native_Effect_1setRotation
  (JNIEnv *, jclass, jint, jfloat);

/*
 * Class:     com_perblue_heroes_cparticle_Native
 * Method:    Effect_setScale
 * Signature: (IF)V
 */
JNIEXPORT void JNICALL Java_com_perblue_heroes_cparticle_Native_Effect_1setScale
  (JNIEnv *, jclass, jint, jfloat);

/*
 * Class:     com_perblue_heroes_cparticle_Native
 * Method:    Effect_update
 * Signature: (IF)Z
 */
JNIEXPORT jboolean JNICALL Java_com_perblue_heroes_cparticle_Native_Effect_1update
  (JNIEnv *, jclass, jint, jfloat);

/*
 * Class:     com_perblue_heroes_cparticle_Native
 * Method:    Effect_usesMultiply
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_perblue_heroes_cparticle_Native_Effect_1usesMultiply
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_perblue_heroes_cparticle_Native
 * Method:    Effect_usesZOffsets
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_perblue_heroes_cparticle_Native_Effect_1usesZOffsets
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
